### ISSUE TITLE
Website Not Responsive

### ISSUE THREAD

**Issue by Hamza20203064** [ML-Fusion-Lab/ML-Fusion-Lab-Website#10]
**Issue Summary:**
The website is not responsive across various devices and screen sizes. This impacts the user experience significantly.

**Expected Behavior:**
The website should adjust its layout to fit different screen sizes and devices, ensuring that all elements are visible and usable.

**Actual Behavior:**
- Elements are overlapping.
- Navigation is difficult on smaller screens.
- Some buttons/links are not clickable.

**Screenshots:**
![Screenshot 2024-10-01 195053](https://github.com/user-attachments/assets/fd42a4b5-4647-4176-90d8-b1ca0e4f365b)
![Screenshot 2024-10-01 195108](https://github.com/user-attachments/assets/acd462b6-cdbc-434f-b823-df7ead1a5214)

**Comment by vivekvardhan2810** [comment]
Hi, @Hamza20203064 

Can you explain the solution in detail

**Comment by Hamza20203064** [comment]
I would try to set all parent blocks to display: flex. 
If that doesn't work, I will use a @media query.

**Comment by vivekvardhan2810** [comment]
Okay, @Hamza20203064 

Assigning this issue to you.

make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH

**Comment by Hamza20203064** [comment]
OK, Thanks brother....

**Comment by vivekvardhan2810** [comment]
and @Hamza20203064 please make sure to complete this issue for the next 3 days.

**Comment by Hamza20203064** [comment]
I need some extra time. Tonight, I will submit the issue.

**Comment by vivekvardhan2810** [comment]
Take your time @Hamza20203064

**Comment by Hamza20203064** [comment]
thankyou somuch.

**Comment by Hamza20203064** [comment]
@vivekvardhan2810 Brother I made the pull request please check and murg to main branch

**Comment by vivekvardhan2810** [comment]
@Hamza20203064 I will check and merge ot tomorrow.

**Comment by Hamza20203064** [comment]
The issue I created has already been resolved by someone else, so I am going to close it.

**Comment by Hamza20203064** [comment]
@vivekvardhan2810 If there is any issue for me other than that please let me know I will create the PRs.

**Comment by vivekvardhan2810** [comment]
Okay @Hamza20203064 I will let you know.
