### ISSUE TITLE
Make the Navbar Consistent Across All Pages to Match the Home Page

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1000]
### Description

Currently, each page has a different navbar, which leads to inconsistencies in navigation and user experience. I propose standardizing the navbar across all pages to match the design and functionality of the Home page navbar. This will not only create a cohesive look and feel but also improve usability by providing a familiar navigation structure throughout the site. Implementing this change will enhance the overall user experience and streamline navigation for all users.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

### Steps to Reproduce

NA

### Expected Behavior

Na

### Actual Behavior

NA

### Screenshots

https://github.com/user-attachments/assets/4315b74c-d20c-42cf-9470-5193cefaebae

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

and one more thing this project is going to be inactive from october 26th including me also.
