### ISSUE TITLE
Add Button Google  Facbook And X login Page

### ISSUE THREAD

**Issue by RahulPrasadYadav** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1004]
### Is your feature request related to a problem? Please describe.

Adding a Google sign-in button can streamline the process, allowing users to log in quickly with an account they already have.

Google sign-in reduces the need for password management, relying on Google's secure authentication system. This alleviates password fatigue and leverages Google’s strong security features.

### Show us the magic with screenshots

![Screenshot (401)](https://github.com/user-attachments/assets/7fe055ab-e5fa-4565-9f6c-64720e2e79d0)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@RahulPrasadYadav assigning this issue to you.

Make sure to complete this.
