### ISSUE TITLE
Unexpected behavior of the navbar

### ISSUE THREAD

**Issue by pbln** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1007]
### Description

On the contact page the navbar contents appear shifted to the right . is it a bug or have been done intentionally ? If it is a bug pls assign me this task to fix it . 

### Steps to Reproduce

When I go on the contact us page , the navbar elements appear to be shifted rightwards which I think is a bug and should be fixed . 

### Screenshots

![image](https://github.com/user-attachments/assets/ba73aa92-3617-4d13-9b38-dcc8bce53519)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
it has been done intentionally and we don't want any further updation on this page.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

and one more thing this project is going to be inactive from october 26th including me also.
