### ISSUE TITLE
Add `Waste Management Optimization` Page In Project Section website.

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1008]
- I will create a Project Detail Page to the Card `Waste Management Optimization` 
- similar to the other project detail pages
- consistent header and footer.

@vivekvardhan2810

![image](https://github.com/user-attachments/assets/45719ca2-4ba8-4f4e-98f9-02546e4fdd76)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this.

And one more thing from now on the PR's are gonna be reviewed by the program manager.

so do it carefully.
