### ISSUE TITLE
Add Interactive "Quizzes and Assessments" Section!

### ISSUE THREAD

**Issue by SCR01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#101]
**Title:**  
Add Interactive Quizzes and Assessments for Each Course Module

**Description:**  
Introduce quizzes and assessments at the end of each course module to evaluate learners' understanding of key concepts. These quizzes will help users track their progress and reinforce their learning.

**Comment:**  
The feature will involve:
- MCQ-style quizzes with automatic grading.
- Could you provide feedback after submission, including correct answers and explanations?
- Optional timed assessments for each module.
- Ability to track quiz completion and scores for each user.

Example:
![image](https://github.com/user-attachments/assets/4d06677b-8802-491f-a006-79693f1d1f61)

**Comment by jyothimanoj12** [comment]
can you assign this issue to me

**Comment by SCR01** [comment]
@vivekvardhan2810 Hey can you please tell me why did you close it?
