### ISSUE TITLE
Improvement of CSS portion

### ISSUE THREAD

**Issue by noobremon** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1010]
### Is your feature request related to a problem? Please describe.

I would like to improve the css portion of the website , like the ui/ux.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by noobremon** [comment]
Please assign this to me @ML-Fusion-Lab

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many issues related to this , and i have mentioned it before for contributors to not create issues regarding this and there should be no more issues regarding this, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for the design of the website updates for now, as it was done and changes many times before.

please understand.

And one more thing this project is going to be inactive from tomorrow evening.
