### ISSUE TITLE
[Feature]: Adding tutorial on How to Make Neural networks from Scratch in the website project section

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1013]
### Is your feature request related to a problem? Please describe.

We need to create and add a tutorial to the website project section that guides users through the process of building neural networks from scratch. This tutorial will cover fundamental concepts and provide step-by-step instructions to enhance users' understanding of neural networks.

### Describe the solution you'd like.

1. **Introduction to Neural Networks**
   - Overview of neural networks and their applications.
   
2. **Setting Up the Environment**
   - Instructions on installing necessary libraries and tools.

3. **Building a Simple Neural Network**
   - Step-by-step coding guide to create a basic neural network.

4. **Training the Model**
   - Explanation of the training process and how to evaluate the model.

5. **Advanced Topics (optional)**
   - Discussion on optimization techniques, activation functions, and architecture variations.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@IkkiOcean assigning this issue to you.

Make sure to complete this.

this will be the last issue assigning you from my side.
