### ISSUE TITLE
[Mention The Feature]: Adding a Submit your Project Button 

### ISSUE THREAD

**Issue by krishashah-03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1018]
### Is your feature request related to a problem? Please describe.

Currently, there is no way for users to submit and showcase their own machine learning projects on the platform. This limits user engagement and collaboration, as users cannot contribute their work or learn from others’ projects.

The platform should provide an option for users to submit their own projects. The feature will allow users to upload details about their projects, including title, description, technologies used, project link etc. 

### Describe the solution you'd like.

Add a "Submit Your Project" button on the Projects page.
Clicking the button should open a submission form (modal or dedicated page) where users can enter project details.
Upon submission, the project will be reflected back on the Project page .

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now it is not required.

so i am closing this issue 

please understand.
