### ISSUE TITLE
Adding social media icons to the footer on all pages.

### ISSUE THREAD

**Issue by Orca-63** [ML-Fusion-Lab/ML-Fusion-Lab-Website#102]
The footer on some pages lacks social media icons, creating inconsistency with the home page. I would like to add social media icons to the footer across all pages, ensuring uniformity and enhancing the user experience.
![image](https://github.com/user-attachments/assets/fed8b595-52ee-4460-b43d-a36f63aa590c)

**Comment by pankajsaini1** [comment]
i want to solve this issue can you please assign to me for ggsoc, hacktoberfest

**Comment by Orca-63** [comment]
@faisal07777 could you please assign this issue to me

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 this issue will be on first come first serve.

You Can look for other issues please and don't create the PR directly without assigning the issue.

**Comment by vivekvardhan2810** [comment]
@Orca-63 pls wait i will assign the issue

**Comment by Orca-63** [comment]
@vivekvardhan2810 could you please assign this issue to me

**Comment by vivekvardhan2810** [comment]
@Orca-63 i am assigning this issue to you.

**Comment by Orca-63** [comment]
@vivekvardhan2810 I have completed the task.

**Comment by vivekvardhan2810** [comment]
You have completed @Orca-63, but still resolve the conflicts in the Pull request.
