### ISSUE TITLE
colourful buttons to make it attractive 

### ISSUE THREAD

**Issue by SandhyaBadwaik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1020]
### Description

there are so many buttons in the navbar which are not that attractive because there are not colourful.for example if we are clicking home button it changes colour to orange or another colour,and if it goes to project button it changes colour to yellow like this.

### Steps to Reproduce

by making changes in the code we make improve this issue .

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we are not looking for this.

so i am closing this issue.

please understand.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

and one more thing this project is going to be inactive from october 26th including me also.
