### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for predict car prices with Machine Learning in projects page website

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1022]
### Is your feature request related to a problem? Please describe.

add tutorial page

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.

this will be the last issue that i am gonna assign you.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 from tomorrow i won't be active and this project also.

**Comment by DarshAgrawal14** [comment]
got it , there is the description bug again after this can i solve that i just take 5 mins

**Comment by vivekvardhan2810** [comment]
okay @DarshAgrawal14
