### ISSUE TITLE
pop up description not matching title

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1024]
### Description

two new projects added in between

### Steps to Reproduce

projects.html not updated

### Screenshots

https://github.com/user-attachments/assets/cfb4cf62-07b9-42a1-94d6-009b44667484

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 this will be the last issue that i am gonna assign you.

Make sure to complete this.

**Comment by DarshAgrawal14** [comment]
@vivekvardhan2810  , Thanks for being so active man , it was fun working with you and contributing to this repo
keep up the great work!

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 thank you for the compliments.

Wishing you all the best for your future endeavors.
