### ISSUE TITLE
Adding animation on scrolling down on courses

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1029]
### Is your feature request related to a problem? Please describe.

To increase user engagement and improve the overall experience on the courses page, I propose implementing scroll-triggered animations. This feature would animate elements as they come into view during scrolling, making the page more interactive and visually appealing.

### Describe the solution you'd like.

1. Enhanced Engagement: Keeps users’ attention as they explore each course section.
2. Improved Aesthetics: Adds a professional and modern touch to the page design.
3. Guided Experience: Directs focus toward important information as users navigate through the content.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we are not looking for this.

so i am closing this issue.

Please understand.

and one more thing this project is going to be inactive from october 26th including me also.
