### ISSUE TITLE
🐛[BUG] : Contact Us form First Name validation

### ISSUE THREAD

**Issue by akash70629** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1030]
### Description

The "First Name" field in the Contact Us form should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to Contact Us page.
2. Click on First Name field.
3. Type number and symbol .
4. See there is no error.

### Expected Behavior

The "Name" field should only accept alphabetical letters (a-z, A-Z) and prevent users from invalid entries.

### Actual Behavior

Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/5c073798-158e-4862-88a7-e55503208746)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@akash70629 assigning this issue to you,

Make sure to complete this.

And one more thing this project is going to be inactive from tomorrow.
