### ISSUE TITLE
🐛[BUG] : Contact Us form Last Name validation

### ISSUE THREAD

**Issue by akash70629** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1031]
### Description

The " Last Name" field in the Contact Us form should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to Contact Us page.
2. Click on Last Name field.
3. Type number and symbol .
4. See there is no error.the 

### Expected Behavior

The "Name" field should only accept alphabetical letters (a-z, A-Z) and prevent users from invalid entries.

### Actual Behavior

Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/e281da4a-5b00-445f-9b5f-cea0de5860f5)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@akash70629 please complete the previous issue first which i have assigned you.

And please don't create multiple issues.

**Comment by vivekvardhan2810** [comment]
@akash70629 you should have added this issue in your previous issue, why are you creating multiple issues.

this is the last warning from my side.

**Comment by vivekvardhan2810** [comment]
i am closing this issue, make sure to add this one into your previous issue.
