### ISSUE TITLE
🐛[BUG] : Contact Us form Phone validation

### ISSUE THREAD

**Issue by akash70629** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1032]
### Description

The "Phone" field in the Contact Us form should only accept number . Currently, the field allows users to input symbols and special characters, alphabetical letters (a-z, A-Z) which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to Contact Us page.
2. Click on Phone  field.
3. Type alphabetical letters and symbol .
4. See there is no error.the  

### Expected Behavior

The "Phone" field should only accept numbers and prevent users from invalid entries.

### Actual Behavior

Currently, the field allows users to input alphabetical letters , symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/a652840a-2b8c-44ed-b0fb-3b591d82aa3b)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@akash70629 this will be the warning from my side, don't create multiple issues, please add this issue in your previous issue which i have assigned you.

Don't spam again.

this is the warning.

i am closing this issue.

please understand.

**Comment by akash70629** [comment]
> @akash70629 this will be the warning from my side, don't create multiple issues, please add this issue in your previous issue which i have assigned you.
> 
> Don't spam again.
> 
> this is the warning.
> 
> i am closing this issue.
> 
> please understand.

@vivekvardhan2810 Apologies for the multiple requests! I'm not spamming, but rather creating separate issues to help streamline the review process and make it easier for you to accept the changes. This way, each issue can be addressed individually, making it more efficient for both of us.Hope this helps!

**Comment by vivekvardhan2810** [comment]
@akash70629 you could have written these all in one issue.

**Comment by vivekvardhan2810** [comment]
@akash70629 And one more thing this project and I won't be active from 26th october.
