### ISSUE TITLE
🐛[BUG] : Sign up form Name validation

### ISSUE THREAD

**Issue by akash70629** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1035]
### Description

The "Name" field in the Sign-up form should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to Sign-up page.
2. Click on Name field.
3. Type number and symbol .
4. See there is no error.

### Expected Behavior

The "Name" field should only accept alphabetical letters (a-z, A-Z) and prevent users from invalid entries.

### Actual Behavior

Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/1bbde1be-c286-4f30-bf47-59b48ccbae55)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@akash70629 make sure to complete this fast.

and please do contribute to other projects also.
