### ISSUE TITLE
🐛[BUG] : Email Page form Name validation

### ISSUE THREAD

**Issue by akash70629** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1037]
### Description

The "Name" field in the Contact Us form should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to Contact Us page.
2. Click on Name field.
3. Type number and symbol .
4.  See there is no error.

### Expected Behavior

The "Name" field in the Contact Us form should only accept alphabetical letters (a-z, A-Z). 

### Actual Behavior

Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/141b9bd3-d8bc-48a6-aad0-01a960914568)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@akash70629 this will be the last issue that i am gonna assign you.

make sure to contribute to other projects.

As this Issues and PR's are reviewed by the program manager.
