### ISSUE TITLE
Broken Link for "Data Science Specialization - Coursera"

### ISSUE THREAD

**Issue by shreyasparaj** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1042]
### Description

The link for the "Data Science Specialization - Coursera" course directs to an error page stating, "We were not able to find the page you're looking for." I tried accessing the course directly from the course section but encountered this issue.

### Steps to Reproduce

Navigate to the "Courses" section in Pathsphere.
Click on "Data Science Specialization - Coursera."
Observe the redirect to the error page.

### Expected Behavior

The link should direct to the appropriate course page on Coursera.

### Actual Behavior

The link redirects to an error page stating, "We were not able to find the page you're looking for."

### Screenshots

![Screenshot (629)](https://github.com/user-attachments/assets/f685ab6f-e89d-4002-8f87-4fa4bbc9f6a6)

### Additional Information

The issue may be due to the course being removed or the URL being updated on Coursera.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by shreyasparaj** [comment]
Please assign this issue to me , I will fix this error by adding updated URL of data science course (COURSERA)

**Comment by vivekvardhan2810** [comment]
See we have kept that page like that and we don't want to add any link on that for now.

So I am closing this issue

Please understand.

One more thing I am going to be inactive from tomorrow.
