### ISSUE TITLE
Ensure Consistent Data Structure and Add Validation for Course Details

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1043]
The `courseDetails.js` file contains details about various courses, which are structured as objects in an array. While the data is well-organized, adding consistency checks and validation will help prevent missing or incorrectly formatted properties, which may cause runtime errors or inconsistent UI behavior. This issue proposes adding validation to enforce a consistent data structure.

**Proposed Solution:**

1. **Consistent Data Structure:** Define a standard structure for each course object, including required properties such as `id`, `title`, `price`, `instructors`, `learningOutcomes`, and `requirements`. All courses should follow this structure to maintain data integrity.

2. **Data Validation:** Implement a validation step to check for the presence and type of required properties in each course object.

3. **Dynamic Discount Calculation (Optional):** If the project’s UI displays a discount percentage, calculate it dynamically from `strikedPrice` and `price` rather than storing a hard-coded value. This will ensure accurate discounts across the UI.

**_Kindly add gssoc-ext with level and hacktoberfest-accepted labels!_** @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@smog-root assigning this issue to you.

Make sure to complete this.

And one more thing this project and I are going to be inactive from today evening, so make sure to complete this.
