### ISSUE TITLE
Minor Update to `Terms & Conditions Page` + Add 10 `Project Detail Pages` to Cards Under Project Section of website

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1046]
### Is your feature request related to a problem? Please describe.

-  Links are not clickable at `terms and condition` page
- `Project Detail Pages` are not built yet

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/1dc1c560-6ccb-4aae-b829-d3f784a69816)
- it will be better if this block is clickable  to `contact us` page in case some user need help
![image](https://github.com/user-attachments/assets/642c099c-bac1-4d13-8731-f6b7b4cf563c)

## I will add 10 pages to these cards similar to other available project pages.
1. Traffic Accident Prediction System  
2. Personalized Learning Recommendation System  
3. AI for Mental Health Analysis  
4. AI-Driven Disaster Relief Supply Chain Optimization  
5. Urban Sound Classification  
6. Smart Home Energy Prediction  
7. AI for Personalized Nutrition Plans  
8. Plastic Waste Classification To Recycle  
9. AI-Powered Virtual Therapist  
10. Human Face Landmark Detection
![Screenshot 2024-10-26 111718](https://github.com/user-attachments/assets/7a129927-83c3-437b-98c8-c33a264efe8c)

### Additional context.

@vivekvardhan2810

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 please explain for this.

![image](https://github.com/user-attachments/assets/488e7d20-401a-44e3-86f4-f0eeaa716f80)

like what do you want to change.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 please explain for this.
> 
> ![image](https://private-user-images.githubusercontent.com/91594529/380367955-488e7d20-401a-44e3-86f4-f0eeaa716f80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MjMxMzIsIm5iZiI6MTcyOTkyMjgzMiwicGF0aCI6Ii85MTU5NDUyOS8zODAzNjc5NTUtNDg4ZTdkMjAtNDAxYS00NGUzLTg2ZjQtZjBlZWFhNzE2ZjgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA2MDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmMTI1ZTM5NWY4YTk5YzJlYjAzNGE1Yzg4YzYyMjgyMzg3MGJkNDlmNWY2ZTJkNDI3NmY1MzE4NDBkMmRjNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VXLjAAESZCkIZ8X6FJYXE67Xh4B4b2oSypxEYzajQWI)
> 
> like what do you want to change.

These cards do not have project detail pages like cards above them are having. i will add respective `project detail page` for each project card like this:
![image](https://github.com/user-attachments/assets/8557e5d7-2ae7-49c0-8f4a-a37fd824e085)

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this.

And this will be the last issue i am gonna assign you.

As i have said earlier that this project and i am going to be inactive from today evening.
