### ISSUE TITLE
Navbar UI Enhancement for Better Layout and Alignment

### ISSUE THREAD

**Issue by Aman-G-upta** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1047]
The current navbar layout has a few inconsistencies affecting the overall appearance and usability of the website. Here are the proposed enhancements:

1. Logo Alignment: The logo on the left side of the navbar appears slightly misaligned. Ensuring it aligns properly with the rest of the elements will enhance visual symmetry.

2. Spacing Between Tabs: The tabs in the navbar have inconsistent spacing between them, which makes the layout look crowded. Adding uniform padding between each tab will improve readability and aesthetics.

3. Dark Mode Toggle Position: The dark mode toggle switch is currently placed in the middle of the navbar. For better usability and a cleaner design, it should be moved to the far right, aligning with the "Login" or "Community Support" tab. This change will make the navbar elements appear in a single, orderly line.

4. Single-Line Layout: All elements in the navbar should ideally align on a single line to maintain a clean and professional look.

Proposed Solution

1. Adjust logo positioning to align it properly with other navbar items.
2. Add consistent padding between tabs to ensure equal spacing.
3. Move the dark mode toggle to the right side of the navbar, aligning it with other elements.
4. Ensure all navbar elements are vertically centered and aligned in a single line for consistency.

![Screenshot 2024-10-26 110846](https://github.com/user-attachments/assets/153f63d0-cf1c-4b40-99b1-efeca79968d6)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
