### ISSUE TITLE
Show Back-to-Top Button Only After Scrolling some distance down

### ISSUE THREAD

**Issue by swathivemula7** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1048]
Currently, the back-to-top button appears immediately when the page loads, which can be improved further. To improve the user experience, I would like to update the button's behavior so that it only becomes visible after the user scrolls down a certain distance (e.g., 200px).

Since every page in the website has a back to top button, I would like to add this feature to all the pages

@vivekvardhan2810  Kindly assign me this issue under the gssoc and hactoberfest labels

**Comment by vivekvardhan2810** [comment]
for now we are not looking for this.

so i am closing this issue.

please understand.

And one more thing i am going to be inactive from today evening, including project also.
