### ISSUE TITLE
Add Theme Toggle Button on Missing Pages

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1051]
Add the theme toggle button to the pages where it is currently missing to ensure users can switch between light and dark themes consistently across the website. This will improve user experience by maintaining theme control throughout the site

![image](https://github.com/user-attachments/assets/9460193e-dae6-4868-a655-ea599a44be20)

**Comment by vivekvardhan2810** [comment]
@AnushkaChouhan25 assigning this issue to you.

Make sure to complete this fast.

And one more thing this project and i am going to be inactive from today evening.

**Comment by vivekvardhan2810** [comment]
@AnushkaChouhan25 please complete this issue.
