### ISSUE TITLE
Make Navbar Consistent Across All Pages

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1052]
Update the navbar on all pages to match the design and structure of the home page navbar for a consistent user experience and cohesive site navigation. Ensure that styling, links, and responsiveness remain uniform across the website.

![image](https://github.com/user-attachments/assets/f44701aa-22df-42b1-8f5e-cddf09b47751)
![image](https://github.com/user-attachments/assets/11176f84-a7e6-4724-9657-e2ef77b0e8ed)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
