### ISSUE TITLE
[DOCS] : Add Stargazers and Forkers Profiles to README.md ✨ 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1053]
### Issue Description

To showcase community engagement and make the project more interactive, add the stargazers and workers profiles to the README.md, as shown in the screenshot.

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/4da5c285-87c6-49f9-91c5-9007f0c2e94b)

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
@AnushkaChouhan25 please complete the previous issue that i have assigned you.

**Comment by vivekvardhan2810** [comment]
and we don't require this also.

so i am closing this issue.

please understand.

and please don't create multiple issues.
