### ISSUE TITLE
[Mention The Feature]: add an effect

### ISSUE THREAD

**Issue by Ash182004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1055]
### Is your feature request related to a problem? Please describe.

want to add transition to these footer options

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/2eb77a78-803a-485f-ba37-b10328f2a263)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require any transition effects on footer.

so i am closing this issue.

please understand.

And one more thing this project and i am going to be inactive from today evening.
