### ISSUE TITLE
 Interactive Navbar

### ISSUE THREAD

**Issue by Veda273** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1056]
I would like to address the following issues:
Issues Identified
Hover Effects: The navbar items do not change visually on hover, which reduces engagement.
Active Section Indicator: There is no clear highlight for the active section, making navigation less intuitive.
Contrast with Homepage: The navbar lacks the interactive elements present in other sections of the homepage, creating a disjointed user experience.
Suggested Enhancements
Implement Hover Effects: Add color changes or underline effects to navbar items on hover.
Highlight Active Sections: Use a distinct style for the active navbar item.
Consistency with Homepage: Make the navbar visually similar to other interactive elements on the homepage.

https://github.com/user-attachments/assets/90f1af10-7dc1-420f-9782-95165c65969b

@vivekv2810 ,please assign me this issue under gssoc'24 extend

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

and one more thing this project is going to be inactive from evening today.
