### ISSUE TITLE
[Feature✨]: Add Cursor Tail Effect on Pages Where It's Missing

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1057]
### Is your feature request related to a problem? Please describe.

 Implement the cursor tail effect consistently across all pages as some pages don't contain it, this enhances the interactive feel and provides a cohesive user experience.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@AnushkaChouhan25 we are not looking for this now.

so i am closing this issue.

please understand.

and i have said you early that this project is going to be inactive from today evening.
