### ISSUE TITLE
[Feature✨]: Add Hover Effect and Animations to Testimonial Cards

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1058]
### Is your feature request related to a problem? Please describe.

Enhance the testimonial cards with subtle hover effects and small animations to improve aesthetics and engage users.
The cards should have smooth hover effects (e.g., scaling, shadow changes) and light animations to make them visually appealing.

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/68cdf72e-01e8-45b9-afcf-7af6989b3a6d)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@AnushkaChouhan25 we are not looking for this.

i am closing this issue.

please understand.

and please don't create multiple issues on same time.

this is the warning  from my side.

**Comment by AnushkaChouhan25** [comment]
@vivekvardhan2810 Oh Okay I Apologize, I didn't see your comment.

**Comment by vivekvardhan2810** [comment]
@AnushkaChouhan25 i appreciate your work, but see that i am going to be inactive from today including project also.

and now please do contribute to other projects also.
