### ISSUE TITLE
 Unable to Access Forgot Password Feature After Navigating Back to Login

### ISSUE THREAD

**Issue by saras-69** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1059]
### Description

There is a bug that occurs when a user clicks on the "Forgot Password" link, navigates back to the login page, and then attempts to revisit the "Forgot Password" feature. The feature does not open again.

### Steps to Reproduce

Navigate to the login page.
Click on the "Forgot Password" link.
Navigate back to the login page (using the back button or a link).
Click on the "Forgot Password" link again.

### Expected Behavior

The "Forgot Password" feature should open and allow the user to input their email for password recovery each time the link is clicked

### Actual Behavior

Upon clicking the "Forgot Password" link after returning to the login page, the feature does not open or becomes inaccessible.

### Screenshots

https://github.com/user-attachments/assets/5962dea4-92a7-4f9c-8064-c798d7eab06d

### Additional Information

This issue has been observed on both Firefox, Microsoft Edge and Chrome browsers.
This issue affects user experience by preventing access to the password recovery process.

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@saras-69 assigning this issue to you.

Make sure to complete this fast.

make sure to add the same toggle design in other page.

And one more thing this project and i am going to be inactive from today night.

so make sure to complete this.

**Comment by vivekvardhan2810** [comment]
@saras-69 have you completed the task.

**Comment by saras-69** [comment]
@vivekvardhan2810 give me few minutes
