### ISSUE TITLE
Adding Relevant Content to the Course Supervised vs Unsupervised Learning, making it a Structured Course.

### ISSUE THREAD

**Issue by SoumyaU25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#106]
I want to make the whole Structured and Organized Course Structure for Supervised vs Unsupervised Learning which will make it a complete course Structured for 3 weeks. I'll be covering each and everything important in Supervised vs Unsupervised Learning course along with making it visible and Interactive on the web site. I will also try to include a Assessment test at the end of this course.

Please assign me this issue under gssoc-ext label.
<img width="352" alt="s" src="https://github.com/user-attachments/assets/474e9525-597f-424e-b242-67a83ed0c239">

**Comment by SoumyaU25** [comment]
hello @vivekvardhan2810  can you assign this to me as I really want to work on this project

**Comment by vivekvardhan2810** [comment]
Okay @SoumyaU25 Assigning this issue to you.

Make sure to complete this in next 3 days.

**Comment by Kavish-Paraswar** [comment]
"I would like to work on this issue as I have a strong background in CSS and HTML. Please assign me to this task under GSSOC'24 Extended."

**Comment by vivekvardhan2810** [comment]
You Can Complete this issue @SoumyaU25, i have closed that previous issue.

**Comment by SoumyaU25** [comment]
Okay thanks @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
I am closing this issue, as the courses page were updated including contents, But don't get disappointed, i would encourage you to create new issue regarding website improvements, then you can create new issue.
