### ISSUE TITLE
[Mention The Feature]: FAQ section should be in accordion

### ISSUE THREAD

**Issue by KrishnaMohanty08** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1060]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/1aaa1214-ef2a-470b-a4d2-162c5fb862a7)
It organizes content into collapsible sections, enhancing readability, space efficiency, and user interaction for streamlined information access.
I would like to work on this issue under gssoc extd and hackober-fest

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/7102145b-93af-44f5-baa4-77aa3db6c671)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
we are not looking for this now.

so i am closing this issue.

please understand.

And one more thing this project and i am going to be inactive from today evening.
