### ISSUE TITLE
Add a feedback form

### ISSUE THREAD

**Issue by samiksha1618** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1061]
Using a feedback form on ML Fusion Labs makes the platform better for everyone. It helps the team understand what users like, improve courses to match skill levels, and keep projects relevant and practical. Feedback also helps build a supportive community and guides new features that users want. Overall, it makes ML Fusion Labs more useful and enjoyable for learners.

**Comment by vivekvardhan2810** [comment]
this one already exists please check the website.

So I am closing this issue.

Please understand.

And one more thing this project and i am going to be inactive from today night.
