### ISSUE TITLE
Add Demo Link to README

### ISSUE THREAD

**Issue by T-Fathima** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1062]
#### Description
To provide users with a quick way to explore the project, a demo link should be added to the README. This will allow potential users and contributors to better understand the project’s features and functionality before setting it up locally.

I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
it's already there in readme, please check it.

So I am closing this issue.

Please understand.

And one more thing this project and i am going to be inactive from today night.
