### ISSUE TITLE
[Mention The Feature]: Enhancement of navbar

### ISSUE THREAD

**Issue by PriyanshiAgr** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1063]
### Is your feature request related to a problem? Please describe.

Professional nav bars are important for user engagement. I want to enhance it.

### Describe the solution you'd like.

I would like to edit the nav bar's fonts, arrangements, and overall look.

### Describe alternatives you've considered.

Changing the looks to a more techy and professional look.

### Additional context.

I will edit navbar css.

### Show us the magic with screenshots

![screencapture-ml-fusion-lab-netlify-app-2024-10-27-01_10_14](https://github.com/user-attachments/assets/bf0f045c-0fa5-47cd-a24f-167f7bb10d72)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

and one more thing this project is going to be inactive from today.
