### ISSUE TITLE
UI enhancement for header

### ISSUE THREAD

**Issue by Mrunali01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1064]
I will create a better UI for header by adjusting spaces and button size
Also i will add name of website besides the logo

<img width="949" alt="ml" src="https://github.com/user-attachments/assets/3134017b-2713-4c5b-9783-e541e59e236f">

Please assign this issue to me under the label gssoc-extd

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header based issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar and header updates for now, as it was done and changes many times before. And for home pages also.

please understand.

And one more thing this project is going to be inactive from today evening including me.
