### ISSUE TITLE
Automation of project structure updation using github workflows and python scripts

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1065]
### Is your feature request related to a problem? Please describe.

Currently, the project doesn't have a project structure. And, it would be a bit difficult for new commers to understand the project structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with github workflows and python script will make the maintainance easier.

### Describe the solution you'd like.

I want to add a detailed project structure in a separate file(redirect in README.md) for the contributors to refer to and automate the process of it's updation as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand.

### Describe alternatives you've considered.

I would like to have your feedback on whether the feature is working for you after the merge. I have tested it out by creating a sample repository. But conducting another test won't harm, which will increase the credibility of this feature. Hope I can get your cooperation.

### Additional context.

None.

### Show us the magic with screenshots

Sample of how the workflow would be automated and the project structure after updation in readme:
![image](https://github.com/user-attachments/assets/81e8ca29-70d3-421e-aabc-1a2e428f13d5)

![image](https://github.com/user-attachments/assets/0bc44243-5a2a-4e6e-8afc-e0dd9097515f)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising this issue.

But for now we don't require this.

So I am closing this issue.

Please understand.

And one more thing this project is going to be inactive from today evening including me.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 That's fine! Thanks for letting me know and thanks for helping us participate in the program through your repository.

**Comment by vivekvardhan2810** [comment]
Always welcome @rajdeepchakraborty-rc. 

And Thank you for contributing to ML Fusion Labs.

Your contribution to this repository gives a value to us.

And wishing you all the best for your future endeavours.
