### ISSUE TITLE
Feature Request: Enhancement of explore course Option 

### ISSUE THREAD

**Issue by AshmitaBarthwal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1067]
### Is your feature request related to a problem? Please describe.

SINCE THE OPTON FOR COURSE EXPLORE IS NOT VISIBLE TO THE USER, IT IS NECESSARY TO MAKE IT BOLD OUT.

### Describe the solution you'd like.

MADE THE EXPLORE COURSE BUTTON VISIBLE TO USER USING WHITE FONT.

### Show us the magic with screenshots

EARLIER:
![Screenshot 2024-10-27 195403](https://github.com/user-attachments/assets/8be7d292-13d5-4cc3-a624-eda861fe7a7c)

AFTER UPDATION: 
![Screenshot 2024-10-27 195349](https://github.com/user-attachments/assets/510e8ec5-e550-47bc-a9fd-3076983a62cf)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by AshmitaBarthwal** [comment]
@vivekvardhan2810 ASSIGN THIS ISSUE TO ME UNDER GSSOC EXT

**Comment by vivekvardhan2810** [comment]
This issue was assigned before and they are working on it.

Please check the existing issues.

So I am closing this issue.

Please understand.

And one more thing this project and I am are going to be inactive from today night due to some works.

So please do contribute to other projects.
