### ISSUE TITLE
we can add the feature of FAQ in the about us section

### ISSUE THREAD

**Issue by adityalaxkar123** [ML-Fusion-Lab/ML-Fusion-Lab-Website#107]
# we can add the feature of FAQ in the about us section.

**Comment by adityalaxkar123** [comment]
me a gssoc'24 extended member can you assign it to me

**Comment by pankajsaini1** [comment]
i want to solve this issue under ggsoc extd, hacketoberfest.

**Comment by adityalaxkar123** [comment]
If this idea is not good then tell me I close this issue @faisal07777

**Comment by vivekvardhan2810** [comment]
@adityalaxkar123 this FAQ issue was created before and we will add that feature at later.

But i still encourage to look for other issues at website like improvements, then create the new issue.
