### ISSUE TITLE
[DOCS] Contact form

### ISSUE THREAD

**Issue by Dipeshdahiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1073]
### Issue Description

I view your page contact form and it looks not that much good . Please allow me to work on the adjustment of the section 

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/b51eee5b-0619-416b-8dd7-96db30eb05b5)

### Proposed Solution (optional)

Here is a batter way to adjust the mage , map and the form to make it look more good please allow me to readjust the blocks of that page 
Allow me to work under gssoc-ext

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.
