### ISSUE TITLE
[Mention]: Fix Cursor Follower to Disappear on Cursor Exit from Webpage

### ISSUE THREAD

**Issue by CoderFleet** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1074]
### Is your feature request related to a problem? Please describe.

**Description:**  
The website currently features a cursor follower element that tracks the cursor position across the page. However, when the cursor exits the webpage (e.g., when moving outside the browser window), the follower remains visible and stops at the boundary of the page. This behavior is visually distracting and disrupts the user experience. The desired behavior is for the cursor follower to disappear when the cursor leaves the webpage and reappear as soon as the cursor reenters.

**Steps to Reproduce:**  
1. Open the webpage with the cursor follower enabled.
2. Move the cursor towards the edge of the window until it exits the webpage.
3. Observe that the cursor follower remains at the boundary and does not disappear.

**Expected Behavior:**  
The cursor follower should:
- Disappear when the cursor leaves the webpage.
- Reappear and resume following the cursor as soon as it reenters the webpage.

### Describe the solution you'd like.

**Proposed Solution:**  
Add event listeners to detect when the cursor exits and reenters the webpage:
- On `mouseleave`, hide or remove the cursor follower.
- On `mouseenter`, make the cursor follower visible again and resume tracking the cursor.

### Additional context.

**Additional Context:**  
This change will enhance the website’s interactivity by providing a cleaner experience, especially when users switch tabs or move the cursor outside the browser window.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/6606b3ac-828a-4a02-92a9-1eea196140a2)
![image](https://github.com/user-attachments/assets/ca67859b-b443-4a44-bb90-22e6d5b8f3bb)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

**Comment by vivekvardhan2810** [comment]
@CoderFleet assigning this issue to you.

Make sure to complete this fast within an hour.

This will be the only issue that I will assign you.

As I have said earlier this project will be inactive from today night including me also.

**Comment by CoderFleet** [comment]
Very Thank You... started working on it right away
