### ISSUE TITLE
No proper redirection to pages !!!

### ISSUE THREAD

**Issue by SrijaVuppala295** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1076]
![image](https://github.com/user-attachments/assets/4e28f189-e30f-409e-a36a-6aeeafc7d8f5)

**Comment by vivekvardhan2810** [comment]
For now we don't require this.

So I am closing this issue.

Please understand.

And don't create multiple issues at a single time.

This is the warning from my side.
