### ISSUE TITLE
Adding projects !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1079]
![image](https://github.com/user-attachments/assets/75cd972c-9887-4099-ac73-2f2b544ae3e0)

**Comment by vivekvardhan2810** [comment]
@SrijaVuppala295 please don't create multiple issues at a single time.

This is the warning from my side.

Please understand.

And for now we don't require this

So I am closing this issue please understand.
