### ISSUE TITLE
Add more projects to project.html

### ISSUE THREAD

**Issue by shravya312** [ML-Fusion-Lab/ML-Fusion-Lab-Website#108]

**Comment by faisal07777** [comment]
please describe it properly.

**Comment by shravya312** [comment]
Sure 
![image](https://github.com/user-attachments/assets/ec9796eb-787d-4e0e-9643-40f2c3ef3ff3)
in project.html file there are total of around 8 machine learning project, I would like to add more number of machine learning projects to the same

**Comment by faisal07777** [comment]
yeah sure . but let me know u r gssoc contributor??

**Comment by shravya312** [comment]
I am a gssoc ext contributor

**Comment by shravya312** [comment]
can u please assign me the task. I am a gssoc contributor @faisal07777

**Comment by vivekvardhan2810** [comment]
Okay @shravya312, I am Assigning this issue to you.

Make sure to Complete this issue by the next 3 days.

and make sure to join the discord channel: https://discord.gg/FZxBRpTEeH for the further communication and updates.

**Comment by shravya312** [comment]
Sure I will complete it within the deadline Thanks @vivekvardhan2810 for assigning the issue for me 
I have joined the discord

**Comment by Kavish-Paraswar** [comment]
"I would like to work on this issue as I have a strong background in CSS and HTML. Please assign me to this task under GSSOC'24 Extended."

**Comment by shravya312** [comment]
I have successfully submitted the pr @vivekvardhan2810. can u review the pr @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Yes, I will Review it, but pls mention your issue number. @shravya312
