### ISSUE TITLE
Code Optimization and Enhancements for `course.js`

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1081]
The `course.js` file handles the rendering, filtering, and animation of course cards. While the current implementation is functional, there are several opportunities for optimization and enhancement to improve readability, maintainability, and performance.

**_Kindly add gssoc-ext with level and hacktoberfest-accepted labels!_** @vivekvardhan2810 

**Suggested Improvements:**

**1. Event Delegation for Card Creation:**

- Implement event delegation for card interactivity to reduce the number of event listeners attached to individual cards.

**2. Modularization of Components:**

- **Break down functions into smaller modules for better readability and reusability:**
- Group `renderCourses()`, `createCourseCard()`, and `filterCourses()` into a `courseRenderer` module.
- Separate animation-related functions into an `animation` module.

**3. Conditional Display of Elements:**

- Simplify the logic for toggling the visibility of the load more button using `classList.toggle("hide-btn", condition)`.

**4. Enhanced Filtering Logic:**

- Improve the `filterCourses()` function to support filtering based on multiple skills tags if `skills` contains multiple tags.

**5. DOM Content Loaded Handling:**

- Consolidate the setup logic within a single `DOMContentLoaded` event listener to improve clarity and efficiency.

**Comment by vivekvardhan2810** [comment]
@smog-root assigning this issue to you.

Make sure to complete this.

this will be the last issue i am gonna assign you.

**Comment by smog-root** [comment]
can you make it level 2. because i'm doing multiple stuff there!

**Comment by vivekvardhan2810** [comment]
@smog-root I mean these are very small minor issues...that can be fixed within minutes.

And one more thing.

Though it seems these are multiple but all of them are just issues that can be fixed easily ...so I am sorry that I can't add it to level 2.

i hope you understand.
