### ISSUE TITLE
Chatbot is not working!!!

### ISSUE THREAD

**Issue by sezallagwal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1083]
### Description

https://github.com/user-attachments/assets/6c4f2adf-9463-4be2-88b9-ca6888bda145

@vivekv2810 please assign this to me under `gssoc-ext` and `hacktoberfest`

### Steps to Reproduce

click on chatbot icon ask anything 

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@sezallagwal can you fix this within an hour.

**Comment by sezallagwal** [comment]
@vivekvardhan2810 yes

**Comment by vivekvardhan2810** [comment]
@sezallagwal assigning this issue to you.

Make sure to complete this fast.

As I have said earlier this project and I are going to be inactive from today night

Reason being due to some of my works.

This will be the only issue that I am gonna assign you.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
@sezallagwal i will  add the updated level at PR.

please wait i am checking the code and the deploy preview.

once i have done, i will update it.
