### ISSUE TITLE
Improvising landing Page: Images attached below

### ISSUE THREAD

**Issue by swatified** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1087]
### Is your feature request related to a problem? Please describe.

The problem is current ui having hiccups so i wanna add improvisations one by one and make it better for users.

### Describe the solution you'd like.

I am thinking of adding a better animation on homepage for now. Would improve whole homepage by keeping earlier elements same but it would be too much for a single issue so just sticking to landing section and about us in this one. Kindly see my designs in screenshot section.

### Additional context.

Can you assign me under gssoc-ext and hacktoberfest-accepted?

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/28d5dd34-6c45-4857-bd2e-df38ba8ed03c)
![image](https://github.com/user-attachments/assets/431e3026-81c6-4ad8-ad29-08932cb8e024)
![image](https://github.com/user-attachments/assets/069b7857-9a9a-4990-84ca-748b07efbdb2)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.
