### ISSUE TITLE
Implement Auto-Label workflow for Issues/PRs🚀

### ISSUE THREAD

**Issue by amiya-cyber** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1088]
Description: Create a GitHub Actions workflow that automatically labels new issues and pull requests based on their content. This will help categorize and prioritize tasks for better project management.

please assign this with level 3 label

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now workflows are not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.
