### ISSUE TITLE
[Mention The Feature]:  Adding favicon in login page

### ISSUE THREAD

**Issue by charrviwadhwa** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1089]
### Is your feature request related to a problem? Please describe.

favicon in login page is not added

### Describe the solution you'd like.

adding a favicon will enhance website more

### Show us the magic with screenshots

![Screenshot 2024-10-29 000513](https://github.com/user-attachments/assets/b8528fae-7b29-4300-a910-8977c6821834)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@charrviwadhwa  assigning this issue to you.

Make sure to complete this fast.

As I have said earlier this project and I are going to be inactive from today night

Reason being due to some of my works.

This will be the only issue that I am gonna assign you.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
@charrviwadhwa assigning this issue to you.

Make sure to complete this fast.

As I have said earlier this project and I are going to be inactive from today night

Reason being due to some of my works.

This will be the only issue that I am gonna assign you.

I hope you understand.
