### ISSUE TITLE
[Mention The Feature]: Adding Hover Effect on Explore Courses Button

### ISSUE THREAD

**Issue by shivhere007** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1092]
### Is your feature request related to a problem? Please describe.

When users hover over the "Explore Courses" button, the background color smoothly transitions from its default shade

### Show us the magic with screenshots

https://github.com/user-attachments/assets/c9537ef7-8f04-4673-8bda-e917d6aef247

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shivhere007 assigning this issue to you.

Make sure to complete this fast.

As I have said earlier this project and I are going to be inactive from today night

Reason being due to some of my works.

This will be the only issue that I am gonna assign you.

I hope you understand.

**Comment by shivhere007** [comment]
Okay @vivekvardhan2810
