### ISSUE TITLE
Enhance The Heading of the Home Page

### ISSUE THREAD

**Issue by shivhere007** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1094]
The current heading on the Home Page could be improved to create a stronger visual impact and align better with the overall design aesthetic of the site. Enhancing the heading with updated styling, such as a more prominent font size, updated font weight, or color contrast, would make it more attention-grabbing and engaging for users upon arrival.

Header Style right now:
![Screenshot 2024-10-29 095227](https://github.com/user-attachments/assets/2567175f-8e9b-4576-bd88-975c2a32c2bb)

Suggested Header Style :

https://github.com/user-attachments/assets/aca6c192-e16d-4eb6-9a9d-aca0a9a6e69b

**Comment by shivhere007** [comment]
Kindly allow me to do this last change @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@shivhere007 assigning this issue to you.

Make sure to complete this fast.

This will be the only issue that I am gonna assign you.

I hope you understand.

**Comment by shivhere007** [comment]
Okay, thanks
