### ISSUE TITLE
[Bug] : Scroll to Top Button Should Appear Only After Scrolling Down

### ISSUE THREAD

**Issue by ygowthamr** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1096]
### Description

Currently, the "Scroll to Top" button is visible from the very beginning of the page load, which affects the user experience. The button should only appear after the user has scrolled down a certain threshold (e.g., 100px).

### Steps to Reproduce

1. Open the page.
2. Observe that the "Scroll to Top" button is visible immediately upon page load.

### Expected Behavior

- The "Scroll to Top" button should remain **hidden** when the page is loaded at the top.
- It should **appear** only after the user has scrolled down beyond a set threshold (e.g., 100px).

### Actual Behavior

- The button is displayed from the very beginning, even without scrolling.

### Screenshots

![image](https://github.com/user-attachments/assets/7878b4f3-2dcd-4984-9aff-8cee162206e0)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

@vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@ygowthamr assigning this issue to you.

Make sure to complete this fast.

As I have said earlier this project and I are going to be inactive from today.

Reason being due to some of my works.

This will be the only issue that I am gonna assign you.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
@ygowthamr This will be the only issue that I am gonna assign you.

As I have said earlier this project and I are going to be inactive from today night.

Reason being due to some of my works.

make sure to complete this fast.

**Comment by ygowthamr** [comment]
@vivekvardhan2810 
I am gonna complete this task within 1 hr, There will be no problem for you.
