### ISSUE TITLE
[Mention The Feature]: add a faq section at footer popup modal

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1098]
### Is your feature request related to a problem? Please describe.

Framing the FAQ in a footer popup modal provides users quick access to common questions without leaving the page, enhancing usability. It also keeps the main interface clean, only showing the FAQ when needed.

![image](https://github.com/user-attachments/assets/1eb21477-c714-4b9b-8129-5796e71fa45e)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

already FAQ is there in main page, no need to add this in Footer.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.
