### ISSUE TITLE
About ML Fusions Lab is an essential part of the front page but looks underwhelming

### ISSUE THREAD

**Issue by harbakshsinghbaath** [ML-Fusion-Lab/ML-Fusion-Lab-Website#11]
I would like to format this differently so it maintains the theme but looks a lot better and eye catching
<img width="941" alt="image" src="https://github.com/user-attachments/assets/125483e9-c7c0-472e-8128-10803ced84df">

**Comment by CHIHNITA-REDDY-B** [comment]
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevan.

**Comment by vivekvardhan2810** [comment]
@CHIHNITA-REDDY-B  it is first come first serve i have already assigned it to someone

lets wait for his pull request if he is not able to complete in next 3 days will assign this issue to you

**Comment by vivekvardhan2810** [comment]
@harbakshsinghbaath make sure to complete this issue for the next 3 days.

make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH

**Comment by harbakshsinghbaath** [comment]
yes @vivekvardhan2810 will complete the issue before 4th oct eod.

**Comment by CHIHNITA-REDDY-B** [comment]
Yeah sure @vivekv2810 I will look into other issues till then
