### ISSUE TITLE
need to improve FAQ accordian

### ISSUE THREAD

**Issue by RahulPrasadYadav** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1101]
### Is your feature request related to a problem? Please describe.

mproved user experience: Accordions allow users to control the amount of content they view at one time, making it easier to find answers quickly and reducing cognitive overload.
Enhanced readability: By breaking up long, text-rich content into manageable sections, accordions improve readability and make it easier for users to scan and find the information they need.
Increased flexibility: Accordions enable businesses to showcase their services clearly and concisely, making it easy for customers to compare options and find the information they need.

### Show us the magic with screenshots

![Screenshot (456)](https://github.com/user-attachments/assets/12f1659c-511a-4404-a637-b107f3e61e42)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

For now we are not looking for any improvements on FAQ's.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
