### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for creating pipeline for detecting phishing websites in projects page website

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1104]
### Is your feature request related to a problem? Please describe.

Analyze protocols , meta-dataa , architecture , url , domain , ports , anchors , traffic and various other features of given url and detect whether the given website is malicious or not

### Show us the magic with screenshots

https://github.com/user-attachments/assets/31c1aedc-3de8-4076-abc4-d65d37faf994

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 this will be the last issue that i am gonna assign you.

Make sure to complete this.

**Comment by DarshAgrawal14** [comment]
hey @vivekvardhan2810 , if the repo is active till today evening , will it be alright right if i made few commits. actually i have been inactive for past few days due to exams and currently in need of PRs ..

**Comment by vivekvardhan2810** [comment]
yes @DarshAgrawal14 you can commit, till today.

**Comment by DarshAgrawal14** [comment]
thanks a lot

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 have you done with the task.

**Comment by DarshAgrawal14** [comment]
yeah i just need a little more because this is a pipeline so it has URL feature extraction code along with model training and it is a bit difficult to explain the extraction part properly . just give me like 10 min and i will submit a PR.
