### ISSUE TITLE
[Mention The Feature]: Improving Logos on logging page

### ISSUE THREAD

**Issue by PATILYASHH** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1108]
### Is your feature request related to a problem? Please describe.

The Logo of social media is not perfect they are not looking good on its background

### Describe the solution you'd like.

I will replace that logo with better logos than that and that will look good with that page

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/5bce98cc-0304-4481-b95f-189511a43205)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require any improvements on this login page.

so i am closing this issue.

please understand.

And one more thing this project and me are inactive for sometime due to some of my works.

please do work on other projects.

i hope you understand.
