### ISSUE TITLE
Dark Mode Persistence on Refresh

### ISSUE THREAD

**Issue by PATILYASHH** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1110]
### Description

When a user switches to dark mode, the mode resets to light mode upon refreshing the website. Ideally, the website should retain the user's selected mode (dark or light) even after the page reloads.

### Steps to Reproduce

1. Go to the website.
2. Switch to dark mode.
3. Refresh the page.
4. Observe that the website reverts to light mode.

### Expected Behavior

After a user switches to dark mode, the website should remain in dark mode upon refresh or navigating between pages.

### Screenshots

https://github.com/user-attachments/assets/1a15afe4-71e4-4875-b023-9796522a5c88

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@PATILYASHH assigning this issue to you.

Make sure to complete this fast.

this will be the only issue i am assigning to you.

As i have said earlier this project and i am inactive for now.

so make sure to complete this.

**Comment by PATILYASHH** [comment]
Thank you sir I will do it now

**Comment by vivekvardhan2810** [comment]
@PATILYASHH have you completed the task.

like just want to know the progress of it.

**Comment by vivekvardhan2810** [comment]
@PATILYASHH have you done with the task.

**Comment by vivekvardhan2810** [comment]
@PATILYASHH before creating the pull request make sure to update your branch and then commit the changes, and then create the Pull request.

so that you can avoid merge conflicts.

**Comment by vivekvardhan2810** [comment]
@PATILYASHH please complete this task.

**Comment by vivekvardhan2810** [comment]
@PATILYASHH have you done with the task.

**Comment by PATILYASHH** [comment]
yes sir i will do PR in 15 minutes

**Comment by PATILYASHH** [comment]
I can't do PR because of no electricity I will do it whenever the light comes back sorry for this , I will try my best

**Comment by vivekvardhan2810** [comment]
Okay @PATILYASHH when power comes back, make sure to Create the PR.

As i have said earlier this project and will be inactive from today afternoon due to some of my work.
