### ISSUE TITLE
Issue: Lack of 'Home' Navigation Item on Key Pages

### ISSUE THREAD

**Issue by umar-farooq-shaik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1111]
The omission of a 'Home' navigation item on essential pages like Projects and About Us can create a frustrating and disorienting user experience. This navigation gap leaves users without a straightforward way to return to the homepage, potentially leading to disengagement and decreased user satisfaction.

Impact:

* Reduces ease of navigation and may confuse users.
* Forces users to use indirect methods to return to the homepage.
* Increases the chance of users exiting the site, especially for those unfamiliar with the navigation structure.

Solution: Including a consistent 'Home' link on all main pages allows users to easily return to the homepage, enhancing usability and improving the overall navigation experience.

**Comment by vivekvardhan2810** [comment]
see in some pages, there isn't any requirement for home button, as when user clicks the ml fusion lab logo, then it automatically redirects to home page.

so we don't require this.

so i am closing this issue.

please understand.

And please don't create multiple issues at a single time. this is the warning.

And one more thing this project and me are inactive for sometime due to some of my works.

please do work on other projects.

i hope you understand.

**Comment by umar-farooq-shaik** [comment]
can you please assign me this under gssoc'24 extended edition and I had solved the issue

**Comment by vivekvardhan2810** [comment]
sorry i have said it before for now we don't require this.

please understand.

**Comment by umar-farooq-shaik** [comment]
sorry to say this brother but  i have raised the issue to explain and to get the work.

 hope you understand brother

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik can you do this now.

i will assign you this issue only.

as i have said before this project and i am are going to be inactive from today night.

**Comment by vivekvardhan2810** [comment]
i will assign you this issue only.

as i have said before this project and i am are going to be inactive from today night.

**Comment by umar-farooq-shaik** [comment]
brother i will complete today itself

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik assigning this issue to you.

Make sure to complete this.

i will assign you this issue only.

and please don't disturb anything.

**Comment by vivekvardhan2810** [comment]
and please don't disturb navbar and remaining headers of the pages that you are working.

and make the design same.

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik have you done with the task.

**Comment by vivekvardhan2810** [comment]
@umar-farooq-shaik make sure to update your branch and then do commit the changes and then create the new pull request.

waiting for your Pull Request.

**Comment by umar-farooq-shaik** [comment]
@vivekvardhan2810 completed and have a look at it.
