### ISSUE TITLE
Add Features Page to this Issue 

### ISSUE THREAD

**Issue by rutikakengal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1117]
In this Features added , which are ML fusion providing to users . Assign me I like to work on it , @ML-Fusion Lab Add gssoc-ext, Hactoberfest-accepted and level to this Issue .

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
