### ISSUE TITLE
Creating a 404 page !!

### ISSUE THREAD

**Issue by SrijaVuppala295** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1118]
### Description

![image](https://github.com/user-attachments/assets/d36b79a6-0043-45dc-b7be-bccba6ccaaf1)

### Steps to Reproduce

I want to create a 404 page !!!

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
