### ISSUE TITLE
Enhance Introduction Section Aesthetics and Layout for Improved User Experience of "intr-to-ml.html" Page 

### ISSUE THREAD

**Issue by coderiksenthil** [ML-Fusion-Lab/ML-Fusion-Lab-Website#112]
The current Introduction section on the blog page looks plain and lacks visual appeal. The layout is cramped, and the button interaction is not smooth. The updated version improves the design by adding a light background, a shadow effect for depth, and better spacing between elements. The text size is increased for better readability, and the button now has a hover effect for a smoother user experience. Additionally, the image is made responsive, ensuring it looks good on all screen sizes. These changes will create a cleaner and more user-friendly layout compared to the original design.

**Additionally, the code is already prepared and ready for implementation, I kindly request to assign me to this issue**

## Before 
**Link:-** https://ml-fusion-lab.netlify.app/intr-to-ml
![image](https://github.com/user-attachments/assets/3429f4f3-a2ec-46d9-889c-71b0700b6cba)

## After 
![image](https://github.com/user-attachments/assets/099908ca-ef85-4d8d-9fc3-75d6c69f08ea)
![image](https://github.com/user-attachments/assets/b6b72b05-3305-4c58-8816-dfdac011a485)

**Comment by coderiksenthil** [comment]
@vivekvardhan2810, could you kindly explain why this issue was closed?

**Comment by vivekvardhan2810** [comment]
@coderiksenthil we will look for this afterwards, as we don't need it now, till then you can contribute.

**Comment by coderiksenthil** [comment]
@vivekvardhan2810 understood
