### ISSUE TITLE
[Mention The Feature]: Enhance the UI of some pages.

### ISSUE THREAD

**Issue by inkerton** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1120]
### Is your feature request related to a problem? Please describe.

The problem is that the website UI layout for this page is very boring and as a new student I would not consider learning from here. This time as everything is so advanced making a good interactive website is not so hard and learning from somewhere who seems boring in themselves is not an option.

### Describe the solution you'd like.

I would like to revamp the whole Pages UI I have some ideas like displaying the course info in Boxes like this than some normal textbox

![image](https://github.com/user-attachments/assets/4d514f38-883e-40c2-8a3b-b75916ae930c)

### Describe alternatives you've considered.

Changing this 
![image](https://github.com/user-attachments/assets/f226e73b-ccf5-468e-9938-49398ca86c8e)

TO THIS
![image](https://github.com/user-attachments/assets/c5995ce3-0415-45b6-ac42-f3921dfc11a1)

### Additional context.

Modules from this 
![image](https://github.com/user-attachments/assets/92802bba-e2c1-47da-9ded-ce49c6fb5d08)

TO THIS

![image](https://github.com/user-attachments/assets/d8aefb2d-90e4-46f4-b9f4-6fcd21123172)

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/b8359440-1e1d-49c5-8645-2937c512ee82)
![image](https://github.com/user-attachments/assets/c5feaa7e-2835-4703-9ea7-5841c606c7c2)
![image](https://github.com/user-attachments/assets/d83538bb-9c65-489b-8c09-f90113e826eb)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@inkerton assigning this issue to you.

Make sure to complete this fast.

this will be the only issue i am assigning to you.

As i have said earlier this project and will be inactive from tonight due to some of my work.

so make sure to complete this.

**Comment by vivekvardhan2810** [comment]
@inkerton this will be the only issue i am assigning to you.

As i have said earlier this project and will be inactive from tonight due to some of my work.

so make sure to complete this.

**Comment by inkerton** [comment]
By when tonight ??? Can you give me a specific time till when do I complete it ?
@vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@inkerton can you complete before 10:30 pm

**Comment by inkerton** [comment]
Sure @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@inkerton can you do one thing.

can i close this issue and reopen the terms and conditions page. so that you can work on that.

will it be okay for you.

**Comment by inkerton** [comment]
Yeah sure making a page from scratch would be more easier for me

**Comment by inkerton** [comment]
I will get started on that

**Comment by vivekvardhan2810** [comment]
Okay i am closing this issue.

**Comment by inkerton** [comment]
I will try to do it by 12 tonight thankx a lot

**Comment by vivekvardhan2810** [comment]
i have reopened that issue, make sure to complete that by tonight.
