### ISSUE TITLE
Improving Terms and Conditions Page.

### ISSUE THREAD

**Issue by inkerton** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1121]
### Is your feature request related to a problem? Please describe.

Their is no terms and conditions Page present Right now.

### Describe the solution you'd like.

Make a whole new terms and Conditions Page

I can make it similar to privacy policy or maybe introduce new changes 
![image](https://github.com/user-attachments/assets/ceeb6bc3-2766-4934-81cd-24ace16df311)
or 
![image](https://github.com/user-attachments/assets/354de1d5-b5d1-4e3f-a97e-68da4bb33ced)
both were made by me I can make whichever one you prefer.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/242b7461-dd0b-46a9-b1a8-2ce71ca54d85)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@inkerton the page is there, please check it.

so i am closing this issue.

please understand.

and please complete the previous issue which i have assigned to you.

and As i have said earlier this project and will be inactive from tonight due to some of my work.

**Comment by inkerton** [comment]
Yeah I saw till when would you like it can I do it till 10 I'll finish up the work by then ?
@vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@inkerton assigning this issue to you.

Make sure to complete this issue by tonight

this will be the only issue i am assigning to you.

As i have said earlier this project and I will be inactive from tonight due to some of my work.

so make sure to complete this before.

and make sure the designs shall be good and don't disturb anything.

**Comment by vivekvardhan2810** [comment]
@inkerton already the terms and condition page is there, you just have to make some improvements in that page.

**Comment by vivekvardhan2810** [comment]
@inkerton i will be waiting for your PR.

**Comment by inkerton** [comment]
@vivekvardhan2810 Hey I will finish the other issue also in 10-15 minutes if you are willing can that reopen that one too

**Comment by vivekvardhan2810** [comment]
@inkerton for now it is not required.

**Comment by inkerton** [comment]
ok
![image](https://github.com/user-attachments/assets/ac6ad58b-776e-4ade-a520-e33a2eb7efd8)

 No issues

**Comment by vivekvardhan2810** [comment]
@inkerton thank you for your contribution towards ML Fusion labs.

your contribution gives value to us.

now please do work on other projects.
