### ISSUE TITLE
button overlapping at the testimonial page

### ISSUE THREAD

**Issue by bhat-shubham** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1123]
### Description

While on the testimonial page, The "Go-to-Top" button is overlapping with the "Chatbot" button when scrolling down. 
This overlap hinders user interaction with the "Chatbot" button.
The issue has been resolved by modifying the CSS to adjust the positioning of the "Go-to-Top" button.

### Steps to Reproduce

Navigate to: https://ml-fusion-lab.netlify.app/
Click on: "Projects" page
Click on: "Testimonials" page
Scroll down: On the "Testimonials" page
Observe: The "Go-to-Top" button appears and overlaps with the "Chatbot" button.

### Expected Behavior

The "Go-to-Top" button should appear without overlapping any other elements on the page, ensuring a smooth user experience. It should be positioned appropriately, typically in the bottom-right corner of the viewport.

### Actual Behavior

The "Go-to-Top" button appears but is positioned incorrectly, overlapping with the "Chatbot" button. This overlap hinders user interaction with the "Chatbot" button.

### Screenshots

![image](https://github.com/user-attachments/assets/48f19f33-8e2b-4e8d-b572-04725bd9628e)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@bhat-shubham assigning this issue to you.

Make sure to complete this fast.

And this will be the only issue i am assigning to you.

As i have said earlier this project and I will be inactive from today due to some of my work.

so make sure to complete this before.

**Comment by vivekvardhan2810** [comment]
@bhat-shubham and before creating PR, make sure to update your branch and then do commit changes and then create PR.
