### ISSUE TITLE
Framer Animations 

### ISSUE THREAD

**Issue by Mallik-vinukonda** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1125]
I will add Framer animations to your website ,
it will enhance the user experience ,

Animations @ Hero section , about us , courses page and project page

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by Mallik-vinukonda** [comment]
> Thank you for raising the issue.
> 
> But for now it is not required.
> 
> So I am closing this issue.
> 
> Please understand.
> 
> And one more thing this project is already inactive including me also due to some of my works.
> 
> Please do contribute to other projects.
> 
> I hope you understand.

Ok
No worries
