### ISSUE TITLE
[Mention The Feature]: want to add animations on the social media icons in the footer on hovering.

### ISSUE THREAD

**Issue by ritikm31** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1129]
### Is your feature request related to a problem? Please describe.

no, that's a additional feature that's make the social media icons looks more appealing.

### Describe the solution you'd like.

want to add animation on the social icons when someone hovers on them.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by ritikm31** [comment]
it's totally fine but you're not updated the code of what i'm gonna implenting in your website its still seems normal to me.

**Comment by vivekvardhan2810** [comment]
Okay, for now it won't be required.

I hope you understand.
