### ISSUE TITLE
The About ML Fusion Labs paragraph is repeated and the text is not properly visible due to light font colour

### ISSUE THREAD

**Issue by ahinagangopadhyay** [ML-Fusion-Lab/ML-Fusion-Lab-Website#113]
I want to remove the repeated text and make the font colour darker so that the ui of the page is improved and the text is readable.
![Screenshot (252)](https://github.com/user-attachments/assets/692e1c3d-ea1c-4503-963e-574a77f618ae)
Please assign me this issue under Hacktoberfest and GSSOC-Extended'24

**Comment by ANANDISHARMA0109** [comment]
Please  assign me this issue under ggsoc-extd and hacktoberfest @tabinayaseen

**Comment by vivekvardhan2810** [comment]
@ahinagangopadhyay this issue was resolved, so i am closing this issue.
