### ISSUE TITLE
[Mention The Feature]:  Beginner-friendly Tutorials

### ISSUE THREAD

**Issue by falak412** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1131]
### Is your feature request related to a problem? Please describe.

add tutorials for different machine learning algorithm. and introduction of different libraries. also project documentation guide.  
GSSoC'24 Extd Contributor 
please assign me this issue. 

### Show us the magic with screenshots

![Screenshot (106)](https://github.com/user-attachments/assets/bfa9f402-9027-45de-9ac9-341c1a8d5cce)
i will add this feature here in future.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

But we don't require this. 

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
