### ISSUE TITLE
Toggle button for dark and light mode is not working

### ISSUE THREAD

**Issue by varshasric4** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1132]
### Description

Toggle buuton for both dark theme and light theme is giving same interface
.Which stops the user interactiveness

### Steps to Reproduce

steps :
1.To change we need to develop the interface for both light and dark theme

### Expected Behavior

we need to change the theme according to user opinion

### Actual Behavior

The actual behaviour is that the toggle button is showing same theme that is dark

### Screenshots

![bug1](https://github.com/user-attachments/assets/3cf74f7a-62b5-4b9a-9037-51ae2c68c22e)

### Additional Information

we should change the theme

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising the issue.

From my side it is okay and there is no issues on that and there won't be any changes on that.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
