### ISSUE TITLE
[Mention The Feature]: Adding Search Bar On Project Page

### ISSUE THREAD

**Issue by Arshia-163** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1135]
### Is your feature request related to a problem? Please describe.

Currently, users may find it challenging to locate specific types of projects on the project page due to the lack of a Search option. This makes it time-consuming to browse through a large list, especially when users are searching for projects that fit certain categories or criteria.

### Describe the solution you'd like.

With this feature, users will be able to quickly narrow down the list of projects to match their preferences, making it easier to find relevant projects and improving overall navigation and user experience.

### Describe alternatives you've considered.

Add a filtering option on the project page, allowing users to sort and filter projects based on criteria such as category, status, date added, or popularity.

### Additional context.

Please add gssoc-ext labels and assign me this issue

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/878e6a00-b413-4eb7-ab3b-a938e47adfa1)
Search bar like this above the list of projects make it easier for the user to browse.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, Thank you for raising the issue.

But for now it is not required.

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
