### ISSUE TITLE
[DOCS] Enhancement Proposal for CSS Styling

### ISSUE THREAD

**Issue by divyaaa16** [ML-Fusion-Lab/ML-Fusion-Lab-Website#1139]
### Issue Description

The ML Fusion Lab website’s current CSS lacks advanced styling, resulting in a basic and outdated look. Enhancing the CSS will improve the website's visual appeal, readability, and user experience, especially on various screen sizes.

### Additional Context

Modern websites often use responsive and dynamic CSS elements, like animations and transitions, for a better user experience. Adding these features can make the website feel more engaging and professional.

### Screenshots or Examples (if applicable)

![Screenshot 2024-11-08 222227](https://github.com/user-attachments/assets/115e5fa6-a244-4575-b747-b33e07e1c858)

### Proposed Solution (optional)

Integrate additional CSS (or Tailwind CSS utilities) to:

Add animations/transitions.
Enhance layout responsiveness for different devices.
Style buttons, forms, and navigation for a modern look.

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [x] I am willing to work on this issue (optional)

**Comment by divyaaa16** [comment]
@vivekvardhan2810 
please assign me this issue under labels gssoc-ext, hacktoberfest.

**Comment by vivekvardhan2810** [comment]
Hi, @divyaaa16 ,Thank you for raising the issue.

But for now it is not required. we the team will improve it later,

So I am closing this issue.

Please understand.

And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.

**Comment by vivekvardhan2810** [comment]
@divyaaa16 And one more thing this project is already inactive including me also due to some of my works.

Please do contribute to other projects.

I hope you understand.
