### ISSUE TITLE
Clustered organization of the files

### ISSUE THREAD

**Issue by bjamre13** [ML-Fusion-Lab/ML-Fusion-Lab-Website#114]

**Comment by bjamre13** [comment]
Keep all the related files in one particular folder.
That helps in easy searching and updating them as required.

**Comment by vivekvardhan2810** [comment]
@bjamre13 keep the index.html outside, for deployment. don't include it in file.

**Comment by bjamre13** [comment]
Sure.
Thank you 👍

**Comment by vivekvardhan2810** [comment]
it's been one week, you haven't even changed it, so i am closing this issue. please understand.
