### ISSUE TITLE
Enhancement of the Navbar of the page

### ISSUE THREAD

**Issue by snehaapratap** [ML-Fusion-Lab/ML-Fusion-Lab-Website#115]
Improving the navbar involves making it more intuitive by streamlining navigation links, using clear labels, and ensuring it is mobile-friendly. Adding dropdowns for better organization and a search function can enhance usability. This helps users find what they need faster, improving overall site experience.

**Comment by vivekvardhan2810** [comment]
@snehaapratap this issue was mentioned early and they have created the pull request.

But for the encouragement, pls look for other issues in website like improvements.

I am closing this issue.
