### ISSUE TITLE
✨[feature enhancement]: CSS of the home page ✨

### ISSUE THREAD

**Issue by snehaapratap** [ML-Fusion-Lab/ML-Fusion-Lab-Website#116]
The CSS of the home page is not really pleasing. The text is also not aligned properly.

**Comment by vivekvardhan2810** [comment]
@snehaapratap Can you explain this in detailed solution with screenshot of that you want to change.

**Comment by snehaapratap** [comment]
![image](https://github.com/user-attachments/assets/c96d7ca9-0c2a-46ce-ba4a-e22dcabcb10d)
![image](https://github.com/user-attachments/assets/60c2837e-a654-4b7e-917a-bd7d01fd7b69)
![image](https://github.com/user-attachments/assets/cc589df2-f82e-444b-96f8-7d1eba1c53e5)
the css of few pages are not looking great.
the text isnt aligned properly in a few pages.
Please assign me this for better enhancement of the page.
Thank you!

**Comment by vivekvardhan2810** [comment]
the issue has been solved, so i am closing this issue.
