### ISSUE TITLE
i want to improve SEO of this website

### ISSUE THREAD

**Issue by pankajsaini1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#118]
i want to improve seo of this website by which overall execution time becomes fast.

**Comment by vivekvardhan2810** [comment]
@pankajsaini1 can you explain the detailed solution with screenshot that you wanna change.

**Comment by vivekvardhan2810** [comment]
Okay @pankajsaini1 I will look into it and check it by tomorrow, as i have to resolve the conflicts in website.
