### ISSUE TITLE
Feat: Add Clickable Link to Logo Redirecting to Home Page

### ISSUE THREAD

**Issue by HarshadaGirase** [ML-Fusion-Lab/ML-Fusion-Lab-Website#120]
Description:
The website logo in the header should be clickable and redirect users to the Home page. This functionality will improve navigation and user experience, allowing users to easily access the main page from any part of the website.

Steps to Reproduce:
1. Visit any page on the website.
2. Try clicking the logo in the navigation bar.
3. Notice that the logo is not linked to the Home page.

Expected Behavior:
When the user clicks on the logo, they should be redirected to the Home page.

Actual Behavior:
The logo is not clickable and does not link to any page.

![mllabs](https://github.com/user-attachments/assets/428433b1-c2c7-4388-83c5-cb8b38ab596c)

**Comment by HarshadaGirase** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by AnupamKumarPanditofficial** [comment]
I would like to work on this issue kindly assign it to me ASAP.

**Comment by vivekvardhan2810** [comment]
@HarshadaGirase remove home from the navbar in all pages.

**Comment by HarshadaGirase** [comment]
Okay
