### ISSUE TITLE
Redesigning Of About Section

### ISSUE THREAD

**Issue by Gaurav075** [ML-Fusion-Lab/ML-Fusion-Lab-Website#121]
I find that the About section is not up to the mark so I want to redesign it. Pls assign this task to me @vivekvardhan2810 
![Screenshot (318)](https://github.com/user-attachments/assets/a59dcff3-cae4-47d5-8213-ea5a34b78306)

**Comment by vivekvardhan2810** [comment]
Hi, @Gaurav075 Thank You for Creating the issue, But this issue was presented before and Created the PR,

So I am Closing this issue

But i will Encourage You to look for other issues in website improvements. then create the new issue.
