### ISSUE TITLE
Improved Font Clarity in Home Section

### ISSUE THREAD

**Issue by Gaurav075** [ML-Fusion-Lab/ML-Fusion-Lab-Website#122]
I will make the home section more clear as the colors are very dull as you can see in the picture. So, I will make it look more attractive. Assign this issue to me @vivekvardhan2810 
![Screenshot (319)](https://github.com/user-attachments/assets/01b7da50-0fb3-414c-8542-3bef2fe60586)

**Comment by Kavish-Paraswar** [comment]
"I would like to work on this issue as I have a strong background in CSS and HTML. Please assign me to this task under GSSOC'24 Extended."

**Comment by vivekvardhan2810** [comment]
@Kavish-Paraswar its already assigned to someone else

**Comment by vivekvardhan2810** [comment]
@Gaurav075 this issue was solved, so i am closing this issue.
