### ISSUE TITLE
A section for live events and webinars 

### ISSUE THREAD

**Issue by kaushalendra0812** [ML-Fusion-Lab/ML-Fusion-Lab-Website#123]
Hey Vivek !
I would like to contribute to your project by adding the section for live events and webinars.

Solution : Adding a section where user can find the live events and webinars. 

Tech to be used:
-HTML : For structuring and adding content
-CSS : For designing and responsiveness
-JavaScript : For hiding and displaying the content when user click on the question
Please assign me this issue under the labels of Gssoc-extd, hacktoberfest, hacktoberfest-accepted and relevant level.

![Screenshot 2024-10-03 232140](https://github.com/user-attachments/assets/75ca7010-99fd-49f8-9e3e-d3e58431fa35)

**Comment by kaushalendra0812** [comment]
Thank you for assigning me the issue !
I will submit the work very soon !

**Comment by vivekvardhan2810** [comment]
@kaushalendra0812 you can continue, some random guy don't know has created PR, he didn't look proper,

You can continue with the work.

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by PREM-A261** [comment]
3 weeks are pass away 
@PREM-A261 Can you please assign me this one

**Comment by vivekvardhan2810** [comment]
@kaushalendra0812 this project is going to be inactive from october 25th including me also.

And the page was also updated, please check this.

**Comment by vivekvardhan2810** [comment]
Hi @kaushalendra0812 ,

It’s been over 3 weeks without any updates. I will be closing this issue by the end of the day. If you have any progress to share, please do so before then.

if this task is delaying from your side, then you can close this issue also. No problem.

i am asking this because i am going to be active for today only.

Thank you!

**Comment by vivekvardhan2810** [comment]
as there is no response from your side, i am closing this issue.

this project is gonna be inactive from 25th october including me also.
