### ISSUE TITLE
Responsiveness Issue

### ISSUE THREAD

**Issue by SatyaJaiss** [ML-Fusion-Lab/ML-Fusion-Lab-Website#125]
This is the screen recording done from a mobile screen...

https://github.com/user-attachments/assets/d1261e3f-3f38-4834-ad4b-6424d54f3e56

The site should be responsive/compatible for all screen sizes.
@vivekv2810 Kindly Assign me, I will resolve the issue

**Comment by vivekvardhan2810** [comment]
@SatyaJaiss this issue was completed before, so i am closing this issue.
