### ISSUE TITLE
Re-designing the navbar

### ISSUE THREAD

**Issue by synakr** [ML-Fusion-Lab/ML-Fusion-Lab-Website#127]
I'd love to work on the navbar, adding animations and responsiveness o it with eye pleasing color scheme.
I'd like to work on:

1. clickable logo
2. hover effects on the navbar links (with some animated logos)
3. right side positioning of the links
4. responsiveness of navbar in changing dimensions

**Comment by 4F24L** [comment]
Can you assign me on this ? I will make it happen @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
Hi, @synakr This issue was Presented before and created the PR.

So i am closing this issue

But i will encourage you to look for other issues in website improvement, Then create the new issue.
