### ISSUE TITLE
updation in navbar

### ISSUE THREAD

**Issue by Shraddha-Deshmukh2119** [ML-Fusion-Lab/ML-Fusion-Lab-Website#128]
The current navbar requires updates to improve its design and usability. The font size of the navigation links should be increased to 18px for better readability. The button design needs enhancement by adding border-radius for rounded corners and a hover effect with a smooth background color transition for a more interactive experience.the logo size should be adjusted to a maximum width of 50px with added margin for better alignment. These updates will make the navbar cleaner and more user-friendly.
![navissue](https://github.com/user-attachments/assets/41114409-880b-4739-a7ff-49bca4889b58)
i can fix this issue i request to assign me this.

**Comment by ayushiu** [comment]
assign this issue to me

**Comment by komal-kumawat** [comment]
I would like to request the assignment of this issue for GSSOC extended . As the current navbar requires updates  for improving its interface . I believe I can solve this issue with my skills in HTML , CSS and JAVASCRIPT .So please assign it to me

**Comment by ANANDISHARMA0109** [comment]
I would like to link the logo image in the navbar to home page. Please assign this task to me under ggsoc-extd 24 and hacktoberfest. @tabinayaseen
