### ISSUE TITLE
updation in main section

### ISSUE THREAD

**Issue by Shraddha-Deshmukh2119** [ML-Fusion-Lab/ML-Fusion-Lab-Website#129]
The current design in the image needs enhancements to improve its appearance and readability. The font size should be increased for both the headings and body text to make them more noticeable and easier to read. The background color should be updated to a more vibrant or contrasting tone to make the section visually appealing and help the text stand out. Additionally, the font style should be updated to a more modern, clean typeface, and the font color should be adjusted to create better contrast with the background for improved readability and aesthetics.
![mid](https://github.com/user-attachments/assets/82b5e089-4a28-4ff4-a8d5-aab1a9c97857)
i can fix this issue i request you to assign me this.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
