### ISSUE TITLE
Implement Login/Signup with User Dashboard

### ISSUE THREAD

**Issue by Coderamrish** [ML-Fusion-Lab/ML-Fusion-Lab-Website#130]
Login/Signup Forms: Create secure login and signup forms with field validation (email, password, username) and password reset functionality.
User Authentication: Implement authentication using secure methods such as JWT or sessions for managing user logins.
User Dashboard: Design a personalized dashboard that displays user information and is responsive across devices.
Security Measures: Ensure strong security by hashing passwords and protecting user data.

**Comment by vivekvardhan2810** [comment]
Hi, @Coderamrish This issue was presented before and created the PR

So I am closing this issue.

But i will encourage you to look for other issues in website improvements, then you can create the new issue.
