### ISSUE TITLE
About section improvement

### ISSUE THREAD

**Issue by NishantK-07** [ML-Fusion-Lab/ML-Fusion-Lab-Website#131]
The about section can be improved by increasing the text and picture's visibility which will have a great impact on user
![Uploading Screenshot 2024-10-04 094421.png…]()

**Comment by NishantK-07** [comment]
Please assign this issue to me under gssoc 2024 extended

**Comment by ayushiu** [comment]
please assign this issue to me @NishantK-07

**Comment by Raj-Aditya-27** [comment]
![image](https://github.com/user-attachments/assets/209eb62f-53ae-46f1-ba2c-525ded1a3eb6)


Hi @vivekvardhan2810
 
I found that about page is not working properly.
Please assign me this issue.
I will not take too much time to fix it.

**Comment by ANANDISHARMA0109** [comment]
![image](https://github.com/user-attachments/assets/f1f79de2-30d8-4108-ad21-a7e19acc6c31)

In the above page, there is no proper spacng between different sections. Please assign this task tome under ggsoc-extd 24  and hactoberfest. @tabinayaseen
