### ISSUE TITLE
Improving the navigation bar

### ISSUE THREAD

**Issue by NishantK-07** [ML-Fusion-Lab/ML-Fusion-Lab-Website#132]
The header section or the navigation bar can be improved by making the links placed in a good position
![Uploading Screenshot 2024-10-04 094821.png…]()

**Comment by NishantK-07** [comment]
Please assign this issue to me under gssoc 2024 extended

**Comment by vivekvardhan2810** [comment]
Hi @NishantK-07, This issue was created before and ready for PR, 

For now I am closing this issue.

But I Will encourage you to look for other issues in website like improvements.
