### ISSUE TITLE
: Responsive Design and Content Overflow Issue

### ISSUE THREAD

**Issue by sahhoArjun097** [ML-Fusion-Lab/ML-Fusion-Lab-Website#133]
Responsive Design Issue: The current design does not properly adjust for different screen sizes, particularly on smaller devices. The layout seems to overflow the viewport.
Content Overflow: Some of the content overflows beyond the screen, causing a horizontal scroll or incomplete display. 

![image](https://github.com/user-attachments/assets/6cb7142b-b4e9-4d8f-8fa4-d3cd94a1ba6a)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant  and lvl .

**Comment by vivekvardhan2810** [comment]
Okay @sahhoArjun097 assigning this issue to you.

Make sure to complete this issue in the next 3 days.

**Comment by sahhoArjun097** [comment]
#162
