### ISSUE TITLE
Bug: Add functionality in Contact form to send mail 

### ISSUE THREAD

**Issue by AkankshaSinghK** [ML-Fusion-Lab/ML-Fusion-Lab-Website#135]
@vivekvardhan2810 
I would like to implement functionality in the 'Contact Us' form to send an email upon clicking the 'Send Message' button, as it currently displays a 'Page Not Found' error that needs to be resolved.

![image](https://github.com/user-attachments/assets/5cc2c7dd-f3d1-4c14-9c06-d39b93289135)
![image](https://github.com/user-attachments/assets/a2e198db-3c15-4b15-a6c6-b2a97e1b87e3)

Please assign this issue to me and add gssoc and hactoberfest tags.

**Comment by vivekvardhan2810** [comment]
Okay, @AkankshaSinghK Assigning this issue to you.

Make Sure to complete this issue for the next 3 days.

And make sure to join the discord channel: https://discord.gg/FZxBRpTEeH for further communication and Updates.
