### ISSUE TITLE
User Profile , Sign in page 

### ISSUE THREAD

**Issue by prvn-kumar01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#136]
![Screenshot 2024-10-04 110745](https://github.com/user-attachments/assets/fb33c651-ce77-4030-81bc-b8f6164563c8)
we can add user profile 
We can add login / sign in page so that we can track all user data regarding labs , courses and other activity
that he/she do in our webpage.

**Comment by vivekvardhan2810** [comment]
@prvn-kumar01 this issue was created before and worked already on it., so i am closing this issue.
