### ISSUE TITLE
Bug : Hamburger Menu Icon is not working

### ISSUE THREAD

**Issue by AkankshaSinghK** [ML-Fusion-Lab/ML-Fusion-Lab-Website#137]
@vivekvardhan2810 
Upon clicking the hamburger menu icon, the navigation links do not display.

I want to work on this issue to ensure that the navigation links display correctly when the hamburger menu icon is clicked.

![image](https://github.com/user-attachments/assets/533d3488-5692-4485-85a9-f947e1cfa8b4)

Kindly assign this issue to me to resolve it and add gssoc-extd  and hactobefest tag.

**Comment by vivekvardhan2810** [comment]
@AkankshaSinghK it is working, I am closing this issue.
