### ISSUE TITLE
Proposal: Enhancing the Navbar and Aligning Navigation Links.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [ML-Fusion-Lab/ML-Fusion-Lab-Website#139]
Aligned the navigation links to the right side, similar to professional websites, for a cleaner and more modern look. Additionally, enhanced the overall UI to improve user experience and provide a polished, professional design.

**Comment by anannya-2032** [comment]
please assign this task to me under ggsoc -ext 24 and hactoberfest. @tabinayaseen @faisal07777
