### ISSUE TITLE
Create a Separate page for ML Courses 

### ISSUE THREAD

**Issue by Sapta-Dev27** [ML-Fusion-Lab/ML-Fusion-Lab-Website#14]
Create a Separate Page for ML Courses 
Features 👍: 
1.  Display of the best ML across Yt 
2. Display of best ML articles , blogs , Docs !!
3. Create separate boxes for them 
4. Add a Newsletter section

**Comment by vivekvardhan2810** [comment]
Hi @Sapta-Dev27, thanking you for creating this issue, but could you give a proper detail on this issue #13

**Comment by vivekvardhan2810** [comment]
@Sapta-Dev27 assigned to you.

make sure to complete this issue for the next 2 days.

**Comment by Sapta-Dev27** [comment]
OKay sure  @vivekvardhan2810 ..

so I will be adding all the Features or only the Newsletter section ?? Pls clarify

**Comment by vivekvardhan2810** [comment]
@Sapta-Dev27 pls add the only newsletter section.

**Comment by Sapta-Dev27** [comment]
okay @vivekvardhan2810 
I will be adding the newsletter section in the Main Landing Page right ??

**Comment by vivekvardhan2810** [comment]
yes,@sapta-Dev27 you can add wherever you want

**Comment by Sapta-Dev27** [comment]
okay @vivekvardhan2810 !!
 I will make the PR asap !!

**Comment by Sapta-Dev27** [comment]
@vivekvardhan2810 I have made the PR ..kindly check it
