### ISSUE TITLE
Different colour of headings in different page

### ISSUE THREAD

**Issue by tulikaa25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#141]
Presently the introduction heading of every page is in grey except for courses page.
![Screenshot 2024-10-04 153651](https://github.com/user-attachments/assets/4c6e0308-28ad-4bc6-8b6d-a70f99200606)
![Screenshot 2024-10-04 153700](https://github.com/user-attachments/assets/5cdbde62-2671-4363-a78e-92eb971059f9)
## After Improvement
The colour should be same across all pages.

**Comment by tulikaa25** [comment]
Please assign this issue to me.

**Comment by Kavish-Paraswar** [comment]
"I would like to work on this issue as I have a strong background in CSS and HTML. Please assign me to this task under GSSOC'24 Extended."

**Comment by anannya-2032** [comment]
please assign this task to me under ggsoc -ext 24 and hactoberfest. @tabinayaseen @faisal07777

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
