### ISSUE TITLE
 Improve Flexbox Layout and Button Visibility

### ISSUE THREAD

**Issue by Kavish-Paraswar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#145]
Issue:
The Projects page currently displays four flexboxes in a row, creating a cramped layout. Additionally, the "Learn More" button is black in dark mode, which reduces visibility and affects overall user experience.
![image](https://github.com/user-attachments/assets/c3b6db10-4747-46ba-9122-4aefab73fd77)
Proposed Solution:

Change the layout to display three flexboxes per row for better spacing.
Add shadows to the flexboxes for depth and improved aesthetics.
Modify the "Learn More" button color in dark mode to enhance visibility and complement the overall design.

**Comment by anannya-2032** [comment]
please assign this task to me under ggsoc -ext 24 and hactoberfest. @tabinayaseen @faisal07777
