### ISSUE TITLE
Toggle between "Learn More" and "Learn Less" in Course Section

### ISSUE THREAD

**Issue by riddhij0804** [ML-Fusion-Lab/ML-Fusion-Lab-Website#148]
- Currently, the "Learn More" button is displayed even after expanding the course content. Once the user clicks on "Learn More," the   extended content is shown, but the button does not toggle to "Learn Less."
- The button should initially display "Learn More" when the content is collapsed. Upon clicking the button, the content expands, and the button text should toggle to "Learn Less." When clicked again, the content should collapse, and the button text should revert to "Learn More."

**Comment by faisal07777** [comment]
please share related photos

**Comment by riddhij0804** [comment]
This is when the content is collapsed.
![Learn more pg](https://github.com/user-attachments/assets/65c17a98-81b2-4133-90a2-26ca0f128c34)
This is when the content expands.
![Learn less pg](https://github.com/user-attachments/assets/bf11b6ab-c8bc-449e-a564-7d2bedae45b4)

**Comment by riddhij0804** [comment]
@vivekvardhan2810 @faisal07777  
**I have already provided the requested images, but I haven't received any further updates or been assigned to the issue yet.
Could you kindly take a look and let me know if there's anything else I need to do or if I can move forward with it?**

**Comment by faisal07777** [comment]
i have assinged the issue kindly complete it in 3 days  nd as a mentor i can only give  1 level label it will further decide by PA

**Comment by riddhij0804** [comment]
Ok got it!Thanks for assigning.
