### ISSUE TITLE
Add a Page for Proper ML Projects 

### ISSUE THREAD

**Issue by Sapta-Dev27** [ML-Fusion-Lab/ML-Fusion-Lab-Website#15]
Features :
1. Proper  Projects from Github 
2. Projects For Interview Purposes
3. Projects From Yt for Hackathons Purposes

**Comment by vivekvardhan2810** [comment]
@Sapta-Dev27 this website should be like to make and collaborate with other developers, to work on innovative projects

Not like the projects should already been there

So i am closing this issue.

make sure to join the discord for further communication and updates: https://discord.gg/FZxBRpTEeH
