### ISSUE TITLE
Features: The projects section of the webpage 

### ISSUE THREAD

**Issue by Lekkhasri** [ML-Fusion-Lab/ML-Fusion-Lab-Website#150]
The projects section of the webpage is looking collapsed i would like to work on it . Can you assign it to me .
![Uploading ml labs.png…]()

**Comment by faisal07777** [comment]
please give full description nd also share related photos

**Comment by Lekkhasri** [comment]
![ml fusion labs](https://github.com/user-attachments/assets/2e392bc9-6ec2-46dc-9239-7c4e94f96bf8)
@faisal07777 assign this work to me

**Comment by Lekkhasri** [comment]
![Screenshot 2024-10-04 215255](https://github.com/user-attachments/assets/6cc0a0ba-28fa-465e-aacf-8284c59850c0)
@faisal07777 assign this issue to me i will rectify it

**Comment by vivekvardhan2810** [comment]
@Lekkhasri sure go ahead

make sure to join the discord server for further communication

and also star the repo

complete the task in next 2 days

**Comment by Lekkhasri** [comment]
@vivekvardhan2810 can you add hacktoberfest tag also sir
