### ISSUE TITLE
Features: The contact section  looks collapsed

### ISSUE THREAD

**Issue by Lekkhasri** [ML-Fusion-Lab/ML-Fusion-Lab-Website#151]
The contact section of the webpage looks collapsed and the footer also not in the correct alignment .
i would like to work on this issue . can you assign the issue to me.
![Uploading ml fusion labs.png…]()

**Comment by komal-kumawat** [comment]
The contact section of the webpage looks collapsed . I would like to work on it so **Please** assign this issue to me under **GSSOC extended**.

**Comment by vivekvardhan2810** [comment]
@Lekkhasri assigning this issue to you.
