### ISSUE TITLE
Fix Footer Section Background Color

### ISSUE THREAD

**Issue by Abhishek-223** [ML-Fusion-Lab/ML-Fusion-Lab-Website#153]
The footer section of the website currently has an incorrect or inconsistent background color. It either does not match the overall design of the website or doesn't meet the desired color specified in the design requirements.

**Comment by vivekvardhan2810** [comment]
@Abhishek-223 sure go ahead

make sure to join the discord server for further communication

and also star the repo

complete the task in next 2 days

**Comment by jyothimanoj12** [comment]
can you assign this issue for me to work on
