### ISSUE TITLE
Alignment of the project section should be altered

### ISSUE THREAD

**Issue by jeevika17** [ML-Fusion-Lab/ML-Fusion-Lab-Website#159]

**Comment by srishti023** [comment]
The alignment of the project section is currently off. The project cards are not evenly spaced, and the text appears misaligned in some cases.

Proposed Solution:

Implement a responsive grid layout (using CSS Grid or Flexbox) to ensure even spacing between project cards on all screen sizes.
Add consistent margins and padding around the project items.
Ensure the text inside each project card is properly centered and aligned.
Test the alignment on different devices and screen sizes to ensure a responsive design. 

Please assign me this issue under gssoc'24 extd and hacktoberfest 2024.

Thank you

**Comment by vivekvardhan2810** [comment]
This problem is solved.

So i am closing this issue.
