### ISSUE TITLE
Text is not visible clearly at some parts of the website

### ISSUE THREAD

**Issue by sriraghavi22** [ML-Fusion-Lab/ML-Fusion-Lab-Website#161]
![WhatsApp Image 2024-10-04 at 23 00 04_88d1aa7c](https://github.com/user-attachments/assets/79f3b487-c24a-484f-a906-27530f06a81d)

In the image the text below the image is not visible and size of the text for parts of the website is comparatively small.

Also community support card doesn't match with other two cards. It takes off the look of the website.

I would like to work on these issues.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
