### ISSUE TITLE
Bug report : Dark mode feature is not present in Home page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#164]
**the dark mode feature isnt present in the home page , if you could assign me this then i would fix this.**

**Comment by vivekvardhan2810** [comment]
Okay @T-Rahul-prabhu-38 assigning this issue to you

**Comment by T-Rahul-prabhu-38** [comment]
@vivekvardhan2810  sir ive made 1 pull request about refactring css if u can pass it i can call for this fix as well

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 I will look it by tomorrow.

**Comment by T-Rahul-prabhu-38** [comment]
im soo sorry to disturb u sir , but what should i do with my current Issue as i cant call 2PR's.

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 don't worry mention the other issue number in the PR and change the title then I will upgrade the level

**Comment by T-Rahul-prabhu-38** [comment]
sure sir ill do that.

**Comment by vivekvardhan2810** [comment]
i am closing this issue, as this issue was resolved.
