### ISSUE TITLE
ADDING LOGIN AND SIGNUP OPTION AS WELL AS PAGE TO THE SITE

### ISSUE THREAD

**Issue by dnyanesh99borse** [ML-Fusion-Lab/ML-Fusion-Lab-Website#165]
**### ADDING LOGIN AND SIGNUP OPTION AS WELL AS PAGE TO THE SITE**

I have to add the login and signup option to the header of the main page and then after clicking on that the user will redirect to the login and signup  page and then i will also make the separate login and signup page with the fully user interaction and will make it very effective.

which will definately helps the user to interact with the site very effectively and spend more time on the site and also will get chance to register and be the member of the site without missing any future updations and all.

**Comment by dnyanesh99borse** [comment]
AS A EXPERIENCED FRONTEND DEVELOPER I HUMBLY REQUESTING YOU TO PLEASE ASSIGN THIS TASK TO ME I CAN RESOLVE THIS TASK VERY EFFECTIVELY AND CAN ENHANCE THE SITE 10X THAN THE EARLIER ONE. ~thankyou 

**you can refer my work on the basis of the data provided below:**
![image](https://github.com/user-attachments/assets/1923e454-3c27-4ef7-856f-b464eab557a9)


![image](https://github.com/user-attachments/assets/9058a209-2e8e-4875-a5f7-cf62dfbbfb0f)

**Comment by ANANDISHARMA0109** [comment]
Please assign this task to me under ggsoc-extd 24 and hacktoberfest. I can add login/signup very efficiently. @tabinayaseen
