### ISSUE TITLE
update the about page 

### ISSUE THREAD

**Issue by rounakdey6** [ML-Fusion-Lab/ML-Fusion-Lab-Website#166]
when we are on about page , the name of the website is not showing 
please assign this work to me

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by rounakdey6** [comment]
please level this issue

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
