### ISSUE TITLE
Inconsistent UI in About Section

### ISSUE THREAD

**Issue by srishti023** [ML-Fusion-Lab/ML-Fusion-Lab-Website#167]
![Screenshot (33)](https://github.com/user-attachments/assets/c89f771f-d38f-4318-b6f0-2000335fa213)
The UI of the "About" section does not align with the design and layout of the other pages on the website. The section feels inconsistent and lacks the cohesive style seen throughout the rest of the site.
1. the text is not visible in header part
2. does not match the color scheme used in other sections of the website.
 
please assign me this task with gssoc-ext and hecktoberfest

**Comment by vivekvardhan2810** [comment]
i am closing this issue, since i have assigned you the issue 2 days ago.

**Comment by srishti023** [comment]
Work in progress:

https://github.com/user-attachments/assets/5f9d61c0-4413-46d4-afdd-1deb6e2fa07d

Hi @vivekvardhan2810 ,

I hope you're doing well. I apologize for the delayed response regarding the issue assigned to me. I have been working on it and am making good progress. I will be able to complete it by tonight.

Could you kindly reopen the issue so I can proceed further and submit my work? I truly appreciate your understanding and patience.

Thank you for your support!

Best regards,

**Comment by vivekvardhan2810** [comment]
I have reopened this issue, make sure to complete it on time.
