### ISSUE TITLE
Adding Relevant Content to the Course Introduction to Machine Learning, making it a Structured Course.

### ISSUE THREAD

**Issue by Amanjayswal500** [ML-Fusion-Lab/ML-Fusion-Lab-Website#169]
I want to make the whole Structured and Organized Course Structure for Introduction to Machine Learning which will make it a complete course Structured for 3 weeks. I'll be covering each and everything important in Introduction to Machine Learning including types of ML and key algorithms course along with making it visible and Interactive on the web site. I will also try to include a Assessment test at the end of this course.

Please assign me this issue under gssoc-ext label.

![Screenshot 2024-10-05 002747](https://github.com/user-attachments/assets/5a0d4531-7940-4cce-bd54-e6fcde2d7d47)

**Comment by Amanjayswal500** [comment]
hello @faisal07777 can you assign this to me

**Comment by Amanjayswal500** [comment]
hello @vivekvardhan2810 can you assign this to me as I really want to work on this project?

**Comment by Siddhant432** [comment]
If you want @vivekvardhan2810  I can structurize it properly.

**Comment by vivekvardhan2810** [comment]
@Siddhant432 pls wait if he doesn't completes, then i will assign you.

**Comment by Siddhant432** [comment]
ok  no problem

**Comment by vivekvardhan2810** [comment]
I am closing this issue, as the courses page was updated.
