### ISSUE TITLE
Bird icon to X icon

### ISSUE THREAD

**Issue by sriharsha0x1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#170]
![image](https://github.com/user-attachments/assets/29b8218f-9727-4805-befe-3bf39bcc4506)
Could you please assign this to me?

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by ChauhanAyush04** [comment]
Plz assign me this issue

**Comment by vivekvardhan2810** [comment]
This issue was assigned earlier, so i am closing this issue
