### ISSUE TITLE
Toggle button is not working when appears in small pages

### ISSUE THREAD

**Issue by sayanp607** [ML-Fusion-Lab/ML-Fusion-Lab-Website#171]
![Screenshot 2024-10-05 010932](https://github.com/user-attachments/assets/f0d10e45-aefc-4be8-8c05-cecdf472b3a2)
the toggle button on the top right corner do not respond while clicking. Please assign me this task , I will solve it.

**Comment by iamprathama** [comment]
Please assign me this task , I will solve it.

**Comment by sayanp607** [comment]
> @sayanp607 can you fix this issue.
> 
> Sorry for the late reply from my side.
Sure,assign me please

**Comment by vivekvardhan2810** [comment]
@sayanp607 assigning this issue to you.

Make sure to complete this within 2 days.

**Comment by vivekvardhan2810** [comment]
@sayanp607 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

**Comment by sayanp607** [comment]
> @sayanp607 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

i have newly forked the whole repository and doing code newly.

**Comment by vivekvardhan2810** [comment]
Done, @sayanp607 thank you.
