### ISSUE TITLE
 Update the Design of "ML Fusion Labs" Section

### ISSUE THREAD

**Issue by sahhoArjun097** [ML-Fusion-Lab/ML-Fusion-Lab-Website#172]
The "ML Fusion Labs" section of the website needs a design update to improve its visual appeal and user engagement. The current layout and style require enhancements to align with the latest design trends and provide a more professional look.

![Screenshot 2024-10-05 022722](https://github.com/user-attachments/assets/d27673f3-8ae3-43a9-bdb1-2734d306852c)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by vivekvardhan2810** [comment]
@sahhoArjun097 assigned it.

make sure to complete this work in the next 3 days.

**Comment by Akanshaku** [comment]
I would like to work on this issue updating its design to look more modern style for users. @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@Akanshaku this issue was assigned before.
