### ISSUE TITLE
Hamburger Menu is not working in small devices

### ISSUE THREAD

**Issue by Raj-Aditya-27** [ML-Fusion-Lab/ML-Fusion-Lab-Website#173]
@vivekvardhan2810 

![image](https://github.com/user-attachments/assets/537a6490-228d-4d0f-ade8-14ac3783209d)

Hamburger Menu is not working. when user clicks on it , nothing is happening.
Please assign this issue to me.
I will fix it.

And please add label to it.

**Comment by Raj-Aditya-27** [comment]
Hii @vivekvardhan2810 
Can you please assign it to me?
Please add gssoc extd,hactoberfest and level label

**Comment by Smit1610** [comment]
@vivekvardhan2810 Please assign this issue to me under hactoberfest 24

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue
