### ISSUE TITLE
Changes in home page

### ISSUE THREAD

**Issue by karthik-kiran-29** [ML-Fusion-Lab/ML-Fusion-Lab-Website#175]
1.The Line below the nav will respond to the scroll that is when they are at top it will be only little visible and increase as they scroll.
![image](https://github.com/user-attachments/assets/6638e4ec-a2c3-433d-bb7a-32556526b85c)
2.about section is bugging.Can improve and add something to it to make them look good.
![image](https://github.com/user-attachments/assets/e8067229-b3fa-4dc6-aa45-ee06eb8020d9)
3.Add dark mode in the home page.
4.rearrange the footer so socials appear at the top, i can change them completely as well.
![image](https://github.com/user-attachments/assets/82b8dc37-8c9c-4bd4-8544-2922450792ec)
assign me under hactoberfest and gssoc-extd, Thank you.
@vivekvardhan2810

**Comment by ANANDISHARMA0109** [comment]
1 . Same content is repeated various  times on  home page
![Screenshot 2024-10-05 091151](https://github.com/user-attachments/assets/383bc391-2f0d-4c72-b1e4-f59648ced29a)

2. No dark mode for home page
![Screenshot 2024-10-05 091939](https://github.com/user-attachments/assets/7a506d3a-6fa2-4545-a511-5677f977cddd)

Please  assign this task to me under ggsoc-extd 24 and hactoberfest. @tabinayaseen

**Comment by faisal07777** [comment]
as a mentor i can only assign level 1 label it will further decide by project admin

**Comment by pameladeysarkar2003** [comment]
@faisal07777 kindly please assign me with this task.

the necessary solution is:

1. necessary css is to added in about section to improve and look good.
2. add dark mode on the page

kindly add hactoberfest and gssoc-extd

**Comment by vivekvardhan2810** [comment]
@pameladeysarkar2003 again I am repeating don't spam in other's issues, this is not a good practice and this issue was assigned before.

**Comment by vivekvardhan2810** [comment]
This issue has been resolved, so i am closing this issue.
