### ISSUE TITLE
Adding anchor to redirect to homepage

### ISSUE THREAD

**Issue by shimmer12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#177]
![image](https://github.com/user-attachments/assets/4e2aac9c-8e16-4d34-a475-9c62f08bb938)

I would like to add anchor to the logo of website so that it can be redirected to root page whenever someone clicks on it from any page

Thank you !

@vivekvardhan2810  please assign this issue to me under gssoc extd and hacktoberfest accepted .

- [ ]  the dark  mode for home page not working
- [x] I have read guidelines for issue raiseing
- [ ] I want to fix this issue

**Comment by vivekvardhan2810** [comment]
@shimmer12 this issue was assigned before, so i am closing the issue, and someone by mistakenly mentioned this issue number in PR, His PR Was different, he rectified it.

**Comment by shimmer12** [comment]
okay sure, but i can see no updates about this issue as resolved on site

**Comment by vivekvardhan2810** [comment]
@shimmer12 some one raised the PR, and he is resolving the conflicts, and his issue was the same.

**Comment by shimmer12** [comment]
okay I get it, thank you. New to contributing.
