### ISSUE TITLE
First of all the main issue is responsiveness and second thing, i think a bit of animations on landing page main container texts make the website more interactive! 

### ISSUE THREAD

**Issue by Ashish2k03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#18]

**Comment by vivekvardhan2810** [comment]
@Ashish2k03 pls elaborate your detailed solution

**Comment by Ashish2k03** [comment]
> @Ashish2k03 pls elaborate your detailed solution

The main text on the landing page, "Learn Machine Learning with Us," doesn't sound quite right. How about changing it to "Learn ML with Us!"? Additionally, I suggest adding some text animation when the webpage loads, as well as container animations when scrolling down, to enhance the website's overall appearance.

Also, please take a look at the "Our Features" section—it is not responsive. The navbar button is floating outside of the navbar, which needs to be addressed.

**Comment by vivekvardhan2810** [comment]
Okay, @Ashish2k03, assigning this issue to you.

I am giving you level 3 for responsiveness and text animation.

And do not change the text.

**Comment by vivekvardhan2810** [comment]
yes, it will be counted @Ashish2k03

**Comment by Ashish2k03** [comment]
> yes, it will be counted @Ashish2k03 

Sir I added the changes please check it and give feedback.
