### ISSUE TITLE
Repetitive Content and Poor Engagement on the Homepage

### ISSUE THREAD

**Issue by snehhhcodes** [ML-Fusion-Lab/ML-Fusion-Lab-Website#180]
Hey there!!

I hope this message finds you well. I would like to address an issue I encountered on the website and propose a solution that I believe will enhance the user experience:

# Description of issue:

The homepage currently contains repetitive text, making it less engaging for users. Additionally, the "About Us" section has a separate page, which may not be necessary. This redundancy can lead to user disengagement, as visitors may lose interest in the content. Moreover, having "About Us" on a separate page diverts attention from the homepage, where users typically seek concise and relevant information. Users are unlikely to navigate to the "About Us" page, missing out on essential context about the platform.

# Proposed Solution:

To enhance user experience, the homepage should feature more engaging content that is visually appealing and easy to digest. The proposal includes:

1.) Removing repetitive text to make the content more concise and impactful.
2.) Integrating the "About Us" information directly into the homepage, allowing users to access essential details without navigating to a separate page.
3.) Implementing a better layout that presents important information in a visually appealing format, making it easier for users to quickly grasp the site’s purpose and offerings.

I've added a video so you can better visualize the issue.

[screen-capture.webm](https://github.com/user-attachments/assets/82f35062-e407-406c-a14a-30c2c80e329d)

If you find this issue/proposed solution suitable, please assign this to me under the labels of GSSoC and Hacktoberfest and appropriate level.

**Comment by vivekvardhan2810** [comment]
@snehhhcodes assigned this issue to you.

**Comment by vivekvardhan2810** [comment]
@snehhhcodes why did you close this issue, I will reopen it for now, while I will merge then I will close this issue.
