### ISSUE TITLE
Success Confirmation Message in Contact us page

### ISSUE THREAD

**Issue by anish013326** [ML-Fusion-Lab/ML-Fusion-Lab-Website#182]
#### Success Confirmation Message: After the user submits the form, display a confirmation message like "Your message has been successfully sent. Our team will get back to you soon!

![Screenshot 2024-10-05 131054](https://github.com/user-attachments/assets/1a7fbfa9-10dc-480a-8d08-8d09b767c6bb)
 when user send message they have not idea about send or not send

**Comment by anish013326** [comment]
#### sir you may have pulled a wrong request in main branch plz check it once because all the pages are mixed up and UI  is also mixed

![image](https://github.com/user-attachments/assets/12d99637-feca-4fff-b6a8-0655736e51e7)

**Comment by pameladeysarkar2003** [comment]
@vivekvardhan2810 kindly please assign me with this task i'm looking forward for contribution.
<h3>[response]</h3>  
by using this tag we can solve this issue

**Comment by vivekvardhan2810** [comment]
@pameladeysarkar2003 this issue was assigned before and please don't spam on every issue.

**Comment by vivekvardhan2810** [comment]
this issue was completed and solved, so i am closing this issue.
