### ISSUE TITLE
unwanted thing in About us page 

### ISSUE THREAD

**Issue by anish013326** [ML-Fusion-Lab/ML-Fusion-Lab-Website#183]
#### To identify and remove unwanted elements from an "About Us" page, consider the following common issues that might be unnecessary or detract from the page's quality:

![image](https://github.com/user-attachments/assets/ac54e34c-0dea-401d-b427-b17bcef3c283)

**Comment by vivekvardhan2810** [comment]
@anish013326 this issue was completed before, so i am closing this issue.
