### ISSUE TITLE
Better ui - adding graphics

### ISSUE THREAD

**Issue by ANANDISHARMA0109** [ML-Fusion-Lab/ML-Fusion-Lab-Website#184]
all pages look kind of plain with no  images or graphics. Please issue me this task under ggsoc extd 24 and hacktoberfest. @tabinayaseen

![Screenshot 2024-10-05 132053](https://github.com/user-attachments/assets/237210bb-cafd-47d1-beb3-131bf3637cf3)
![Screenshot 2024-10-05 132112](https://github.com/user-attachments/assets/7757a09b-f2ce-43ef-9a91-c1ed79057b95)

i can add graphics to make it look more appealing

**Comment by tabinayaseen** [comment]
May I know you. ?
Because I didn't submit any project

**Comment by ANANDISHARMA0109** [comment]
are you not ggsoc extd 24 mentor for project "ML Fusion"?

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
