### ISSUE TITLE
 Implement a Mini Chatbot for this website

### ISSUE THREAD

**Issue by DivyaJyothi9** [ML-Fusion-Lab/ML-Fusion-Lab-Website#186]
This issue involves the development of a mini chatbot for the platform. The chatbot will provide users with an interactive experience, helping them explore ML courses, hands-on projects...

Kindly assign this issue to me..I would like to contribute.
Kindly add the label Gssoc-ext, Hactoberfest, and level-3..as it needs to integrate.
Thank you!!

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 make sure to join the discord.

**Comment by DivyaJyothi9** [comment]
Sure @vivekvardhan2810 
Thank you

**Comment by pameladeysarkar2003** [comment]
this issue involves the implementation of mini chatbot which will provide the users for interactive experience.
@vivekvardhan2810 kindly please assign me with this task i would like to contribute
thank you..

**Comment by vivekvardhan2810** [comment]
@pameladeysarkar2003 this issue was assigned before.

**Comment by DivyaJyothi9** [comment]
@vivekvardhan2810 I have created the PR #236 ..for the issue #186.
kindly check it..Assign the labels as well.
Thank you!!
