### ISSUE TITLE
footer problem

### ISSUE THREAD

**Issue by Amankr200** [ML-Fusion-Lab/ML-Fusion-Lab-Website#187]
footer have problems @faisal07777 pls assign it to me
![Screenshot 2024-10-05 151729](https://github.com/user-attachments/assets/b8af4a67-8db4-4e5a-acc4-a5ee2545be03)

**Comment by vivekvardhan2810** [comment]
@Amankr200 this issue was assigned to someone.

make sure to join discord server.
