### ISSUE TITLE
ui of contact us page is messed up 

### ISSUE THREAD

**Issue by saurabhsagar99** [ML-Fusion-Lab/ML-Fusion-Lab-Website#188]
![image](https://github.com/user-attachments/assets/ae9efa0f-9b70-4520-9fcc-3eedc7ebbe03)
ui of contact us page is messed up and in addition there are some unwanted code snippets. I will fixed those errors and also make a impressive contact us page

**Comment by vivekvardhan2810** [comment]
@saurabhsagar99 

make sure to join discord server.
