### ISSUE TITLE
add FAQs section to Footer 

### ISSUE THREAD

**Issue by devxMani** [ML-Fusion-Lab/ML-Fusion-Lab-Website#19]
For a better description of the company 
assign me this task add Gsoc extended label to it.

**Comment by vivekvardhan2810** [comment]
Hi, @devxMani we can put this issue in later updates.

I will Let You know about this.

make sure to join discord channel: https://discord.gg/FZxBRpTEeH

for further communication and updates.

**Comment by devxMani** [comment]
okk sure

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by ManjeshGowda06** [comment]
Hi, can I take this issue and work on it?

**Comment by ManjeshGowda06** [comment]
if yes please assign this work on the label of gssoc extended 24

**Comment by eddy1112004** [comment]
Please assign this task to me

**Comment by naitikhoriya1** [comment]
Hi @ML-Fusion-Lab,

I’d like to take up this task: add FAQs section to Footer #19. I’m confident I can complete it and contribute to the project.

Could you please assign it to me? I’ll make sure to deliver by the deadline and follow the project’s guidelines closely. If there are any specific requirements or preferences, feel free to let me know.

Looking forward to your approval!

Thanks,
@naitikhoriya1

**Comment by vivekvardhan2810** [comment]
@devxMani can you complete this issue now.

i am gonna assign you.

**Comment by devxMani** [comment]
@vivekvardhan2810 ok I'll do that

**Comment by vivekvardhan2810** [comment]
this project is going to be inactive from october 25th including me also.

**Comment by vivekvardhan2810** [comment]
@devxMani have you done with this task.

**Comment by devxMani** [comment]
@vivekvardhan2810 I'll do this issue today
