### ISSUE TITLE
Footer Improvement

### ISSUE THREAD

**Issue by akshattiwarii** [ML-Fusion-Lab/ML-Fusion-Lab-Website#193]
![Screenshot from 2024-10-05 16-25-16](https://github.com/user-attachments/assets/fbb5b081-ddb9-4b55-a454-2d8a54687dc8)

I can make this type of productive footer in website. If yo like this format you can assign this function to me.

**Comment by vivekvardhan2810** [comment]
@akshattiwarii i have assigned this issue before, if he does that then i will be closing this issue.

if he doesn't complete it then i will be assigning this issue to you.

**Comment by vivekvardhan2810** [comment]
we will look for this later, so i am closing this issue.

Please Understand.
