### ISSUE TITLE
making courses page visible correctly

### ISSUE THREAD

**Issue by devxMani** [ML-Fusion-Lab/ML-Fusion-Lab-Website#20]
![Screenshot 2024-10-01 220047](https://github.com/user-attachments/assets/54b10544-daa5-4760-a0da-8579e0eabe59)

**Comment by devxMani** [comment]
can you assign me this task

**Comment by vivekvardhan2810** [comment]
@devxMani, please elaborate with detailed solution.

**Comment by devxMani** [comment]
machine learning courses text is not visible

**Comment by vivekvardhan2810** [comment]
Hi @devxMani, 

It has been done previously like kept for PR and ready for merge 

But still I will encourage you to look for other issues in website like improvements.

I am closing this issue.
