### ISSUE TITLE
[FEATURE] : Can add scroll animations in your website :)

### ISSUE THREAD

**Issue by Vatsal-Verma** [ML-Fusion-Lab/ML-Fusion-Lab-Website#202]
I can add scroll animations in your website , When you scroll down then different elements of your website will appear in different effect i.e. (Incoming or outgoing effect) , It will not only make your website look better and catchy but will make it look more professional. You can assign this to me , I can do it for you :)

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
For now it is not required, we will look it for later, So I am closing this issue, Please Understand.
