### ISSUE TITLE
[Mention The Feature]: Add Pre-loader

### ISSUE THREAD

**Issue by soumyajit254** [ML-Fusion-Lab/ML-Fusion-Lab-Website#207]
### Is your feature request related to a problem? Please describe.

I want to add a pre-loader

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by soumyajit254** [comment]
please assign this issue. I want to contribute.

**Comment by vivekvardhan2810** [comment]
we don't need this for now, so i am closing this issue.
