### ISSUE TITLE
Design a Logo and Add it as Favicon to Enhance Brand Credibility

### ISSUE THREAD

**Issue by manninookala** [ML-Fusion-Lab/ML-Fusion-Lab-Website#21]
**Under gssoc-exd2024 :**
The ML Fusion Labs platform currently lacks a logo, which impacts brand identity and recognition. A logo is essential for building user trust and brand credibility. Additionally, a favicon (a small icon visible in the browser tab) would improve the user experience by providing a visual cue associated with the website.

This issue involves two tasks: designing a logo for ML Fusion Labs and adding it as a favicon on the website.

A logo will improve brand recognition and build trust among users.
A favicon enhances user experience by giving a visual cue on the browser tab, making the website more professional.

![image](https://github.com/user-attachments/assets/0008bc48-ecee-4f85-ad00-1495b9a81f52)

**Comment by vivekvardhan2810** [comment]
Hi @manninookala, assigned this issue.

make sure to join discord channel: https://discord.gg/FZxBRpTEeH, for further communication and updates.

make sure to complete this issue for the next 2 days.

**Comment by manninookala** [comment]
@vivekvardhan2810 
Resolved the Issue, added the favicon & Logo.
Added it to the pull request.
Thank you.

**Comment by vivekvardhan2810** [comment]
@manninookala why did you close the issue

**Comment by manninookala** [comment]
@vivekvardhan2810 I have fixed the issue and added it to the pull request. So I have closed the Issue. 
Am I not allowed to close it this way?

**Comment by vivekvardhan2810** [comment]
@manninookala No you shouldn't close, untill i merge it. I am reopening this issue.

Once i will merge it then i will close this issue.

**Comment by manninookala** [comment]
@vivekvardhan2810 Ok. Thanks for letting me know. This is my first time contributing. Thanks for letting me know.
