### ISSUE TITLE
[Mention The Feature]: Add a Slider to the Features Section

### ISSUE THREAD

**Issue by 19Sonali** [ML-Fusion-Lab/ML-Fusion-Lab-Website#213]
### Is your feature request related to a problem? Please describe.

I would like to contribute by adding a slider to the features section to enhance the user experience. A slider can help present the features in a more visually appealing and interactive way, making the website more engaging.
![Screenshot 2024-10-05 221707](https://github.com/user-attachments/assets/1009deab-29af-49c8-b377-1356162d4ccb)

### Describe the solution you'd like.

I plan to implement a responsive slider for the features section, using a library like Slick Slider to improve the presentation of features.

### Additional context.

Kindly assign this issue to me under Hacktoberfest and GSSoC-Extd. Thank you!

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
not needed, so closing this issue.
