### ISSUE TITLE
add functionality to newsletter form

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#216]
### Is your feature request related to a problem? Please describe.

add functionality to accept user response and display the respective subscribing popup message 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
