### ISSUE TITLE
[BUG] contact us submission allows single-letter input

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#217]
### Description

contact us submission allows single-letter input This leads to unhelpful and incomplete feedback. 

### Steps to Reproduce

A minimum character limit should be enforced to ensure meaningful responses.

### Expected Behavior

The form should enforce a minimum character limit (e.g., 10 characters) to ensure users provide more detailed and meaningful message.

### Actual Behavior

Users can submit feedback with only a single letter, resulting in incomplete and non-actionable responses.

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues).
- [X] I have read the [Code Of Conduct](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by maniacedoc** [comment]
I would like to work on this issue, please assign me

**Comment by faisal07777** [comment]
Hey @ananyag309  I'm assigning this issue to you. Please submit it within 3 days. As a mentor, I can only assign the 'Level 1' label the project admin will decide the rest.
