### ISSUE TITLE
✨[BUG] Dark mode not avaiable in home page and UI of about us page is broken✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#220]
### Description

the dark mode is not shown in the home page and the Ui of about us page is not aligning with the other pages.

### Additional Information

<img width="1445" alt="Screenshot 2024-10-06 at 9 54 52 AM" src="https://github.com/user-attachments/assets/4a351008-0d97-43ec-8237-0eda46573465">

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues).
- [X] I have read the [Code Of Conduct](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigning this issue to you.
