### ISSUE TITLE
[Mention The Feature]: Want to changes the css of the home page

### ISSUE THREAD

**Issue by Dipanita45** [ML-Fusion-Lab/ML-Fusion-Lab-Website#221]
### Is your feature request related to a problem? Please describe.

Transform , effect, etc 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was resolved, so I am closing this issue.
