### ISSUE TITLE
[BUG] Issue with Project and About Modules

### ISSUE THREAD

**Issue by sadafhukkeri** [ML-Fusion-Lab/ML-Fusion-Lab-Website#224]
### Description

When clicking on the "Learn More" option in the Project module, the project details appear incorrectly on the main page, overlapping the existing content. The close button (cancel) does not function properly to close the project details. Additionally, upon navigating to the About module, the contents of the navigation bar appear misaligned and display below the navigation bar instead of within it.
![Screenshot (150)](https://github.com/user-attachments/assets/d42d9e1b-aee8-447d-8dde-749574cfaabb)
![Screenshot (151)](https://github.com/user-attachments/assets/4f3a279c-64ae-46b0-b572-53f7577b2d24)

### Steps to Reproduce

1.Go to the "Projects" section.
2.Click on "Learn More" for any specific project.
3.Observe how the project details overlap with the main content of the page, and try to close it with the cancel button (which doesn't work properly).
4.Then, go to the "About" section.
5.See how the navigation bar's contents are displayed incorrectly below the actual navigation bar.

### Expected Behavior

1.The project details should appear in a proper modal or dedicated section without overlapping other content.
2.The cancel button should successfully close the project details.
3.The About page should display navigation bar contents aligned correctly within the navigation area.

### Actual Behavior

1.The project details are displayed on the main page, overlapping existing content.
2.The cancel button is non-functional.
3.The About page shows the navigation bar contents misaligned and appearing below the navigation bar.

### Additional Information

The issue occurs on the ML Fusion Labs website when navigating through the Project and About modules. The user experience is affected as content presentation is broken, and the cancel button does not function as expected.

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues).
- [X] I have read the [Code Of Conduct](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by sadafhukkeri** [comment]
i want to work on this project please assign me

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
