### ISSUE TITLE
[BUG] Popular courses card's width bug

### ISSUE THREAD

**Issue by SurajSG23** [ML-Fusion-Lab/ML-Fusion-Lab-Website#226]
### Description

Hey, I noticed that in your courses page the cards width is not proper,

![image](https://github.com/user-attachments/assets/cf05d48f-a645-4c46-8c66-6614a87aa8c7)

i would like to fix it and make it more appealing UI! and make it responsive too.
please assign me this task under gssoc and hacktoberfest and a level, Thank You  🙏

### Steps to Reproduce

Fix the issue in Courses page

### Expected Behavior

card content should be within the card, 

### Actual Behavior

card content is overflowing!, width not taking the proper pixels or vw of the website 

### Browser

Chrome

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues).
- [X] I have read the [Code Of Conduct](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] The changes don't break the code
- [X] Please attach screenshots and videos of the development work once done

**Comment by vivekvardhan2810** [comment]
@SurajSG23 this issue was assigned before and he kept the PR, and he is fixing it, so i am closing this issue. You can look for other issues in website.
