### ISSUE TITLE
[Mention The Feature]: UI Updates

### ISSUE THREAD

**Issue by akhil11sharma** [ML-Fusion-Lab/ML-Fusion-Lab-Website#227]
### Is your feature request related to a problem? Please describe.

<img width="947" alt="Screenshot 2024-10-06 at 1 24 02 PM" src="https://github.com/user-attachments/assets/eb2c90a0-af43-4599-9b52-6cf6fdc226c0">
 i as we can see, the website bar doesnt have good button alignment as well as being very simple

### Describe the solution you'd like.

I can make changes to these buttons and give good animations on hovering 

### Describe alternatives you've considered.

<img width="691" alt="Screenshot 2024-10-06 at 1 26 39 PM" src="https://github.com/user-attachments/assets/d0aea258-3ec0-4e5e-95b5-52f368d30221">
Can add some hovering or animation effect on this to make it more interactvee

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was resolved before, but still i would encourage you to look for other issues in website improvements, then you can create an new issue,
