### ISSUE TITLE
  Want to improve the text layout and typography  and add some different effects 

### ISSUE THREAD

**Issue by Vaibhavkumar5158** [ML-Fusion-Lab/ML-Fusion-Lab-Website#231]
![image](https://github.com/user-attachments/assets/dc709a20-7c4b-4789-91be-c37eb2735fd4):

 The text layout and typography don't distinguish enough between sections, making it hard for users to navigate

so I want to fix this bug .

Pls add GSSOC EXTD'24 and HACKTOBERFEST Badge and level .
@ML-Fusion-lab

Thank you, looking forward to contribute .

**Comment by vivekvardhan2810** [comment]
this issue was resolved and the courses page was updated, so i am closing this issue.
