### ISSUE TITLE
Proposal: Courses page is not properly structured

### ISSUE THREAD

**Issue by Siddhant432** [ML-Fusion-Lab/ML-Fusion-Lab-Website#237]
### Is your feature request related to a problem? Please describe.

I will correct the structurisation of the courses. The content is coming out of the boxes.
![Screenshot (476)](https://github.com/user-attachments/assets/3ed8ab6e-aa44-4f26-9b0b-3040397ab8d7)

### Describe alternatives you've considered.

I will correct with bootstrap with proper design and structure.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Siddhant432** [comment]
Pls assign me this task. I will do it properly.

**Comment by vivekvardhan2810** [comment]
@Siddhant432 this issue was assigned before, and he is updating it.

**Comment by Siddhant432** [comment]
ok thank you for telling @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
