### ISSUE TITLE
[Mention The Feature]: Blogs section

### ISSUE THREAD

**Issue by kanCHI-Singhal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#238]
### Is your feature request related to a problem? Please describe.

If someone wants to see the users experience towards this site and id you want to advertise your courses then you need a separate section for it.

### Describe the solution you'd like.

I want to build a Blogs section in a home page as well as add it in the nav bar .
Please assign me this issue under the labels of Gssoc-extd, hacktoberfest, hacktoberfest-accepted and relevant level.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal make sure to join discord server mentioned in readme.

**Comment by kanCHI-Singhal** [comment]
Ok I will join the discord server and will complete this issue in next two days.

**Comment by kanCHI-Singhal** [comment]
Thank you for assigning me this issue. I will resolve this issue very soon .

**Comment by kanCHI-Singhal** [comment]
Hey I had created a pull request for the blogs section, please review it and tell me if any changes required, else accept it.

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by vivekvardhan2810** [comment]
@SaanyaGarg5 please don't spam on other's issues.

**Comment by vivekvardhan2810** [comment]
> @kanCHI-Singhal will it be okay for you, if i close this issue, so that you can work for other issues.
> 
> as for now blog section is not required.

@kanCHI-Singhal please reply.

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal please reply, 

will it be okay for you, if i close this issue.

as for now blog section is not required.

**Comment by vivekvardhan2810** [comment]
@kanCHI-Singhal please reply,

will it be okay for you, if i close this issue.

as for now blog section is not required.

**Comment by vivekvardhan2810** [comment]
Hi @kanCHI-Singhal 

It’s been over 3 weeks without any updates. I will be closing this issue by the end of the day. If you have any progress to share, please do so before then.

Thank you!

**Comment by vivekvardhan2810** [comment]
i am closing this issue, as there is no update from your side since 2 weeks. as for now blog section is not required.
