### ISSUE TITLE
Enhanced Scroll Button Design: Height, Width, Line-Height, and Color Adjustment

### ISSUE THREAD

**Issue by YOGINIMAHIMA1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#241]
Height Adjustments: Increased the button's height for improved accessibility.
Width Adjustments: Modified the width to create a more balanced appearance.
Line-Height Adjustments: Optimized line-height for better text readability within the button.
Color Changes: Updated the color to enhance visibility and match the overall design theme.

**Comment by vivekvardhan2810** [comment]
@YOGINIMAHIMA1 this is not needed, so i am closing this issue.
