### ISSUE TITLE
Improving "Our Popular Courses" page

### ISSUE THREAD

**Issue by komalnalage** [ML-Fusion-Lab/ML-Fusion-Lab-Website#242]
Hi @vivekvardhan2810 .I can improve Our Popular page to make it look more eye-appealing and easy to use .
![image](https://github.com/user-attachments/assets/5a23e5cb-c01b-49a7-9cfd-578ab0966761)
Could you assign me this issue and add labels gssoc-ext and hactoberfest-accepted ?

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
