### ISSUE TITLE
[Feature Request] Addition of Images to the Project Cards 

### ISSUE THREAD

**Issue by priyanka350** [ML-Fusion-Lab/ML-Fusion-Lab-Website#246]
ISSUE:
- Title:  Addition of Images to the Project Cards
- Summary: To improve the visual appeal and user experience, I propose adding relevant images to each project card on the Featured Projects section. This will provide users with a better understanding of the project at a glance and make the layout more engaging.
- Expected Behavior: Each project card will display an image above the title, providing visual context to the users.
- Actual Behavior: Currently, the cards only contain text with titles and brief descriptions.
---
 Proposed Solution:

- Addition of a small image (preferably 200x150 px) to each card that visually represents the project.
- The images will align with the project description, e.g., an image of crops for "Crop Height Using Computer Vision" or a chatbot for "Chatbot Development for Customer Support."
---
Name : Priyanka Kumari
Identity : Gssoc extd. Contributor and HACKTOBER fest

I can work on this issue. Please assign it to me

**Comment by YOGINIMAHIMA1** [comment]
@vivekvardhan2810 assign  any issue to me also
