### ISSUE TITLE
Proper allignement in about us

### ISSUE THREAD

**Issue by monishkumardvs** [ML-Fusion-Lab/ML-Fusion-Lab-Website#249]
![image](https://github.com/user-attachments/assets/e1a4a414-4402-4e15-bc4d-b5845d5fdda5)
there is proper gap between What We Offer and our team
Can u assign me i will work on that

**Comment by Ek-ta-bharti** [comment]
Hey, I can do this really well! Please assign it to me for user experience enhancement.

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, and they have created PR, so I am closing this issue.
