### ISSUE TITLE
Improving the explore section contents

### ISSUE THREAD

**Issue by Rajata-Hegde** [ML-Fusion-Lab/ML-Fusion-Lab-Website#252]
![Screenshot 2024-10-06 214734](https://github.com/user-attachments/assets/a517556a-62fc-4946-861a-41ec03f30e3a)

when we click the explore section  the text/contents are not fitted in the box. I want to improve this page. Please assign this to me .
Thankyou.

**Comment by vivekvardhan2810** [comment]
@Rajata-Hegde this issue was there already and he is working on it , he has created the PR and resolving it.

So i am closing this issue.
