### ISSUE TITLE
List of popular courses is not developed properly.

### ISSUE THREAD

**Issue by Nikhat623446** [ML-Fusion-Lab/ML-Fusion-Lab-Website#254]
<img width="1440" alt="Screenshot 2024-10-06 at 10 59 00 PM" src="https://github.com/user-attachments/assets/42c8637e-df88-4b0e-bdec-b827c40ef62e"> .

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue, and the page was updated.
