### ISSUE TITLE
Contact page doesn't look interactive.

### ISSUE THREAD

**Issue by Nikhat623446** [ML-Fusion-Lab/ML-Fusion-Lab-Website#255]
<img width="1394" alt="Screenshot 2024-10-06 at 11 03 17 PM" src="https://github.com/user-attachments/assets/e5ce3a0a-978c-4819-adee-4ce5eeec3cf5">

**Comment by BhavikaPachauri** [comment]
@Nikhat623446  i wolud like t0 solve this issue

**Comment by Nikhat623446** [comment]
I want to work on this issue, assign me.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
