### ISSUE TITLE
Hamburger Menu Not Functioning Properly

### ISSUE THREAD

**Issue by adityakr0660** [ML-Fusion-Lab/ML-Fusion-Lab-Website#256]
I can solve the issue with the hamburger menu to ensure it functions correctly.

https://github.com/user-attachments/assets/2be31a59-e144-4b44-974a-2781c091e99c

Please assign to me for this task.

**Comment by vivekvardhan2810** [comment]
@adityakr0660 make sure to join discord server and complete this issue for the next 2 days.

**Comment by vivekvardhan2810** [comment]
Have you completed the work.

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by Palmistry2310** [comment]
@vivekvardhan2810  I am interested in working on it. I understand that it has already been assigned to someone else, but if the current assignee does not provide updates or progress within the expected timeline, I will be happy to take it over and ensure it is resolved efficiently.
Please let me know if it's possible for me to work on this issue or if I can contribute in any way.

**Comment by vivekvardhan2810** [comment]
@adityakr0660 I apologize, but I need to close this issue for now. Please don't be discouraged!
