### ISSUE TITLE
 Fix responsiveness issues across all screen sizes

### ISSUE THREAD

**Issue by Karan-purkait** [ML-Fusion-Lab/ML-Fusion-Lab-Website#257]
There are some responsiveness issues across various screen sizes in the project. Elements on the page do not resize or rearrange properly when viewed on smaller devices such as smartphones or tablets. Some examples include:

Texts and buttons overlapping
Images not resizing properly
Layouts breaking on mobile view
Overflowing elements beyond the viewport
Steps to Reproduce:

Open the website on a smaller screen or resize the browser window.
Observe the following elements not adjusting properly:
[Mention specific components or pages]
Expected Behavior: The layout should adapt to different screen sizes, ensuring that the website is fully usable and visually appealing on all devices (desktops, tablets, smartphones).

Devices and Screen Sizes Tested:

Desktop: [e.g., 1920px]
Tablet: [e.g., 768px]
Mobile: [e.g., 375px]
Solution Ideas:

Implement media queries to adjust the layout for different breakpoints.
Use responsive units like percentages, ems, or rems for elements to scale properly.
Ensure images and videos are responsive with appropriate CSS properties (e.g., max-width: 100%).

![Screenshot 2024-10-06 231842](https://github.com/user-attachments/assets/a71ffa2e-1f91-4ccb-bf0e-2f0836ebc87b)

**Comment by Karan-purkait** [comment]
Assgined me for solving this issues

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
