### ISSUE TITLE
Fix Scroll to top button in all pages

### ISSUE THREAD

**Issue by Abankita** [ML-Fusion-Lab/ML-Fusion-Lab-Website#258]
The scroll to top button looks alright in the home page but in all the other pages it looks like this : 
![Screenshot_20241006-234906~2](https://github.com/user-attachments/assets/fd64dca0-e8e3-42f0-9e3c-abb18f3e7d85)

@vivekvardhan2810 Hence I would request you to assign me, so that I can work on it to make it uniform in all pages

**Comment by Abankita** [comment]
@vivekvardhan2810 can you please assign this issue to me?

**Comment by Abankita** [comment]
Hii @vivekvardhan2810 can you please check this issue and assign me? 
Thank you!

**Comment by vivekvardhan2810** [comment]
@Abankita make sure to complete this issue within 2 days, 

and make sure to join discord server for further updates and communication
