### ISSUE TITLE
add a sound after clicking the button 

### ISSUE THREAD

**Issue by rounakdey6** [ML-Fusion-Lab/ML-Fusion-Lab-Website#259]
Please assign this work to me

**Comment by vivekvardhan2810** [comment]
@rounakdey6 provide me a detailed solution.

**Comment by rounakdey6** [comment]
@vivekvardhan2810 like will I code ?

**Comment by vivekvardhan2810** [comment]
@rounakdey6 what sound would you want to put and what improvements you wanna make, pls tell it in detail.

**Comment by rounakdey6** [comment]
I want to add a click sound, for the navbar button, every time some one clicks on the navbar button a sound will generate.

**Comment by vivekvardhan2810** [comment]
for now we don't need it, so i am closing this issue.
