### ISSUE TITLE
Feedback page updated

### ISSUE THREAD

**Issue by Ankitaghavate** [ML-Fusion-Lab/ML-Fusion-Lab-Website#260]
To update your feedback page with a new background, button colors, hover colors, and added placeholders, you can make the following adjustments. I’ll provide a sample that includes these updates:

Background Color: Change the body background to a new color or gradient.
Button Color: Update the button's default and hover colors.
Placeholders: Ensure that each input field has an appropriate placeholder.
After Updated
![Screenshot 2024-10-07 002919](https://github.com/user-attachments/assets/7de0d2e0-a72b-4b40-b454-8c9aaac2ecc4)

**Comment by vivekvardhan2810** [comment]
@Ankitaghavate make sure to join discord and complete this issue for the next 2 days.
