### ISSUE TITLE
Enhance about us section

### ISSUE THREAD

**Issue by vijaychandra1910** [ML-Fusion-Lab/ML-Fusion-Lab-Website#262]
enhancing about us page by adding some scroll animation effect. Also creating some cards for our mission, our  team section and adding hover effect in that.
![Screenshot 2024-10-07 015848](https://github.com/user-attachments/assets/27d2069c-a427-4627-ac5f-034e7e9dffa9)

**Comment by GeetikaNahak** [comment]
Hi!
I would like to work on enhancing the "About Us" page. Could you please assign this issue to me?
Thank you!

**Comment by vivekvardhan2810** [comment]
This issue was assigned before and created the PR, so I am closing this issue
