### ISSUE TITLE
✨UI fix needed on this page✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#263]
<img width="1020" alt="Screenshot 2024-10-07 at 5 43 30 AM" src="https://github.com/user-attachments/assets/9fbacf49-ffa7-4be0-bbfd-a9f9d085fefa">

@vivekvardhan2810 can you assign me this task so i can fix this issue.

**Comment by BhavikaPachauri** [comment]
I would like to work on this. Please assign this to me.

**Comment by Ek-ta-bharti** [comment]
Please assign this to me.  i able to do this
