### ISSUE TITLE
Improve UI of the About Us Section

### ISSUE THREAD

**Issue by Rahul-AkaVector** [ML-Fusion-Lab/ML-Fusion-Lab-Website#264]
## Description

I would like to propose an enhancement to the UI of the "About Us" section. The current layout could be improved to create a more visually engaging experience for users. Below are the specific suggestions:

- **Adjust Font Size:** The font size currently used is not as readable or impactful as it could be. I propose adjusting the font size to ensure better readability and aesthetic appeal.
  
- **Add Relevant Images:** Including visually appealing and relevant images in the "About Us" section can enhance the overall user experience, making the section more attractive and informative.

## Benefits
- Enhanced user engagement with the page
- Improved readability and aesthetics
- Better representation of the brand's values through visuals

## Proposed Steps
1. Adjust the font size to match modern UI trends and ensure consistency across the section.
2. Source or design relevant, high-quality images that align with the section's content.
3. Integrate the images into the layout while maintaining balance and harmony with the text.
4. Test responsiveness and cross-device compatibility after updates.

I am willing to work on these changes and contribute to the improvement of the website's UI. Please let me know your thoughts on this proposal.
![image](https://github.com/user-attachments/assets/b2d423cb-b1b1-48ea-ba30-1b2db135c611)

**Comment by BhavikaPachauri** [comment]
I would like to work on this. Please assign this to me.

**Comment by vivekvardhan2810** [comment]
i have assigned this to someone before, so i am closing this issue.
