### ISSUE TITLE
issue in courses page that is text is overflowing through section 

### ISSUE THREAD

**Issue by Abhishek89chauhan** [ML-Fusion-Lab/ML-Fusion-Lab-Website#265]
![Screenshot 2024-10-07 085332](https://github.com/user-attachments/assets/c2c5f2b0-4e2b-49ec-a35b-3dff7b7dcd6d)

**Comment by Abhishek89chauhan** [comment]
here is issu that text is over flowing throug the section and when we switch to dark mode some part of text disappear

![Screenshot 2024-10-07 085353](https://github.com/user-attachments/assets/37f311e9-813a-4a25-8310-e2c6eac57dc2)

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
