### ISSUE TITLE
Bug: Homepage Feature section cards are not responsive

### ISSUE THREAD

**Issue by AkankshaSinghK** [ML-Fusion-Lab/ML-Fusion-Lab-Website#269]
@vivekvardhan2810 
On homepage  features cards are not responsive as content is overflow in th card.

![image](https://github.com/user-attachments/assets/b3f8173a-3301-4f19-b49a-00231fe5ef41)

Kindly assign this issue to me to fix this.
Add gssoc-extd and hactoberfest tags and level it.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
