### ISSUE TITLE
Add User Profile Section

### ISSUE THREAD

**Issue by SCR01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#273]
# Title: Add User Profile Section

### Feature Description:
I propose adding a **User Profile** section to the application. This section will allow users to manage their account settings, view and manage their activities, and interact with the platform's features such as **Add to Cart**, **My Learning**, and **Share Your Blogs**.

### Key Features:
1. **Add to Cart**: Users can view and manage the items they have added to their cart.
2. **My Learning**: Displays the courses, lessons, or resources the user is currently enrolled in or has completed.
3. **Share Your Blogs**: Allows users to write, share, and manage their personal blog posts.

### Use Case:
This feature will provide users with a personalized experience by organizing their platform interactions in one place. It will help users better manage their activities and keep track of their learning progress and contributions.

### Benefits:
- **User Engagement**: The profile section will encourage users to explore more platform features like learning courses or writing blogs.
- **Personalization**: Each user will have their own space to track progress and purchases.
- **Content Sharing**: Users can easily manage and share their blogs, which may lead to higher platform activity and user retention.

### Additional Context:
This feature will enhance the user experience by giving them a dedicated section for their activities and interaction with the platform.

**Comment by vivekvardhan2810** [comment]
we will look for this later, so i am closing this issue.

Please Understand.
