### ISSUE TITLE
 Add Pop-up Notification in Courses Section

### ISSUE THREAD

**Issue by SCR01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#274]
# Title:
[Feature Request]: Add Pop-up Notification in Courses Section

## Issue Description:
I propose adding a pop-up notification similar to the image provided, which displays in the **Courses** section. This pop-up will notify users about the courses on their wishlist and encourage them to take action.

## Feature Description:
- A pop-up notification will appear at the top of the **Courses** section.
- The notification will inform users about the wishlist courses and provide a link to the wishlist page.
- The pop-up will be dismissible with an "X" button.
- The notification should have the same design as the one shown in the provided image.

## Use Case:
- The feature enhances user engagement by reminding users of their wishlist items.
- Users can easily access their wishlist and purchase courses, improving conversion rates.

## Benefits:
1. **Improved User Experience**: Users will be reminded of their wishlist without navigating away from the **Courses** page.
2. **Increased Conversion Rates**: By encouraging users to take action on wishlist items, this feature could lead to more course purchases.
3. **Customizable Design**: The pop-up will match the current website design and branding.

## Tasks:
1. Create a `WishlistPopup` component that displays a notification at the top of the **Courses** page.
2. Add a dismiss button to the notification.
3. Link the pop-up text to the user's wishlist.
4. Style the pop-up to match the design provided (background color, text style, etc.).
5. Ensure the pop-up only appears once per session or until dismissed by the user.

## Mockup/Example (Based on Image Provided):
![Screenshot 2024-10-07 122127](https://github.com/user-attachments/assets/788f7b79-504e-483c-802c-ea4f3a32205a)

❤️ We heard you made a wish | Achieve your goals and [get the courses on your wishlist](#).

## Additional Context:
The pop-up should match the style and behavior of the provided example. It should not disrupt the user experience but should serve as a gentle reminder for the wishlist.

---

**Close**: #63 (replace with your actual issue number once merged)

**Comment by vivekvardhan2810** [comment]
for now we don't require this, we will look it later, so i am closing this issue

Please Understand.
