### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by Codewithmeowmeow** [ML-Fusion-Lab/ML-Fusion-Lab-Website#277]
I would like to create a new page for feedback in which users can give feedback.
![Screenshot_20241006_233101_Chrome](https://github.com/user-attachments/assets/7f6ad6f1-00b7-4acc-b51e-e8958709afd6)
Something like this.

**Comment by vivekvardhan2810** [comment]
this issue was complete before, so i am closing this issue
