### ISSUE TITLE
font style and font size 

### ISSUE THREAD

**Issue by KAmaL-senpai** [ML-Fusion-Lab/ML-Fusion-Lab-Website#28]
I can modify the font size and font color platter of the website making is more visual appealling assign this to me

**Comment by vivekvardhan2810** [comment]
@KAmaL-senpai can you share the screenshot and give me the detailed solution.

**Comment by KAmaL-senpai** [comment]
@vivekvardhan2810 Assign this to me with GSsoC 2024 and hacktoberfest 2024 i will share the screenshot once i made the changes.

**Comment by vivekvardhan2810** [comment]
@KAmaL-senpai i am asking the screenshot of which you wanna change.

**Comment by vivekvardhan2810** [comment]
@KAmaL-senpai I will look and assign by tomorrow.

**Comment by vivekvardhan2810** [comment]
@KAmaL-senpai i don't understand the solution, i asked for solution and screenshot, but you didn't provided, so i am closing this issue.
