### ISSUE TITLE
fix the Bug : in newsletter form and add functionality to it

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#280]
the newsletter input feild is not vsible 
![image](https://github.com/user-attachments/assets/d624e718-e885-448b-8c5c-22e41d9dfded)
need to change the font colour 
![image](https://github.com/user-attachments/assets/ec00f20c-0b32-489d-bd2b-9437017ef49c)

 and add functionality to it and display confirmation message after subscribing

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
