### ISSUE TITLE
Make Multiple changes with the UI

### ISSUE THREAD

**Issue by SamarthDS** [ML-Fusion-Lab/ML-Fusion-Lab-Website#286]
I'll make the header look cleaner and more uniform. 
![image](https://github.com/user-attachments/assets/b3758079-260c-40b7-913b-96f20797ded9)

![image](https://github.com/user-attachments/assets/c726f10b-f6c9-4ad5-bbae-bc4a5811aeef)

as you can see in the above 2 images the header doesn't look uniform.

![image](https://github.com/user-attachments/assets/0c01d772-61ab-4a97-815b-2edf740d6c29)

I'll add good images and make it like a carousel.

![image](https://github.com/user-attachments/assets/c70f64d1-e051-48bc-93dd-cb6cc40e56fc)

cards look too congested

![image](https://github.com/user-attachments/assets/faaafa86-4b42-4d24-bac2-ad226e5db3c6)

ill make this section look more neat and beautiful.

![image](https://github.com/user-attachments/assets/c1e8dc54-86d6-4971-ae5b-76c8af4873bc)

improve the Contact Us page and make it look more readable.

Assign me this task, and I'll make sure everything looks amazing!

**Comment by vivekvardhan2810** [comment]
for now we don't want any changes, as it is in updation, so i am closing this issue. please understand.
