### ISSUE TITLE
Course Card Layout Overlap and Overflow

### ISSUE THREAD

**Issue by sahhoArjun097** [ML-Fusion-Lab/ML-Fusion-Lab-Website#288]
The "Our Popular Courses" section on the page is experiencing layout issues, causing some course cards to be cut off or not fully visible. This negatively impacts the user experience by preventing users from seeing all the courses clearly. The cards seem to overflow horizontally, and there might be a need for better handling of the container's width or scroll behavior.

Steps to Reproduce:

Navigate to the "Our Popular Courses" section.

Observe that some course cards are cut off on the right side of the screen.

Inspect the layout and responsiveness of the cards.

Expected Behavior:

All course cards should be fully visible within the screen, even in responsive or smaller window sizes. If necessary, a scroll feature or better container alignment should be implemented to accommodate the cards.

![image](https://github.com/user-attachments/assets/9e70d604-c9a2-4e50-a584-bf936e96fa42)

**Comment by Mansi07sharma** [comment]
I am interested to work on that issue.

**Comment by vivekvardhan2810** [comment]
this issue was completed and resolved, so i am closing this issue.
