### ISSUE TITLE
improve contact 

### ISSUE THREAD

**Issue by shivamy009** [ML-Fusion-Lab/ML-Fusion-Lab-Website#29]
![Screenshot 2024-10-01 233058](https://github.com/user-attachments/assets/3b5cedef-eaf8-4a8b-90b8-707e892cff1f)
improve this overflow in contact form

**Comment by vivekvardhan2810** [comment]
Okay @shivamy009 

Assigning this issue to you.

**Comment by kjvlasyapriya** [comment]
![Screenshot 2024-10-02 094752](https://github.com/user-attachments/assets/75cec9e9-0acf-4401-812b-60ffa0131b0a)
in this we have to improve the overflow in contact form
