### ISSUE TITLE
Improving Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [ML-Fusion-Lab/ML-Fusion-Lab-Website#290]
### Description
The current Loading has no preloader. The screen becomes blank when the website loads. Enhancing the preloader, and improving the styling of the preloader design would greatly improve the user experience and website presentation

### Tasks:
Redesign the preloader for better visual appeal.
Improving the preloader.
@vivekvardhan2810  can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by vivekvardhan2810** [comment]
we don't need this for now, so i am closing this issue.
