### ISSUE TITLE
 Incomplete Courses Page and Overflowing Text on ML Fusion Lab Website

### ISSUE THREAD

**Issue by AJ-Athira** [ML-Fusion-Lab/ML-Fusion-Lab-Website#293]
**Issue:** Incomplete Courses Page and Overflowing Text on ML Fusion Lab Website

Hello Project Admin,

I’ve noticed that the Courses page on the ML Fusion Lab website is incomplete, with missing information in some sections. Additionally, the text in the section boxes is overflowing, making the whole page look messy and hard to navigate. I’d love to contribute and help fix these issues.

![mlfusion](https://github.com/user-attachments/assets/932832e3-e5ef-4d04-bbe5-cb5aa8bcb13d)

**Checklist:**
=>Contributor in GSSoC-ext ✨
=>Want to work on this issue and improve the design and content 💻

**Additional Information:**
Please add the hacktoberfest-accepted and level3 labels to this issue.

 **I'd be grateful if you could assign this task to me**. 

so that i can fix  course page by completing the whole updated info. Looking forward to contributing and making improvements!

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
