### ISSUE TITLE
Course Section Alignment 

### ISSUE THREAD

**Issue by Mohammedmaaz541** [ML-Fusion-Lab/ML-Fusion-Lab-Website#297]
I have identified an issue with the alignment of content within the course section of the website/application. The current layout appears misaligned, affecting the user experience and the overall readability of the content. I would like to take the opportunity to work on fixing this issue, ensuring that the content in each section is properly aligned and presented in a clear, organized manner. This will improve both the aesthetic appeal and functionality of the course section, leading to a better user interface and experience.

By addressing this issue, I will focus on:

Analyzing the root cause of the misalignment.
Correcting the layout structure and CSS properties.
Ensuring the alignment is consistent across various devices and screen sizes for responsiveness.
I am eager to contribute to improving the quality of the course section and would appreciate the chance to work on resolving this issue.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
