### ISSUE TITLE
IDEA: Add a Better Font.

### ISSUE THREAD

**Issue by sarinsanyal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#298]
Rather than using Times New Roman, I can use much better fonts like Poppins, or Raleway, or Montserrat.

I would like to implement it on all pages of this website using Google Fonts, and my knowledge of HTML and CSS.

![image](https://github.com/user-attachments/assets/17db2f98-cc03-4faf-8678-c82373007797)

@vivekv2810 Please assign me this issue. Also, please add the Hacktoberfest and GSSoC Extended Labels. Thank you!!

**Comment by vivekvardhan2810** [comment]
we will look for fonts later, for now we are closing this issue.

**Comment by sarinsanyal** [comment]
> we will look for fonts later, for now we are closing this issue.

Alright! Thank you very much for your time!
