### ISSUE TITLE
improve the courses section , footer section 

### ISSUE THREAD

**Issue by Web-Dev-Learner** [ML-Fusion-Lab/ML-Fusion-Lab-Website#3]
Courses Section - Content Expansion,Layout Improvements,

 Footer Section- Content Updates

Could you please assign this issue to me? add a labels aslo , My GitHub username is Web-Dev-Learner.
![Screenshot 2024-10-01 174914](https://github.com/user-attachments/assets/608b5045-f939-4322-be10-2c1aef110c8f)
![Screenshot 2024-10-01 174924](https://github.com/user-attachments/assets/19f5c4e9-7b6b-4bf5-bfbe-0caae7def6e9)

Could you please assign this issue to me? add a labels aslo , My GitHub username is Web-Dev-Learner.

**Comment by Khushi14404** [comment]
I would like to work on this please assign this to me

**Comment by sweta123761** [comment]
assign that to me .

**Comment by vivekvardhan2810** [comment]
@Khushi14404 assigned you.

**Comment by vivekvardhan2810** [comment]
@Web-Dev-Learner assigned to you.

**Comment by vivekvardhan2810** [comment]
@Web-Dev-Learner please complete this issue in the next 3 days.

**Comment by vivekvardhan2810** [comment]
@sweta123761 you can look for other issues at website  like improvement and changes, make sure to create an new issue

**Comment by vivekvardhan2810** [comment]
make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH

**Comment by vivekvardhan2810** [comment]
@Web-Dev-Learner added the label.

**Comment by Web-Dev-Learner** [comment]
Thank you so much.

**Comment by vivekvardhan2810** [comment]
Done.

**Comment by vivekvardhan2810** [comment]
@Web-Dev-Learner I have removed the label because this project doesn't come under hacktoberfest.

**Comment by Web-Dev-Learner** [comment]
okay , Thanks for your information @vivekvardhan2810 .
