### ISSUE TITLE
Add dedicated Signup and Login Pages in the Navigation Bar and making this Navigation Bar fixed

### ISSUE THREAD

**Issue by Nitheesha33** [ML-Fusion-Lab/ML-Fusion-Lab-Website#300]
![WhatsApp Image 2024-10-08 at 01 15 21_a59f892c](https://github.com/user-attachments/assets/8cf6509c-1080-48cc-af43-aa286ef75bdb)

I would like to take on this task and contribute by adding the dedicated signup and login pages to the navigation bar. I kindly request the project mentors @vivekvardhan2810 to assign this issue to me and add relevant gssoc labels.

**Comment by vivekvardhan2810** [comment]
We will look for login and signup later.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
