### ISSUE TITLE
Resolve Logo Display Issue in community_support.html

### ISSUE THREAD

**Issue by coderiksenthil** [ML-Fusion-Lab/ML-Fusion-Lab-Website#302]
In the **community_support.html page**, I want to replace the current static logo inside the <div class="logo"> that only displays the text "ML Fusion Labs" with a more dynamic <nav> element. This updated navbar will include a logo image linked to the homepage, a responsive hamburger menu for mobile devices, and navigation links to key sections of the website (Courses, Projects, About Us, Contact, and Testimonials). This change enhances both the visual appeal and functionality, providing better navigation and a cohesive user experience.

**Additionally, the code is already prepared and ready for implementation, I kindly request to assign me to this issue**

## Before
![image](https://github.com/user-attachments/assets/8353795e-f071-4c62-8790-7353f1ecdd7e)
## After
![image](https://github.com/user-attachments/assets/7e097f8d-beb2-460a-8991-cb1caa5f5582)

**Comment by vivekvardhan2810** [comment]
@coderiksenthil make sure to complete this issue within 2 days 

And make sure to join discord Server for further updates and communication.
