### ISSUE TITLE
BUG: Dark Mode not functioning in the testimonial section

### ISSUE THREAD

**Issue by sindhuja184** [ML-Fusion-Lab/ML-Fusion-Lab-Website#303]
![image](https://github.com/user-attachments/assets/64e94977-ae0a-4d21-85f1-3e9977604798)
I have tried to enable the dark mode in the testimonial section, but its not functioning at all.

Please assign me this issue, I would like to add dark mode and some additional features.

Thanks

**Comment by vivekvardhan2810** [comment]
@sindhuja184 make sure to complete this issue within 2 days 

and make sure to join discord server for further communication and updates.

**Comment by sindhuja184** [comment]
Ok will complete within 2 days
