### ISSUE TITLE
BUG: The Redirection of page from the courses is not correctly done

### ISSUE THREAD

**Issue by sindhuja184** [ML-Fusion-Lab/ML-Fusion-Lab-Website#304]
![image](https://github.com/user-attachments/assets/c15be1a7-a70b-4a49-9d63-748443d19b9b)
Every time I try to click on learn more of the 6 topics provided. The page is always directed to the Introduction to machine learning.

Additionally the UI of the Introduction to machine learning page is not impressive.

Please assign this issue so that I can solve the redirection issue and ensure that the UI of the page is impressive.

Thanks @vivekv2810, @faisal07777

**Comment by vivekvardhan2810** [comment]
this issue was completed, so i am closing this issue.
