### ISSUE TITLE
NAV BAR ISSUES

### ISSUE THREAD

**Issue by RAJIV81205** [ML-Fusion-Lab/ML-Fusion-Lab-Website#305]
FIXING THE NAV BAR IN CENTER AND MAKING IT ATTRACTIVE ALSO MAKING IT RESPONSIVE AND TRANSPARENT GLASS UI
![image](https://github.com/user-attachments/assets/30be8b51-6eee-40ad-b382-e02b4cd08419)

**Comment by vivekvardhan2810** [comment]
This issue was created before and assigned it before and made the PR. so i am closing this issue.
