### ISSUE TITLE
Add color background

### ISSUE THREAD

**Issue by Mehtarishita** [ML-Fusion-Lab/ML-Fusion-Lab-Website#309]
we can add colors to the background to make it more attractive
![image](https://github.com/user-attachments/assets/a394c0f0-5194-4c45-8b2f-d0d043e58ccc)
Please assign this issue to me under gssoc'24 EXTENDED with label gssoc'24 and hacktoberfest.

**Comment by AkashJaiswal15** [comment]
We can add colors to the background to make it more attractive as well as in div boxes.
please assign me this task.

**Comment by vivekvardhan2810** [comment]
we will look for this later and we don't require this for now, so i am closing this issue, Please Understand.
