### ISSUE TITLE
Incorrect alignment of courses in courses section

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [ML-Fusion-Lab/ML-Fusion-Lab-Website#311]
![image](https://github.com/user-attachments/assets/8937e4da-e49f-4e33-96d1-86892d5ffbf4)
i would like to correct the alignment in making the website more responsive
please assign me with required labels as per gssoc'24 extended program!

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
