### ISSUE TITLE
Issue: Improve Contact Form Design

### ISSUE THREAD

**Issue by komalkushwaha30** [ML-Fusion-Lab/ML-Fusion-Lab-Website#312]
![Screenshot 2024-10-08 145048](https://github.com/user-attachments/assets/01b6142a-e318-463c-b513-b36862693a69)

The current contact form can be made more attractive and professional by improving its design and usability. Here are a few suggestions to enhance the user experience:
Suggestions
1.Apply rounded corners to input fields and buttons for a modern look.
2.Use shadow effects and subtle hover animations to make elements more interactive.
3.Add icons inside the input fields (e.g., email icon for the email field, message icon for the text area) to guide the user.
4.Improve the typography by using readable fonts, proper font sizes, and spacing between form elements.
5.Button Styling: 
- Make the submit button stand out with a bold color, hover effects, and a concise label (e.g., "Send Message").
- Ensure buttons are responsive and well-sized on both mobile and desktop devices.
6. Responsive Design:
- Make sure the form is mobile-friendly by using responsive frameworks like Bootstrap or CSS Grid.
- Adjust padding and margins for smaller screens to ensure the form elements are easy to tap and navigate.

**Comment by vivekvardhan2810** [comment]
for now it is looking good, we will look for the improvements later, so i am closing this issue.
