### ISSUE TITLE
Enhancement - Level1 - Github Greetings bot

### ISSUE THREAD

**Issue by KiranBaliga** [ML-Fusion-Lab/ML-Fusion-Lab-Website#314]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, so i am closing this issue.
