### ISSUE TITLE
IMPROVEMENT: CONTACT US (FOOTER AND THE FORM)

### ISSUE THREAD

**Issue by sindhuja184** [ML-Fusion-Lab/ML-Fusion-Lab-Website#317]
![image](https://github.com/user-attachments/assets/af141091-7d5a-4034-9937-f15bfa6fc5d7)
In the contact us section the font-color is same as background and the form related to the contact us can be improved.

![image](https://github.com/user-attachments/assets/eb8c7538-972a-4719-a3bf-3e90fbf02e06)
The footer is not correctly placed this can be changed and the UI of the footer can be improved.

I am confident to add value to the contact us page
Please assign this issue to me.

Thanks @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing the issue.
