### ISSUE TITLE
Adding back button to return to home page

### ISSUE THREAD

**Issue by Abhi9shinde** [ML-Fusion-Lab/ML-Fusion-Lab-Website#318]
![image](https://github.com/user-attachments/assets/40b3793b-555b-4ef3-85e1-768d45b8fb52)
As you can see in the screenshot the feedback page has no back button which is not good for a website.
Please assign this task to me under gssoc-ext, hactoberfest and level 1 would be enough

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde make sure to complete this issue within 2 days.

make sure to join discord server mentioned in readme for further updates and communications.

**Comment by vivekvardhan2810** [comment]
i will add the hacktoberfest label at PR.

**Comment by Abhi9shinde** [comment]
ok sir I'll start working on the issue
