### ISSUE TITLE
Font Color not visible in Contact section

### ISSUE THREAD

**Issue by tanya-soni-git** [ML-Fusion-Lab/ML-Fusion-Lab-Website#319]
<img width="723" alt="Screenshot 2024-10-08 192101" src="https://github.com/user-attachments/assets/9f0d5462-c5bc-48da-9a87-a95a2878e52c">
Dear Project Manager,
Please assign me this issue under GSSoC Extd'24 I wish to resolve this issue.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
