### ISSUE TITLE
Creating and completing features community support

### ISSUE THREAD

**Issue by vinit105** [ML-Fusion-Lab/ML-Fusion-Lab-Website#32]
Under gssoc-exd2024 :

Community Support
Collaborate with other learners and contribute to open-source ML projects.

**Comment by rounakdey6** [comment]
please assign this to me, i will update the navbar section and footer section as well

**Comment by Pranjalmishr1** [comment]
kindly assign this to me, i will update the navbar section and footer section

**Comment by Farah-Maqbool** [comment]
Assign it to me so I update the home page including footer, our feature section, About ML fusion lab section and nav bar by making them responsive and interactive
