### ISSUE TITLE
Distorted Footer on the Course Page in ML Fussion

### ISSUE THREAD

**Issue by sahhoArjun097** [ML-Fusion-Lab/ML-Fusion-Lab-Website#324]
The footer on the course page of the ML Fussion website appears distorted or misaligned, causing layout issues that disrupt the overall design and user experience.

![image](https://github.com/user-attachments/assets/792ed225-3d08-41f2-8352-8f94b93f1427)

**Comment by vivekvardhan2810** [comment]
@sahhoArjun097 make sure to complete this issue within 2 days.
