### ISSUE TITLE
The course page content in ML Fusion is misaligned and spans the entire viewport width.

### ISSUE THREAD

**Issue by Ujjwal5705** [ML-Fusion-Lab/ML-Fusion-Lab-Website#325]
![Screenshot 2024-10-08 201502](https://github.com/user-attachments/assets/f1da1176-c240-40f3-9655-48a37160f4c4)
![Screenshot 2024-10-08 202225](https://github.com/user-attachments/assets/bae02e0b-abfd-43ca-9550-be12c116ec98)

i would like to fix this issue under gssoc-ext.

**Comment by vivekvardhan2810** [comment]
from my side, it is looking good, so i am closing this issue, please understand. But don't worry you can look for other issues.
