### ISSUE TITLE
Features: Community Section 

### ISSUE THREAD

**Issue by Lekkhasri** [ML-Fusion-Lab/ML-Fusion-Lab-Website#331]
The Community section can be enhanced by forming like the cards and join forum in the cards.
It give awesome looks to the page . I already have the experience in working it . Can you assign the work to me.
@vivekv2810 
Before:
![image](https://github.com/user-attachments/assets/5497671c-6b95-461c-b39a-ec17b5c74f18)
Expected Output:
![image](https://github.com/user-attachments/assets/65b3c96a-3422-4a12-aba5-2eb27ccfe790)

**Comment by vivekvardhan2810** [comment]
make sure to complete this issue within 2 days.
