### ISSUE TITLE
Website Responsiveness for mobile view

### ISSUE THREAD

**Issue by banasmita24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#334]
Adding menu bar(navigation) for the mobile view. please assign me this.

![Screenshot 2024-10-08 221156](https://github.com/user-attachments/assets/9cb30034-7e41-4059-bcbe-5c85d641cf02)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, so i am closing this issue.
