### ISSUE TITLE
Fix the website responsiveness issue

### ISSUE THREAD

**Issue by banasmita24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#335]
Current condition:
When the screen size is reduced, there is no menu or navigation bar at the top of the website. It just shows menu lines(three lines). When we click on it, it does not show anything.

After resolving this issue:
After resolving, the menu list will be shown for all screen sizes.

I would like to address this. Please assign this to me @vivekvardhan2810

![image](https://github.com/user-attachments/assets/3634f9ba-727e-417f-a121-daf4aca6632c)

**Comment by Riya7045** [comment]
I would like to work on this issue ,please assign it to me.
please add label gssoc-ext 24,hactoberfest and level 1,2 and level 3
