### ISSUE TITLE
Inconsistent Navbar UI

### ISSUE THREAD

**Issue by SagnikGos** [ML-Fusion-Lab/ML-Fusion-Lab-Website#336]
The Navbar changes its structure and color as I navigate through different pages making very it very hard to traverse through pages.
Home Page Navbar
![image](https://github.com/user-attachments/assets/db61a956-2acd-4635-87dd-cd18cd90c6d1)
Course Page Navbar
![image](https://github.com/user-attachments/assets/27fe4203-6c7c-4216-bd84-e96bd09a2b6d)
Project Page Navbar
![image](https://github.com/user-attachments/assets/89f4b300-67b0-4fa6-ac31-79a1918e537c)

I am willing to make a consistent Navbar with better UI.
Please Assign me this issue, I hold a strong grasp in Frontend CSS styling.
I'm a GSSOC'24 Contributor & Hacktoberfest Contributor.
Thank you!

**Comment by SagnikGos** [comment]
Can you tell me the reason of closing the issue?

**Comment by vivekvardhan2810** [comment]
I have seen navbar issues, and i have mentioned it before also for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.
