### ISSUE TITLE
Issue with CONTACT US form UI 

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#337]
Hi, 
I was exploring this project and I came across CONTACT US form and there the text which is written is not visible. If we select that text then only we get to know that YES, there's some text..

What's next?

I would like to change the UI of form and make a better one. I'd love to contribute, kindly assign me this issue.

Thank you :)

![image](https://github.com/user-attachments/assets/5c902846-6c21-4cf5-8ca1-92af33e721df)
![image](https://github.com/user-attachments/assets/d3c82bd0-5f97-457a-9cf7-a8ec65d337e8)

**Comment by vivekvardhan2810** [comment]
@neeru24 make sure to complete this issue within 2 days.

make sure to join discord server for further communication and updates.

**Comment by neeru24** [comment]
> @neeru24 make sure to complete this issue within 2 days.
> 
> make sure to join discord server for further communication and updates.

Sure, I'll complete it by tomorrow. Can I get the discord link?

**Comment by vivekvardhan2810** [comment]
it's mentioned in Readme.

**Comment by neeru24** [comment]
> it's mentioned in Readme.

Okay thank you

**Comment by neeru24** [comment]
> @neeru24 make sure to complete this issue within 2 days.
> 
> make sure to join discord server for further communication and updates.

Done with the task
