### ISSUE TITLE
Enhancing ABOUT US page

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#339]
Hi, this page can be enhanced and UI can be made more attractive and good looking with the proper use of text containers as it seems a bit simple now.

Kindly assign me this issue, I'd love to contribute.

Thank you:)

![image](https://github.com/user-attachments/assets/e5457818-36c4-42f3-acf9-89315e2bfdaf)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before and created the PR, so I am closing this issue
