### ISSUE TITLE
FIX Course page 

### ISSUE THREAD

**Issue by sahhoArjun097** [ML-Fusion-Lab/ML-Fusion-Lab-Website#34]
i will make the content of the course page visible and do effect change in it to enhance the view.
![Screenshot 2024-10-01 231951](https://github.com/user-attachments/assets/68c75cf2-cd55-4c1f-be3f-856601683a86)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant .

**Comment by vivekvardhan2810** [comment]
@sahhoArjun097 it was completed before,

I will encourage you to look for other issues in website like improvements, then create an new issue

for now i am closing this issue.
