### ISSUE TITLE
Improper alignment of contents in the navbar at every pages

### ISSUE THREAD

**Issue by banasmita24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#340]
Hi, I went through the website again, and i found that the contents of the navbar at every pages are arranged differently along with the logo.
I would like to address this by aligning the navbar in every pages along with the logo.
Please assign this to me under gssoc-ext and hactoberfest-accepted

![image](https://github.com/user-attachments/assets/f666b42a-67df-498e-ace2-4f06a77e9f5b)
![image](https://github.com/user-attachments/assets/68f3c817-07c0-4584-8827-ca586c4d197d)
![image](https://github.com/user-attachments/assets/743f3794-6a17-4502-8040-9b6da25933c6)

Thank you

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

**Comment by vivekvardhan2810** [comment]
we are not looking for navbar updates, as it was done many times before, please understand.
