### ISSUE TITLE
social icon and footer upgradation

### ISSUE THREAD

**Issue by Antima2004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#342]
In the footer section there are social media icon but the twitter logo is not updated 
Here's the image of it:
![Screenshot 2024-10-09 12 20 01 AM](https://github.com/user-attachments/assets/8f34e9e9-a93d-40a5-86c5-0a6a2ac54a0e)
And i can make the footer more attractive for the users
Please assign this to me and also add label

**Comment by vivekvardhan2810** [comment]
this issue was assigned before and created the Pull Request, so i am closing this issue.
