### ISSUE TITLE
ENHANCING THE HOME PAGE AND PUTTING LOGO 

### ISSUE THREAD

**Issue by shruti9935** [ML-Fusion-Lab/ML-Fusion-Lab-Website#344]
ASSIGN ME THIS TASK UNDER GSSOC EXT,

**Comment by vivekvardhan2810** [comment]
can you provide me the description 

like the changes that you want to make.

**Comment by shruti9935** [comment]
![Screenshot 2024-10-09 093557](https://github.com/user-attachments/assets/10568427-ddc7-477d-97ce-50d17f61f6c4)
![Screenshot 2024-10-09 093610](https://github.com/user-attachments/assets/7e33594a-ba25-4162-a9a2-856b2fad8f87)
we can close the logo or just put the front part of the your used logo (bg makes logo boring) .
and after designing the logo we can give the background color in home page

**Comment by vivekvardhan2810** [comment]
for now the logo is looking good, the improvements will be made later, so i am closing this issue.
