### ISSUE TITLE
correcting the footer links and adding github repo link and icon

### ISSUE THREAD

**Issue by devxMani** [ML-Fusion-Lab/ML-Fusion-Lab-Website#345]
![image](https://github.com/user-attachments/assets/9c903c5e-64ed-4d22-81cb-84a2ee8cda0d)
add gsoc ext and hacktoberfest label to this

**Comment by vivekvardhan2810** [comment]
@devxMani I have assigned you an issue before, have you completed that.

**Comment by vivekvardhan2810** [comment]
For now we don't require this, we can look it later, so I am closing this issue
