### ISSUE TITLE
Navbar Readability and Alignment Issues

### ISSUE THREAD

**Issue by TornovDutta** [ML-Fusion-Lab/ML-Fusion-Lab-Website#346]
# Description:
The current navbar suffers from low text contrast, making the menu options hard to read against the dark background. Additionally, some items are misaligned or overlapping, creating a cluttered appearance. The buttons lack sufficient spacing, causing a disjointed layout. To fix this, increasing text contrast, aligning the menu options correctly, and improving button spacing will enhance readability and navigation. Adding hover effects can also improve interaction and clarity.

#sceenshot:
![Screenshot 2024-10-09 015409](https://github.com/user-attachments/assets/c2021274-a334-4b2c-8799-e96b6bf796d7)

**Comment by TornovDutta** [comment]
@vivekvardhan2810 please label the issuse

**Comment by TornovDutta** [comment]
@vivekvardhan2810 please asign the project to me

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

**Comment by vivekvardhan2810** [comment]
we are not looking for navbar updates for now, as it was done many times before, please understand.
