### ISSUE TITLE
Lagging issues in courses page solving that ....

### ISSUE THREAD

**Issue by devxMani** [ML-Fusion-Lab/ML-Fusion-Lab-Website#348]
courses page stuck too much unable to load courses quickly.
![image](https://github.com/user-attachments/assets/bc0ad4ed-c851-4221-a047-d92b821c7a6d)

**Comment by devxMani** [comment]
add gsoc ext level 2 and hacktoberfest label

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, so I am closing this issue.
