### ISSUE TITLE
i would like to fix the frontend view of navbars aboutus and community overlap problem

### ISSUE THREAD

**Issue by harshgupta2125** [ML-Fusion-Lab/ML-Fusion-Lab-Website#352]
![image](https://github.com/user-attachments/assets/9afae268-af74-4464-8fad-6ea35bffafc0)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

**Comment by vivekvardhan2810** [comment]
we are not looking for navbar updates for now, as it was done and changes many times before, please understand.
