### ISSUE TITLE
Add Proper Spacing to Project Cards

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#355]
The cards displayed in the projects section seem too congested, making it difficult for users to visually distinguish between them. I would like to enhance the layout by adding proper spacing between the cards to improve readability and overall user experience.

Could you please assign me this issue? I’m excited to work on this enhancement and submit a PR shortly after it's completed.

Thank you!

![image](https://github.com/user-attachments/assets/65a5406b-1124-4870-b549-9702a203500d)

**Comment by vivekvardhan2810** [comment]
@neeru24 make sure to complete this issue within 2 days.

**Comment by vivekvardhan2810** [comment]
@neeru24 why did you removed your assignment.
