### ISSUE TITLE
Enhance About Section by Wrapping Text in a Card

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#356]
The About section on the homepage appears quite plain and could benefit from a visual enhancement. I propose wrapping the text in a card to give it a more structured and appealing look. This change would help improve the overall aesthetics of the page and provide a clearer distinction of the section.

Could you please assign me this issue? I would love to work on this enhancement and submit a PR once it's completed.

Thank you!

![image](https://github.com/user-attachments/assets/ee6f9490-d41a-4f3c-9999-69273b7678e1)

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@neeru24 can you work on this issue. 

as i have unassigned you the previous issue.

**Comment by neeru24** [comment]
> @neeru24 can you work on this issue. 
> 
> as i have unassigned you the previous issue.

Sure, I will. 
You can assign me but I'll complete it in a day.. Maybe by tomorrow night. 

Is it fine? 

I've classes na

**Comment by vivekvardhan2810** [comment]
Okay @neeru24 assigned you this issue, make sure to complete this issue within 2 days.
