### ISSUE TITLE
Adding Quiz testing feature for Every ML topic.

### ISSUE THREAD

**Issue by SoumyaU25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#36]
I want to add a quiz test system for each and every topic available in the web site which will tell a student based upon their performance in a certain topic that he/she is at beginner , Intermediate or advance level and on that basis the Student can decide that which course is preferable for them. It will make the site more Interactive for users.

 Please assign me this issue under gssoc-ext label.

**Comment by vivekvardhan2810** [comment]
@SoumyaU25 make sure to complete this issue for the next 2 days.

and join the discord server.

**Comment by vivekvardhan2810** [comment]
@SoumyaU25 i have assigned you this issue before 5 days, and didn't updated yet so i am closing this issue.

**Comment by SoumyaU25** [comment]
@vivekvardhan2810 actually my exams are going on in between this so can you extend my deadline to 11th or 12th October. I'll surely complete it by then

**Comment by vivekvardhan2810** [comment]
@SoumyaU25 no problem, for now I have closed this issue, I have assigned you a issue which is open, you can complete that.
