### ISSUE TITLE
making footer better

### ISSUE THREAD

**Issue by Rehan0016** [ML-Fusion-Lab/ML-Fusion-Lab-Website#360]
Description:
We need to implement a footer for our website to provide essential information and improve navigation.

Requirements:
HTML Structure:

Create a new <footer> element at the bottom of the page.
Include the following sections:
Company information
Quick links (e.g., About, Services, Contact)
Social media icons (e.g., Facebook, Twitter, LinkedIn)
Styling:

Background color: #333
Text color: #fff
Padding: 20px
Align text to the center.
Content:

Add a copyright notice (e.g., "© 2024 Company Name. All rights reserved.")
List links in the quick links section.
Include social media icons with appropriate links.
Functionality:

Ensure all links are functional.
Make the footer responsive for mobile devices.
Acceptance Criteria:
The footer is displayed at the bottom of each page.
It matches the specified styles.
All content is correctly formatted and links are functional.
Priority:
High
Additional Notes:
Please refer to the attached design mockups for reference.

![image](https://github.com/user-attachments/assets/3d96488e-e131-42a8-8146-1de302950b64)

**Comment by vivekvardhan2810** [comment]
for now we don't require this, we will look into this later, so i am closing this issue.
