### ISSUE TITLE
follows us should be on the top of footer

### ISSUE THREAD

**Issue by Rehan0016** [ML-Fusion-Lab/ML-Fusion-Lab-Website#361]
Description:
We need to add a "Follow Us" section at the top of the footer to enhance our social media presence and encourage user engagement.

Requirements:
HTML Structure:

Create a <div> with the class name follow-us.
Place it at the top of the footer section.
Content:

Include a heading (<h3>) with the text "Follow Us".
Add social media icons for the following platforms:
Facebook
Twitter
Instagram
LinkedIn
Ensure each icon links to the corresponding social media page.
Styling:

Align the section in the center.
Use a background color that complements the footer (e.g., #444).
Style the icons with a uniform size and appropriate spacing.
Functionality:

Ensure all social media links are functional.
Acceptance Criteria:
The "Follow Us" section is displayed correctly at the top of the footer.
It matches the specified styles.
All social media links are operational.
Priority:
Medium
Additional Notes:
Please refer to the design mockups for guidance on layout and icon style.

![image](https://github.com/user-attachments/assets/ca4eb546-f569-49e3-b75f-5952bbcbc390)

**Comment by vivekvardhan2810** [comment]
for now it is not required, we will look into it later. so i am closing this issue, and don't create multiple issues
