### ISSUE TITLE
Improving the navbar as it looks conjusted

### ISSUE THREAD

**Issue by Ashish-Patnaik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#362]
The navbar looks conjusted ,i will fix these issue please assign it to me

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.
