### ISSUE TITLE
 UI Issues on Course Page and Missing "Load Less" Button

### ISSUE THREAD

**Issue by SurajSakhare100** [ML-Fusion-Lab/ML-Fusion-Lab-Website#364]
![Screenshot 2024-10-09 160723](https://github.com/user-attachments/assets/4955403a-c079-40f1-9052-e222c55597e6)
![Screenshot 2024-10-09 160744](https://github.com/user-attachments/assets/8bacb46f-fdb4-4109-92c9-3a7b5d6cb4c2)

**UI Issue on the Course Page:**

The UI of the course page is not well-designed and has several responsiveness issues. The layout breaks on smaller screens, with elements misaligned and text overflowing.
Specific areas affected:
Course titles and descriptions overlap or break layout on mobile devices.
Images are distorted and not resizing correctly.
Buttons are inconsistently placed, leading to a poor user experience on different screen sizes.

**Missing "Load Less" Button:**

There is no "Load Less" button to collapse the course list after expanding it. This creates an issue where users cannot reduce the number of displayed courses once they have expanded the list, leading to a cluttered interface.
Expected behavior: After expanding the list of courses, there should be a "Load Less" button to allow users to collapse the course view and show fewer items. However, this functionality is missing.

@vivekvardhan2810  Assign this issue to me under gsscoc and hactober fest.

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by ananyashinde2434** [comment]
As i have a strong background in UI/UX i request u to assign it to me , i would be really glad to solve this issue

**Comment by vivekvardhan2810** [comment]
for now we don't required load less button, So i am closing this issue.

Please Understand.
