### ISSUE TITLE
Background Color change in the Feedback Form 

### ISSUE THREAD

**Issue by Wangmo-inn** [ML-Fusion-Lab/ML-Fusion-Lab-Website#365]
![Screenshot 2024-10-09 164630](https://github.com/user-attachments/assets/cb341beb-456b-4a98-bb7f-e604d0b44913)
Background color and icon color change in the Feedback Form section to black and blue to maintain consistency and follow the website color theme.

@vivekvardhan2810 Could you please assign this issue to me under gsscoc and hactober fest?.

Thank You!

**Comment by vivekvardhan2810** [comment]
@Wangmo-inn make sure to complete this issue within 2 days, i will add hacktoberfest label at the time you have created the Pull Request.

**Comment by Akanshaku** [comment]
I would like to work on this issue by making it more enhanced and attractive for users pls assign me this @vivekvardhan2810

**Comment by Shrutibansal22** [comment]
Hlo sir,
I would like to chage the background more effective and attractive to maintain consistency over the website.
Could you please assign me this task
