### ISSUE TITLE
Task Request: Navbar Improvement and Alignment

### ISSUE THREAD

**Issue by ujwala-k** [ML-Fusion-Lab/ML-Fusion-Lab-Website#366]
Hey, I would like to work on improving the navbar and its alignment. Please assign me the task. Attaching for reference.
![Screenshot 2024-10-09 173151](https://github.com/user-attachments/assets/2d4686a4-4784-4b95-828a-07aba4501147)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.
