### ISSUE TITLE
 Proposal for GitHub Bot to Acknowledge Issues

### ISSUE THREAD

**Issue by Abhi9shinde** [ML-Fusion-Lab/ML-Fusion-Lab-Website#367]
Description:
I propose creating a GitHub bot that automatically responds to new issues with a message thanking users for their contributions and informing them that our team will review it shortly.
When I raised a issue yesterday I saw there was no bot to respond to the issues.
So I would like to work on it

Benefits:
Enhances user experience by providing immediate feedback.
Encourages more contributions to our project.

Please assign this task to me under hacotoberfest, gssoc-ext and I think level 1 would be enough

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde you can have this one as reference.

https://github.com/aditya-bhaumik/Pathsphere/tree/main/.github

**Comment by Abhi9shinde** [comment]
@vivekvardhan2810  Yes sir, I have made changes please review and merge, Again sorry for the inconvenience

**Comment by vivekvardhan2810** [comment]
@Abhi9shinde Done.

**Comment by Abhi9shinde** [comment]
Thank you so much for your help and guidance! 🙌 I really appreciate your help on this project.
