### ISSUE TITLE
Improve Navbar Background Color for Enhanced Visual Appeal

### ISSUE THREAD

**Issue by ansiace** [ML-Fusion-Lab/ML-Fusion-Lab-Website#369]
The current background color of the navbar on the website can be improved to enhance its overall visual appeal and make it stand out more effectively. A better color choice could provide a more modern and cohesive look that aligns with the rest of the site's design, improving user experience.

Update the navbar background color to a more visually appealing shade that complements the existing site color scheme. 
- Ensure the new background color enhances readability for text and icons in the navbar. 
- Test the changes for consistency across various devices (desktop and mobile) and browsers. 

![Screenshot 2024-10-09 194002](https://github.com/user-attachments/assets/fd0f56d0-3265-4ab0-9884-b84866cdf781)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.
