### ISSUE TITLE
Important Labeling Reminder

### ISSUE THREAD

**Issue by faisal07777** [ML-Fusion-Lab/ML-Fusion-Lab-Website#37]
Whenever you're creating new issues, please make sure to add only the following labels:

gssoc-ext
hacktoberfest-accepted
level1
level2
level3

These labels are important as they help the GSSOC to award points more easily. So please stick to only these two labels to ensure your work is counted properly.

Do not add any other labels apart from these. This will help keep everything organized.

**Comment by vivekvardhan2810** [comment]
@faisal07777 there are more labels like level1 level2 level3

**Comment by faisal07777** [comment]
one more thing, as a mentor we can only assign one level label.

**Comment by faisal07777** [comment]
> @faisal07777 there are more labels like level1 level2 level3

 as a mentor  we can only assign one level label .
