### ISSUE TITLE
[BUG] Fixing the about us and other button in navigation bar

### ISSUE THREAD

**Issue by akanksha1055** [ML-Fusion-Lab/ML-Fusion-Lab-Website#371]
Can i fix  About us and Support Community button that are dissorted  making it difficult for users to visually distinguish between them.
please assign me this task under Hacktober and GSSoC 

thankyou!

![image](https://github.com/user-attachments/assets/e454ce44-7685-42f9-8ca9-3eac7756e50b)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and there was an updation also, so please understand.
