### ISSUE TITLE
Layout issue with nav items.

### ISSUE THREAD

**Issue by grasyPatel** [ML-Fusion-Lab/ML-Fusion-Lab-Website#372]
[X] Bug

**Description:**
The navigation items in the header are not aligned properly. They are overlapping and do not follow the design specifications. This issue is affecting the visual appearance and user experience on screens .

**Expected Behavior:**
The navigation items should be evenly spaced, aligned horizontally, and responsive across all screen sizes.

**ScreenShot**

<img width="1444" alt="Screenshot 2024-10-09 at 7 58 01 PM" src="https://github.com/user-attachments/assets/b0e002b6-b21d-4687-807f-887985f57f2c">

**Details to Include When Taking the Issue:**
Participant Role: GSSOC'24-extd Contributor

**Comment by grasyPatel** [comment]
@vivekvardhan2810 I would like to take responsibility for fixing this issue. Please assign it to me.

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand
