### ISSUE TITLE
[BUG] the footer in not aligned properly for about page

### ISSUE THREAD

**Issue by akanksha1055** [ML-Fusion-Lab/ML-Fusion-Lab-Website#374]
![image](https://github.com/user-attachments/assets/c9edc4e7-4954-4b0e-8a23-f52902b67928)

the text is not aligned properly ! let me fix that !!

Thankuou

**Comment by vivekvardhan2810** [comment]
@akanksha1055 make sure to complete this issue within 2 days.

**Comment by akanksha1055** [comment]
> @akanksha1055 make sure to complete this issue within 2 days.

sure sir thanks

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@Akanshaku don't spam in other issues, this is the warning.
