### ISSUE TITLE
 Not effective nav bar in home page

### ISSUE THREAD

**Issue by BVPKARTHIKEYA** [ML-Fusion-Lab/ML-Fusion-Lab-Website#378]
i would like to make the nav bar more effective by designing it properly!!
please assign me with the required labels as per gssoc'24 extended program

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
