### ISSUE TITLE
[BUG] background image disappears in dark mode

### ISSUE THREAD

**Issue by akanksha1055** [ML-Fusion-Lab/ML-Fusion-Lab-Website#380]
The background image available in the light theme disappears in dark theme making the dark theme UI very plain and boring
Let me add the same picture in the dark theme too 
Also the Nav bar buttons are mostly disappeared in dark mode ...let me fix UI of that too

please assign this task under Hacktober and Gssoc level2 !!
thankyouuu!

![image](https://github.com/user-attachments/assets/f6bfbfb8-237e-49bd-81f5-5d277356936c)

The background image not avail in dark mode
also the nav bar appears quite plain

![image](https://github.com/user-attachments/assets/67d1aefa-afff-44aa-9f52-35bc69e8cd7d)

**Comment by akanksha1055** [comment]
sure i understand ! please assign for under level 1 and hacktober label if possible

**Comment by vivekvardhan2810** [comment]
@akanksha1055 i am assigning this issue to you for level 1, and make sure to ass the same image that is there in light mode.

**Comment by akanksha1055** [comment]
> @akanksha1055 i am assigning this issue to you for level 1, only for background image in dark mode and make sure to add the same image that is there in light mode.

sure thankyouuu ! yes won't make changes in nav bar

**Comment by vivekvardhan2810** [comment]
make sure to complete this within 2 days.
