### ISSUE TITLE
The Featured project cards  are overlapping on hover

### ISSUE THREAD

**Issue by Anjalis14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#381]
I will fix this issue that is overlapping when we are hovering through it 

![image](https://github.com/user-attachments/assets/05e22c77-b368-480a-8323-97da2d977bce)

**Comment by Anjalis14** [comment]
@vivekvardhan2810  plz assign me this

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, you can check it, so i am closing this issue.
