### ISSUE TITLE
Enhanced Image Management to Ensure Code Readability & Usability In Main File

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#384]
- All image files are scattered in the main file randomly

-  I will create a new folder & transfer all images to it to ensure:
      * better code readability
      * easy access to developers & contributors
     
![image](https://github.com/user-attachments/assets/282591ee-4455-45db-9fff-826d3691c3e6)
@vivekvardhan2810 
Please assign this task to me.

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 
Please assign this task to me.

**Comment by Adarsh-Chaubey03** [comment]
![image](https://github.com/user-attachments/assets/99cfbfe9-fd14-4521-8910-fba4840df311)
also i will be correcting this missing images.
please assign the task to me @vivekv2810

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 pls complete the task that I have assigned you before.

**Comment by vivekvardhan2810** [comment]
> ![image](https://private-user-images.githubusercontent.com/179824602/375633178-99cfbfe9-fd14-4521-8910-fba4840df311.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjQxNTcsIm5iZiI6MTcyODYyMzg1NywicGF0aCI6Ii8xNzk4MjQ2MDIvMzc1NjMzMTc4LTk5Y2ZiZmU5LWZkMTQtNDUyMS04OTEwLWZiYTQ4NDBkZjMxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwNTE3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTcxYjc2ZWEwMzdjMTllMDY1N2U3ZWVkYTkwMWUxODA4MTEyNGIxZTJhNTQ0NzM5ZGUwMzY1NjY2NjljM2YyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.X4NLPw6BjOy7EPxtfRISNJs39DqgJKux-KeLngZJ9Gw) also i will be correcting this missing images. please assign the task to me @vivekv2810

And also we are updating this page, so that's why I didn't assigned the course page related issue to anyone 

Please understand.
