### ISSUE TITLE
Add a new feature of testimonials section. 

### ISSUE THREAD

**Issue by AasthaSingh28** [ML-Fusion-Lab/ML-Fusion-Lab-Website#386]
We can add a review or testimonials section just before footer to enhance user experience. 
It will include the reviews in text format and also stars will be given. 
@ML-Fusion-Lab - Kindly assign me this issue I want to work on this.

**Comment by vivekvardhan2810** [comment]
@AasthaSingh28 make sure to complete this issue within 2 days.

**Comment by AasthaSingh28** [comment]
Can you please assign me the hacktober label too..?

**Comment by vivekvardhan2810** [comment]
@AasthaSingh28 i will assign that label when you will create the PR, i will add that label in PR.

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by vivekvardhan2810** [comment]
i am closing this issue, but don't worry and get discouraged, you can look for other issues in website and then create the new issue.
