### ISSUE TITLE
incomplete alignment in navigation bar + Bug in text area

### ISSUE THREAD

**Issue by ParulPrashar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#39]
![Opensource1](https://github.com/user-attachments/assets/9bd003a9-d3d3-4322-8291-3ce7340034f7)

the content in top right corner of nav bar are not aligned correctly

![opensource2](https://github.com/user-attachments/assets/5fe7e235-c1e5-432c-b584-14cb639ddbf5)
 
 there is an incorrect font in the text area leading to unattractive web page

**Comment by ParulPrashar** [comment]
@Nandini-13 @vivekvardhan2810 kindly assign this issue to me with labels of hacktoberfest and gssoc

**Comment by Pratikpawar13** [comment]
@Pratikpawar13 I can solve this issue within time and 10 times more effectively than others 
please assign me this issue

**Comment by vivekvardhan2810** [comment]
@Pratikpawar13, pls wait as this issue was created by @ParulPrashar,

it will be on first come first serve

pls look for other issues

**Comment by vivekvardhan2810** [comment]
@ParulPrashar assigned this issue to you.

make sure you complete this work for the next 3 days.

**Comment by ParulPrashar** [comment]
sure sir would never let you down!
