### ISSUE TITLE
Navbar of courses and contact are different , not looking good, and In feedback section no navbar present

### ISSUE THREAD

**Issue by Piyush-t24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#391]

**Comment by Piyush-t24** [comment]
I will love to solve this issue. @ML-Fusion_Lab please assign it to me under gssoc-extended , hactober fest accepted and level .

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
