### ISSUE TITLE
Layout Issue: "About Us" and "Community Support" Sections Not Displayed Properly

### ISSUE THREAD

**Issue by madhavi-peddireddy** [ML-Fusion-Lab/ML-Fusion-Lab-Website#392]
The "About Us" and "Community Support" sections on the ML Fusion Labs website are functioning, but their layout and design are not properly displayed. The following issues were observed:

About Us Section: The text or content in this section may be misaligned, making it difficult to read or navigate. It could benefit from better spacing, font consistency, or visual structure.
Community Support Section: The section may appear cluttered, or certain elements might be overlapping or not appropriately sized for different screen resolutions.
![Screenshot (112)](https://github.com/user-attachments/assets/7fcecbff-43a7-4b0a-ac16-1acb185cc86f)
@vivekv2810 

Can you assign me the issue, i would like to work on it

**Comment by vivekvardhan2810** [comment]
I have assigned this issue before, and they are resolving it, so I am closing this issue.
