### ISSUE TITLE
Build Resource Library Section 

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#393]
I will be building the `resource library section`:
- user friendly layout
- books, study material, etc.
- video (lecture) section
- and other essential features of a resource library section
![Screenshot 2024-10-10 102209](https://github.com/user-attachments/assets/de59ffad-d79b-45bd-b318-567f2f30fb64)

![Screenshot 2024-10-10 102203](https://github.com/user-attachments/assets/e14e757e-5d29-42bd-9364-e5cbd624986a)
this section is to be built yet....
@vivekvardhan2810 please assign me this task under gssoc-extd and hectoberfest

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me this task under gssoc-extd and hectoberfest

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigned this issue to you, make sure to complete this issue within 2 days.
