### ISSUE TITLE
Projects Cards Overlapping – Add Padding/Gaps Between Project Cards

### ISSUE THREAD

**Issue by sagarbendale2004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#394]
### **Description:**
The project cards on the /projects route are currently overlapping each other, making the layout visually unappealing and difficult to navigate. There seems to be no padding or gaps between the cards, causing them to stack or overlap.

### **Steps to Reproduce:**

Visit the [Projects page] - (https://ml-fusion-lab.netlify.app/projects).
Observe the layout of the project cards.

### **Expected Behavior:** 

Each project card should be spaced properly with appropriate padding or gaps between them to ensure a clean and responsive layout.

![Screenshot 2024-10-10 102813](https://github.com/user-attachments/assets/d01975a4-b799-47dd-b8c2-5790bd49db03)

**Comment by sagarbendale2004** [comment]
@vivekvardhan2810 can you assign me this issue. I'd like to work on this issue. I'll add padding or margins to fix the card overlap and ensure the layout is responsive.

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 this issue was assigned before, you can check in issues section, so I am closing this issue.

Hope you understand it.

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 this issue was assigned before, if that contributor does completes the issue I will be closing this issue.

If she doesn't completes, I will assign you this issue, pls wait.

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 make sure to complete this issue within 2 days.

make sure to join discord server fr further updates.
