### ISSUE TITLE
Fixing Header section 

### ISSUE THREAD

**Issue by AsifQamar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#395]
Fixing the Header section , and alignment of the logo
priority -High
@vivekvardhan2810 please assign me this issue with gssoc and hacktober tag
<img width="960" alt="Screenshot_120" src="https://github.com/user-attachments/assets/1fb270a1-20e2-4eb7-a08a-9c612d308c5d">

**Comment by Kajalmehta29** [comment]
@vivekvardhan2810 Please assign this issue to me under gssoc-extd and hacktoberfest.

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues and header issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
