### ISSUE TITLE
Fixing the alignment of navbar and footer using bootstrap

### ISSUE THREAD

**Issue by neerajsharma897** [ML-Fusion-Lab/ML-Fusion-Lab-Website#397]
![image](https://github.com/user-attachments/assets/3ca89274-843f-4855-b002-bc53be7d0e48)
![image](https://github.com/user-attachments/assets/fa4a470a-6b42-4802-acb0-a33495ddd936)
So I would like to contribute to your project.

What will I do:
1. Use bootstrap to make it responsive 
   ![image](https://github.com/user-attachments/assets/d945883a-a9cb-41a5-8424-2d0c6098e04a)

If you want i can do this with plain CSS too

2. align the chatbot button and arrow button 

Please assign this to me under gssoc-extended and hacktoberfest-accepted

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.

**Comment by neerajsharma897** [comment]
okay thanks for the reply
