### ISSUE TITLE
Add Low button visibility due to insufficient contrast with the background.

### ISSUE THREAD

**Issue by aryanadla** [ML-Fusion-Lab/ML-Fusion-Lab-Website#398]
Button backgrounds blend with the dark interface, reducing visibility and usability; improve contrast and add hover effects for clarity.

![Screenshot 2024-10-10 144811](https://github.com/user-attachments/assets/dfc18c8f-7739-416c-9986-3b4f789eba4e)
![image](https://github.com/user-attachments/assets/0bded321-85db-40f2-91dd-2176d8414239)

Please Assign me this Issue I want to work on it with gssoc-ext and Hacktoberfest-accepted labels, Thank you!

**Comment by vivekvardhan2810** [comment]
for now we don't require this feature, we will look into this  later, so i am closing this issue and we are not looking for navbar or header updates.
