### ISSUE TITLE
Introducing a Detailed Course Page for Future Expansion

### ISSUE THREAD

**Issue by ArchanRD** [ML-Fusion-Lab/ML-Fusion-Lab-Website#399]
Currently, there isn't a dedicated course detail page, and users only get a brief overview of each course from the card on the **Courses** page. By creating a course detail page, we can offer users a more comprehensive understanding of what's included in each course. This detailed view could cover the course 

- content
- objectives
- duration
- instructor information

and more. Additionally, it would include a **Purchase Course** button, enabling users to take action directly from the detail page.

## Future scope after implementing this

This feature is a critical step in scaling the web app. Once the course detail page is implemented, we can further enhance the platform by adding **Login/Register** functionality, enabling users to 
- sign up
- purchase courses
- personalized User Dashboard

@vivekvardhan2810 I would like to work on this under "**gssoc-ext**" and "**hacktoberfest**". Though this issue needs dedicated time and efforts, I would request you to assign the **level labels** accordingly.

**Comment by vivekvardhan2810** [comment]
@ArchanRD make sure to complete this issue within 2 days.

**Comment by ArchanRD** [comment]
I will make it responsive if you considering this issue upgrading to level 3. Please let me know!

**Comment by vivekvardhan2810** [comment]
@ArchanRD Updated the level, please make it good.

**Comment by ArchanRD** [comment]
For sure!
