### ISSUE TITLE
Fix Navbar 

### ISSUE THREAD

**Issue by ezDecode** [ML-Fusion-Lab/ML-Fusion-Lab-Website#4]
The navbar could be improved. If you allow me to contribute, I can fix it!
![Uploading Screenshot 2024-10-01 182802.png…]()

**Comment by ezDecode** [comment]
![Screenshot 2024-10-01 184449](https://github.com/user-attachments/assets/e1918c39-f3c2-4be5-8658-ef10672bb38b)

**Comment by ezDecode** [comment]
we make the UI more better and a floating navbar also!
what do you think?

**Comment by ezDecode** [comment]
I'm done with it! want to see!!

**Comment by ezDecode** [comment]
![Screenshot 2024-10-01 185016](https://github.com/user-attachments/assets/acd75f7c-4a10-490d-a176-956098b2746c)
What do you think??

**Comment by ezDecode** [comment]
Let me know what additional changes you’d like; I’d be happy to implement them.

**Comment by vivekvardhan2810** [comment]
@ezDecode, it looks good, but could you think some alternate improvements like 

In terms of colours, buttons (like at home, courses and all that)

**Comment by Codewithmeowmeow** [comment]
Hey can u assign me this issue. I would love to work on this.

**Comment by aditya-bhaumik** [comment]
its first come first serve you can create another issue if you want @Codewithmeowmeow

**Comment by vivekvardhan2810** [comment]
@ezDecode 

make sure to complete this issue for the next 3 days.

make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH

**Comment by ezDecode** [comment]
i cant join the discord server showing unable to join tell me you discord name i will join or connect with you
