### ISSUE TITLE
Missing logo in home tab 

### ISSUE THREAD

**Issue by ParulPrashar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#40]
It is crucial to add logo of company for distinction in nav bar
![Opensource1](https://github.com/user-attachments/assets/2d3808d4-e109-4a49-9cdf-9663bd058ee2)

@vivekvardhan2810 Kindly assign this issue to me labels gssoc, hacktoberfest

**Comment by Iampratyush004** [comment]
@vivekvardhan2810 Kindly assign this issue to me labels gssoc, hacktoberfest

**Comment by vivekvardhan2810** [comment]
@ParulPrashar will it be okay for you if i assign this issue to @Iampratyush004, as he had completed this and kept PR.

But still @ParulPrashar i will assign you the other issue which you have mentioned (Will it be ok for you).

**Comment by ParulPrashar** [comment]
sure sir but please do assign me some as it takes a lot to find out issues. its a request

**Comment by vivekvardhan2810** [comment]
> @vivekvardhan2810 sure sir but please do assign me some as it takes a lot to find out issues. its a request

@ParulPrashar i have assigned you in other issue.

please do that work.
