### ISSUE TITLE
Adding  a Newsletter Sign-Up Confirmation Message

### ISSUE THREAD

**Issue by Palmistry2310** [ML-Fusion-Lab/ML-Fusion-Lab-Website#400]
#### Description
When users submit their email to sign up for the newsletter, there is currently no confirmation message displayed to inform them if the submission was successful. This can lead to confusion, as users may be unsure whether their action was completed. 

#### Enhancement Proposal:
- **Add a confirmation message** that informs users if their newsletter sign-up was successful.
- Display the message after the form submission.
- Ensure the message is dismissible or disappears automatically after a few seconds.

@vivekvardhan2810 I would like to work on this under "gssoc-ext" and "hacktoberfest-accepted". And also assign level label accordingly.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 make sure to complete this issue within 2 days.

**Comment by Palmistry2310** [comment]
Sure, @vivekvardhan2810 may you please add "hacktoberfest-accepted" label ?

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 i will add the label, when you create the Pull Request.

**Comment by Palmistry2310** [comment]
@vivekvardhan2810
I noticed that my work on the Newsletter Sign-Up Confirmation Message issue was given a level 1 rating. While I appreciate the feedback and the opportunity to contribute, I wanted to explain why I believe this issue might warrant a higher level.

This feature is more than just a simple UI update; it adds an essential user experience improvement, ensuring that users are informed of successful newsletter subscriptions. The implementation required me to:

- Design and integrate a user-friendly, responsive message that is visible across different devices.
- Ensure proper functionality and visual consistency within the site's theme.
- Handle  email validation  improving the overall experience.
Given the combination of UX considerations, the technical integration of feedback mechanisms, and ensuring responsive behavior, I believe this work adds significant value to the project and involves more complexity than a typical level 1 task.

I would appreciate it if you could reconsider the level assigned.

**Comment by vivekvardhan2810** [comment]
Upgrading the level @Palmistry2310, make sure to complete it.
