### ISSUE TITLE
Request for Permission to Improve UI Navigation Bar

### ISSUE THREAD

**Issue by Aryan-joh** [ML-Fusion-Lab/ML-Fusion-Lab-Website#401]
Hi @vivekvardhan2810,

I hope this message finds you well. I am reaching out to request your permission to enhance the user interface of the navigation bar on the website.
![Screenshot 2024-10-06 162653](https://github.com/user-attachments/assets/c0534b27-334d-47fd-af79-9638bbda4b5e)
i will make the changes in this from the following screenshot ..
![Screenshot 2024-10-06 180019](https://github.com/user-attachments/assets/885f25da-dbb5-4ced-9435-62f615614f88)
this change make the website attractive .
Please assign this issue to me with "hactoberfest" "hactoberfest-accepted" "gssoc-extd" "level-1" labels to make more confident towards open source.
Please let me know if i can proceed this issue. I appreciate your consideration.

Best regards,
Aryan-joh

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
