### ISSUE TITLE
Adding FavIcons on about us section 

### ISSUE THREAD

**Issue by VidhanThakur09** [ML-Fusion-Lab/ML-Fusion-Lab-Website#402]
### Description

The visibility of the favicon on the About Us section is missing which led to Visitors to About Us pages can not easily identify the page they are on and make it difficult to navigate the website more efficiently.

### Screenshots

![Screenshot 2024-10-10 195205](https://github.com/user-attachments/assets/25396296-e96a-407c-a3fa-c7e0cc850e66)

@vivekvardhan2810 can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 assigning this issue to you, 

make sure to complete this issue within 2 days, i will add hacktoberfest-accepted label at PR.
