### ISSUE TITLE
[Bug] The navbar is overlapping!

### ISSUE THREAD

**Issue by isnehamondal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#404]
Hello @vivekvardhan2810 ,
this is Sneha, a contributor in GSSoC.

ISSUE: 
The navbar has some overlappig contents.
![mlfusion navbar b](https://github.com/user-attachments/assets/5166e079-8093-4004-b111-d99488152e66)

I want to work on this and contribute. I request you to assign this task to me and add the labels(gssoc-ext, hacktoberfest-accepted, level).
Thanks!

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
