### ISSUE TITLE
The about us section in home page!

### ISSUE THREAD

**Issue by isnehamondal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#405]
Hello @vivekvardhan2810 ,

Description of the issue:
The about us section(read more) isn't taking to the page of about us.
I am providing a video of the issue.

https://github.com/user-attachments/assets/379c333f-529a-45c4-9e3b-9f2d770cb428

![mlfb](https://github.com/user-attachments/assets/66b4a20f-0bea-43f9-a770-0e4242fb3de7)

I can fix this issue. I request you to assign this task to me and add the labels. Thanks!

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, so i am closing this issue.
