### ISSUE TITLE
[BUG]: The cards under project section [class: project-item] is overlapping with each other.

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#406]
The card that are in under project section below Featured Projects are overlapping  which is not giving a clean look.
I would like to improve this issue.
![Screenshot 2024-10-10 205451](https://github.com/user-attachments/assets/01ff13a3-fa79-46da-8ad2-9c5e14b8305b)

@vivekvardhan2810  if u find this issue suitable kindly assign it to me under hactktoberfest and GSSOC.

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 this issue was assigned before, please check it, so i am closing this issue, but don't worry
