### ISSUE TITLE
Buttons Overlapping in navbar Section

### ISSUE THREAD

**Issue by potdarsrushti4** [ML-Fusion-Lab/ML-Fusion-Lab-Website#407]
<img width="959" alt="p1" src="https://github.com/user-attachments/assets/1184ad0f-eda2-4830-afb8-9458e1f0b0fc">
I encountered an issue with the layout of the "About Us" and "Support Community" buttons. When viewing the page, these buttons overlap, making it difficult to click on them.

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.

**Comment by potdarsrushti4** [comment]
Okay
