### ISSUE TITLE
[BUG]: Under about us section footer text color is not not complementing also in dark mode the text color remains the same.

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#409]
I would like to update the about us section as,
footer text color are not complementing with the background  and
the Class `h2text` are not changing with the mode change
![Screenshot 2024-10-10 210926](https://github.com/user-attachments/assets/ccefb931-02f9-4212-9e66-d66627118756)
![Screenshot 2024-10-10 210505](https://github.com/user-attachments/assets/6d0aca6d-108b-408a-9361-190c6df8f920)

@vivekvardhan2810  if you fins this issue suitable kindly assign it to me under hacktoberfest ,GSSOC

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 make sure to complete this issue within 2 days, i will add the hacktoberfest label at PR which you create.

**Comment by shreyabajaj12** [comment]
Thanks a lot sir... I would make sure to complete on time
