### ISSUE TITLE
Responsiveness of home page

### ISSUE THREAD

**Issue by Ishika-Singhal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#410]
Home page is not responsive  on mobile screens .
![IMG_20241010_211353](https://github.com/user-attachments/assets/f774d306-b11a-40c2-bf3c-73335502b1ed)

Please assign this issue

**Comment by vivekvardhan2810** [comment]
@Ishika-Singhal make sure to complete this issue within 2 days, 

make sure to star the repo, join the discord server for more updates.
