### ISSUE TITLE
[Feat]: Adding a sliding feature with 3 pictures in the home page complementing the text and background color

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#411]
I would like to add a feature of sliding multiple images that would complement the text written on it and also the background 
that would enhance the look of the page.
![Screenshot 2024-10-10 210630](https://github.com/user-attachments/assets/e95844f2-8223-4940-99b6-46a2245f2dfe)

@vivekvardhan2810  if u find this feature useful kindly assign it to me under hacktoberfest and GSSOC.

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 pls complete the issue assigned you before.

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 for now we don't require this, we will look into this later, so i am closing this issue.
