### ISSUE TITLE
Mouse Cursor Trail Effect

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#419]
The mouse cursor trail effect creates a visual trail that follows the cursor's movement, leaving a fading imprint behind. 

Benefits:

1. Enhanced Visibility: Makes the cursor easier to locate, especially on busy or cluttered screens.
2. User Engagement: Adds an interactive element that can make navigation more enjoyable and visually appealing.
3. Accessibility Improvement: Aids users with visual impairments by providing a clearer indication of cursor movement.
4. Aesthetic Appeal: Contributes to a modern and dynamic look, enhancing the overall design of applications and websites.
5. Tracking Assistance: Helps users follow the cursor’s path, improving interaction with complex interfaces.

Please assign this issue to me under GSSoC- ext and Hacktoberfest

**Comment by vivekvardhan2810** [comment]
@Priyanshi0112 assigning this issue to you, make sure to complete this issue within 2 days.
