### ISSUE TITLE
Add a SEARCH bar OPTION in your PROJECTS SECTION.

### ISSUE THREAD

**Issue by Shivasingh15** [ML-Fusion-Lab/ML-Fusion-Lab-Website#422]
### Is your feature request related to a problem? Please describe.

In your PROJECTS SECTION there is no search bar 
option, I want you to please assign me.
so that's way I'll give my contribution in your website.
Thanking you
![Screenshot 2024-10-10 235718](https://github.com/user-attachments/assets/7dfbe6cc-64ae-446e-bca9-496f74163245)

### Describe the solution you'd like.

![Screenshot 2024-10-10 235808](https://github.com/user-attachments/assets/98f9aaec-9402-4db3-b642-86ea26e5afd9)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Shivasingh15 assigning this issue to you, ame sure to complete this issue, within 2 days 

Make sure to join discord server for further updates.

**Comment by PREM-A261** [comment]
2 week are their 
@PREM-A261 Please assign me

**Comment by Lokesh-Mapui** [comment]
I would like to work on this project,please assign it to me.I am confident that my skills and experience will add value to the project

**Comment by vivekvardhan2810** [comment]
@Shivasingh15 this project is going to be inactive from october 25th including me also.

it's been 2 weeks.

if this task is delaying from your side, then you can close this issue also. No problem.

i am asking this because i am going to be active for the next 3 days only.

**Comment by muskiagrwal** [comment]
i want to work on this project please assign me

**Comment by vivekvardhan2810** [comment]
Hi @Shivasingh15 

It’s been over a week without any updates. I will be closing this issue by the end of the day. If you have any progress to share, please do so before then.

Thank you!

**Comment by vivekvardhan2810** [comment]
@Shivasingh15 Any Updates?? It's been a week. Please respond asap.

**Comment by Lokesh-Mapui** [comment]
I would like to work on this project. Please assign it to me, as I have experience

**Comment by vivekvardhan2810** [comment]
As there is no response from your side, i am closing this issue.
