### ISSUE TITLE
Personalized Learning Paths

### ISSUE THREAD

**Issue by potdarsrushti4** [ML-Fusion-Lab/ML-Fusion-Lab-Website#423]
### Is your feature request related to a problem? Please describe.

We could implement a feature where users can input their skills, and based on this information, the system would suggest appropriate courses tailored to their level and interests.

### Describe the solution you'd like.

1) When a user submits their skills and level, the system will:
2) Retrieve courses that match the input skills.
3) Filter courses based on the specified skill level.
4) display a list of recommended courses along with brief descriptions, ratings, and links to enroll.

--pseudo code--
function getMatchingCourses(userSkills, userLevel) {
    const courses = [
        { name: "Intro to Machine Learning", skills: ["Python", "Machine Learning"], level: "beginner" },
        { name: "Advanced Data Science", skills: ["R", "Statistics"], level: "advanced" },

    ];

    // Filter courses
    const matchingCourses = courses.filter(course => {
        const skillMatch = course.skills.some(skill => userSkills.includes(skill));
        const levelMatch = course.level === userLevel;
        return skillMatch && levelMatch;
    });

    return matchingCourses;
}

const userSkills = ["Python", "Data Analysis"];
const userLevel = "beginner";
const recommendedCourses = getMatchingCourses(userSkills, userLevel);
console.log(recommendedCourses);

### Additional context.

Filter Logic:

1. Perform a keyword match against the course database.
2. Retrieve courses that contain the input skills in their descriptions or tags.
3. Filter the results based on the user-specified skill level.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/e041960e-55d5-4f26-9a72-e8e9acc8d920)
![image](https://github.com/user-attachments/assets/58806883-3f1f-45f2-97e7-7ae120f952d9)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, so I am closing this issue.
