### ISSUE TITLE
i want to create responsive navbar and footer for every page 

### ISSUE THREAD

**Issue by ragineedarade** [ML-Fusion-Lab/ML-Fusion-Lab-Website#424]

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
