### ISSUE TITLE
Add a hover when mouse runs over these components

### ISSUE THREAD

**Issue by ShaliniKashyap717** [ML-Fusion-Lab/ML-Fusion-Lab-Website#425]
### Description

i think it would be better if the text could hover also (change colour) when the mouse runs over those components (data science, programming and development page, etc.) in the course section. please assign it to me under gssoc-extd and hacktoberfest-accepted if possible. if u dont want it, then i also saw one issue, that the navbar wasnt properly aligned for all screen types like in my pc, i have a small screen so it wasn't really fitting into it. so i can also fix it. but i saw someone was fixing for mobile screens so maybe she might be doing for all screen types. if not then i can.

### Steps to Reproduce

i simply need to add some css and we're done with the hover effect.

### Expected Behavior

the text would hover when the user runs its mouse over it :)

### Actual Behavior

<img width="959" alt="hober" src="https://github.com/user-attachments/assets/09460c2f-1f28-4289-b64d-c9e090ad8661">

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now we are not looking for this feature, as we are updating the course page,  But don't discourage, you can look out for other issues in website then you can create new issue.

So I am closing this issue.
