### ISSUE TITLE
Fix header

### ISSUE THREAD

**Issue by poorvikaa08** [ML-Fusion-Lab/ML-Fusion-Lab-Website#426]
### Description

The header of the homepage seems broken as it contains duplicate elements and overlapped.

### Steps to Reproduce

I would like to fix this by removing the duplicate header elements

### Screenshots

![image](https://github.com/user-attachments/assets/c0567ac9-f905-492a-87e5-57bee6f6f733)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues and header issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
