### ISSUE TITLE
Update twitter icon

### ISSUE THREAD

**Issue by poorvikaa08** [ML-Fusion-Lab/ML-Fusion-Lab-Website#427]
### Description

The current display button for Twitter on the website still shows the old Twitter bird icon. Twitter has rebranded to "X" with a new logo, so this button should be updated to reflect the latest branding.

### Steps to Reproduce

Replace the old twitter bird icon with the new twitter-X icon

### Screenshots

![image](https://github.com/user-attachments/assets/eceec131-44cd-4867-879b-8e68529b049d)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@poorvikaa08 assigning this issue to you, make sure to complete this issue within 2 days.

And make sure to join discord server for further updates.

And only update the symbol on the pages which is needed to be update.

**Comment by vivekvardhan2810** [comment]
I will add that label, when you create the Pull request

**Comment by poorvikaa08** [comment]
Okay, Thanks for it assigning me

**Comment by vivekvardhan2810** [comment]
Make sure to complete it within 2 days.

**Comment by poorvikaa08** [comment]
@vivekvardhan2810 
I didn't notice that this icon has to be updated on the courses page too

![image](https://github.com/user-attachments/assets/bf935a43-d2c7-4d7f-af2c-51a37bc47db8)

**Comment by poorvikaa08** [comment]
can I update it?

**Comment by vivekvardhan2810** [comment]
For now it is okay

**Comment by Antima2004** [comment]
please assign this to me @vivekvardhan2810
