### ISSUE TITLE
Font style

### ISSUE THREAD

**Issue by poorvikaa08** [ML-Fusion-Lab/ML-Fusion-Lab-Website#429]
### Description

There are different font styles used on the website.
It is preferably good to implement a single font-style throughout the website.

### Steps to Reproduce

Use a single font style such as arial or poppins from sans-serif family

### Screenshots

![image](https://github.com/user-attachments/assets/312094cc-4c88-4d88-b8a9-dc860b3d8063)
![image](https://github.com/user-attachments/assets/dda82f53-c705-4d3e-8072-c64b224be048)
![image](https://github.com/user-attachments/assets/489e4746-6ba5-4576-9772-9fd866b3b718)
![image](https://github.com/user-attachments/assets/94e18909-1d80-44e8-a901-9af186ec6d02)
![image](https://github.com/user-attachments/assets/c5e6fad7-0942-4b76-82b4-98833b2b0bb2)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@poorvikaa08 we will look for fonts later, for now we are closing this issue.

Please understand.
