### ISSUE TITLE
Create a sign up and log in page

### ISSUE THREAD

**Issue by ParulPrashar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#43]
We need to create a log in and sign up page right from scratch to keep access to our customer details
1. name
2. email
3. password
4. interested courses
etc.

@vivekvardhan2810 @Nandini-13 Kindly assign this issue to me

**Comment by vivekvardhan2810** [comment]
Hi @ParulPrashar, i will assign this issue soon,

and you can tag me only

as nandini is the contributor (don't tag @Nandini-13 )

@vivekvardhan2810 (i am) the project admin

**Comment by Krisha0208** [comment]
could you assign the tsk to me under gssoc ext

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
