### ISSUE TITLE
The text and the descriptions of each page needs some animations

### ISSUE THREAD

**Issue by ThunderShadows** [ML-Fusion-Lab/ML-Fusion-Lab-Website#430]
The animation of the text area and the description of the sub topics in each page is static and needs some responsiveness.

@ML-Fusion-Lab

I shall include some CSS styling and text animations in each page so that it is user friendly and responsive and interactive for the users.

**Comment by vivekvardhan2810** [comment]
For now we don't require for this feature,we will look it later, So I am Closing this issue

Please Understand.
