### ISSUE TITLE
[BUG]: There is no reset button in contact form page and also after submitting the record no successful message

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#432]
### Description

1) No reset button in the contact us page
2) No successful msg after submitting the record except it is leading to uncreated page.

### Steps to Reproduce

I would add a reset button in the page so that user could be able to reset the information if found error.
I would add a successful message which would be showing after submitting the form and will try to add a custom error message for email and name field if the trying to submit blank.

### Expected Behavior

There should be a reset button
successful message after summiting  the form.

### Screenshots

![Screenshot 2024-10-11 082424](https://github.com/user-attachments/assets/a3f6cb39-884c-4a4b-b0c4-f6f545150c60)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 assigning this issue to you

Make sure to complete this issue within 2 days.
