### ISSUE TITLE
Enhancing the fonts of the website

### ISSUE THREAD

**Issue by faeez004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#433]
### Is your feature request related to a problem? Please describe.

The enhancement of fonts is not related to any problem. The existing Times New Roman font looks too generic so I propose to replace it with better looking font - Montserrat.

### Describe the solution you'd like.

I would like to improve the overall look of website by changing the font to Montserrat. The reason I chose Montserrat is that it looks elegant and professional and improvises the overall look of the website.

### Describe alternatives you've considered.

If admin/mentor wants a font other than Montserrat to be used on the website, I'll be happy to do that.

### Show us the magic with screenshots

![Screenshot (59)](https://github.com/user-attachments/assets/9b3f96c0-126c-4b59-b1de-4f8deb6d2563)
The website looks more elegant with the new font.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by faeez004** [comment]
I have worked on it and am ready to take this issue. Please assign it to me.

**Comment by vivekvardhan2810** [comment]
Hi, @faeez004 we will look for fonts later, for now we are closing this issue.

Please understand.

**Comment by faeez004** [comment]
Thank you for the update.

I understand the decision to prioritize other tasks for now. Please feel
free to reach out whenever the font issue is revisited—I'd be happy to
contribute.
