### ISSUE TITLE
[Mention The Feature]: Working on navbar and Home page navigation for projects, about us, contact, community support page

### ISSUE THREAD

**Issue by saumyayadav25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#434]
### Is your feature request related to a problem? Please describe.

1) Navbar on home page does'nt look good, and text is also hidden.-> no proper styling of navbar
<img width="1418" alt="Screenshot 2024-10-11 at 10 42 15 AM" src="https://github.com/user-attachments/assets/c0389ae1-819e-485e-a854-617439ccdcc2">

2) No option to navigate back to home page on other pages (home page navigation is only available for courses page)
<img width="1420" alt="Screenshot 2024-10-11 at 10 43 10 AM" src="https://github.com/user-attachments/assets/e5c2147b-761c-4be6-b08e-69b5b490a798">

### Describe the solution you'd like.

1) Proper styling for navbar so that all the content is clearly visible.
2) adding home page navigation on other pages for better user experience and easy navigation on different pages.

### Describe alternatives you've considered.

1) Proper styling for navbar so that all the content is clearly visible.
2) adding home page navigation on other pages for better user experience and easy navigation on different pages.

### Additional context.

Attached screenshots in feature requests.

### Show us the magic with screenshots

1) for navbar
<img width="1388" alt="Screenshot 2024-10-11 at 10 58 52 AM" src="https://github.com/user-attachments/assets/2c09b1b6-e18e-4667-900d-ed526f915d8c">
2) Home page navigation
<img width="1424" alt="Screenshot 2024-10-11 at 11 00 59 AM" src="https://github.com/user-attachments/assets/3b860967-6344-4d19-a47a-7201dfaa9938">
similarly for other pages, navigation to home page is made available.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
