### ISSUE TITLE
Header is not responsive 

### ISSUE THREAD

**Issue by Parth-Gupta-github** [ML-Fusion-Lab/ML-Fusion-Lab-Website#435]
### Description

While changing zoom in desktop or in mobile phone Header section of "About Us" and "Community Support" Is not visible properly I will remove this bug if issue is assigned to me . I request @vivekvardhan2810 to kindly assign me this issue i have full faith that i can solve it in a better UI friendly manner.

### Steps to Reproduce

I will make properly alignment of header options and check it for compatibility with different devices.

### Screenshots

![Screenshot_49](https://github.com/user-attachments/assets/700dddc7-cf8d-45c1-9dd0-f85ee4293135)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues and header issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
