### ISSUE TITLE
Fix the Course Page 

### ISSUE THREAD

**Issue by Gahlotkumkum** [ML-Fusion-Lab/ML-Fusion-Lab-Website#436]
### Description

Not all boxes are aligned properly and needs a margin from both side.  Remove the unnecessary box at the top.

### Steps to Reproduce

Adding some margin and fixing alignment.

### Screenshots

![image](https://github.com/user-attachments/assets/d29e448b-a0b5-4bcc-808e-40c6d1e69749)
![image](https://github.com/user-attachments/assets/64e2d888-0f61-4c44-b67b-bd5e948d1b63)

### Additional Information

"I will address this issue and resolve any additional errors I find later, so please assign it a level 2 label."

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue and the course page updation was assigned before, so I am closing this issue.
