### ISSUE TITLE
upgrade your footer section of COMMUNITY SUPPORT menu and add some more detail

### ISSUE THREAD

**Issue by Pranjalsinha110** [ML-Fusion-Lab/ML-Fusion-Lab-Website#438]
### Is your feature request related to a problem? Please describe.

Assign me to upgrade the footer section of the Community Support menu, which will enhance your UI/UX and also increase your user reach as well as engagement.
A good footer section is responsible for branding of the company as well as its product

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Pranjalsinha110 I have assigned this issue to someone and they have created the PR, and Updating it.

So I am Closing this issue, I hope you understand.
