### ISSUE TITLE
[Mention The Feature]: LOGIN SIGN UP PAGE 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#441]
### Is your feature request related to a problem? Please describe.

ADD A LOGIN AND SIGN UP PAGE 

### Describe the solution you'd like.

I WANT TO ADD A LOGIN AND SIGN UP PAGE 

### Show us the magic with screenshots

THESE ARE FEW SAMPLES OF WHAT I HAVE MADE BEFORE

https://github.com/user-attachments/assets/1275d2fd-e2e9-442d-982e-37a075f433c0

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by HS202022** [comment]
i will change the color palate accordingly

**Comment by Krisha0208** [comment]
could you assign this task to me under gssoc 24

**Comment by vivekvardhan2810** [comment]
@HS202022 assigned this issue to you.

Make Sure to complete this issue within 2 days.

and make sure to join discord server for further updates.
