### ISSUE TITLE
[DOCS] social media group

### ISSUE THREAD

**Issue by Lekkhasri** [ML-Fusion-Lab/ML-Fusion-Lab-Website#442]
### Issue Description

i like to create the social media group for the webpage.

### Screenshots or Examples (if applicable)

![Uploading Screenshot 2024-10-10 224220.png…]()

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
@Lekkhasri can you keep the screenshot properly, so that i can look onto it.

**Comment by Lekkhasri** [comment]
@vivekvardhan2810 
![image](https://github.com/user-attachments/assets/63416582-1dd5-45e4-a5ef-77aa744dbcfb)

social media group in the community page.

**Comment by vivekvardhan2810** [comment]
@Lekkhasri assigning this issue to you, make sure to complete this issue within 2 days.

**Comment by Lekkhasri** [comment]
@vivekvardhan2810 can you provide the social media links of your webpage

**Comment by vivekvardhan2810** [comment]
@Lekkhasri for now ML fusion labs don't have a social media links,

for the temporary you can use these links.

Linkedin: https://www.linkedin.com/in/vivek-vardhan-23682521b/

Twitter: https://x.com/Vivek43862

i don't have any instagram

Github: https://github.com/ML-Fusion-Lab

**Comment by Lekkhasri** [comment]
@vivekvardhan2810 ok i will create the page with these links
