### ISSUE TITLE
Page improvisation of feature projects

### ISSUE THREAD

**Issue by MetiUmashri** [ML-Fusion-Lab/ML-Fusion-Lab-Website#443]
### Is your feature request related to a problem? Please describe.

Here basically the cards are overlapping due to poor css. Hence this is giving very bad effect on the overall webpage as well.
<img width="960" alt="image" src="https://github.com/user-attachments/assets/81678c6b-f6b9-4270-87ce-396de60bdcbd">

### Describe the solution you'd like.

I would like to improvise the overall ui of the projects page of ML fusion labs website

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by MetiUmashri** [comment]
@vivekvardhan2810 kindly assign this feature request issue to me

**Comment by vivekvardhan2810** [comment]
this issue was assigned before and it it existing, you can check the issues section also, so I am Closing this issue.

**Comment by MetiUmashri** [comment]
[vivekvardhan2810](https://github.com/vivekvardhan2810) is there any issue which i can work upon
