### ISSUE TITLE
[Mention The Feature]: Need to add some features 

### ISSUE THREAD

**Issue by Trumilnasit** [ML-Fusion-Lab/ML-Fusion-Lab-Website#445]
### Is your feature request related to a problem? Please describe.

@vivekvardhan2810 :-I want to add more details regarding every ML projects in their description and also want to lock-screen when it show and also wants to add some more features can you assign it to me with level3 for all level or level2 for some with all labels like hactoberfest,gssoc'24 and etc..

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require this, we will look it later, so I am Closing this issue.

Please Understand.
