### ISSUE TITLE
Some icon is not showing on the Courses page

### ISSUE THREAD

**Issue by Sadab-Hussain** [ML-Fusion-Lab/ML-Fusion-Lab-Website#447]
### Description

 I have tried the following:

Confirmed that the icon library is included in the HTML.
Verified that the icon class names are correct.
Used the "Inspect" tool and found the icons present in the DOM.
Checked the CSS but found no rules hiding the icons.

### Steps to Reproduce

Open the Courses page.
Check the <head> for the icon library inclusion.
Verify the icon class names in the HTML.
Inspect the DOM to confirm the icon elements are present.
Review CSS rules for any visibility issues.
Refresh the page to see if the icons appear.

### Expected Behavior

I expected the icons to display correctly on the Courses page, visually representing their intended functions and enhancing the overall user interface.

### Actual Behavior

The icons did not display on the Courses page, resulting in missing visual elements that were intended to enhance the user interface and convey functionality.

### Screenshots

![Screenshot 2024-10-11 163543](https://github.com/user-attachments/assets/ec097750-811a-40d1-a93f-4bb17f06946d)

### Additional Information

I believe the issue is due to a missing or non-functional icon library.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Sadab-Hussain assigning this issue to you,

Make sure to complete this issue within 2 days.

**Comment by Sadab-Hussain** [comment]
yeah sure thank you for assign to me
