### ISSUE TITLE
navigation bar alignment/ overall UI/UX

### ISSUE THREAD

**Issue by thlghs** [ML-Fusion-Lab/ML-Fusion-Lab-Website#453]
![image](https://github.com/user-attachments/assets/dc39b354-f31f-475c-ba80-72c5b690be15)
![image](https://github.com/user-attachments/assets/605ef5ab-ed5f-43e0-95d1-a223dd8f3815)
![image](https://github.com/user-attachments/assets/86c434be-3f71-4068-bad4-fa2913abc47f)

the navigation bar is not aligned. the course icons on the courses page are not aligned perfectly. the signup for newsletter textbox can be bigger and more visually appeal. let me make these changes please

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
