### ISSUE TITLE
fixing padding in courses section

### ISSUE THREAD

**Issue by AsifQamar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#457]
### Description

there should me padding between the courses section card 

### Steps to Reproduce

i'll fix it

### Expected Behavior

there should be space between the sides of cards 

### Actual Behavior

no spaces

### Screenshots

<img width="960" alt="Screenshot_142" src="https://github.com/user-attachments/assets/57b50fa3-d7a3-4e6f-bba3-311aac2a4551">

### What browser are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by AsifQamar** [comment]
@vivekvardhan2810 please assign me this issue with hacktober and gssoc tag

**Comment by vivekvardhan2810** [comment]
from my side it is looking good, so i am closing this issue, please understand.
