### ISSUE TITLE
[Mention The Feature]: Firebase integration

### ISSUE THREAD

**Issue by ArchanRD** [ML-Fusion-Lab/ML-Fusion-Lab-Website#458]
### Is your feature request related to a problem? Please describe.

The website has grown significantly, and with the addition of courses, the next logical step is to enable users to purchase them. To facilitate this, we need a database to store user information. This will be a major step towards expanding the website's functionality, allowing for more personalized and detailed features such as course tracking, purchase history, and user accounts. Not only for authentication, the courses can be stored on firebase. One of the cool thing firebase offers is real time database which can be also considered in use for required features.

### Describe the solution you'd like.

Integrating a Firebase database is a simple and efficient solution, offering quick integration without the need for a complex backend setup. Firebase offers 
1. Simple and quick integration  
2. Multiple authentication methods  
3. No framework dependency   
4. No need of schema  
5. Scalable Solution  

### Describe alternatives you've considered.

Once the website has grown upto certain level or a proper folder structure or framework is used, we can shift to **MySQL** databases which are optimal for larger web applications. Though it would be not very simple to use but it provides great hands on with such web apps.

Right now using MySQL can make project complex and could mess up for other contributors too. Using it right now doesn't seems to be a good option according to me.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ArchanRD i am keeping this issue for hold.

As this project is for beginner friendly only.

**Comment by ArchanRD** [comment]
No problem 👍🏻

**Comment by vivekvardhan2810** [comment]
@ArchanRD till then you can contribute to other projects also.

**Comment by vivekvardhan2810** [comment]
@ArchanRD for now we don't require for this.

so i am closing this issue.

Please understand.

And Thank you for contributing to ML Fusion Labs.

And one more thing this project is gonna be inactive from today evening including me also.

Wishing you all the best for your future endeavors
