### ISSUE TITLE
Navigation Bar and Footer

### ISSUE THREAD

**Issue by akansha-02** [ML-Fusion-Lab/ML-Fusion-Lab-Website#46]
The header looks straightforward, but we could add subtle effects and could be paired with a simple, minimalistic icon related to machine learning or technology for better branding.
![Screenshot 2024-10-02 002540](https://github.com/user-attachments/assets/e54aa72f-0bb4-487f-b2d4-109e3f2c0758)

**Comment by vivekvardhan2810** [comment]
Hi @akansha-02 I have assigned you an issue before.

Please complete that first 

And this issue was resolved

for now i am closing this issue.
