### ISSUE TITLE
 🚀Feature Request: Q&A Session Page

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#461]
### Is your feature request related to a problem? Please describe.

This Section is not built yet

## **Features to Include:**
- Weekly Q&A video` section with latest video on the main page and archives of previous sessions.
- Last week's Q&A `FAQs`.
- `Ask Your Question` section for user submissions.
- Q&A guidelines and regulations.
- Next Q&A `date and event` schedule.
- `responsive` for both mobile and desktop
- with `dark mode` and `light mode` too (as it is the theme of website)
- @vivekvardhan2810 

## This is the current status of the part i want to improve

![Screenshot 2024-10-11 211540](https://github.com/user-attachments/assets/ba418044-8dc9-4066-bc03-6a63e437dfdb)

![Screenshot 2024-10-11 211713](https://github.com/user-attachments/assets/eee7e0fd-2138-4c96-ac40-667e7463548b)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 you want to improve

![image](https://github.com/user-attachments/assets/89bbb4b1-f72c-4e98-a778-ad06c5fb3a4a)

this one in community support page, is it.

**Comment by Adarsh-Chaubey03** [comment]
yes

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 Okay, Assigning this issue to you, 

make sure to complete this issue within 2 days.
