### ISSUE TITLE
[improve privacy-policy and terms page]: Remove large gaps between the titles and details

### ISSUE THREAD

**Issue by Vaishh18** [ML-Fusion-Lab/ML-Fusion-Lab-Website#462]
### Is your feature request related to a problem? Please describe.

Yes, this feature request is related to a design issue on the "Privacy Policy" and "Terms" pages. Currently, there are large gaps between section titles and their respective content, leading to poor readability and a disjointed user experience. These unnecessary spaces make it harder for users to quickly scan through the information, which is especially important for legal documents. Reducing these gaps will improve the overall page layout and ensure a cleaner, more professional appearance.

![Screenshot 2024-10-11 213149](https://github.com/user-attachments/assets/089be8f8-b8ec-4d30-be7f-fe1d75a7d650)
![Screenshot 2024-10-11 213139](https://github.com/user-attachments/assets/c5b27d92-2614-4d23-85dc-fad92210f65b)
![Screenshot 2024-10-11 213121](https://github.com/user-attachments/assets/f0b082b6-989c-4da2-9ec2-bf3251a70c89)
![Screenshot 2024-10-11 213107](https://github.com/user-attachments/assets/1f6e76da-38db-4dcf-a7f4-efd61a86b83c)

### Describe the solution you'd like.

Reduce the Spacing:

Adjust the CSS to reduce the large gaps between section titles and the corresponding details. Ensure that the spacing is consistent and visually appealing, without causing the content to feel too compressed.
Maintain enough space for readability, but remove excessive padding or margins that disrupt the flow.
Improve Layout Consistency:

Ensure uniform spacing between all sections and subheadings on both pages to provide a cohesive reading experience.
Use standardized spacing that aligns with the rest of the website's design guidelines.

### Show us the magic with screenshots

I will make a similar page to this one which will match to the styling of the website

![Screenshot 2024-10-11 210802](https://github.com/user-attachments/assets/0f327923-c81c-40ae-aa77-690e2b34bcfb)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Vaishh18** [comment]
@vivekvardhan2810 ,please assign me this issue .i would like to work on it.

**Comment by vivekvardhan2810** [comment]
@Vaishh18 Okay, Assigning this to you.

make sure you complete this issue within 2 days.
