### ISSUE TITLE
Change the background Image of Homepage as it's of low pixels and blurry with unsplash watermark.

### ISSUE THREAD

**Issue by RohanShrivastava08** [ML-Fusion-Lab/ML-Fusion-Lab-Website#464]
![Screenshot (476)](https://github.com/user-attachments/assets/38810e25-376e-4b17-92f2-b0ee67dc6253)

I can enhance the image quality and add a good and catchy image that makes the Homepage(index page) looks awesome and great.
Assign me it, so that I begin asap !!

**Comment by vivekvardhan2810** [comment]
for now we don't require for this, we will look at this later, so i am closing this issue.

Please Understand.
