### ISSUE TITLE
Arrange the Courses section, as they look unarranged.

### ISSUE THREAD

**Issue by RohanShrivastava08** [ML-Fusion-Lab/ML-Fusion-Lab-Website#466]
![Screenshot (477)](https://github.com/user-attachments/assets/7d3b2006-8988-4351-9a64-58536e6b939c)

I can make them appear well and organized in proper row and column format.
Kindly, assign me with this and I will get the work done asap !!

**Comment by vivekvardhan2810** [comment]
from my side it is looking good, so i am closing this issue.

Please understand.
