### ISSUE TITLE
Add github icon

### ISSUE THREAD

**Issue by Aditijainnn** [ML-Fusion-Lab/ML-Fusion-Lab-Website#467]
### Is your feature request related to a problem? Please describe.

Add github icon with github repo link in footer

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/06db2d50-1024-42df-9fec-a37c0b17ff9c)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Aditijainnn assigning you this issue. 

Make Sure to complete this issue within 2 days.

**Comment by vivekvardhan2810** [comment]
@Aditijainnn, sorry from my side, 

i have assigned you, make sure to complete this issue within 2 days.

**Comment by RishabxBhardwaj** [comment]
want to be contributer

**Comment by SaanyaGarg5** [comment]
you can assign this task to me...

**Comment by vivekvardhan2810** [comment]
@SaanyaGarg5 please don't spam on other's issue.

**Comment by Bhavik-Mittal-26** [comment]
i would like to work on this project please assign it to me
