### ISSUE TITLE
[Mention The Feature]: improving the feedback page.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#468]
### Is your feature request related to a problem? Please describe.

after submitting the form , the data is not stored, i can add backend functionality to store the user response.
@vivekvardhan2810 can you please assign me this task.

<img width="1416" alt="Screenshot 2024-10-11 at 11 53 47 PM" src="https://github.com/user-attachments/assets/0e91c5c7-74eb-4c92-9307-c236b92a6a37">

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigned this issue to you.

make sure to complete this issue within 2 days.
