### ISSUE TITLE
 Adding a map with contact us page

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#469]
### Is your feature request related to a problem? Please describe.

Adding a map to a contact us page allows users to easily find the location of your business or organization.

### Describe the solution you'd like.

The solution involves creating an HTML structure for the contact us page with a map, and using CSS to style the page and map. An iframe is used to embed a Google Map.

### Additional context.

1. The contact us page with a map can be created using HTML and CSS.
2. An iframe is used to embed a Google Map.
3. The HTML structure consists of a container element for the contact us page, a form element, and a container element for the map.
4. The CSS styles are used to style the contact us page and map.
5. The solution can be customized by adjusting the HTML structure and CSS styles.

Please assign this issue to me under GSSoC- ext and Hacktoberfest

Thank you

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Priyanshi0112 assigning this issue to you.

make sure to complete this issue within 2 days.

**Comment by Priyanshi0112** [comment]
Dear @vivekvardhan2810 

I hope this message finds you well. I am reaching out to clarify the preferred location for the website attachment. If you have a specific location in mind that you would like to use, please let me know. Otherwise, I can proceed with attaching India as the default location.

Thank you for your guidance.

**Comment by vivekvardhan2810** [comment]
@Priyanshi0112 you can proceed with attaching India as the default location.
