### ISSUE TITLE
THE  USER INTERFACE OF THE LANDING PAGE IS QUITE POOR I CAN ENHANCE IT 10X

### ISSUE THREAD

**Issue by dnyanesh99borse** [ML-Fusion-Lab/ML-Fusion-Lab-Website#47]
**### THE  USER INTERFACE OF THE LANDING PAGE IS QUITE POOR I CAN ENHANCE IT 10X**

I CAN ENHANCE THE USER INTERFACE IN VERY CREATIVE AND INTERACTIVE MANNER AS PER THE ML THEME AND WILL PROVIDE THE NEXT LEVEL EXPERIENCE

**Comment by dnyanesh99borse** [comment]
**### please assign this issue to me cause as a experienced front end developer i can solve this issue more effective**

**Comment by vivekvardhan2810** [comment]
Hi, @dnyanesh99borse, could you provide the screenshot, so that i can look and assign this issue.

**Comment by Ishika-codeit** [comment]
hey kindly assign this to me ...user interface is the first impression of any web page if you assign it to me i try my best on this...

**Comment by vivekvardhan2810** [comment]
@dnyanesh99borse pls join the discord channel mentioned in readme.
