### ISSUE TITLE
Inconsistent Navbar and Footer Design Across ML Fusion Lab Website

### ISSUE THREAD

**Issue by vkprogrammer-001** [ML-Fusion-Lab/ML-Fusion-Lab-Website#472]
**Description:** The website for ML Fusion Lab currently displays inconsistencies in the navbar and footer sections across different pages. The navbar varies from page to page, disrupting the user experience and navigation flow. Additionally, the footer design is not cohesive or visually appealing, affecting the overall aesthetic and functionality of the site. These issues need to be addressed to ensure a uniform and user-friendly interface throughout the entire website.

**Suggestions for Improvement:**

- Standardize the navbar design and layout across all pages for a consistent user experience.

- Enhance the footer design to be more cohesive and visually appealing, incorporating essential links and information.

**Home Page:**
<img width="1428" alt="Screenshot 2024-10-12 at 12 44 35 AM" src="https://github.com/user-attachments/assets/4a771127-02d4-4b3a-be32-979727255871">
<br>
**Course:**
<img width="1440" alt="Screenshot 2024-10-12 at 12 44 58 AM" src="https://github.com/user-attachments/assets/cd0ffda5-e381-463c-a5d4-1aa99b4bb5ec">
<br>
**Project and About Us:**
<img width="1432" alt="Screenshot 2024-10-12 at 12 45 09 AM" src="https://github.com/user-attachments/assets/a8b5b18f-c56a-4956-b89b-f7f7f981e95f">
<br>
**Contact:**
<img width="1430" alt="Screenshot 2024-10-12 at 12 45 35 AM" src="https://github.com/user-attachments/assets/2959d7da-5e56-4906-a809-ea44f24b8879">

<br>
**Footer:**
<img width="1440" alt="Screenshot 2024-10-12 at 12 58 39 AM" src="https://github.com/user-attachments/assets/9be2b0e5-e04e-40d6-84f7-a8d904863903">

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
