### ISSUE TITLE
[BUG] : Course Detail Page Hiding Behind Navbar

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#473]
### Description

On the Course Detail page, content is partially hidden behind the navbar, causing a poor user experience. The page should adjust its layout so that all content is fully visible and accessible without being obstructed by the fixed navigation bar.

### Steps to Reproduce

1. Navigate to the Course Detail page.
2. Scroll or attempt to view the course information.
3. Observe that part of the content (especially near the top of the page) is obscured by the navbar.

### Expected Behavior

- The Course Detail page should display all content below the navbar, ensuring the information is fully visible to the user.
- The page layout should be adjusted to add proper spacing/margins between the top content and the fixed navbar.

### Actual Behavior

- The top portion of the Course Detail page is hidden behind the navbar, making it difficult to read or access.

### Screenshots

<img width="1280" alt="Screenshot 2024-10-12 at 6 15 34 AM" src="https://github.com/user-attachments/assets/b8b0afc7-7a2a-4195-9b63-a95f89ee7e9c">

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
