### ISSUE TITLE
[Feature]: Adding the entire tutorial page for Dog Species Classification

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#474]
### Is your feature request related to a problem? Please describe.

- Currently no projects are actually present are just cards on the website.

### Describe the solution you'd like.

- I propose adding a Dog Species Classification project using deep learning to the application. This project will leverage deep learning models to classify various dog breeds based on images provided by users.
-  The feature will allow users to understand how a deep learning model actually works and gets build.
- The project will be in a guide format to make it easily understandable to the users.

### Show us the magic with screenshots

![Input](https://github.com/user-attachments/assets/c0c1ad85-d1c2-44df-b4ee-94b4748a82b6)
![dog_3](https://github.com/user-attachments/assets/f127f6cc-275b-45e5-ba9d-360dc8ecfd94)

This is the dataset of dogs I will be using for the tutorial.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by IkkiOcean** [comment]
Please mark it LEVEL 3 as I will be going to create a easy to understand, beginner friendly tutorial on how to use deep learning techniques to create project like these.

**Comment by vivekvardhan2810** [comment]
@IkkiOcean make sure complete this issue within 2 days.

and join the discord server for further updates.
