### ISSUE TITLE
add mini chatbot in all website pages

### ISSUE THREAD

**Issue by Antima2004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#475]
### Description

In the course section there is not mini chatbot is there , I can add this please assign this to me.

### Steps to Reproduce

Go to index.html
search for chatbot 
integrated chatbot in all website pages

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [x] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require any chatbot issues regarding in courses or in any section, We will Look into this later.

So I am Closing this issue.

Please Understand.
