### ISSUE TITLE
[ BUG ] "Enroll Today" Button is not working

### ISSUE THREAD

**Issue by GunaVardhanaReddyT** [ML-Fusion-Lab/ML-Fusion-Lab-Website#476]
### Description

The Enroll today button in courses section is not working.

### Steps to Reproduce

Correct the Enroll today button.

### Expected Behavior

The button should take the user to a page where the user can enroll into the course.

### Actual Behavior

The button is not at all functional.

### Screenshots

![image](https://github.com/user-attachments/assets/c455d61f-6935-4656-bafd-1d3017578436)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now we have kept the enroll button for updation only, as the page is updating slowly, so enroll button also will update, for now we don't require for this.

So I am closing this issue. Please understand.
