### ISSUE TITLE
 Hamburger Menu Not Functioning

### ISSUE THREAD

**Issue by srishti023** [ML-Fusion-Lab/ML-Fusion-Lab-Website#477]
### Description

The hamburger menu in the application is not functioning as expected. When I resize the browser to a small screen size and click on the hamburger icon, the menu does not expand or display the navigation options.

### Steps to Reproduce the Issue:

**1.Launch the Application:** Open the web application in any web browser.

**2. Change the Viewport Size:** Resize the browser window to a mobile or tablet size (below 768px in width).

**3. Find the Hamburger Menu Icon:** Locate the hamburger menu icon at the top right corner of the navigation bar.

**4. Click the Hamburger Menu:** Click on the hamburger menu icon to attempt to open the menu.

**5. Check the Response:** Observe that the menu does not appear or expand as expected.

### Expected Behavior

When I click the hamburger menu icon, I expect the following to happen:

**Menu Expansion**
All menu **items should be clearly visible** and accessible.
There should be a **visual animation or transition effect** to indicate that the menu is opening,
Each menu item should be **clickable,**

### Actual Behavior

https://github.com/user-attachments/assets/7a1d5468-68a2-4143-91e5-10ade487aaa2

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, you can check it, So I am closing this issue.
