### ISSUE TITLE
Course Cards Layout Problem on /courses Route

### ISSUE THREAD

**Issue by sagarbendale2004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#478]
### Description

On the /courses route, the first and last course cards are stuck to the left and right sides of the page, respectively. There is no margin on the X-axis, making the layout feel cramped and unbalanced.

### Steps to Reproduce

- Navigate to the [Courses page](https://ml-fusion-lab.netlify.app/courses).
- Observe how the first card sticks to the left and the last card to the right side of the screen.

### Expected Behavior

There should be appropriate margins on both the left and right sides of the page to create balanced spacing. The gap between the cards should be reduced slightly to accommodate this margin, without the cards sticking to the edges.

### Actual Behavior

- The first course card is flush against the left side of the page, and the last course card is flush against the right side.
- There is no visible margin or padding on the left and right sides of the card container.
- The gap between the cards is wide, but the lack of space on the outer sides (left and right) creates an imbalanced layout.

### Screenshots

![Screenshot 2024-10-12 094723](https://github.com/user-attachments/assets/c37ffbef-ce7e-49d1-8acc-96ec85863ab4)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by sagarbendale2004** [comment]
@vivekvardhan2810 "Hi, I've noticed the issue with the course cards on the /courses route. I’d like to fix it by adding margins and adjusting the gaps. Could you please assign this to me?"

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 assigning this issue to you.

Make sure to complete this issue within 2 days.

**Comment by sagarbendale2004** [comment]
@vivekvardhan2810 please add “hacktoberfest-accepted” label

**Comment by vivekvardhan2810** [comment]
@sagarbendale2004 i will add it in Pull Request, first do check the reply in the Pull Request.
