### ISSUE TITLE
[Mention The Feature]: Add Progress Bar to Page

### ISSUE THREAD

**Issue by srishti023** [ML-Fusion-Lab/ML-Fusion-Lab-Website#479]
### Is your feature request related to a problem? Please describe.

Currently, there is no visual indicator of scroll progress on the web application. Users have no way to gauge how far down the page they are, which can lead to confusion, especially on long pages. A scroll progress bar would help enhance the user experience by providing immediate feedback on their position within the content.

please assign me for this issue with hacktoberfest and gssoc-ext label!
Thankyou!

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Please share the screenshot that you want to work on

**Comment by srishti023** [comment]
Here!
![Screenshot 2024-10-12 100516](https://github.com/user-attachments/assets/c4655bdf-23de-41f5-a67e-5f541ef75463)

there's no visual indicator for scroll position, The progress bar would dynamically increase or decrease as users scroll, I want to add this on every page.

Like this : 

https://github.com/user-attachments/assets/1c2fe568-b907-4e95-8d74-78a7d9cf9785

it is also one of my previous work!

**Comment by vivekvardhan2810** [comment]
@srishti023 assigning this issue to you.

Make sure to complete it within 2 days.

**Comment by srishti023** [comment]
yes definetly !
