### ISSUE TITLE
Backgrounnd image, appealing text ,alignment and spacing & text Overlap.

### ISSUE THREAD

**Issue by akansha-02** [ML-Fusion-Lab/ML-Fusion-Lab-Website#48]
The background image looks visually appealing but seems slightly busy for mobile. We might want to reduce the opacity or add a darker overlay to improve text readability on top.
Consider adding icons or visuals next to bullet points or key phrases in the About section to break up text and make it more engaging.
The feature headings ("Structured Learning," "Practical Projects," "Community Support") seem to be overlapping, making it hard to read and decreasing the clarity of the design.

![Screenshot 2024-10-02 005316](https://github.com/user-attachments/assets/bc28e6d9-4f01-49de-a336-0b5fae369353)
![Screenshot 2024-10-02 005330](https://github.com/user-attachments/assets/288137c7-96b0-4162-8cdf-6da615ea4540)

Please assign me these issues  under gssoc'24 EXTENDED and hacktoberfest.

**Comment by akansha-02** [comment]
Thank you for assigning. Also could you please add Hacktoberfest label.

**Comment by vivekvardhan2810** [comment]
Yes @akansha-02

**Comment by kundana29** [comment]
can you please assign this issue to me

**Comment by vivekvardhan2810** [comment]
@kundana29 this issue was assigned already.

But i would encourage you to look for other issues like improvement in website and then you can create new issue.
