### ISSUE TITLE
Add a Favicon to enhance user Experience 

### ISSUE THREAD

**Issue by Sanjanah8** [ML-Fusion-Lab/ML-Fusion-Lab-Website#480]
### Is your feature request related to a problem? Please describe.

The website currently lacks a favicon, making it harder for users to visually identify the tab among multiple open pages

### Describe the solution you'd like.

Creating a simple recognizable favicon representing ML Fusion, such as a fusion of an "M" and "L" with a tech-inspired design

### Describe alternatives you've considered.

Using a default or minimalist icon, but this lacks branding and recognition 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Can you please tell me on which pages you want to add the favicon

**Comment by vivekvardhan2810** [comment]
And already favicon exists, for now it is looking Good, So I am closing this issue, Please Understand.
