### ISSUE TITLE
[Mention The Feature]: Add FAQ Section to the Website

### ISSUE THREAD

**Issue by 13Sharad** [ML-Fusion-Lab/ML-Fusion-Lab-Website#481]
### Is your feature request related to a problem? Please describe.

The website currently lacks a Frequently Asked Questions (FAQ) section, which can help users quickly find answers to common questions and enhance their user experience.

### Describe the solution you'd like.

I would like to add an FAQ section to the website. This section will address common questions about the services, features, and functionality of the website. The FAQ should be easily accessible from the navigation menu and should be organized into categories for better clarity.

### Describe alternatives you've considered.

An alternative could be to provide a chatbot or automated help system to address user queries. However, an FAQ section is simpler and more user-friendly for quick reference.

### Additional context.

The FAQ section will reduce the number of repetitive inquiries and improve user satisfaction by providing instant answers to frequently asked questions. It will also make the website look more comprehensive and professional.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Krisha0208** [comment]
could you assign this task to me under gssoc-ext 
I would like to add an FAQ section so that users can enquire about their queries without any hassle 
I would like to implement an AI chatbot for this

**Comment by vivekvardhan2810** [comment]
it's already there in community support page, so i am closing this issue.
