### ISSUE TITLE
[Mention The Feature]: can add interactive coding environment at navbar

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [ML-Fusion-Lab/ML-Fusion-Lab-Website#482]
### Is your feature request related to a problem? Please describe.

users are not provided with direct coding section for practice

### Describe the solution you'd like.

can add interactive coding section onsisting of various ml related problems
![image](https://github.com/user-attachments/assets/86115517-959c-4085-aeff-b1f5bc3fc59c)

### Describe alternatives you've considered.

NA

### Additional context.

NA

### Show us the magic with screenshots

NA

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
