### ISSUE TITLE
Addition of  `Join Our Forums`  Page In Community Part

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#484]
### Is your feature request related to a problem? Please describe.

This page is not built yet

### Describe the solution you'd like.

1. Topic-Specific Discussion Threads  
2. Course-Specific Discussion Threads  
3. Project Sharing and Collaboration Space  
4. Peer Study Groups  
5. Career Advice and Job Postings  
6. Virtual Whiteboard for Collaboration

### Describe alternatives you've considered.

I am happy to add more features if u suggest any. @vivekvardhan2810 

### Show us the magic with screenshots

![Screenshot 2024-10-12 121132](https://github.com/user-attachments/assets/a595a17a-247a-420e-9ebb-216f46c1d9ff)
![Screenshot 2024-10-12 121141](https://github.com/user-attachments/assets/e516e140-e1ce-42ae-b18a-bbe3aef2dc02)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign this task to me

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 i will be assigning this issue to you.

Make sure to complete this issue within 2 days.

And Please Do contribute to Other Projects.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 i will be assigning this issue to you.
> 
> Make sure to complete this issue within 2 days.
> 
> And Please Do contribute to Other Projects, it's my request.

Ok..I will take care of it after this issue.
