### ISSUE TITLE
[BUG]: Twitter logo in projects section.

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#485]
### Description

The logo of the twitter under project section in footer is old one I want to renew it.

### Steps to Reproduce

go to project section.
in the footer part.

### Expected Behavior

it should be the lastest X logo.

### Screenshots

![Screenshot 2024-10-12 123747](https://github.com/user-attachments/assets/dae870b3-3346-41d5-904e-c855ac044b08)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 assigning this issue to you.

Make sure to complete it within 2 days.
