### ISSUE TITLE
About us page banner Image path not correct in light mode

### ISSUE THREAD

**Issue by sneha056** [ML-Fusion-Lab/ML-Fusion-Lab-Website#487]
### Description

![Screenshot 2024-10-12 132715](https://github.com/user-attachments/assets/2f8d461b-423f-4f4a-aa7c-b286093f5b0c)
Hey @vivekvardhan2810 please assign me this task ( #487 ) I can correct this

### Steps to Reproduce

1. I visit this site 
2. Move towards about us page - https://ml-fusion-lab.netlify.app/about banner image was not been loading in light mode but when we switch from light to dark mode . everything was correct. 
![Screenshot 2024-10-12 133508](https://github.com/user-attachments/assets/6f78265b-581e-4a0f-851f-01c9a58974f1)

### Expected Behavior

Image should be visible in light mode of about us page

### Actual Behavior

Image is not visible in light mode of about us page

### Screenshots

![Screenshot 2024-10-12 132715](https://github.com/user-attachments/assets/baef0cf5-319f-4c95-bbfe-f1e00e7bba8e)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@sneha056 assigning this issue to you.

Make Sure to complete this issue within 2 days.

**Comment by sneha056** [comment]
Hi @vivekvardhan2810, thanks for giving me the opportunity to work on your project and assigning the Issue to me. I have worked and done the fix for the issue and have raised the https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/pull/501 request for the same.
If possible I would like to have the label Hacktoberfest assigned with this issue.
