### ISSUE TITLE
A blank pop up box appearing 

### ISSUE THREAD

**Issue by Ashish-Patnaik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#488]
### Description

A white/blank pop up box appearing when clicking the "Learn more" button in "Projects" section

### Steps to Reproduce

Go to Projects then click the learn more button in any one project you will see a white/blank popup box appearing

### Screenshots

![555](https://github.com/user-attachments/assets/21e0327b-fc04-422a-aa9c-7e1d482f60ad)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Ashish-Patnaik i think when you will check in dark mode it will appear as blank.

**Comment by Ashish-Patnaik** [comment]
Yes that's right

**Comment by vivekvardhan2810** [comment]
so, what's your solution on this.

**Comment by vivekvardhan2810** [comment]
we will look for this later, so I am closing this issue,

**Comment by vivekvardhan2810** [comment]
We will look for this later, So I am closing this issue.

But don't be discouraged.

Please understand.
