### ISSUE TITLE
Improve Scroll Bar UI

### ISSUE THREAD

**Issue by VidhanThakur09** [ML-Fusion-Lab/ML-Fusion-Lab-Website#49]
### Description
The current Scroll bar Ui has a very basic layout and outdated design. The Thumb and Track has outdated and default styling. Enhancing the colour scheme of Thumb and Track, improving spacing and modernizing the scroll bar design would greatly improve the user experience and website presentation

https://github.com/user-attachments/assets/e0951d25-9455-4271-980f-8f4b57410eb4

### Tasks:
Redesign the Scroll bar for better visual appeal.
Improving the scroll bar thump and track.

@vivekvardhan2810  can you assign this issue to me

**Comment by vivekvardhan2810** [comment]
Okay @VidhanThakur09 

Assigning this issue to you.

make sure to complete this issue for the next 2 days.

make sure to join discord channel: https://discord.gg/FZxBRpTEeH

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me.
I will join the discord server.
