### ISSUE TITLE
[BUG]: there is no github logo/link in the footer section of the website.

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#490]
### Description

There is no github logo in the footer section anywhere in the website so that person could reach out to this github page.

### Steps to Reproduce

Open the website.
Go to footer section.

### Screenshots

![Screenshot 2024-10-12 142332](https://github.com/user-attachments/assets/78bbafb3-4c78-4222-90ee-94e3016f92d7)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, you can check it.

So I am Closing this Issue.

and please complete the issue that i have assigned you.

**Comment by shreyabajaj12** [comment]
okey sir I didn't saw that .
Thankyou
