### ISSUE TITLE
Add mini chatbot to the website

### ISSUE THREAD

**Issue by rutikakengal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#492]
This chatbot gives quike response to the users questions and answers every question , Assign me I like to work on it @ML-Fusion-Lab
Add gssoc-ext, hactoberfast-accepted , and level to this issue

**Comment by vivekvardhan2810** [comment]
this issue was created and resolved also previously, you can check it on website. and you check previous issues also.

So I am closing this issue, Please Understand.
