### ISSUE TITLE
[Mention The Feature]:  Add Login and Sign-Up Pages to the Website

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#493]
### Is your feature request related to a problem? Please describe.

Integrating a dedicated login and sign-up page will enhance user experience by providing a secure and easy way to manage accounts. This will streamline user authentication, allowing returning users to quickly log in and new users to register seamlessly. Additionally, it will enable better personalization of the website and increase user engagement by offering features like password recovery and social media login options.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
we will look for the login and sign up page for later, because there were same issues raised before, but didn't assigned till now.

For Now i am closing this issue.

Please understand.

But don't worry you can look for other issues.

And please do continue to work on other projects.
