### ISSUE TITLE
Adding Contributors page

### ISSUE THREAD

**Issue by TBorundia** [ML-Fusion-Lab/ML-Fusion-Lab-Website#495]
### Is your feature request related to a problem? Please describe.

I can add the option to navigate contributor page.
I will show the github profile of all the contributors worked for the project.
I will ensure to make the page UI similar to the theme and also responsive for all screens.
It will directly fetch the data from the repository.

### Describe the solution you'd like.

It will show,
Transparency: It shows transparency in the project's development and highlights the collaborative effort behind it.
Engagement: It helps build a community by encouraging more people to contribute and get involved.
Networking: It provides an opportunity for users to connect with contributors, potentially leading to more collaboration and support.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@TBorundia Assigning this issue to you.

Make sure to complete this within 2 days.

And make sure to join discord server for further updates and communication.
