### ISSUE TITLE
Updating the background  color of the content of nav bar.

### ISSUE THREAD

**Issue by Tanushree084** [ML-Fusion-Lab/ML-Fusion-Lab-Website#496]
### Is your feature request related to a problem? Please describe.

Hey @vivekvardhan2810,

I want to update the background color of the content of nav bar when in dark mode .
<img width="808" alt="image" src="https://github.com/user-attachments/assets/65715517-ce1e-4331-bf76-e3372f4118fe">

Can you please   assign  me this issue ?

### Describe the solution you'd like.

.

### Describe alternatives you've considered.

.

### Additional context.

.

### Show us the magic with screenshots

<img width="808" alt="image" src="https://github.com/user-attachments/assets/d7241cbe-7920-4e4d-9e12-09ece2f0d973">

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
