### ISSUE TITLE
[Mention The Feature]: Add hover effect to the social icons in the footer and add insta icon

### ISSUE THREAD

**Issue by Vaishh18** [ML-Fusion-Lab/ML-Fusion-Lab-Website#499]
### Is your feature request related to a problem? Please describe.

This feature request aims to enhance the user experience on the website by adding a hover effect to the social icons in the footer and incorporating an Instagram icon for better social media representation.

### Describe the solution you'd like.

Currently, the social icons in the footer lack interactivity, which can make them feel static and less engaging for users. Without hover effects, users may not realize that these icons are clickable links leading to social media profiles. Additionally, the absence of an Instagram icon limits our social media presence, as it is one of the most widely used platforms for audience engagement.

Proposed Changes
Add Hover Effect:

Implement a visual hover effect for the existing social icons (e.g., Facebook, Twitter, LinkedIn) that highlights them when users hover over them. This could include:
Changing the icon color or applying a subtle scale transformation.
Adding a shadow effect or glow to signify that the icon is interactive.
Include Instagram Icon:

Add an Instagram icon to the footer to represent our presence on this popular social media platform. The icon should match the design style of the existing social icons for consistency

### Show us the magic with screenshots

https://github.com/user-attachments/assets/eab0411e-b27f-42eb-921e-406266f0cb35

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Vaishh18 for now the social media icons are ok, no need for hover effect improvements for now, We will look it later.

For Now I am Closing this issue.

Please Understand.
