### ISSUE TITLE
Add scroll to top option 

### ISSUE THREAD

**Issue by Khushi14404** [ML-Fusion-Lab/ML-Fusion-Lab-Website#5]
I would like to add this to the website please assign it to me and please add label to the issue

**Comment by vivekvardhan2810** [comment]
@Khushi14404 assigned to you.

**Comment by vivekvardhan2810** [comment]
@Khushi14404  please complete this issue in the next 2 days.

**Comment by Khushi14404** [comment]
I would like to kindly ask if you could add the Hacktoberfest-accepted label to this.
This would help me earn the Hacktoberfest badge and promote my engagement with the community.

**Comment by vivekvardhan2810** [comment]
@Khushi14404 added the label

**Comment by Khushi14404** [comment]
Thank you so much sir

**Comment by vivekvardhan2810** [comment]
@Khushi14404 I have removed the label because this project doesn't come under hacktoberfest.
