### ISSUE TITLE
Contact us page logo is not linked with home page.

### ISSUE THREAD

**Issue by sneha056** [ML-Fusion-Lab/ML-Fusion-Lab-Website#502]
### Description

Hey @vivekvardhan2810 please assign me this task so that I can start working on this.

https://github.com/user-attachments/assets/84dca000-38dd-464f-9f1d-a2718ed3153d
As every page logo is linked with home page but as mention in screen recording contact us page is not linked with home page

### Steps to Reproduce

When you open contact us page and wish to go to home page by clicking on website logo , it will not redirect you you to home page .

### Expected Behavior

In contact us page website logo should navigate end user to home page.

### Actual Behavior

In contact us page website logo is not  navigating end user to home page.

### Screenshots

https://github.com/user-attachments/assets/a65505ce-cb57-4e95-8fd0-dc672d03c56a

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [x] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@sneha056 the screenshot or the video that you have sent is of courses page not contact Page

Please check it and Update it.

**Comment by sneha056** [comment]
Sorry for inconvenience, here's the correct video 

https://github.com/user-attachments/assets/bf86f5ac-4ded-4844-9e33-a51f3248e5e8

**Comment by vivekvardhan2810** [comment]
@sneha056 Assigning this issue to you.

Make Sure to complete it within 2 days.
