### ISSUE TITLE
[Mention The Feature]: Cursor feature

### ISSUE THREAD

**Issue by Vivisteria11** [ML-Fusion-Lab/ML-Fusion-Lab-Website#504]
### Is your feature request related to a problem? Please describe.

the cursor seems very distracting and I would like to update it to something else ,it feels blurry at points and not great on the eyes 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now cursor is looking good, we will look for this later

So I am Closing this issue.

Please Understand.
