### ISSUE TITLE
Home page logo and contact page, testimonials page logo are different.

### ISSUE THREAD

**Issue by Adityadhiman0** [ML-Fusion-Lab/ML-Fusion-Lab-Website#508]
### Description

What i see Home page logo and contact page, testimonials page logo are different. All the pages should have same logo.

### Steps to Reproduce

1. Open the website and see website logo.
2. Go to contact page and see logo.
3. Go to testimonials page and see logo.

### Expected Behavior

All pages should have same logo.

### Screenshots

![Screenshot 2024-10-12 2111139](https://github.com/user-attachments/assets/54c79012-57b0-4e90-b892-8d6574a0aeba)
![Screenshot 2024-10-10 200739](https://github.com/user-attachments/assets/296b8366-d26a-4daa-a611-cf4650fa59ff)
![Screenshot 2024-10-12 211028](https://github.com/user-attachments/assets/a828b1ff-d1da-40db-8f2a-213ef73214c3)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 can you make the contact page logo common in every page in website.

**Comment by Adityadhiman0** [comment]
assign this issue to me and i will Fix this in an hour.

**Comment by vivekvardhan2810** [comment]
Okay @Adityadhiman0 assigning this issue to you.

Make sure complete this within an hour
