### ISSUE TITLE
[Feat]: Making Header and footer part in feedback section 

### ISSUE THREAD

**Issue by shreyabajaj12** [ML-Fusion-Lab/ML-Fusion-Lab-Website#509]
### Is your feature request related to a problem? Please describe.

I want to add header and footer section in feedback form so that user could easily navigate among different links.

### Describe alternatives you've considered.

![Screenshot 2024-10-12 211358](https://github.com/user-attachments/assets/8d47136d-9339-43a2-bda2-20495bc0f9e1)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 assigning this issue to you.

Make sure to complete this within 2 days.

**Comment by vivekvardhan2810** [comment]
@shreyabajaj12 have you done with it.

**Comment by shreyabajaj12** [comment]
Sir actually I want to unassign this issue because I am not able to figure out the same layout as it is in the other pages.
Sorry for the delay.

**Comment by vivekvardhan2810** [comment]
Okay, @shreyabajaj12 can I close this issue.

**Comment by shreyabajaj12** [comment]
yes sir thank u very much
