### ISSUE TITLE
Issue in the hamburger icon 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#512]
### Description

The hamburger icon doesn't work

### Steps to Reproduce

https://github.com/user-attachments/assets/f70ad2b2-9e29-44eb-9415-574c38593da2

### Expected Behavior

The hamburger must work as it is made for mobile screens 

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, you can check in issues he is resolving, 

So i am closing this issue.

Please understand.
