### ISSUE TITLE
footer is not aligned properly at bottom

### ISSUE THREAD

**Issue by srishti023** [ML-Fusion-Lab/ML-Fusion-Lab-Website#514]
![Screenshot 2024-10-12 235909](https://github.com/user-attachments/assets/1a99f326-7a3a-46bf-b891-2e6b571c3aec)

The footer of social media page .
It comes up because of css property . 
Assign me this issue I want to fix this.

Thankyou!

**Comment by vivekvardhan2810** [comment]
@srishti023 assigning this issue to you

Make sure to complete this within 2 days.
