### ISSUE TITLE
Feature: Enhance UI of Intro-to-ML Page with Attractive Styling, Images, and Videos

### ISSUE THREAD

**Issue by srishti023** [ML-Fusion-Lab/ML-Fusion-Lab-Website#515]
### Is your feature request related to a problem? Please describe.

Improvement in UI  of the "Intro-to-ML" page by incorporating more visually appealing design elements, images, and videos to enhance user engagement. It also lacks a lot of Information. 

![Screenshot 2024-10-13 000711](https://github.com/user-attachments/assets/6a5e0a5c-7892-4809-a000-4cb5c48d187f)

### Describe the solution you'd like.

Add high-quality, relevant images (e.g., diagrams, charts, AI/ML visuals)
Embed short, informative videos that explain core ML concepts
Ui that matches the Ui of website.
Ensure the design is fully responsive,
Hovering effect 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@srishti023 can you please tell me, the screenshot which you have is from which page of the website.

**Comment by vivekvardhan2810** [comment]
And the screenshot was existing and the page was updated way before, so i am closing this issue.

Please Understand.
