### ISSUE TITLE
Improper Placement of Navbar Items

### ISSUE THREAD

**Issue by ShaikHafiza** [ML-Fusion-Lab/ML-Fusion-Lab-Website#517]
The items in the navigation bar are not properly placed, leading to a cluttered and unprofessional appearance. 

![image](https://github.com/user-attachments/assets/605e8935-7e66-413a-b788-c57b207f1d49)

please assign this issue, I would like to work on this.

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.

**Comment by ShaikHafiza** [comment]
It's ok
