### ISSUE TITLE
 Add margin and spacing between course cards

### ISSUE THREAD

**Issue by srishti023** [ML-Fusion-Lab/ML-Fusion-Lab-Website#519]
The current "Featured Courses" section has a messy appearance due to the lack of proper spacing and margin between the course cards. This results in a cluttered layout, making it difficult to visually separate each course and affecting the overall user experience.

Current View :
![Screenshot 2024-10-13 014640](https://github.com/user-attachments/assets/cbb0b56d-1fae-4595-a487-f1ff29061d37)

After enhancement : 
![Screenshot 2024-10-13 015420](https://github.com/user-attachments/assets/958be89e-c90f-4831-b650-744acd6a7071)

Assign me this issue
Thankyou!

**Comment by vivekvardhan2810** [comment]
@srishti023 the screenshot is of project's page not the courses page, please check it.

**Comment by srishti023** [comment]
Thank you for pointing that out. This was my mistake, and I will go ahead and close this issue.

**Comment by vivekvardhan2810** [comment]
@srishti023 please do contribute to other projects also.
