### ISSUE TITLE
[Mention The Feature]: About us page update 

### ISSUE THREAD

**Issue by eshaalal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#520]
### Is your feature request related to a problem? Please describe.

1. Scrolling animation 
2. Using GSAP

### Describe the solution you'd like.

GSAP will make the page look very cool and modern

### Show us the magic with screenshots

https://github.com/user-attachments/assets/7743dd9d-c95c-4779-aa7e-7009aa488833

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now the about us page is looking good and don't want any updates further from it.

So I am closing this issue.

Please Understand.
