### ISSUE TITLE
[Contact us page ]: update the contact Us page 

### ISSUE THREAD

**Issue by eshaalal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#521]
### Is your feature request related to a problem? Please describe.

1. More cleaner
2. Using nicer UI

### Describe the solution you'd like.

I would like to create a better UI for contact us page

### Show us the magic with screenshots

![Screenshot 2024-10-13 021658](https://github.com/user-attachments/assets/07f4769d-277c-44d8-8a96-b5b67aa9d311)
![Screenshot 2024-10-13 021723](https://github.com/user-attachments/assets/9d8ebe3f-2da0-4746-9129-609ebdd4981f)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by eshaalal** [comment]
@ML-Fusion-Lab please assign me this issue with labels , gssoc-ext, hacktoberfest-accepted , level-3

**Comment by vivekvardhan2810** [comment]
@eshaalal assigning this issue to you

Make sure to complete it within 2 days.

For now I can give you level 2, as you are updating the page.

**Comment by vivekvardhan2810** [comment]
And I will add the hacktoberfest label, when you will create the Pull Request.

**Comment by eshaalal** [comment]
okey
