### ISSUE TITLE
improve the display of featured projects in projects page

### ISSUE THREAD

**Issue by Riyachauhan11** [ML-Fusion-Lab/ML-Fusion-Lab-Website#522]
currently there is no responsivness in display of featured projects and they all look a little too congested. The additional info displayed on clicking Learn more isnt very appealing either. 

I would like to fix these issues by adding responsiveness and gap between projects/cards. Also i would add a flip animation to all the cards so that the learn more info is displayed at the back of each card rather than getting displayed in an additional popup.

![image](https://github.com/user-attachments/assets/5da58eee-7953-480c-a8fc-ba2894a2aac3)

**Comment by vivekvardhan2810** [comment]
For now it is okay, we will look for this later

So I am closing this issue.

Please understand.
