### ISSUE TITLE
Feature: Change the navbar of Projects page

### ISSUE THREAD

**Issue by nksmanya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#523]
### Is your feature request related to a problem? Please describe.

The projects page's navbar does not match the rest of the website pages' navbar.

### Describe the solution you'd like.

I would like to change the nav bar of the projects page to match with the other pages too.

### Show us the magic with screenshots

![Screenshot 2024-10-13 065924](https://github.com/user-attachments/assets/54d56f3e-1526-42fd-8351-05f9ce0f190f)
![Screenshot 2024-10-13 065937](https://github.com/user-attachments/assets/960b2d9b-33dd-4be1-9e25-b4f20817a5de)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
