### ISSUE TITLE
 Uneven Border Radius in Image Display

### ISSUE THREAD

**Issue by diwakarchaurasiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#524]
Description:

The border radius of the image appears uneven, causing inconsistencies in the visual design. This issue impacts the aesthetics of the layout, as the border radius is not uniformly applied across the image. It may result in the image looking distorted or asymmetrical on different screens or when viewed at various resolutions.

Expected Behavior: The image should have a consistent border radius applied evenly across all corners, maintaining a smooth and uniform appearance for better user experience and look professional.

![Screenshot 2024-10-13 072736](https://github.com/user-attachments/assets/528580fb-293c-48b6-9966-b182440bba73)

Proposed Solution: Apply a uniform border radius value to ensure that the image has an even and symmetrical appearance on all corners.

**Comment by vivekvardhan2810** [comment]
From my side it is looking good, for now we don't require for this

So I am closing this issue.

Please understand.
