### ISSUE TITLE
Logo Appears with Background Color in Dark Mode

### ISSUE THREAD

**Issue by diwakarchaurasiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#525]
The current logo has a visible background color that clashes with the dark mode theme of the website, resulting in a poor visual experience. In light mode, the background is also not visually appealing. To maintain a seamless and professional look, the logo should have a transparent background and be of high quality, ensuring it looks sharp and blends well with both dark and light modes.

**Expected Behavior**: The logo should have no background (transparent) and maintain high resolution, so it adapts smoothly to both dark and light modes without any visual inconsistencies.

![Screenshot 2024-10-13 073125](https://github.com/user-attachments/assets/aec9bf75-ceaa-47c0-90bf-6fe672a4286e)

**Proposed Solution**: Replace the current logo with a transparent, high-resolution version that adjusts well to both dark and light themes.

**Comment by vivekvardhan2810** [comment]
for now we don't require this, So i am closing this issue.

Please understand.
