### ISSUE TITLE
Unprofessional Cursor Interaction

### ISSUE THREAD

**Issue by diwakarchaurasiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#526]
The current cursor interaction with certain UI elements feels unprofessional and inconsistent with standard design practices. The cursor either lacks proper feedback (such as hover effects) or behaves in a way that does not meet modern UX/UI guidelines, which may confuse users or lead to a less engaging experience. This impacts the overall user experience and diminishes the polished feel of the platform.

**Expected Behavior-**
When interacting with clickable elements or hovering over actionable items, the cursor should provide appropriate feedback, such as changing shape or applying subtle animations. This would enhance user experience by signaling that an element is interactive and improve the platform’s professional appearance.

![Screenshot 2024-10-13 073734](https://github.com/user-attachments/assets/4cd38ff3-2327-44a7-b33b-4d9659f7539e)

**Proposed Solution-**
Changing the animation happening on cursor movement ,and this should be set as default cursor
Implement standard cursor changes for different interactions (e.g., pointer for clickable items).
Consider adding hover animations or visual cues to improve the interaction experience.
Ensure cursor behavior is consistent across all UI elements to meet modern UX standards.

**Comment by vivekvardhan2810** [comment]
for now cursor is looking good, we will look for this later

So I am Closing this issue.

Please Understand.

**Comment by diwakarchaurasiya** [comment]
thanks for your kind response,It's completely understandable.
