### ISSUE TITLE
[Mention The Feature]: want to add 3d version dark and light toggle mode 

### ISSUE THREAD

**Issue by sv410** [ML-Fusion-Lab/ML-Fusion-Lab-Website#527]
### Is your feature request related to a problem? Please describe.

nope can make  it a better version of toggle dark and light mode 

### Show us the magic with screenshots

![WhatsApp Image 2024-10-12 at 11 20 20 PM (1)](https://github.com/user-attachments/assets/e8509f4c-ca75-4b80-be0e-0d53c393e978)
![WhatsApp Image 2024-10-12 at 11 19 35 PM (1)](https://github.com/user-attachments/assets/0d0f2c0a-10c6-47cc-bd28-81f68d38a100)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
At present the dark and light mode toggle is enough for now, we can look it for further.

So I am closing this issue.

Please understand.
