### ISSUE TITLE
Animate on scrolling down 

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#528]
### Is your feature request related to a problem? Please describe.

when the user scrolling down the featured project section it is looking quite static .

### Describe the solution you'd like.

when the user scrolls down I will animate the projects this will be helpful in :

- Enhanced User Engagement: Animations triggered as users scroll create a dynamic experience, capturing attention and keeping users engaged as they explore the content.

- Improved Visual Flow: Scroll animations help guide users through the content in a structured and visually appealing way, making it easier to highlight key sections or messages.

- Better Information Retention: Movement and transitions can make important elements stand out, helping users retain information better than with static content alone.

- Modern and Interactive Feel: Animated elements give the website a modern and polished appearance, improving its appeal and the perceived quality of the brand or service.

- Increased Time on Site: Engaging animations can encourage users to stay longer on the site, leading to improved metrics such as lower bounce rates and higher average session duration.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Can you please share the screenshot of the page you wanna work with.

**Comment by Priyanshi0112** [comment]
this gives the dynamic behaviour to the projects
https://github.com/user-attachments/assets/c3c4057b-20b0-4087-bb66-30a2127b2d53

**Comment by vivekvardhan2810** [comment]
Okay, Assigning this issue to you.

Make sure to complete this issue within 2 days.

And so it properly.
