### ISSUE TITLE
Hamburger menu not showing options on mobile

### ISSUE THREAD

**Issue by 2016archana** [ML-Fusion-Lab/ML-Fusion-Lab-Website#529]
The hamburger menu on the ML Fusion Lab website is not functioning properly on mobile devices. When viewed on a mobile device or when the browser window is resized to mobile dimensions, clicking on the hamburger menu does not display any navigation options.

Expected Behavior: The hamburger menu should expand to show navigation options when clicked.

Actual Behavior: Clicking on the hamburger menu does not reveal any navigation options.
![menu_issue](https://github.com/user-attachments/assets/401f0033-b541-4f2b-bc22-ec0297f581db)

**Comment by 2016archana** [comment]
Please assign this issue to me.

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, you can check in issues he is resolving it.

So i am closing this issue.

Please understand.
