### ISSUE TITLE
Logo is not properly aligned, navigation bar components are not properly visible

### ISSUE THREAD

**Issue by kumudsalunke26** [ML-Fusion-Lab/ML-Fusion-Lab-Website#530]
The logo for ML Fusion is not properly aligned. We can do some modifications using CSS to align it properly.
Also , when we hover on the components of navigation bar, the text is not visible properly, so for this, we can do some changes to make it properly visible.
The scroll up button and message button in the bottom right corner of the homepage are not well aligned with each other to which we can do some modifications with the help of CSS.
I would love to work on these mentioned parts of the project to make it more appealing.
Attaching a screenshot of the issues I would like to resolve!
![Screenshot 2024-10-13 132329](https://github.com/user-attachments/assets/490c46db-dc65-4bf5-9e0a-7de5199ee3bc)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues and logo issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.

For now scroll up button and message is okay, don't required any updation for now, we will look it later.

So please Understand.
