### ISSUE TITLE
Inconsistent Box Sizing in Course Section

### ISSUE THREAD

**Issue by TornovDutta** [ML-Fusion-Lab/ML-Fusion-Lab-Website#531]
# About:
The course boxes in the "Courses" section have inconsistent sizes, with some being larger than others. This uneven sizing leads to a cluttered and unprofessional appearance, making the layout look imbalanced. The varying dimensions also disrupt the user experience by causing confusion and difficulty in navigating through the available options. To resolve this, all course boxes should be standardized to have the same size, providing a cleaner and more visually appealing design.

### sceenshot:
![Screenshot 2024-10-13 140202](https://github.com/user-attachments/assets/9d193d84-e9b0-4069-96e1-a1a47c4cbe64)

**Comment by TornovDutta** [comment]
@vivekv2810 please assign this issuse to me and label the issuse

**Comment by vivekvardhan2810** [comment]
@TornovDutta And it appears when you zoom it out for 110%

but you can zoom it for 100% it looks normal.

please look onto it.

**Comment by TornovDutta** [comment]
> @TornovDutta And it appears when you zoom it out for 110%
> 
> but you can zoom it for 100% it looks normal.
> 
> please look onto it.
> 
> From my side it is looking good.
> 
> So i am closing this issue.
> 
> Please understand.

The website is currently at 100% zoom on my end. Can you please check it again?
![Screenshot 2024-10-13 163559](https://github.com/user-attachments/assets/dfdab036-57e0-49dd-b108-972ac96e921c)

**Comment by vivekvardhan2810** [comment]
![image](https://github.com/user-attachments/assets/5a48acd1-b682-4437-9dd7-15e7e7ef52ca)

@TornovDutta The website is currently at 100% zoom on my end.

**Comment by TornovDutta** [comment]
> ![image](https://private-user-images.githubusercontent.com/91594529/376029066-5a48acd1-b682-4437-9dd7-15e7e7ef52ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTgwODMsIm5iZiI6MTcyODgxNzc4MywicGF0aCI6Ii85MTU5NDUyOS8zNzYwMjkwNjYtNWE0OGFjZDEtYjY4Mi00NDM3LTlkZDctMTVlN2U3ZWY1MmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDExMDk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyOTU0ODZlMmVjMjZlNjMzM2YxYWYxMDg5Y2NkMTE4NGVkZjVjN2FiZGUyNDFmMzI4MDk1YTI3ZWUzZTRlMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Jv71fDPjGp76KueaYisfx_sGjNDodTJiWNIku7UVglU)
> 
> @TornovDutta The website is currently at 100% zoom on my end.

This looks blurry on my end. Could you try checking it on a different browser?
![Screenshot 2024-10-13 163559](https://github.com/user-attachments/assets/6f48aeaa-c4bf-4e49-88e4-af25f1f7a7c8)

**Comment by vivekvardhan2810** [comment]
@TornovDutta this one is from firefox.

![image](https://github.com/user-attachments/assets/f6e410b8-1614-4fed-bb35-e18c5f08789a)

**Comment by TornovDutta** [comment]
> # About:
> The course boxes in the "Courses" section have inconsistent sizes, with some being larger than others. This uneven sizing leads to a cluttered and unprofessional appearance, making the layout look imbalanced. The varying dimensions also disrupt the user experience by causing confusion and difficulty in navigating through the available options. To resolve this, all course boxes should be standardized to have the same size, providing a cleaner and more visually appealing design.
> 
> ### sceenshot:
> ![Screenshot 2024-10-13 140202](https://private-user-images.githubusercontent.com/162907041/376020082-9d193d84-e9b0-4069-96e1-a1a47c4cbe64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTg1NjIsIm5iZiI6MTcyODgxODI2MiwicGF0aCI6Ii8xNjI5MDcwNDEvMzc2MDIwMDgyLTlkMTkzZDg0LWU5YjAtNDA2OS05NmUxLWExYTQ3YzRjYmU2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMTE3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzNhZTBlN2ZiNjNjYjNlNGFhNTllNWI4YjI1MjM1ODBmODFiZDVjMWJiMjRmMzM1NzVmMmIzMzllM2Y0Mzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Aw-p0P3K5MikThfmR5JSElhTrmWkcb8TQ5XwUjD2j9Y)

This is from google chrome

**Comment by TornovDutta** [comment]
And this is from microsoft edge
![Screenshot (481)](https://github.com/user-attachments/assets/5ad8d1a6-0ed0-4a9b-9a50-fd7539e04a67)

**Comment by vivekvardhan2810** [comment]
![image](https://github.com/user-attachments/assets/712fc385-b717-495a-92a6-7086525d323b)
this one is from Google chrome

**Comment by vivekvardhan2810** [comment]
![image](https://github.com/user-attachments/assets/606a90a9-7a4b-42bc-bbd0-e1388e90dc3f)

this one is from microsoft edge from my side.

**Comment by vivekvardhan2810** [comment]
@TornovDutta don't worry, you can look for other issue, i will look into it assign you it.

**Comment by vivekvardhan2810** [comment]
but still can i reopen this issue if you want it @TornovDutta

**Comment by TornovDutta** [comment]
OK

**Comment by vivekvardhan2810** [comment]
can i reopen it or let it be closed

**Comment by TornovDutta** [comment]
If you think this is indeed an issue with the website, please reopen it. I recommend checking the website on another browser to confirm, and if you still feel it's an issue, reopening it would be the best course of action.

**Comment by vivekvardhan2810** [comment]
@TornovDutta i have checked it in another browser (brave) it's still the same, for now we don't need.

you can look for other issues in website and create a new issue, i will look into it.

**Comment by TornovDutta** [comment]
Ok
