### ISSUE TITLE
IN PROJECTS SECTION THERE IS NO GAP BETWEEN THE THE DIFFRENT PROJECTS 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#533]
### Description

![Screenshot 2024-10-13 152950](https://github.com/user-attachments/assets/5d106f4d-ccf0-4992-a291-d51f3a47b210)

### Steps to Reproduce

Go to the projects page and scroll down 

### Expected Behavior

It should be allign in proper manner 

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
And it appears when you zoom it out for 80%

but you can zoom it for 100% it looks normal.

please look onto it.

From my side it is looking good.

**Comment by HS202022** [comment]
> And it appears when you zoom it out for 80%
> 
> but you can zoom it for 100% it looks normal.
> 
> please look onto it.
> 
> From my side it is looking good.


https://github.com/user-attachments/assets/e2d3a351-9f51-4d95-810a-91b00ecb6ddf

**Comment by vivekvardhan2810** [comment]
@HS202022 can you make it normal for all the sizes with gaps presented.

**Comment by HS202022** [comment]
> @HS202022 can you make it normal for all the sizes with gaps presented.

Yes

**Comment by vivekvardhan2810** [comment]
@HS202022 Okay, Assigning this issue to you.

Make Sure to complete this within 2 days
