### ISSUE TITLE
Search bar is not working in Courses section

### ISSUE THREAD

**Issue by satyamra1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#535]
### Description

In Courses section , when I am trying to find any Course using search bar , it is not filtering courses. In short search bar is not functional.

### Steps to Reproduce

 Go through the code > try to update Javascript > It will be solved

### Expected Behavior

It should be filtering out courses based on their name.

### Screenshots

![image](https://github.com/user-attachments/assets/5b844525-68fd-4205-b2e2-3eb7f162e873)

### What browser are you seeing the problem on?

- [X] Firefox
- [x] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@satyamra1 assigning this issue to you.

Make sure to complete this issue within 2 days.
