### ISSUE TITLE
[Add toggling in contact us page]: 

### ISSUE THREAD

**Issue by eshaalal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#536]
### Is your feature request related to a problem? Please describe.

In other pages toggling from dark to light is available i would like to do the same here

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@eshaalal make sure to complete it within 2 days.

**Comment by eshaalal** [comment]
sure

**Comment by vivekvardhan2810** [comment]
@eshaalal from next time also please mention the issue number while creating the Pull Request.

**Comment by eshaalal** [comment]
Yes, I will keep that in mind
