### ISSUE TITLE
Updation of Footer

### ISSUE THREAD

**Issue by satyamra1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#537]
### Description

IN YOUR WEBSITE ALL THE PAGES HAVE DIFFERENT FOOTER FORMAT WHICH IS NOT GOOD . I CAN MAKE IT SIMILAR FOR ALL THE PAGES AND ALSO YOUR THEME OF FOOTER IS VERY BASIC , IT DO NOT MATCH WITH YOUR WEBSITE THEME.

### Steps to Reproduce

UPDATE THE FOOTER CODE > APPLY SAME FOOTER FOR ALL PAGES

### Screenshots

I will update this >
![image](https://github.com/user-attachments/assets/c9b35c25-a13a-4203-9b79-10a7644e9ece)

TO >

![footer](https://github.com/user-attachments/assets/670cb1a9-ac7b-402f-860d-e3b8b3ecc16c)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now it is not required, we will look into it later. so i am closing this issue.

Please Understand.
