### ISSUE TITLE
Improve Mobile Responsiveness and Fix Hamburger Menu Functionality 

### ISSUE THREAD

**Issue by TyagiManshi** [ML-Fusion-Lab/ML-Fusion-Lab-Website#538]
https://github.com/user-attachments/assets/39fb8964-51cc-4b66-a0b5-0cae9bc4027f

The website's layout does not adapt well to mobile devices, leading to misaligned elements and navigation difficulties. Enhancing mobile responsiveness will improve usability for users on smartphones and tablets.

Also I’d like to fix the hamburger menu functionality. Improving the navigation experience is crucial for user engagement, especially on mobile devices.

 This enhancement will greatly improve usability for all users. Could you please assign this issue to me..

**Comment by TyagiManshi** [comment]
I would appreciate it if you could assign this issue to me, as I am eager to contribute to improving the site’s usability. Thank you!

**Comment by TyagiManshi** [comment]
I would appreciate it if you could assign this issue to me, as I am eager to contribute to improving the site’s usability. Thank you!

**Comment by vivekvardhan2810** [comment]
@TyagiManshi This issue was assigned before, you can check in issues he is resolving it.

**Comment by TyagiManshi** [comment]
Thank you for the update! I’ll check the existing issues to find another one that I can contribute to. If there are any specific areas where help is needed, please let me know!

**Comment by vivekvardhan2810** [comment]
so i am closing this issue.

Plea
