### ISSUE TITLE
Fix the alignment of Image

### ISSUE THREAD

**Issue by khwa04** [ML-Fusion-Lab/ML-Fusion-Lab-Website#539]
![image](https://github.com/user-attachments/assets/93284f57-0dc3-4349-8058-060db198d7a7)
I wish to fix the alignment of the image in "Crop Height Using Computer Vision" in featured projects section.
Please assign me this issue under gssoc extnd. and hacktoberfest.

**Comment by vivekvardhan2810** [comment]
@khwa04 assigning this issue to you.

Make sure to complete this issue within 2 days.
