### ISSUE TITLE
Adding more projects to the project page and linking it ro the "Practicle Project" anchor

### ISSUE THREAD

**Issue by yeshwanth-ds** [ML-Fusion-Lab/ML-Fusion-Lab-Website#54]
Currently the "Practicle Poject " is not linked to any page.
So i would start of by linking it to the project page.
![Screenshot 2024-10-02 025002](https://github.com/user-attachments/assets/f5aaafe0-4f02-4633-a79d-115fe3600c9f)

Now comming to the project page there is now proper alignement in the text inside the projects, I will fix that and addd few more latest and trending projetcs to the list and aslo add few images for user friendly interaction.
![Screenshot 2024-10-02 025026](https://github.com/user-attachments/assets/4a14e35b-50a0-4a1f-837d-b72ef702efb3)

I would like you to assign me this task under gssoc-ext and hacktoberfest tag if possible

**Comment by vivekvardhan2810** [comment]
Okay @yeshwanth-ds 

Assigning this issue.

Make sure to complete this issue for the next 2 days.
