### ISSUE TITLE
Focus of cursor on search bar

### ISSUE THREAD

**Issue by Jerusha547** [ML-Fusion-Lab/ML-Fusion-Lab-Website#540]
### Is your feature request related to a problem? Please describe.

When the courses page is loaded there is no automatic focus of cursor on the search bar.

### Describe the solution you'd like.

I want to make the focus of cursor on the search bar of courses page automatically whenever the page is loaded. This makes searching fast.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
can you please share the screenshot or video that you wanna work with it.

**Comment by Jerusha547** [comment]
![image](https://github.com/user-attachments/assets/1f67ab95-5842-43ef-be54-c47474ef071a)
i want to add the automatic focus of cursor to this search bar whenever the page is loaded

**Comment by vivekvardhan2810** [comment]
@Jerusha547 assigning this issue to you.

Make sure to complete this issue within 2 days.
