### ISSUE TITLE
Can add share option

### ISSUE THREAD

**Issue by PoojaKanagaraj06** [ML-Fusion-Lab/ML-Fusion-Lab-Website#542]
My feature regards to the sharing of website to others by creating a share button, so that others can use it.
![image](https://github.com/user-attachments/assets/a85be80c-58b9-4dd5-968c-e8c7599a0a74)
kindly assign the work to me under label gssoc-24 @vivekvardhan2810 

sue. (optional)

**Comment by vivekvardhan2810** [comment]
@PoojaKanagaraj06 for now we don't require this feature, we will look it in later.

So i am closing this issue.

Please Understand.
