### ISSUE TITLE
[Mention The Feature]: When we hover on navbar so change in color after hover is not so good i want to update it

### ISSUE THREAD

**Issue by rahulbamnuya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#543]
### Is your feature request related to a problem? Please describe.

When we hover on navbar so change in color after hover is not so good i want to update it because after hover background will change but text color will light and mix with background
![Screenshot (148)](https://github.com/user-attachments/assets/2e121fc7-f439-4be5-9fbc-cb4fe9f9224e)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
