### ISSUE TITLE
After selecting learn more in  Featured Projects a blank rectangle appear in screen 

### ISSUE THREAD

**Issue by rahulbamnuya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#545]
![Screenshot (149)](https://github.com/user-attachments/assets/3ca35545-198f-4f0f-86aa-ef4395c4dde2)
![Screenshot (150)](https://github.com/user-attachments/assets/f4d68526-ac34-47d3-88ee-1cdb0fea6cf8)

**Comment by vivekvardhan2810** [comment]
@rahulbamnuya what's your solution on this.

Please explain it.

**Comment by rahulbamnuya** [comment]
we can replace rectangle with loader so user will thick something is loading and will appear in some second .

**Comment by zeba62** [comment]
Assign me this issue I wolud like to contribute to it.

**Comment by zeba62** [comment]
We can add if the user selects "Learn More", a blank rectangle appears, I  can replace it with a summary. This summary could include:
An overview of the course or project
Key topics or skills covered
Learning outcomes
Estimated time required to complete.

**Comment by vivekvardhan2810** [comment]
we will look for this later.

So i am closing this issue.

Please Understand.
