### ISSUE TITLE
I Want to fix padding inside cards and also want to improve their height along text alignment

### ISSUE THREAD

**Issue by rahulbamnuya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#546]
![Screenshot (151)](https://github.com/user-attachments/assets/f1b2ebbf-bb72-4a93-aa82-835279ff3209)

**Comment by vivekvardhan2810** [comment]
@rahulbamnuya can you make the height in a right format.

**Comment by vivekvardhan2810** [comment]
but for now we don't required this, we will look it later, So i am closing this issue.

Please Understand.
