### ISSUE TITLE
Add a Cookie Consent Pop-up 

### ISSUE THREAD

**Issue by TBorundia** [ML-Fusion-Lab/ML-Fusion-Lab-Website#547]
### Is your feature request related to a problem? Please describe.

In order to comply with privacy laws like GDPR and to enhance transparency with users, we need to implement a cookie consent pop-up. This will inform users that the site uses cookies and allow them to accept or manage their preferences.

### Describe the solution you'd like.

A cookie consent pop-up should appear when a user visits the site for the first time.
The pop-up should have options like:
"Accept All Cookies"
"Customize Settings" (which allows users to choose which cookies they agree to)
After acceptance, the pop-up should disappear and not show again on subsequent visits (until cookies are cleared)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by TBorundia** [comment]
@vivekv2810 , please assign this issue to me.
I will make sure that it should matches the theme of website.
Thank You !!

**Comment by vivekvardhan2810** [comment]
@TBorundia assigning this issue to you.

Make sure to complete this issue within 2 days.
