### ISSUE TITLE
Feedback Form Improvement

### ISSUE THREAD

**Issue by TBorundia** [ML-Fusion-Lab/ML-Fusion-Lab-Website#548]
### Is your feature request related to a problem? Please describe.

It should matches to theme of website.
Adding form validation.
Adding selection of star instead of drop-down list.
Adding submission pop-up on submitting the form.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/f50586e8-ca9f-4f82-ab9a-7a03cc9bab2e)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@TBorundia this issue was assigned before, you can check it on issues section.

**Comment by TBorundia** [comment]
@vivekvardhan2810 , OK
