### ISSUE TITLE
`Theme Switcher` Not Present (Contact Section)  & `No link`embedded In feature section

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#549]
### Description

- In the home page section no link is embedded to 'structured learning" and  'community support' box (They are not clickable).
- No theme switcher present in nav bar of 'contact' section

### Steps to Reproduce

- Embed link  `Structured learning => Courses` &  `Community support => community support`
- Add `theme switcher` in nav bar of contact section(dark mode/ light mode)

### Screenshots

- box not clickable 
![Screenshot 2024-10-13 180117](https://github.com/user-attachments/assets/ec70ff24-2c5e-4ff4-9aad-dd184f4e1ee3)\

- no theme switcher in nav bar
![Screenshot 2024-10-13 180103](https://github.com/user-attachments/assets/e7d1f684-fd1b-4731-9c56-174873dcb21d)

### Additional Information

@v

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign this task to me

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 theme switcher for contact section was assigned before and they are updating it. you can check it in issues section.

**Comment by vivekvardhan2810** [comment]
But for the Embed link Structured learning => Courses & Community support => community support.

I will assign this issue.

Will it be okay for you. @Adarsh-Chaubey03

**Comment by Adarsh-Chaubey03** [comment]
yes @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 I am assigning this issue only for the Embed link Structured learning => Courses & Community support => community support.

Make sure to complete this within 2 days.
