### ISSUE TITLE
[Mention The Feature]: add a google translator feature 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#550]
### Is your feature request related to a problem? Please describe.

add a google translator feature for those who cant understand english 

### Describe the solution you'd like.

I can add a translator to this web page

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HS202022 on which page you want to add this feature.

**Comment by HS202022** [comment]
i thought of placing it in the nav bar user might get language difficulty in any of the pages 
so its better to put it in the nav bar

**Comment by vivekvardhan2810** [comment]
Okay, @HS202022 assigning this issue to you.

Make sure to complete this within 2 days.

And please don't make any changes in navbar. just add the feature in it.

**Comment by HS202022** [comment]
> Okay, @HS202022 assigning this issue to you.
> 
> Make sure to complete this within 2 days.
> 
> And please don't make any changes in navbar. just add the feature in it.

for sure

**Comment by vivekvardhan2810** [comment]
@HS202022 After this issue, make sure to contribute to other projects also.
