### ISSUE TITLE
[Mention The Feature]: Change the fonts of the header and make thirer box more curved and hovered 

### ISSUE THREAD

**Issue by Ayush-23479** [ML-Fusion-Lab/ML-Fusion-Lab-Website#554]
### Is your feature request related to a problem? Please describe.

In its header , box are not rounded as much as they needed even thier fonts doesn't look good for website .

### Describe the solution you'd like.

we need to change the font style but it should different  , make the header elements more curved , try to make them attractive. And hovering this header doesn't look responsive
![Screenshot (117)](https://github.com/user-attachments/assets/7a20dd7b-cfbe-44ae-8867-3a422babb5c7)
![Screenshot (117)](https://github.com/user-attachments/assets/c16d67ef-25e3-4fa6-96da-d8c3dc836981)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, @Ayush-23479 we will look for fonts later, for now we are closing this issue.

Please understand.
