### ISSUE TITLE
[Mention The Feature]: Enhance Cousrses

### ISSUE THREAD

**Issue by shreya20v** [ML-Fusion-Lab/ML-Fusion-Lab-Website#556]
### Is your feature request related to a problem? Please describe.

I would like to add the description of all the 6 courses in the website. 
For eg: 
In Data Science Essentials, I would add that: 
Data science is a multidisciplinary field that utilizes various techniques, processes, algorithms, and systems to extract insights and knowledge from structured and unstructured data. Here are some essentials that are fundamental to the practice of data science: 
1. Mathematics and Statistics
2. Programming Skills
3. Data Manipulation and Cleaning
4. Data Visualization
5. Machine Learning
@ML-Fusion_lab I want to work on this issue. Please assign this issue to me under suitable gssoc-exd, hacktobfest, and appropriate level labels.

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/71522525-c8e7-4a6f-a303-219cfd45d922)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shreya20v assigning this issue to you.

Make sure to complete this within 2 days.

and join the discord server for further updates.

**Comment by shreya20v** [comment]
@vivekvardhan2810 could you also assign me the hacktoberfest label.

**Comment by vivekvardhan2810** [comment]
@shreya20v  before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

**Comment by shreya20v** [comment]
@vivekvardhan2810  Thank you for giving a headsup. I have linked the Pull Request for this issue. Please review it.

**Comment by vivekvardhan2810** [comment]
@shreya20v you can create new PR tomorrow, I will check it tomorrow.
