### ISSUE TITLE
[Mention The Feature]: Update UI 

### ISSUE THREAD

**Issue by bhaviya18** [ML-Fusion-Lab/ML-Fusion-Lab-Website#557]
### Is your feature request related to a problem? Please describe.

The website is missing some UI interactions

### Describe the solution you'd like.

I would like to update the UI of the webpage to make it modern and more interactive.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require for UI Improvements, we will look it for later.

So i am closing this issue.

Please Understand.
