### ISSUE TITLE
Adding an entire tutorial page for Object Detection System In Project Page Website.

### ISSUE THREAD

**Issue by nishant4500** [ML-Fusion-Lab/ML-Fusion-Lab-Website#562]
### Is your feature request related to a problem? Please describe.

Feature Description
Deep Learning Project Python, TensorFlow, OpenCV
• Developed a robust pipeline for loading, processing, and analyzing images and video streams.
• Integrated SSD MobileNet v3 for efficient object detection and classification.

Use Case
• Achieved 80+ accuracy in detecting objects across various test scenarios

### Describe the solution you'd like.

• Achieved 80+ accuracy in detecting objects across various test scenarios

### Show us the magic with screenshots

![Screenshot 2024-06-19 121308](https://github.com/user-attachments/assets/551d7911-3218-44a6-aa39-23e34160126b)
![Screenshot 2024-06-19 121106](https://github.com/user-attachments/assets/e1f30796-e1f7-42ee-939a-076ed745759d)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@nishant4500 this repository is meant for website improvements.

**Comment by nishant4500** [comment]
@vivekvardhan2810 if i add  this project in this  portion ??


![image](https://github.com/user-attachments/assets/20df0b8b-36eb-4cc5-8c78-b62db776dc95)

**Comment by vivekvardhan2810** [comment]
Okay, got it

Can you change the title of this issue.

So that while reviewing this issue may get spammed.

**Comment by nishant4500** [comment]
ok @vivekvardhan2810 can you assign me and mark gssoc-ext

**Comment by vivekvardhan2810** [comment]
@nishant4500 make sure complete this issue within 2 days.

and join the discord server for further updates.

**Comment by nishant4500** [comment]
Ok I will do this one request can you add hacktober also

**Comment by vivekvardhan2810** [comment]
@nishant4500 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

**Comment by vivekvardhan2810** [comment]
@nishant4500 have you done with this.

**Comment by nishant4500** [comment]
i am doing it some late cause i have mid term so ..]

**Comment by vivekvardhan2810** [comment]
Okay, No problem @nishant4500 take your time. but make sure to complete it.

**Comment by vivekvardhan2810** [comment]
And @nishant4500 this Project And me (Project Admin) will remain inactive from october 28th.

Take your time. but make sure to complete it before the mentioned date.

**Comment by nishant4500** [comment]
i code work done some errors is coming

**Comment by vivekvardhan2810** [comment]
No problem @nishant4500 take your time.

This Project And me (Project Admin) will remain inactive from october 28th.

**Comment by vivekvardhan2810** [comment]
@nishant4500 have you done with this.

if this task is delaying from your side, then you can close this issue also.

if you are only okay with it. else you can work on it.

i am asking this because more 3 days i am going to be active.
