### ISSUE TITLE
Scroll to top button function visible

### ISSUE THREAD

**Issue by rishabhrawat05** [ML-Fusion-Lab/ML-Fusion-Lab-Website#564]
### Description

Hey! 
I found a bug in the project. When you scroll to bottom of any page there is a function visible i.e scroll to top. Please view the screenshot attached 

### Steps to Reproduce

I can fix the issue by checking if scripts has problem or the function 

### Expected Behavior

Only scroll to top button should be visible 

### Actual Behavior

Scroll to top function is visible with button

### Screenshots

![Screenshot_2024_1013_225519](https://github.com/user-attachments/assets/23021bd0-3df3-40b7-8697-29765a8bfc81)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@rishabhrawat05 assigning this issue to you,

Make sure to complete it within 2 days.
