### ISSUE TITLE
Aligning the Navbar item , improving the social media icons with modern styling and fixing unwanted CSS scripts in footer section 

### ISSUE THREAD

**Issue by VidhanThakur09** [ML-Fusion-Lab/ML-Fusion-Lab-Website#565]
### Description
The current NavBar has aligning elements and the social media icons have very basic styling. At the bottom of the screen, there is CSS unwanted styling that is not properly disposed result in visibility in the HTML file. Enhancing the Navbar, improving social media icon style and removing wanted CSS styling would greatly improve the user experience and website presentation

### Describe the solution you'd like

- Format the Navbar and social media for better visual appeal.
- Improving the overflowing content and unwanted CSS text.

### Problems 

https://github.com/user-attachments/assets/46309ea0-0d6c-49f1-97cf-8fe853c318c8

### Solution 

**After fixing the Navbar**

![Screenshot 2024-10-13 225040](https://github.com/user-attachments/assets/ca7c2f01-d636-47b0-b918-1ea98eea9690)

**After improving social media Icons**

https://github.com/user-attachments/assets/c8a84fbe-a0ea-4644-b457-038de2cc9d8f

@vivekvardhan2810 can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 assigning this issue to you.

Make sure to complete this issue within 2 days.

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me.

**Comment by vivekvardhan2810** [comment]
And @VidhanThakur09 this will be the last issue of Navbar, 

Make sure that this navbar issue don't repeat next time.

Do it properly.

**Comment by VidhanThakur09** [comment]
Ok sir

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 have you done with this.

**Comment by VidhanThakur09** [comment]
I will create pr in mid night.

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 yes sure because footer and navbar issues are coming so that's why.

**Comment by VidhanThakur09** [comment]
Oo, i will Rise pr as soon as possible

**Comment by AshishCh01** [comment]
Hey @vivekvardhan2810 please give me opportunity to contribute on this issue.

**Comment by vivekvardhan2810** [comment]
@AshishCh01 this issue was assigned before.
