### ISSUE TITLE
UPDATION IN README FILE REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [ML-Fusion-Lab/ML-Fusion-Lab-Website#567]
Hello @vivekvardhan2810 

the current readme file lacks proper structure and does not contain the following :

-featured in section
-table of contents
-contributors 
-forkers and stargazers section
-back to top button

kindly assign me the issue under gssoc-extd and hacktoberfest labels so my work counts under these events
Thankyou .

**Comment by vivekvardhan2810** [comment]
@soham0028 assigning this issue to you.

Make sure to complete this within a day.

**Comment by soham0028** [comment]
will revert back asap thankyouu
