### ISSUE TITLE
[Feedback form enhancement]: Would improve the UI of feedback form 

### ISSUE THREAD

**Issue by eshaalal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#568]
### Is your feature request related to a problem? Please describe.

Right now it is too boring, we need to make it interesting so that user can interact
![Screenshot 2024-10-14 003227](https://github.com/user-attachments/assets/9f618736-3559-44d2-b874-4bf6621fb6a2)
![Screenshot 2024-10-14 003344](https://github.com/user-attachments/assets/8e4db01a-fa4d-42e8-9202-58a5dce83dbb)

This is the design idea

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@eshaalal for now the feedback issue was assigned before to someone. You can check it in issues

After their updation, i will look into this.

Till then do contribute to other projects.

**Comment by eshaalal** [comment]
sure

**Comment by vivekvardhan2810** [comment]
@eshaalal assigning this issue to you.

Make sure to complete this issue within 2 days.
