### ISSUE TITLE
[DOCS] Improve Readme file with animation and add Link to LICENSE File

### ISSUE THREAD

**Issue by heizshubham** [ML-Fusion-Lab/ML-Fusion-Lab-Website#569]
### Issue Description

The Readme file is not as good, I'll put animation in readme file with MIT LICENSE Link to the LICENSE file.

### Screenshots or Examples (if applicable)

<img width="962" alt="image" src="https://github.com/user-attachments/assets/a03859be-8b39-42a9-9b3b-a4801af8b579">

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
@heizshubham this issue was assigned before, you can check it.

So i am closing this issue.

Please Understand.
