### ISSUE TITLE
The Text ML FUSION LAB is not showing properly in the Home page 

### ISSUE THREAD

**Issue by heizshubham** [ML-Fusion-Lab/ML-Fusion-Lab-Website#571]
### Description

The Text ML FUSION LAB is not showing properly in the Home page, both the text ML and FUSION is colliding to each other and also while in white light mode the text is showing white color, It should be black while in light mode and in white while in dark mode.

### Steps to Reproduce

when the user will be in dark mode the text will automatic converted into white color and while the user is in light mode the text should be in black color, and also the overlapping ML FUSION LAB Text.

### Screenshots

<img width="739" alt="image" src="https://github.com/user-attachments/assets/1d3c8a97-fce2-476a-83e0-acbf0034527a">

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@heizshubham for now it is okay and it doesn't make any difference with symbol, either in light or dark mode.

So i am closing this issue.

Please understand.

**Comment by heizshubham** [comment]
ok
