### ISSUE TITLE
 Create a Consistent UI for the Header

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#573]
### Description

The current header UI has inconsistent alignment, with elements like the logo, navigation links, and toggle button appearing misaligned or on different lines. We need to ensure that all elements, including the logo, navigation menu, language selector, and dark mode toggle button, are displayed in a single horizontal line. This will create a cleaner and more uniform appearance, enhancing the overall user experience and visual appeal of the site.

### Steps to Reproduce

na

### Screenshots

![image](https://github.com/user-attachments/assets/638aa007-0beb-43aa-962a-7c3fd6d7cbaa)

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, And they are working on it.

So I am Closing this issue.

Please Understand.
