### ISSUE TITLE
 Add "Scroll Back to Top" Button Across All Pages

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#574]
### Description

The website is currently missing a "Scroll Back to Top" button, making navigation inconvenient for users, especially on longer pages. We need to implement a scroll-to-top button on all pages, ensuring it appears when users scroll down and allows them to quickly return to the top of the page. This feature will improve usability and enhance user experience across the site.

### Steps to Reproduce

N/A

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ananyag309 can you please check on which pages does scroll back to top button requires.

So that I can look onto it.

Please share the screenshots for the proof.

**Comment by ananyag309** [comment]
example feedback 
![image](https://github.com/user-attachments/assets/dc81d906-20d0-4e3e-aed4-0a15cc12dd18)
either scrolling need improvement to needed a back to top button

**Comment by vivekvardhan2810** [comment]
@ananyag309 assigning this issue to you.

Make sure to complete this issue within 2 days.
