### ISSUE TITLE
[Mention The Feature]: I want to redesign the footer UI.

### ISSUE THREAD

**Issue by rishika105** [ML-Fusion-Lab/ML-Fusion-Lab-Website#575]
### Is your feature request related to a problem? Please describe.

I think according to the theme the footer can be enhanced with icons and a better UI design.

### Describe the solution you'd like.

I want to redesign the footer that's it.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before and they are improving it.

So I am closing this issue.

Please understand.
