### ISSUE TITLE
[Feature]: Add Star rating widget

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ML-Fusion-Lab/ML-Fusion-Lab-Website#576]
### Is your feature request related to a problem? Please describe.

![Screenshot 2024-10-14 112439](https://github.com/user-attachments/assets/6dd56ea3-c893-4104-9ff4-7570eeaa52ac)

I want to add a star rating widget in Feedback page instead of the rating text box. That will make this website more beautiful.

PA please assign me this task.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was raised before, and they are updating the page with star rating. You can check in issues section.

So i am closing this issue.

Please understand.

**Comment by Subhajit-2023-44** [comment]
@vivekvardhan2810 If he doesn't add this feature in 2 days then please assign me.. I am waiting
