### ISSUE TITLE
[Mention The Feature]: Feedback section UI designing

### ISSUE THREAD

**Issue by Sshailwal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#577]
### Is your feature request related to a problem? Please describe.

Design a user-friendly feedback section with form elements like name, email (optional), message box, and a rating system. Utilize responsive design (e.g., Tailwind CSS) with interactive elements such as hover effects and smooth transitions. Optionally, display user feedback summaries with pagination or carousel for better presentation.
Assign me asap.

![image](https://github.com/user-attachments/assets/3043191b-b774-4bc8-bd5b-e885b9353029)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was raised and assigned it before, you can check in issues section.

I am closing this issue.

Please Understand.
