### ISSUE TITLE
Improving the header and home section by making it look more Appearing 

### ISSUE THREAD

**Issue by SoumyaU25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#58]
I want to improve the header and home section of this page by making it responsive and more appearing to the users by using some advance CSS features.
Please assign me this issue under gssoc-ext label.

**Comment by vivekvardhan2810** [comment]
Hi @SoumyaU25 

Can you please share the screenshot 

So that I can check and assign this issue.

**Comment by SoumyaU25** [comment]
it's not responsive . So I want to make it responsive and more appealing for better user experience.

<img width="385" alt="Screenshot 2024-10-02 105522" src="https://github.com/user-attachments/assets/8f8f74ed-6be6-4dc2-8ac5-71495712874c">
<img width="861" alt="Screenshot 2024-10-02 105600" src="https://github.com/user-attachments/assets/0c6f6014-932c-4445-aec8-c17872fd392e">

**Comment by vivekvardhan2810** [comment]
Okay @SoumyaU25, I will assign you soon, because there are some conflicts that are to be resolved, then i will assign you.

**Comment by SoumyaU25** [comment]
Okay @vivekvardhan2810 I'll be waiting .

**Comment by vivekvardhan2810** [comment]
@SoumyaU25 join the discord server mentioned below the readme and explain me what you are going to do.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue, but i will always encourage you to look for other issues in website, then you can create new issue.
