### ISSUE TITLE
[FEAT]: Filter Courses

### ISSUE THREAD

**Issue by ArchanRD** [ML-Fusion-Lab/ML-Fusion-Lab-Website#582]
### Is your feature request related to a problem? Please describe.

Feature is not related to any problem. It is associated with Courses feature as a part of extending the functionality.

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/ca71093e-e7ab-4bd0-b458-32351553c726)
We can implement filtering courses. On course details page, the tags when clicked will open a new page which will filter the courses containing those tags. 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ArchanRD can you explain the solution in detail.

**Comment by ArchanRD** [comment]
Here's a simple explanation:  

Right now, all courses are shown on the **courses.html** page. This feature adds the ability to **filter courses based on tags**.  

For example, if there’s a tag like **"AI Interaction"**, the user can click or select that tag. After that, **only the courses with the "AI Interaction" tag will appear** on the page, hiding the rest.  

So, it makes it easier for users to **find specific types of courses** by selecting the tags they are interested in.

**Comment by vivekvardhan2810** [comment]
Okay, @ArchanRD Assigning this issue to you.

Make sure to complete this issue within 2 days.
