### ISSUE TITLE
[Security] Using only reputed mail services for signup's.

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#586]
Update the existing signup flow to validate email domains. Restrict signups to users with email addresses from trusted providers (e.g., Gmail, Outlook). etc.

Extract the domain from the user's email during signup. Compare it against a predefined list of trusted providers. If the domain matches, proceed with the signup; otherwise, return an error.

**i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!**

@vivekvardhan2810 @vivekv2810

**Comment by vivekvardhan2810** [comment]
@smog-root assigning this issue to you.

Make sure to complete this issue within 2 days.

And join discord server for further more updates.

**Comment by vivekvardhan2810** [comment]
for this task even level 2 is more @smog-root

**Comment by smog-root** [comment]
@vivekvardhan2810 i understand. even though thanks for adding level2!
