### ISSUE TITLE
[Security] Password need to meet minimum requirements for signup.

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#588]
I was crawling you'r website and noticed there is no minimum requirement for setting password while signup's!!

**Password Requirements:**

At least 8 characters long.
At least 1 uppercase letter (A-Z).
At least 1 lowercase letter (a-z).
At least 1 number (0-9).
At least 1 special character (e.g., !@#$%^&*()).

Now, when a user tries to register, they will receive immediate feedback if their password does not meet these criteria. Let me know if you need any further changes or additional features!

**i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!**

@vivekvardhan2810 @vivekv2810

**Comment by vivekvardhan2810** [comment]
@smog-root assigning this issue to you.

Make sure to complete this within 2 days.

**Comment by smog-root** [comment]
@vivekvardhan2810 2days? huh! i can do it in 1 hour!
