### ISSUE TITLE
UI Issues on Newsletter Subscription and Contributor Page Alignment

### ISSUE THREAD

**Issue by Lokesh-Bijarniya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#589]
### Description

There are two distinct issues present in the interface:
  1. The confirmation message after signing up for the newsletter is unclear and not prominent.
  2. The contributor page does not have a proper center alignment, making the layout look 
  unorganized.

### Steps to Reproduce

1. Sign up for the newsletter on the homepage.
2. Observe the confirmation message that appears after subscribing.
3. Navigate to the contributor page.
4. Check the alignment of contributor cards.

### Expected Behavior

1. The confirmation message should be bold and clearly visible.
2. The contributor page should have all elements aligned to the center for a clean appearance.

### Actual Behavior

1. The confirmation message appears faded and lacks prominence.
2. The contributor cards are unevenly aligned, resulting in a disorganized layout.

### Screenshots

<img width="1440" alt="Screenshot 2024-10-14 at 5 22 31 PM" src="https://github.com/user-attachments/assets/a6658bdb-ee80-4706-9693-22f810b12374">
<img width="1439" alt="Screenshot 2024-10-14 at 5 23 46 PM" src="https://github.com/user-attachments/assets/78452db3-c8fe-4d44-96ba-3bf3a5cc90f8">

### Additional Information

The issue may affect UX and could potentially discourage users from engaging with the newsletter and contributor sections.

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Lokesh-Bijarniya assigning this issue to you.

Make sure to complete this issue within 2 days.

**Comment by vivekvardhan2810** [comment]
@Lokesh-Bijarniya before creating make sure to sync the repository, as i have updated the files and clustered the files in one way.
