### ISSUE TITLE
Nav Elements Alignment issue and  About section text issue

### ISSUE THREAD

**Issue by Mohitranag18** [ML-Fusion-Lab/ML-Fusion-Lab-Website#59]
In header nav elements are not aligned with proper spacing and also the basic things are not designed properly like nav elements have a fixed width, which create problem while screen size is decreasing and designing of elements can be better like they can be rounded not just when they are hovered but in default state rounded will look better.
In about section, back color and text color is not in contrast and because of this the text is not readable easily.
Also the alignment of text and images is not proper in about section.
I can solve all this issues if this issue is assign to me.

**Comment by Mohitranag18** [comment]
Please Assign this issue to me i can solve this issue very well.

**Comment by vivekvardhan2810** [comment]
Okay @Mohitranag18 

Assigning this issue to you.

Please complete this issue.

**Comment by Mohitranag18** [comment]
thank you sir for assign this to me i will solve the issue in given time-period.

**Comment by vivekvardhan2810** [comment]
Also join our discord channel : https://discord.gg/FZxBRpTEeH

for further updates and communications.

**Comment by vivekvardhan2810** [comment]
Hi @Mohitranag18, i will be removing hacktoberfest label

as this project is not registered under hacktoberfest

will it be okay for you.

**Comment by Mohitranag18** [comment]
Ok sir, it's fine
