### ISSUE TITLE
[Mention The Feature]: Privacy policy page required major changes, currently it looks more like a dummy website not a professional website for courses.

### ISSUE THREAD

**Issue by anadisharma121** [ML-Fusion-Lab/ML-Fusion-Lab-Website#591]
### Is your feature request related to a problem? Please describe.

- **would like to add this kind of genuine looking privacy policy page at place of current privacy policy**

- **I will introduce tailwind CSS code for the above task**

Please assign this task to me and label the problem with gssoc-ext, hacktoberfest and the respected level. 
![image](https://github.com/user-attachments/assets/22136773-d1d1-4ee3-86ca-70da7fdf36a9)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@anadisharma121 you are talking about this page.

![image](https://github.com/user-attachments/assets/3987985a-538d-4c5d-966d-73eb65393eb7)

**Comment by anadisharma121** [comment]
@vivekvardhan2810 Yes

**Comment by anadisharma121** [comment]
@vivekvardhan2810 Thanks for this, I will get it done soon.
