### ISSUE TITLE
Adding github icon

### ISSUE THREAD

**Issue by Aditijainnn** [ML-Fusion-Lab/ML-Fusion-Lab-Website#593]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/75f328e9-1bba-44d8-8ef4-b5c2795584b2)
in this adding github icon

### Describe the solution you'd like.

assign this to me under gssoc ext

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Aditijainnn check #467

**Comment by vivekvardhan2810** [comment]
So i am closing this issue, please check before creating an issue, you have created the issue with same title before,
