### ISSUE TITLE
[DOCS] Improve Readme file by adding Table of Contents

### ISSUE THREAD

**Issue by Maryam0330** [ML-Fusion-Lab/ML-Fusion-Lab-Website#594]
### Issue Description

I would like to add a `Table of Contents` section to the README file to enhance navigation and provide a more user-friendly experience for end users. This will enable quick access to key sections and improve the overall readability of the project.

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
for now the readme looks good and don't require any updation.

please understand.
