### ISSUE TITLE
[BUG]:In the home tab, the navbar is not properly padded. 

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ML-Fusion-Lab/ML-Fusion-Lab-Website#595]
### Description

In the home tab, the navbar is not properly padded. 
Its UI can be improved.

### Steps to Reproduce

1)Go to the main section.
2)Click on the home tab navbar.
3)You can see the error in the navbar.

### Expected Behavior

The padding should be set properly to enhance user experience.

### Screenshots

<img width="1418" alt="Screenshot 2024-10-14 at 7 34 29 PM" src="https://github.com/user-attachments/assets/8b532d60-c767-4403-945d-a88286136ae7">

### Additional Information

Please assign this issue to me and add level, gssoc-ext, hacktober fest labels.

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, and he is working on it, you can check in issues section.

So i am closing this issue.

Please understand.
