### ISSUE TITLE
Make Copyright Year Dynamic in Footer

### ISSUE THREAD

**Issue by we-nita** [ML-Fusion-Lab/ML-Fusion-Lab-Website#596]
### Description

The copyright year is currently hardcoded in the footer section of the website. This requires manual updates each year, which is not ideal for maintaining the codebase.

### Steps to Reproduce

Navigate to the footer of any page.
Observe that the copyright year is hardcoded (e.g., "© 2024").

### Expected Behavior

The copyright year should dynamically display the current year
Thank you for considering this enhancement

### Actual Behavior

The copyright year in the footer is hardcoded as a fixed value (e.g., "© 2024"). As a result, the year does not automatically update to the upcoming year, which requires manual intervention to change it annually

### Screenshots

![image](https://github.com/user-attachments/assets/162c7abe-8b95-4fc9-88f5-8df600bebeeb)

### Additional Information

This issue can be easily resolved by implementing a small JavaScript code to dynamically generate the current year.
I can provide a pull request with the solution if needed.
Please assign me the issue with gssoc-ext, level, and hactoctober fest label

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@we-nita make sure to complete this within a day.

**Comment by vivekvardhan2810** [comment]
@we-nita before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.
