### ISSUE TITLE
 Update Website Preview Section in README File

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#597]
### Description

 I noticed that the website's UI has been updated, but the preview section in the README file still reflects the old design. I can update the preview section to accurately represent the current website UI. This will provide new users with a more accurate view of the site and ensure consistency across the repository.

Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

### Steps to Reproduce

NA

### Screenshots

**Current UI :**
![current website ](https://github.com/user-attachments/assets/49a83fad-64ab-410d-a72b-fb3bfca326e1)

**Current Preview :**
![website preview](https://github.com/user-attachments/assets/19aeff47-d751-4ec1-bd8f-9d6cf83426ad)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Priyanshi0112 i have updated the picture in readme, thank you for pointing out this issue.

I have updated it.

So i am closing this issue.

you can look for other issues.
