### ISSUE TITLE
[Mention The Feature]: Adding a Registration Pop up 

### ISSUE THREAD

**Issue by PrAyAg9** [ML-Fusion-Lab/ML-Fusion-Lab-Website#598]
### Is your feature request related to a problem? Please describe.

Adding a registration pop-up can serve several purposes:

User Engagement: It encourages visitors to sign up for newsletters, updates, or exclusive content, fostering a sense of community.

Lead Generation: Capturing user information can help build a database for marketing efforts, allowing for targeted communication.

Content Access: You can restrict certain content or features, enticing users to register for access to premium material.

Personalization: Registered users can receive tailored experiences, such as personalized recommendations or offers based on their preferences.

Increased Conversions: A well-designed pop-up can boost conversion rates by prompting users to take action at key moments during their visit.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@PrAyAg9 can you share me the screenshot on which page you wanna work.

**Comment by PrAyAg9** [comment]
@vivekvardhan2810 
![image](https://github.com/user-attachments/assets/643015c5-bf20-4d43-b137-844f4fcd39b2)
On landing page a popup will appear with current offer to login and avail exciting offer on first course like that

**Comment by vivekvardhan2810** [comment]
@PrAyAg9 assigning this issue to you.

Make sure to complete this within a day.
