### ISSUE TITLE
Fix header

### ISSUE THREAD

**Issue by saadgibawa** [ML-Fusion-Lab/ML-Fusion-Lab-Website#6]
![Screenshot 2024-10-01 183133](https://github.com/user-attachments/assets/e5137c9c-09b3-448d-8227-8c728c69ded9)
i want to redesign the header as the current header contents are not properly aligned and spaced. Please assign me this issue.

**Comment by vivekvardhan2810** [comment]
@saadgibawa, assigned to you.

**Comment by Codewithmeowmeow** [comment]
Hey kindly assign me this issue i would love to work on this.

**Comment by vivekvardhan2810** [comment]
Hi, @Codewithmeowmeow , as this issue was presented by other user, so it will be first on first serve, if that user doesn't do this work

Then I will assign you the issue.

But still you can look out for other issues.

**Comment by Codewithmeowmeow** [comment]
Okay

**Comment by vivekvardhan2810** [comment]
Hi, @saadgibawa make sure to complete this issue in the next 3 days.

**Comment by vivekvardhan2810** [comment]
make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH

**Comment by saadgibawa** [comment]
hi @vivekvardhan2810 I'll ensure that
