### ISSUE TITLE
Text visibility and footer section appearing twice

### ISSUE THREAD

**Issue by sriraghavi22** [ML-Fusion-Lab/ML-Fusion-Lab-Website#60]
When i try to type my email in sign up for Newsletters input , I am unable to see what am I typing and also the footer is appearing twice

https://github.com/user-attachments/assets/78ef5eda-51b1-4de2-af3f-9850f7e128a8

I would like to fix this issue

**Comment by vivekvardhan2810** [comment]
Okay @sriraghavi22 

Assigning this issue to you.

Make sure to complete this issue for the next 2 days.
