### ISSUE TITLE
feature: Adding "Crop Height Estimation Using Computer Vision" Tutorial page in project  page.

### ISSUE THREAD

**Issue by Palmistry2310** [ML-Fusion-Lab/ML-Fusion-Lab-Website#600]
I would like to request the addition of a new tutorial on Crop Height Estimation Using Computer Vision to the project section. This tutorial covers how to estimate crop height using contour detection techniques, which is highly relevant for agricultural applications.

Main Steps:
Importing necessary libraries (OpenCV, NumPy, Matplotlib).
Loading and preprocessing the image.
Detecting contours of the crops using Canny edge detection.
Calculating the crop height using the bounding box of the largest contour.
(Optional) Converting the crop height from pixels to real-world units.

Code Example: Include a full code walkthrough with detailed explanations.

Summary: This tutorial explains how to use OpenCV's contour detection techniques to estimate the height of crops in an image. It guides users through image preprocessing, contour detection, and measuring crop height based on detected contours. Additionally, it covers converting pixel-based measurements into real-world units like centimeters.

@vivekv2810 can u please assign this to me under gssoc-ext, hacktoberfest accepted and level label?

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 assigning this issue to you.

Make sure to complete this within 2 days.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

**Comment by Palmistry2310** [comment]
> @Palmistry2310 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

ohh i was just about to create pull request!

**Comment by vivekvardhan2810** [comment]
Sorry @Palmistry2310 but i wanted to arrange it in one structured way, sorry again if i have disturbed you.

**Comment by Palmistry2310** [comment]
@vivekvardhan2810 this is what i see in deployment link now , the images and attached files are not found.May be this happened due to current changes in its structure.

https://github.com/user-attachments/assets/48a64aac-3e54-4c78-91bc-fbf60650316a

**Comment by vivekvardhan2810** [comment]
yes @Palmistry2310.
