### ISSUE TITLE
feature: Adding "Chatbot Development for Customer Support" Tutorial to the project page

### ISSUE THREAD

**Issue by Palmistry2310** [ML-Fusion-Lab/ML-Fusion-Lab-Website#601]
here:
![Screenshot 2024-10-14 211712](https://github.com/user-attachments/assets/34eac204-1f21-4587-a390-2c47ee087aa1)

Description:
This issue is to request the addition of a new tutorial on Chatbot Development for Customer Support to the project page. This tutorial walks through the process of building a simple yet effective chatbot designed to provide automated customer support using natural language processing (NLP) and a conversational framework.

Main Steps:

**Introduction to Chatbots:**
Overview of chatbots and their importance in customer support.
Key chatbot types (Rule-based vs. AI-driven).
**Setup and Environment:**
Installing Python and setting up required libraries (e.g., nltk, spaCy, rasa, ChatterBot).
Creating a virtual environment.
**Designing the Conversation Flow:**
Identifying common customer queries and responses.
Structuring the conversation flow.
**Natural Language Processing (NLP):**
Tokenizing and stemming customer inputs.
Understanding intents and entities.
Training the bot with predefined intents using NLP libraries like spaCy or rasa.
**Implementing the Chatbot:**
Developing a basic rule-based chatbot using ChatterBot.
Expanding the chatbot with NLP-based understanding to handle a broader range of customer inputs.
**Testing and Deployment:**
Testing chatbot responses.
Deploying the chatbot on a website using frameworks like Flask or Django.
**Escalation to Human Agents:**
Adding a feature for escalation when the bot cannot answer a query.

Code Example: A full code walkthrough will be provided, showcasing the integration of the chatbot with a web-based interface and customer support APIs.

@vivekv2810 can u please assign this to me under gssoc-ext, hacktoberfest accepted and level label?

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 please complete the previous issue Which i have assigned you, After then i will assign this.

**Comment by Palmistry2310** [comment]
@vivekvardhan2810 I have completed previous one.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 assigned you.

Make sure to complete it.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 make sure to create these tutorials without disturbing any other elements.

Since there html contains different divs and tags the css is conflicting and causing these issues.
