### ISSUE TITLE
[DOCS] I want to organize entire Code Structure

### ISSUE THREAD

**Issue by PrAyAg9** [ML-Fusion-Lab/ML-Fusion-Lab-Website#604]
### Issue Description

Many css, Js files are kept in a very unorganized way and such as their paths, so Give me a change to organize Files in you repository and changes their path so functionality doesn't have an effect. Organized code will be good for open source.

### Additional Context

I will just keep all external files of css and Js in proper way and if you allow i can take all internal css and js and make it external, It would be hard and time consuming but a better practice.

### Screenshots or Examples (if applicable)

Now:- 
![image](https://github.com/user-attachments/assets/0c4a54a1-6da8-4742-82d1-1e3fec676ad8)
 
WOULD LOOK LIKE:- 
![image](https://github.com/user-attachments/assets/eb929bf0-8801-4a6a-b568-46998973d7a4)

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
@PrAyAg9  can you keep keep the index.html outside, for deployment. don't include it in file.

**Comment by PrAyAg9** [comment]
Yes, Actually that screenshot was how it will look like is just for example all html files would be placed outside only style, script and images would be organized in specific folder.

**Comment by vivekvardhan2810** [comment]
okay @PrAyAg9 assigning this issue to you.

but there won't be any level labels issued for this.

means i will add gssoc ext hacktoberfest labels except level1 level2 level3 labels.

will it be okay for you.
