### ISSUE TITLE
Improvement Needed in `Learn More` Button Under Project Section

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#605]
### Description

- Many `learn more` buttons are not aligned in proper line . 
- Also few are not completely visible

### Steps to Reproduce

I will correct it using proper CSS methods.
@vivekvardhan2810 please assign me this task

### Screenshots

![image](https://github.com/user-attachments/assets/576c6600-28e2-4eb2-babd-104cdfeeae13)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete it.

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

And can you please add the images in projects as i can't see it in my website right now.
