### ISSUE TITLE
nav-bar is not align properly

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [ML-Fusion-Lab/ML-Fusion-Lab-Website#606]
### Description

in many , nav - bar is not allign properly like in about section and many more

### Steps to Reproduce

go to the about section and course section

### Screenshots

![image](https://github.com/user-attachments/assets/0ad14365-c79d-4d2b-a48d-461493120ec1)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, and he is working on it, you can check in issues section.

So i am closing this issue.

Please understand.
