### ISSUE TITLE
want to add chat box

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [ML-Fusion-Lab/ML-Fusion-Lab-Website#607]
### Description

 ML buddy chat-box is comming only in project section while it should come in all pages like HOME  and all

### Steps to Reproduce

1) Navigate to the HOME page of the application.
2) Check for the presence of the ML buddy chat box.
3) Repeat for other pages (e.g., About, Contact).
4) Observe that the chat box only appears in the project section

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now the chatbox is okay with in home section and project and for all pages there is no requirement of chatbox. we will look for this later.

so i am closing this issue.

please understand.
