### ISSUE TITLE
Improvement in CSS of div newsletter

### ISSUE THREAD

**Issue by aakanshimalik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#608]
Subscribe button of newsletter needs proper margin from left and right . h1 and paragraph needs proper spacing between them as they are looking little bit conjusted.
![issue](https://github.com/user-attachments/assets/c7b5b1a7-deca-4b8a-b78b-ac7d30948608)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before, you can check in issues section and they are updating it.

So i am closing this issue.

please understand.
