### ISSUE TITLE
No Proper Alignment 

### ISSUE THREAD

**Issue by Roshn1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#609]
### Description

![Screenshot 2024-10-14 222147](https://github.com/user-attachments/assets/dfceb0b5-d2d5-46ca-8760-9ad32a8ff8ac)
the subscribe button is not properly aligned

### Steps to Reproduce

Hi , I came across this issue . I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Roshn1 assigning this issue to you.

make sure to complete it within a day.
