### ISSUE TITLE
Improve "Contact Us" Form with Enhanced Hover Effects

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#611]
### Is your feature request related to a problem? Please describe.

The current "Contact Us" form could benefit from improved user interaction through enhanced hover effects. This update aims to make the form more visually appealing and user-friendly, thereby encouraging more users to engage with it.

### Describe the solution you'd like.

Enhanced Button Hover Effects 🎨:

- Implement new hover effects for the submit button to make it more interactive. Suggested effects include:
- Changing the background color on hover.
- Adding a subtle shadow to create a 3D effect.
- Increasing the scale slightly for emphasis.

Input Field Focus Effects 🔍:

- Apply focus effects on input fields to improve user experience:
- Change the border color to indicate active fields.
- Add a smooth transition effect for visual appeal.

### Describe alternatives you've considered.

- Increases user engagement and encourages more submissions through a visually appealing interface.
- Enhances accessibility by providing clear indications of active fields and feedback messages.
- Improves overall user experience by making interactions more intuitive and enjoyable.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/6f98fb6f-bc90-45ae-92b7-7416e29a9a29)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@neeru24 i have assigned you a issue before, have you completed that.

**Comment by neeru24** [comment]
> @neeru24 i have assigned you an issue before, have you completed that.

Yes, Actually I'm working on that issue too as enclosing that text in a card is affecting the UI of website, so I'm trying to figure that out also

**Comment by neeru24** [comment]
> so can i hold this issue for now or close this issue.

Can you assign me this issue too, I'll submit a PR for this tommorow

**Comment by vivekvardhan2810** [comment]
for now i don't required for that Enhance About Section by Wrapping Text in a Card.

So instead of that can i close that issue and assign you this issue.

Will it be okay for you.

so that you won't become stress on that,

**Comment by neeru24** [comment]
> for now i don't required for that Enhance About Section by Wrapping Text in a Card.
> 
> So instead of that can i close that issue and assign you this issue.
> 
> Will it be okay for you.
> 
> so that you won't become stress on that,

Okay, Sure
You can close that issue.

**Comment by neeru24** [comment]
@vivekvardhan2810 Thank you so much for understanding. Actually it's my first time when I'm contributing to open source, so sometimes, It take me time to understand the project structure too.

**Comment by vivekvardhan2810** [comment]
No Problem @neeru24 i am assigning this issue to you.

make sure to submit a PR by tomorrow.

**Comment by neeru24** [comment]
> No Problem @neeru24 i am assigning this issue to you.
> 
> make sure to submit a PR by tomorrow.

Yes, I will.

**Comment by vivekvardhan2810** [comment]
@neeru24 before creating the PR make sure to sync the repository, as i have updated the files and clustered the files in one way.
