### ISSUE TITLE
[Mention The Feature]: Adding an tutorial page for Terrain Classification System In Project Page Website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#612]
### Is your feature request related to a problem? Please describe.

Lot of data is gathered regarding terrains from photographs and satellite images which need to me labelled ay fast rates .  

### Describe the solution you'd like.

By using Transfer Learning and GPU implementation , created a model with fast inference and high accuracy for handling large datasets.

### Show us the magic with screenshots

https://github.com/user-attachments/assets/2da0eee6-b3be-4f87-89c5-ab181bad22f5

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 can you share the screenshot of the page that you wanna add this work.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this issue within 2 days.

**Comment by DarshAgrawal14** [comment]
> @DarshAgrawal14 can you please share the screenshot of the page that you wanna add this work.

@vivekvardhan2810 sure! since it would take multiple screenshots to cover the page , here is a video of a scroll through the page


https://github.com/user-attachments/assets/c0054001-f062-4570-a7f1-0146c792de01

if you prefer any changes or would like any idea implemented please let me know.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 Done, Go it on.

> > @DarshAgrawal14 can you please share the screenshot of the page that you wanna add this work.
> 
> @vivekvardhan2810 sure! since it would take multiple screenshots to cover the page , here is a video of a scroll through the page
> 
>  Recording.2024-10-14.233648.mp4 
> if you prefer any changes or would like any idea implemented please let me know.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 before creating make sure to sync the repository, as i have updated the files and clustered the files in one way.
