### ISSUE TITLE
Improving the looks of the Feedback form, Improving font of the navbar and changing padding of the nav elements.

### ISSUE THREAD

**Issue by CodewMilan** [ML-Fusion-Lab/ML-Fusion-Lab-Website#613]
### Issue Description

**### Improving the looks of the Feedback form, Improving font of the navbar and changing padding of the nav elements.**

**The Feedback form needs to be improved in terms of design of the buttons and the design of the entry fields, to match the website.**
<img width="900" alt="improvement 1" src="https://github.com/user-attachments/assets/c43db5d0-5593-4c72-a3dc-791a9ebc48a9">

**The nav bar needs significant improvement in terms of font, spacing, border-radius. i can make sure that i will make the navbar more visually appearing and improve the UI of the navbar**

Kindly assign this to me under gssoc-extd and hacktober-fest
Thank you

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require any navbar improvements and in feedback form also.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
