### ISSUE TITLE
Bug in Project section (Empty spaces)

### ISSUE THREAD

**Issue by satyamra1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#614]
### Description

In project section their are empty spaces for project cards, even though their are many projects .

### Steps to Reproduce

Updation of javascript

### Expected Behavior

At initial their will be 8 projects in 2 rows .

### Screenshots

![image](https://github.com/user-attachments/assets/e9df4722-5e8c-486f-8434-f55750229444)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@satyamra1 have you completed the previous issue that i have assigned you.

**Comment by vivekvardhan2810** [comment]
and when you click the load more option then there will be the appearances of the projects,

this is an animation.

![image](https://github.com/user-attachments/assets/cdd5cbcf-4f24-467c-a080-7b78587217f3)

**Comment by vivekvardhan2810** [comment]
@satyamra1 please complete the issue that i have assigned you before.

**Comment by vivekvardhan2810** [comment]
from my side it is looking good.

So i am closing this issue.

Please understand.

And complete the previous issue that i have assigned you.
