### ISSUE TITLE
[BUG]:Misalignment of tabs

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [ML-Fusion-Lab/ML-Fusion-Lab-Website#616]
### Description

The tabs are are not aligned evenly

### Steps to Reproduce

1)Go to main
2)scroll down

### Expected Behavior

The tabs should be in same alignment for better UI experience.

### Screenshots

<img width="1423" alt="Screenshot 2024-10-15 at 12 23 27 AM" src="https://github.com/user-attachments/assets/bc7089be-026d-4019-ba3f-6843b7738afd">

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Arghya-Chakraborty0812 assigning this issue to you,

Make sure to complete this within a day.

**Comment by vivekvardhan2810** [comment]
@Arghya-Chakraborty0812 before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

**Comment by vivekvardhan2810** [comment]
@Arghya-Chakraborty0812 can i close this issue or can i assign you this issue.

as you have unassigned yourself.

**Comment by vivekvardhan2810** [comment]
i am closing this issue, you can look for other issues. don't be discouraged.
