### ISSUE TITLE
 Add Navbar, Footer, and Styling to Feedback Page for Consistency

### ISSUE THREAD

**Issue by DivyaJyothi9** [ML-Fusion-Lab/ML-Fusion-Lab-Website#618]
### Description

The feedback page currently lacks a navigation bar, footer, background color, and overall styling, making it look inconsistent with the rest of the website. Adding these elements will enhance the page's appearance and provide a cohesive user experience.

### Steps to Reproduce

**Navbar:** Implement a navigation bar at the top of the feedback page, matching the structure and style of the navbars on other pages.

**Footer:** Add a footer to the bottom of the page, ensuring it includes relevant links or information as seen on other pages.

**Styling:** Apply consistent styling by:

1. Adding a background color that aligns with the website's theme.
2. Using CSS to format and structure the page elements.
3. Incorporating fonts, colors, and other design aspects that match the site’s existing design guidelines.

**Responsiveness:** Ensure the page is responsive and displays well on both desktop and mobile devices.

### Expected Behavior

The feedback page should have a similar layout and style as other pages on the website.
Users will experience a consistent look and feel across the website, improving navigation and visual appeal.

### Actual Behavior

The feedback page currently lacks a navigation bar, footer, background color, and overall styling, making it look inconsistent with the rest of the website.

### Screenshots

![Screenshot (328)](https://github.com/user-attachments/assets/8b933300-a7dc-4500-a7fd-4a374047ca20)
![Screenshot (329)](https://github.com/user-attachments/assets/145cb296-72a2-46c3-b148-6c493d132ab0)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by DivyaJyothi9** [comment]
@vivekv2810 sir, Kindly assign this to me, I would like to work upon it.
Thank you

**Comment by vivekvardhan2810** [comment]
@DivyaJyothi9 i think the feedback page was updated way long time., please check once again.

Present:

![image](https://github.com/user-attachments/assets/eed542b7-c1d3-4eb5-8750-031574aaae89)

**Comment by vivekvardhan2810** [comment]
and for now there is no need of navbar, footer updation for this page, so i am closing this issue.

Please understand.

**Comment by DivyaJyothi9** [comment]
Ok sir!! @vivekvardhan2810
