### ISSUE TITLE
[update testimonial page]:  would improve the ui

### ISSUE THREAD

**Issue by eshaalal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#622]
### Is your feature request related to a problem? Please describe.

Right now the UI is too boring , would like to improve it 

https://github.com/user-attachments/assets/5ca3dbf0-8f42-4673-bb10-02bb08eed55a

This is the proposed idea

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@eshaalal assigning this issue to you.

Make sure to complete this within 2 days.

before creating the Pull Request make sure to sync the repository, as i have updated the files and clustered the files in one way.

**Comment by eshaalal** [comment]
sure!
