### ISSUE TITLE
[Mention The Feature]: updating all the fixes across the websites.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#623]
### Is your feature request related to a problem? Please describe.

- there are changes required in the website like scrollbar , the darkmode and images are missing.

can you assign me this task so i can fix all the pages.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigning this to you.

Make sure to complete this issue within 2 days.
