### ISSUE TITLE
[Mention The Feature]: adding local storage to the feedback

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#627]
### Is your feature request related to a problem? Please describe.

<img width="1018" alt="Screenshot 2024-10-15 at 3 11 44 AM" src="https://github.com/user-attachments/assets/7eb98e82-966d-467c-909a-2f30acc9a326">

i can create a local storage functionality to save data on submit.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigning this issue to you.

Make sure to complete this issue within 2 days.
