### ISSUE TITLE
Improving Navigation: A Focus on Navbar Design

### ISSUE THREAD

**Issue by khushimoon014** [ML-Fusion-Lab/ML-Fusion-Lab-Website#63]
The current navbar needs enhancements for better usability, including hover effects, improved text contrast and mobile responsiveness.

Can you assign this issue to me

**Comment by vivekvardhan2810** [comment]
@khushimoon014 can you share the screenshot.

and detailed solution.

**Comment by khushimoon014** [comment]
I'll get it ready and share it with you soon.

**Comment by Kavish-Paraswar** [comment]
"I would like to work on this issue as I have a strong background in CSS and HTML. Please assign me to this task under GSSOC'24 Extended."

**Comment by vivekvardhan2810** [comment]
@Kavish-Paraswar its already assigned to someone else
