### ISSUE TITLE
Fix the footer position in some pages

### ISSUE THREAD

**Issue by Abankita** [ML-Fusion-Lab/ML-Fusion-Lab-Website#630]
### Description

The footer is some pages are not in the bottom of the screen as it should be. 

### Steps to Reproduce

Open feedback or community support page and scroll to bottom. 

### Expected Behavior

The footer should be at the bottom of the screen

### Actual Behavior

The footer is at the bottom of the content leaving space at its bottom

### Screenshots

![Screenshot_2024-10-15-07-46-35-311_com android chrome (1)](https://github.com/user-attachments/assets/4c93efea-1c32-4b05-8388-7320b7304957)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require this, we will look into this later.

i am closing this issue.

Please understand.

**Comment by Abankita** [comment]
> for now we don't require this, we will look into this later.
> 
> i am closing this issue.
> 
> Please understand.

Yes sure
