### ISSUE TITLE
Make the login page mobile responsive

### ISSUE THREAD

**Issue by Abankita** [ML-Fusion-Lab/ML-Fusion-Lab-Website#631]
### Description

The website layout of login page is not responsive on mobile devices, causing visual issues. Elements overflow, and text/buttons appear too large.

### Steps to Reproduce

Open the login page on a mobile device and observe the layout issues.

### Expected Behavior

The website should resize elements to fit smaller screens, maintaining a clean layout. Buttons, text, and images should adjust without overflow.

### Actual Behavior

Elements do not scale properly, causing buttons and text to appear too large. The container exceeds the screen width, leading to an overflow.

### Screenshots

![Screenshot_2024-10-15-08-12-35-180_com android chrome (1)](https://github.com/user-attachments/assets/8280941c-bac1-4b70-8111-3cdd5c5700c9)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Abankita assigning this issue to you.

Make sure to complete this within 2 days.

**Comment by Abankita** [comment]
@vivekvardhan2810  Due to some reasons, I’m unable to complete this issue. I apologize for the inconvenience. If possible, you could consider reassigning it to any other interested contributor. Thanks for understanding!

**Comment by vivekvardhan2810** [comment]
No problem @Abankita you can look for other issues.

for now i am closing this issue.

will it be okay for you

if i close this issue.

**Comment by Abankita** [comment]
> No problem @Abankita you can look for other issues.
> 
> for now i am closing this issue.
> 
> will it be okay for you
> 
> if i close this issue.

No problem

**Comment by vivekvardhan2810** [comment]
@Abankita till then do contribute to other projects also,

**Comment by Abankita** [comment]
Thanks for your understanding and for always being so active in the repo. I really appreciate your continuous involvement and support! I'll definitely look forward to contribute in every way possible in gssoc.
