### ISSUE TITLE
Not All Pages Of Website is following same order of `footer` as that of home page

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#636]
- footer of major pages including home page are like this:
![Screenshot 2024-10-15 111915](https://github.com/user-attachments/assets/98eac463-a099-444d-a2fa-09fe6f36148d)
![Screenshot 2024-10-15 112440](https://github.com/user-attachments/assets/626c7831-e80f-4330-88d8-9d0618b87810)
##
- but some of pages like feedback and contact us pages are not following the same order of text:
![Screenshot 2024-10-15 111946](https://github.com/user-attachments/assets/3afb15de-4112-4133-bf1f-0f0a3b7bba03)
![Screenshot 2024-10-15 112411](https://github.com/user-attachments/assets/e85d1f34-b2ec-4098-be5a-442a7b4aa0c8)
 ##
I will check all such pages and make their footer same as that of home page
@vivekvardhan2810 please assign me the task

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this within 2 days.
