### ISSUE TITLE
[Feature]: Adding Tutorial for Decision Tree to the Project Page

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#639]
### Is your feature request related to a problem? Please describe.

We need to add a detailed tutorial to the project page that demonstrates how to build a Decision Tree model using the Iris Flower dataset. This will be a step-by-step guide aimed at helping users understand the fundamentals of Decision Tree classification and how to apply it to a real-world dataset.

### Describe the solution you'd like.

1. **Introduction:**
   - Brief explanation of the Decision Tree algorithm.
   - Overview of the Iris Flower dataset.

2. **Dataset Preparation:**
   - Instructions on loading and exploring the Iris dataset.
   - Explanation of features and target variables.

3. **Building the Decision Tree Model:**
   - Step-by-step code walkthrough to build the model using `scikit-learn`.
   - Explanation of key parameters like `criterion`, `max_depth`, and `splitter`.

4. **Model Evaluation:**
   - Instructions for evaluating the model using metrics like accuracy, precision, and recall.
   - Visualize the Decision Tree using libraries like `matplotlib`.

5. **Conclusion:**
   - Summarize key takeaways and encourage further experimentation.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@IkkiOcean assigning this issue to you.

Make sure to complete this issue within 2 days.
