### ISSUE TITLE
Enhance UI of Feedback Page

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#640]
### Is your feature request related to a problem? Please describe.

I'd like to suggest adding hover effects to the "Feedback" page to enhance the user experience and visual appeal.

### Describe the solution you'd like.

- Add hover effects to buttons (e.g., change color or scale slightly on hover).
- Highlight form fields on focus for better accessibility.
- Include subtle transitions to make interactions smoother

### Describe alternatives you've considered.

Kindly assign me this issue, I'll submit a PR shortly

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/b23c3e71-1008-4d70-a678-f3eff929dedd)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@neeru24 assigning this issue to you.

Make sure to complete it within 2 days.

**Comment by neeru24** [comment]
> @neeru24 assigning this issue to you.
> 
> Make sure to complete it within 2 days.

I'm starting to work on it now, No worries, I'll submit a PR by today only. 
Thank you for assigning.
