### ISSUE TITLE
Wrong Card Appears After Clicking the "Learn More" Button at Project Page

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#641]
### Description

When clicking the "Learn More" button on the project page, the wrong project card appears in certain instances. This leads to confusion for users, as the displayed content does not match the selected project.

### Steps to Reproduce

1. Navigate to the project page.
2. Click on the "Learn More" button for any project.
3. Observe that the wrong project card is displayed in some cases.

### Screenshots

https://github.com/user-attachments/assets/b6aa8912-b689-46ff-beed-eabf85e104fa

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@IkkiOcean please complete the issue that i have assigned you before, then i will assign you this.

**Comment by IkkiOcean** [comment]
> @IkkiOcean please complete the issue that i have assigned you before, then i will assign you this.

fixing it first will be better as adding more projects to the page will make it more worse. I can fix it rn

**Comment by vivekvardhan2810** [comment]
@IkkiOcean can you fix it now.

**Comment by IkkiOcean** [comment]
> @IkkiOcean can you fix it now.

Hi Vivek, do want those cards as I see no reason keep them there. I can make a button like open project which redirects to the project. it's your wish if you want those cards. I can add more content to them to make them look more appealing and useful 

<img width="1278" alt="Screenshot 2024-10-15 at 12 52 25 PM" src="https://github.com/user-attachments/assets/61e6693b-6c71-4d88-a9ab-c05c9129c2f1">

**Comment by vivekvardhan2810** [comment]
@IkkiOcean yes you can make a button like open project which redirects to the project.

**Comment by IkkiOcean** [comment]
> @IkkiOcean yes you can make a button like open project which redirects to the project.

Okay and for projects which aren't implemented there will be learn more button with some more description. Is that fine?

**Comment by vivekvardhan2810** [comment]
yes.
