### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Malicious PDF detection in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#642]
### Is your feature request related to a problem? Please describe.

PDF can contain various formats of data including malicious links and code . 

### Describe the solution you'd like.

Develop a pipeline to extract features from pdf and detect malicious pdfs using ML model

### Show us the magic with screenshots

https://github.com/user-attachments/assets/1ef79d24-14df-41ed-a205-cf4ed95ead51

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

from now onwards for tutorial updation i am gonna assign level 2 only.

please understand.

**Comment by DarshAgrawal14** [comment]
I do but please see that the level of model and training notebooks that i have added is quite good. I understand if you assign level 2 for tutorial pages of common models , but this one has code has feature extraction from pdf along with model training.

**Comment by vivekvardhan2810** [comment]
okay, then i will update the level, will be it okay for you. @DarshAgrawal14

**Comment by DarshAgrawal14** [comment]
yes ofcourse , thank you!

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 make sure to create these tutorials without disturbing any other elements.

Since there html contains different divs and tags the css is conflicting and causing these issues.

**Comment by DarshAgrawal14** [comment]
@vivekvardhan2810
Is there an issue with my previous page?
I didn’t quite understand what you meant by these issues. Could you please clarify.

**Comment by DarshAgrawal14** [comment]
I’ve created an HTML file named terrain_classifier.html, which contains my tutorial and all the content. I wrote the CSS directly within that file, so I don’t think it will affect the styling of other pages.
