### ISSUE TITLE
Enhance Login Page 

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#644]
### Is your feature request related to a problem? Please describe.

The current login page could benefit from enhanced user interaction through the addition of hover effects. Implementing these effects will improve the overall user experience and make the page visually appealing.

### Describe the solution you'd like.

- Button Hover Effects:

Add scaling and color change effects to the login button to create a more dynamic feel.

- Input Field Effects:

Implement hover effects on input fields (username, password) for better visual feedback.

### Describe alternatives you've considered.

Can you please assign me this issue also? 

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/ed490321-b69e-46fd-9903-82fdfdea30d8)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@neeru24 this issue was assigned before, you can check it on issues section.

**Comment by neeru24** [comment]
Okay, Should I wait for that assignee to submit a PR or what?

**Comment by vivekvardhan2810** [comment]
@neeru24 can you wait for now, till then you can contribute to other projects.

**Comment by neeru24** [comment]
Sure, Do let me know if I can contribute here also

**Comment by neeru24** [comment]
> @neeru24 assigned this issue to you.
> 
> Make sure to complete this.

Sure, any specific change you want??

**Comment by vivekvardhan2810** [comment]
@neeru24 for now it isn't any specific changes are required.

**Comment by neeru24** [comment]
> @neeru24 for now it isn't any specific changes are required.

will submit a PR by tomorrow
