### ISSUE TITLE
[Mention The Feature]: ADD NEW FONT TO THE WEBSITE 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#646]
### Is your feature request related to a problem? Please describe.

ADDING A NE FONT TO THE WEBSITE IT WILL HELP TO MAKE THE WEBSITE LOOK GOOD AND MORE ATTRACTICVE 

### Describe the solution you'd like.

https://github.com/user-attachments/assets/bc4592a1-698a-47a4-be5b-ac8b24aa7a6e

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HS202022 can you make the unique font for all the pages in the website.

**Comment by HS202022** [comment]
> @HS202022 can you make the unique font for all the pages in the website.
> 
> like i want the home page font for all the remaining pages in the website.

I HAVE MADE IT ALREADY
