### ISSUE TITLE
NO EFFECT OF DARKMODE IN CHATBOT 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#649]
### Description

the darkmode doesnt work for chabot 

### Steps to Reproduce

open chatbot and turn on dark mode 

### Expected Behavior

its should turn the color dark 

### Actual Behavior

its not changing 

### Screenshots

https://github.com/user-attachments/assets/1b6fa07d-0e87-4753-b0fb-a4a1a824571a

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HS202022 can you add the video.

i can't see it.

**Comment by HS202022** [comment]
> @HS202022 can you add the video.
> 
> i can't see it.

i have added

**Comment by vivekvardhan2810** [comment]
@HS202022 assign this issue to you.

make sure to complete it fast and do it properly.

**Comment by HS202022** [comment]
> @HS202022 assigned this issue to you.
> 
> make sure to complete it fast and do it properly.

I'm sorry you can close this issue because we can't edit the color of the bot it's directly injected from the website

**Comment by vivekvardhan2810** [comment]
Okay, I am closing this issue, and please do contribute to other projects also.
