### ISSUE TITLE
Create a new and interactive Login and Signin pages

### ISSUE THREAD

**Issue by yeshwanth-ds** [ML-Fusion-Lab/ML-Fusion-Lab-Website#65]
I would like to create a login in page and signin page to this project. A website like this must have this two page so that the registered people can have access to courses and project.

I propoes a clean and user friendly pages which also matches with the main page theme and design.

Would u assign me this task under gssoc-ext tag.

**Comment by vivekvardhan2810** [comment]
@yeshwanth-ds solution is Good.

But could share the screenshot of which one you are gonna update.

So that i can look and assign the issue to you.

**Comment by yeshwanth-ds** [comment]
@vivekvardhan2810 I would add new li in the nav bar and name it "Login" and another as "Signin" 
on click on any one of this would take you the respective login and signin page

I will add next to the contact block
![Screenshot 2024-10-02 120709](https://github.com/user-attachments/assets/6cf233ae-38df-404c-b632-12a17340ef9f)

**Comment by vivekvardhan2810** [comment]
Okay @yeshwanth-ds assigning this issue.

make sure to complete this issue for next 3 days.

**Comment by vivekvardhan2810** [comment]
@yeshwanth-ds why did you close the issue.

**Comment by yeshwanth-ds** [comment]
@vivekvardhan2810 This task hwas been compled and i was look to added new feture for this project to redue the risk of conflits i closed it.

**Comment by vivekvardhan2810** [comment]
Okay, can I close the PR also @yeshwanth-ds

**Comment by yeshwanth-ds** [comment]
@vivekvardhan2810 ok i shall work on new feature You can close

**Comment by vivekvardhan2810** [comment]
Yes
