### ISSUE TITLE
[Mention The Feature]:  Adding New Hover Effect In Footer

### ISSUE THREAD

**Issue by PrAyAg9** [ML-Fusion-Lab/ML-Fusion-Lab-Website#650]
### Is your feature request related to a problem? Please describe.

Actually it's not a problem, I just want an enhancement on the footer section by changing hover effect and background colour.

### Describe the solution you'd like.

![image](https://github.com/user-attachments/assets/a3ea0b13-7a04-4624-9630-25fbaa944928)
Look at this image when you will hover facebook it turns blue, for twitter (black) and insta (a nice gradient of red and pink) that's what i want to do.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@PrAyAg9 assigning this issue to you.

Make sure to complete it very fast.

As there are many footer issues before your issue.
