### ISSUE TITLE
Adding real time signup email and password fields validation!

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#653]
It shows a popup when user clicks on register button! 

i will add a functionality that shows on the page. and updates in real time.

assign me and add gssoc-ext with level3 and hacktober-accepted labels!

**Comment by vivekvardhan2810** [comment]
@smog-root assigning this issue to you.

make sure to complete this.

i can assign you level 2 for now, later i will look into the work and then Update it.

**Comment by smog-root** [comment]
@vivekvardhan2810 i'm really sorry! i tried to complete this task.

i got a lot of errors! the signup and login pages are in one file!

i'm just a beginner! sorry
