### ISSUE TITLE
Multiple `Glitches` And  `Bugs` Found in the website and in community support page.

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#655]
### Description

# I just  sync fork with latest commits and gone through the website these are the areas of improvement i found in the website:
## The email link on the contact page is not clickable; it should open directly into the email client.

![Screenshot 2024-10-15 173418](https://github.com/user-attachments/assets/4346eebf-a1b9-4fe4-8c1f-69ca701425c2)

## The subheading below the newsletter signup has non-uniform letters; some are dull, and some are bright.
![Screenshot 2024-10-15 173614](https://github.com/user-attachments/assets/1e514144-f8e2-42ab-bd8b-755d0902deff)
![Screenshot 2024-10-15 173620](https://github.com/user-attachments/assets/24efe2be-7f5b-466c-a3d0-ac473dfeb511)

## Tiles in the community support section are too bright in dark mode; they should be grey or a calmer color for better user experience.
![Screenshot 2024-10-15 173756](https://github.com/user-attachments/assets/e55cb80c-d4ae-4eb1-a568-41a04c721060)
- some color like this:
![Screenshot 2024-10-15 173817](https://github.com/user-attachments/assets/8175590f-5bf3-497b-a54f-ef6a5a9e8fdb)

## The Twitter X logo in the "join our forum" & mentor section is not clickable.
![Screenshot 2024-10-15 173921](https://github.com/user-attachments/assets/40c4a582-0d53-4144-88f3-82ba6d1a708a)

- Link in the `resource library` & `mentor program` are broken and not found.
- 
![Screenshot 2024-10-15 174139](https://github.com/user-attachments/assets/eeb2690e-2a2f-4c6f-8253-05d1b1204d56)
![Screenshot 2024-10-15 174203](https://github.com/user-attachments/assets/2047e743-cf7c-4d90-af40-19e35033d51b)

### Steps to Reproduce

@vivekvardhan2810 please assign me this task . 
(Kind Reminder : Due to some travel issues. I will be generating PR by 17 October 6pm . But i ensure you all my work will be synced to latest upto that time)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me this task .
(Kind Reminder : Due to some travel issues. I will be generating PR by 17 October 6pm . But i ensure you all my work will be synced to latest upto that time)

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

make sure to complete it within 2 days and make ensure that your  work will be synced to latest upto that time when you Create the Pull Request.
