### ISSUE TITLE
Border Radius of Subscribe Button is Not Perfect

### ISSUE THREAD

**Issue by ansiace** [ML-Fusion-Lab/ML-Fusion-Lab-Website#657]
### Description

The border radius of the "Subscribe" button is not visually consistent with the overall design, which impacts the user interface (UI) performance and aesthetic. A well-rounded border radius is essential for maintaining a clean and modern design.

### Steps to Reproduce

1. Navigate to the section with the "Subscribe" button.
2. Observe the button’s border radius and how it appears inconsistent with the rest of the design.

### Expected Behavior

The "Subscribe" button should have a smoother, more consistent border radius to enhance its appearance and make it more visually appealing.

### Actual Behavior

The "Subscribe" button has a border radius that looks off, making the button appear misaligned or inconsistent with other elements on the page.

### Screenshots

![Screenshot 2024-10-15 192650](https://github.com/user-attachments/assets/25ecb5b0-72a9-447d-b64c-20a34502c6ff)

### Additional Information

I am currently contributing as a participant in GSSoC'24 Extended Edition. I would like to kindly request a Level 1 tag for this contribution.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ansiace make sure to complete and resolve this very fast.

**Comment by ansiace** [comment]
Thank you for assigning this issue. I’ll prioritize it and work on resolving it as quickly as possible.
