### ISSUE TITLE
Improve background color and font styling for better readability

### ISSUE THREAD

**Issue by Swyom** [ML-Fusion-Lab/ML-Fusion-Lab-Website#658]
### Issue Description

 The current background color is very bright, making it difficult for users to read the text clearly, especially on the "About Us" section. Additionally, the font style/weight might need adjustment to improve visibility and make the overall design more accessible

### Additional Context

This issue affects accessibility and could result in a poor user experience, especially for users with visual impairments or in bright environments.

### Screenshots or Examples (if applicable)

![Screenshot from 2024-10-15 19-36-31](https://github.com/user-attachments/assets/9feb6853-1a13-4aca-a2a2-7eb45602a335)

### Proposed Solution (optional)

1.Change Background Color: Switch to a slightly darker or more neutral background color (such as #f0f0f0 or #e5e5e5) to improve contrast.
2.Update Font Style: Consider making the font bold or increasing the font weight. Additionally, ensure the font size is appropriately set for easy readability (e.g., 16px or higher).
3.Text Color: Increase the contrast between the text and background by using a darker text color (e.g., #333 or #222) to make the content more readable.

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
@Swyom assigning this issue to you.

make sure to complete this very fast.

as this is a small issue.

**Comment by Swyom** [comment]
Thanks for assigning me to this, I will finish it as soon as possible.

**Comment by AshishCh01** [comment]
Hey @vivekvardhan2810 Thank you for raising an issue I would love to review and contribute.

**Comment by vivekvardhan2810** [comment]
Sorry @AshishCh01 this issue was assigned before, so please look for other issues in website and then create new issue.

**Comment by vivekvardhan2810** [comment]
And @Swyom 

The Project Admin (me) of the ML Fusion Lab Won't be Available from Oct 28th and also this Project won't be active from Oct 28.

**Comment by vivekvardhan2810** [comment]
@Swyom have you done with this.

because it's been a week and no PR was created also.

please reply to this.

**Comment by NikitaKarmakarP** [comment]
I want to work in this issue Please assigned me

**Comment by sakthijaw** [comment]
Can you assign this project to me

**Comment by vivekvardhan2810** [comment]
Hi @Swyom ,

It’s been over a week without any updates. I will be closing this issue by the end of the day. If you have any progress to share, please do so before then.

Thank you!

**Comment by avinashkrsingh01** [comment]
sir can you assign this project to me.

**Comment by vivekvardhan2810** [comment]
as there is no response from your side, so i am closing this issue.

i hope you understand.

The Project Admin (me) of the ML Fusion Lab Won't be Available from Oct 26th and also this Project won't be active from Oct 26.
