### ISSUE TITLE
fixing alignment issues

### ISSUE THREAD

**Issue by aditya07389** [ML-Fusion-Lab/ML-Fusion-Lab-Website#659]
hey there 

I noticed that these buttons are not aligned properly and it looks ugly
![image](https://github.com/user-attachments/assets/bdb8bad3-0fe2-42c5-914a-1eeaf84793b8)

i would like to fix this

assign this to me under gssoc extd , hacktoberfest pleas

**Comment by aditya07389** [comment]
can u added level 2 pls

**Comment by aditya07389** [comment]
thankyou !! sure ill raise the pr soon

**Comment by vivekvardhan2810** [comment]
@aditya07389 make sure to complete it.

**Comment by aditya07389** [comment]
yeah , can i raise the pr by tom ?

**Comment by aditya07389** [comment]
Okay fine

**Comment by aditya07389** [comment]
Thanks
