### ISSUE TITLE
background image on home tab not visible in other tabs 

### ISSUE THREAD

**Issue by Iampratyush004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#66]
background image on home tab not visible in other tabs and the logo only visible on home tab and not other tabs. 
The logo that i have changed in home tab of issue#40 needs changes that reflect in every other tab of the website , also the background image of the home tab is not visible on the other tabs .

i have a ready code , please assign me to this task. I have to just pull request the code.
@vivekvardhan2810 
please tag hacktober fest and gssoc-extd
thanks

**Comment by vivekvardhan2810** [comment]
@Iampratyush004 can you share the screenshots.

**Comment by Iampratyush004** [comment]
![Screenshot 2024-10-02 125613](https://github.com/user-attachments/assets/92b212f5-f588-49cc-86ea-357887216220)
yes sure sir @vivekvardhan2810

**Comment by Iampratyush004** [comment]
![Screenshot 2024-10-02 125740](https://github.com/user-attachments/assets/c65cdb0e-ef6c-4d0e-ac72-23f0a5ada3a8)
yes sir sure @vivekvardhan2810

**Comment by Iampratyush004** [comment]
kindly assign this to me

**Comment by vivekvardhan2810** [comment]
Okay I will assign you soon @Iampratyush004 . as i have some conflicts i will resolve and i will tell you.
