### ISSUE TITLE
[DOCS] <write your suggestion here>add more courses that are free from ibm 

### ISSUE THREAD

**Issue by Anu142004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#662]
### Issue Description

i want to add more courses in the course section to enhance more users in the website as the free course can be accessed by any one .

### Additional Context

more data to be added in the course section

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
for now the number of courses required is okay for now, we will look into this later.

so i am closing this issue.

please understand.

**Comment by Anu142004** [comment]
Ok
