### ISSUE TITLE
ML Fusion Labs Logo in Navbar Should Be Centered

### ISSUE THREAD

**Issue by ansiace** [ML-Fusion-Lab/ML-Fusion-Lab-Website#665]
### Description

The ML Fusion Labs logo in the navbar is not currently centered, which impacts the visual balance and user interface. For a cleaner and more professional appearance, the logo should be centered to improve the overall layout.

### Steps to Reproduce

1. Navigate to any page with the navbar.
2. Observe that the ML Fusion Labs logo is not centered.

### Expected Behavior

- The ML Fusion Labs logo should be horizontally centered in the navbar for a balanced and consistent design.

### Actual Behavior

- The ML Fusion Labs logo is misaligned in the navbar and does not appear in the center, disrupting the visual harmony of the navigation bar.

### Screenshots

![image](https://github.com/user-attachments/assets/fe533e35-7784-4b12-881f-f03b01d0c6d6)

### Additional Information

I am currently contributing as a participant in GSSoC'24 Extended Edition. I would like to kindly request a Level 1 tag for this contribution.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ansiace assigning this issue to you.

make sure to complete this very fast.
