### ISSUE TITLE
the navbar can be changed to look 

### ISSUE THREAD

**Issue by Anjalis14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#666]
### Is your feature request related to a problem? Please describe.

the current navbar dosent look good

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.

for now the navbar is okay, we don't require any updates.

please understand.
