### ISSUE TITLE
[Mention The Feature]: Improve Footer Design and Usability

### ISSUE THREAD

**Issue by amanver45** [ML-Fusion-Lab/ML-Fusion-Lab-Website#667]
### Is your feature request related to a problem? Please describe.

The current footer design lacks consistency and visual appeal. The social media icons are not uniform, the text lacks proper alignment and emphasis, and the overall user experience could be enhanced with some layout and interactive improvements.

### Describe the solution you'd like.

We need to enhance the current footer design to improve both its visual appeal and functionality. Below are the suggested changes:

1. **Social Media Icons**:
   - Standardize the size and spacing between the social media icons.
   - Use color variants for icons (e.g., blue for Facebook, black for X, blue for LinkedIn, etc.) to make them more noticeable.
   
2. **Text Alignment**:
   - Increase font size for the contact information and ensure it stands out from the legal links.
   - Maintain consistent padding and margins around the footer content for better readability.

3. **Copyright Section**:
   - Centralize the copyright information and consider adding a separator line for a more structured look.

4. **Interactivity**:
   - Ensure all links, social icons, email, and phone number are clickable and add hover effects (e.g., color change or slight size increase) for a better user experience.

5. **Background and Contrast**:
   - Explore adding a gradient effect or a subtle texture to the dark gray background for more depth.
   - Optionally, lighten the text links slightly to improve contrast.

6. **Chat/Support Button Placement**:
   - Align the chat and up arrow buttons closer to the footer or place them in a separate section with background shadows for better visibility.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by amanver45** [comment]
@vivekv2810 yes i fix this by 12

**Comment by vivekvardhan2810** [comment]
@amanver45 i will let you know as some of them raised the footer and copyright and social media icon issue before, if they completes it i will close this issue.

if they don't complete it, then i will let you know.

**Comment by vivekvardhan2810** [comment]
As i have said before they have completed the footer based issue and resolved it.

so i am closing this issue.

please understand and don't get discouraged.
