### ISSUE TITLE
[Scrollbar Styling]: Adding hovering effects

### ISSUE THREAD

**Issue by richa-k23** [ML-Fusion-Lab/ML-Fusion-Lab-Website#669]
### Is your feature request related to a problem? Please describe.

It is no specifically related to a problem. Although, my feature can improve the UI of your webpage.

### Describe the solution you'd like.

I would like to add hovering effects to the scrollbar of the webpage.
That is, when we hover over the scrollbar it changes into a visually appealing color for better user satisfaction.

### Describe alternatives you've considered.

I can also use the gradient effect on the scrollbar. (If and only if it looks good, or else I will drop this idea)

### Additional context.

Kindly add 3 labels (mentioned below) if you consider assigning me this issue -

- gssoc-ext
- hacktoberfest-accepted
- the "level" label

### Show us the magic with screenshots

(This snapshot is not the actual changes I will make, this is only for reference)

https://github.com/user-attachments/assets/fb4bb767-6f64-4d98-bbf0-3adcf29d9fa4

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@richa-k23 you just want to work with only on scrollbar styling

is it.

**Comment by vivekvardhan2810** [comment]
Hello @richa-k23, this is a very good feature, but according to our website, it will not look good. 

So i am closing this issue.

please understand.
