### ISSUE TITLE
DARK THEME FUNCTIONALITY TOGGLE SWITCH 

### ISSUE THREAD

**Issue by STDYGIT** [ML-Fusion-Lab/ML-Fusion-Lab-Website#67]
would like to implement a comprehensive dark theme for your website, recognizing the growing number of users who prefer this aesthetic for their daily tasks. I can customize the design using an appropriate color palette to enhance user experience and accessibility.

below are the switch toggle have a look
![Screenshot 2024-10-02 at 12 44 47 PM](https://github.com/user-attachments/assets/24ca5788-3a2e-4308-9623-0f1ee248e693)
![Screenshot 2024-10-02 at 12 44 31 PM](https://github.com/user-attachments/assets/49294b7d-1fe0-440f-b8f2-3e9bc5dae58a)

**Comment by STDYGIT** [comment]
Sir @vivekv2810 , I would like to work on this feature and would appreciate it if you could assign it to me for Hacktoberfest and GGSOC '24. I believe this is a level 2 task, as it requires a complete overhaul of the page styles. Thank you!

**Comment by vivekvardhan2810** [comment]
Okay @STDYGIT, 

Assigning this issue to you.

make sure to complete this issue for the next 3 days.

and i can't give you the label of hacktoberfest (as this project didn't registered for hacktoberfest).

and also join the discord channel: https://discord.gg/FZxBRpTEeH for the further communication and updates.
