### ISSUE TITLE
DARK MODE NOT WORKING 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#671]
### Description

dark mode button is irresponsive 

### Steps to Reproduce

click the the dark mode toggle 

https://github.com/user-attachments/assets/f1a26b0a-bd89-46b1-adf5-2a237263ae0c

### Expected Behavior

It must work 

### Actual Behavior

its not working 

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HS202022 can you fix this in all pages.

because it is not coming on all pages.

**Comment by HS202022** [comment]
> @HS202022 can you fix this in all pages.
> 
> because it is not coming on all pages.

yes

**Comment by vivekvardhan2810** [comment]
Okay @HS202022 assigning this issue to you.

make sure to complete this.

and update it.

**Comment by vivekvardhan2810** [comment]
@HS202022 i have updated the code,

now the light and dark mode toggle is working.

**Comment by vivekvardhan2810** [comment]
@HS202022 work on it.

**Comment by HS202022** [comment]
> @HS202022 work on it.
someone remove all the js files and also this 
![Screenshot 2024-10-16 002725](https://github.com/user-attachments/assets/ba18cf94-4cda-4d93-99b9-ad07976199fc)
![image](https://github.com/user-attachments/assets/ae334d55-7c0b-4dfa-8124-fdf5ab5323a0)

**Comment by vivekvardhan2810** [comment]
yes, they have removed the courses cards also.

**Comment by HS202022** [comment]
shall i restore the js files?

**Comment by vivekvardhan2810** [comment]
@HS202022 yes you can restore the js files also.

i will update the level also.
