### ISSUE TITLE
[BUG] : Scroll to Top issue in project page

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#675]
### Description

The "Scroll to Top" button is not functioning properly on the crop height using computer vision's project page. When users scroll down the page, the button does not appear, making it inconvenient to quickly navigate back to the top.

### Expected Behavior
The "Scroll to Top" button should appear after users scroll down a certain distance and, when clicked, should smoothly scroll the page back to the top.

### Steps to Reproduce

1. Visit the project page.
2. Scroll down.

### Screenshots

https://github.com/user-attachments/assets/cea1a71a-9f80-40de-8323-a14634f43f1f

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
yes, got it.

@IkkiOcean assigning this issue to you.

make sure to complete this.
