### ISSUE TITLE
In testimonials page there is a text invisibility issue in dark mode 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#677]
### Description

In testimonials page there is a text invisibility issue in dark mode 

### Steps to Reproduce

In testimonials page there is a text invisibility issue in dark mode 

### Expected Behavior

It must be visible 

### Actual Behavior

not visible 

### Screenshots

https://github.com/user-attachments/assets/e794997b-7789-4d6e-b0eb-799bbc14f3eb

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HS202022 assigning this issue to you.

and make sure to complete this.

**Comment by vivekvardhan2810** [comment]
@HS202022 do you have the photos of these ones

![image](https://github.com/user-attachments/assets/c7ecffe3-cf3a-4595-aabf-6debba3d91b5)

if you have it can you add it.

**Comment by HS202022** [comment]
> @HS202022 do you have the photos of these ones in course page. As it is not there in that page right now.
> 
> ![image](https://private-user-images.githubusercontent.com/91594529/376762118-c7ecffe3-cf3a-4595-aabf-6debba3d91b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMjEyNjMsIm5iZiI6MTcyOTAyMDk2MywicGF0aCI6Ii85MTU5NDUyOS8zNzY3NjIxMTgtYzdlY2ZmZTMtY2YzYS00NTk1LWFhYmYtNmRlYmJhM2Q5MWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDE5MzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwMjI3MDBkMTc2ZjBhOThkYTU4ZDI5NjE0ODBiY2ViZjFiZDYzNGZhN2FlMWFkYjhmN2U3ODM2OTc2Y2I3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YecWsX5kfynROGDZyOvVV4JGqwozKi3ArmaRYoFG42s)
> 
> if you have it can you add it.

can i add these?

**Comment by vivekvardhan2810** [comment]
@HS202022 you can create a new issue, i will assign this.
