### ISSUE TITLE
[Mention The Feature]: addition of pictures in the empty section 

### ISSUE THREAD

**Issue by HS202022** [ML-Fusion-Lab/ML-Fusion-Lab-Website#680]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/70269f50-2e97-4cb2-87e8-dd89009e4aac)

### Describe the solution you'd like.

i can add the pictures 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HS202022 assigning this issue to you.

Make sure to complete this.
