### ISSUE TITLE
[Mention The Feature]: fixing the courses page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#682]
### Is your feature request related to a problem? Please describe.

i can fix the bugs of of this page.

### Describe the solution you'd like.

<img width="1031" alt="Screenshot 2024-10-16 at 1 54 05 AM" src="https://github.com/user-attachments/assets/ee8b593b-7a14-4f28-9d4e-2ea9ce12cb35">

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigning this issue to you.

make sure to complete this.
