### ISSUE TITLE
[Mention The Feature]: fixing Contibutors page

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#684]
### Is your feature request related to a problem? Please describe.

the dark mode is missing in the page and the page is not aligned , i can fix the UI and more all the alignments.

### Describe the solution you'd like.

![Screenshot 2024-10-16 at 2 12 35 AM](https://github.com/user-attachments/assets/be4ec8db-c9c8-4e70-ad60-16fd4ac6a7ee)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigning this issue to you.

make sure to complete it.
