### ISSUE TITLE
Navbar Enhancement and Alignment Corrections

### ISSUE THREAD

**Issue by AnushkaChouhan25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#687]
The navbar currently has alignment issues, and the items are not displayed in a line with proper formatting. Additionally, the background of the navbar needs to be removed to improve visibility and aesthetics.

#### Proposed Changes:

- Ensure all items in the navbar are aligned properly in a single line. 
- Apply consistent padding and margin to each navbar item for a balanced appearance.
- Ensure that the font size and style are uniform across all items.
- Remove or adjust the background color of the navbar to provide a cleaner look and better visibility of the items.

![image](https://github.com/user-attachments/assets/a8798112-7b4f-4ed4-82d9-af88fcbe9261)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.
