### ISSUE TITLE
[Mention The Feature]: i want to add a tutorial regarding waste management optimization project in project page website.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#688]
### Is your feature request related to a problem? Please describe.

i have waste mangaement optimization project , and i would like to add it here.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 assigning this issue to you.

Make sure to complete it

make sure to create these tutorials without disturbing any other elements.

Since there html contains different divs and tags the css is conflicting and causing these issues.

so do it carefully.

**Comment by T-Rahul-prabhu-38** [comment]
@vivekvardhan2810 im sorry im not able to find my files for this , can you please assign this to someone else
