### ISSUE TITLE
[DOCS] Add more info button under each course

### ISSUE THREAD

**Issue by Mahima-2404** [ML-Fusion-Lab/ML-Fusion-Lab-Website#689]
### Issue Description

Add more info button under each course .By clicking the button, pages will be opened where description and content of the courses will be given.

### Additional Context

Please assign me this issue

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
I think when you click the courses card directly it redirects to the page and there isn't any requirement for more info button under each courses.

So I am closing this issue, please understand.
