### ISSUE TITLE
[Mention The Feature]: Header alignment and styling improvements

### ISSUE THREAD

**Issue by Rohinipilla** [ML-Fusion-Lab/ML-Fusion-Lab-Website#690]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/63ed80a3-0148-4774-8ccd-75a26b7f3e35)
The header section of the website is currently taking up too much vertical space and needs optimization. The elements (logo, navigation links, and language switcher) are not aligned properly on a single line, which results in inefficient use of space. 

### Describe the solution you'd like.

The ideal solution would involve redesigning the header to ensure all elements are aligned in a single horizontal row, while maintaining a clean and responsive layout.

### Describe alternatives you've considered.

1.Two-line Header Layout
2.Dropdown Navigation Menu

### Additional context.

The website is designed for a tech community platform (ML Fusion Labs) that includes multiple sections like Courses, Projects, Community Support, etc. Therefore, easy access to these sections through a well-organized and compact header is crucial.

The current header design, which spans more vertical space than needed, is negatively impacting the user experience by pushing the main content further down on the page. A compact, sleek design will allow users to engage with the site content more quickly without excessive scrolling.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/4ff58c5f-aa5a-4c65-a18d-82b54dd6c803)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Rohinipilla** [comment]
Assign this issue to me. i really want to work upon it

**Comment by sayednowshad** [comment]
yeah i want to solve this issue please assign me this issue to me i can do better

**Comment by sayednowshad** [comment]
**Yeah I solved It you can check it out**

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.

and already it is in updation, so please understand.
