### ISSUE TITLE
Tems Page not good looking for user Experience 

### ISSUE THREAD

**Issue by sayednowshad** [ML-Fusion-Lab/ML-Fusion-Lab-Website#692]
### Is your feature request related to a problem? Please describe.

Yes , it is related .

### Describe the solution you'd like.

I can is that font size like header and background color with good user experience with supported dark mode 

### Describe alternatives you've considered.

i won't disturb the other content 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by sayednowshad** [comment]
Before 👍 

![Screenshot 2024-10-16 091050](https://github.com/user-attachments/assets/317c0e5a-5537-4691-869d-c24fd0251472)
![Screenshot 2024-10-16 091058](https://github.com/user-attachments/assets/8e5ffdef-eef8-4f7e-a982-55886aaddeb8)

After 💯 : 

![Screenshot 2024-10-16 094635](https://github.com/user-attachments/assets/77310307-4613-4e46-9e4d-407719d0a223)
![Screenshot 2024-10-16 094642](https://github.com/user-attachments/assets/c31cb803-ceec-4dbf-8ce0-f5994acf5191)

**Comment by vivekvardhan2810** [comment]
For now terms page is okay and don't require any improvements.

So I am closing this issue.

Please understand.
