### ISSUE TITLE
Scroll to button is showing when we are present on the top of the website 

### ISSUE THREAD

**Issue by YasirKhan231** [ML-Fusion-Lab/ML-Fusion-Lab-Website#694]
### Description

The scrool to top of the website button are present when we are on the top so it should be remove from the webite when we are on the  top 

### Steps to Reproduce

Do some chnages on the code of the button 

### Expected Behavior

Then when we go down then the button is showing 

### Actual Behavior

When we pressnt on top of  the webiste then also it is present 

### Screenshots

![image](https://github.com/user-attachments/assets/786ee3ef-04fd-4f91-bf75-a2b94ee8a2b4)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Not something we are looking for it.

Please understand.
