### ISSUE TITLE
[ Links are not showing proper ]: 

### ISSUE THREAD

**Issue by YasirKhan231** [ML-Fusion-Lab/ML-Fusion-Lab-Website#696]
### Is your feature request related to a problem? Please describe.

The footer link are showing properly on the footer beacasue of the wrong color of the link 

### Describe the solution you'd like.

I chnage the background color of the links and test the color if should remocve the underline from the links 

### Describe alternatives you've considered.

If alternative are present in that then try to solve by the best method

### Additional context.

No

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/15c97abb-9fff-4f17-ae5b-64d41956568e)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
not something we looking for.

Please understand.
