### ISSUE TITLE
Updating Pop description with projects

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#697]
### Description

the pop up is not matching project titles

### Steps to Reproduce

not updating projects.html concurrently

### Screenshots

https://github.com/user-attachments/assets/988e0cb9-503b-4bfc-8c2c-47d4ee3495a0

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 what's your solution on this

Please tell it.

So that I can check and assign you.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.

**Comment by DarshAgrawal14** [comment]
already dine , submitting pr now

**Comment by vivekvardhan2810** [comment]
Resolve the conflicts in pull request.

**Comment by DarshAgrawal14** [comment]
@vivekvardhan2810  resolved
