### ISSUE TITLE
[Mention The Feature]:  Add complete tutorial page for  COVID19 facemask (Computer vision) detection in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#699]
### Is your feature request related to a problem? Please describe.

Develop a deep learning model to detect whether the person is wearing a facemask or not . This model can be used in hospitals as well as clean room monitoring where it is necessary to wear a facemask . This is necessity in all industries where sanitation is required 

### Show us the magic with screenshots

https://github.com/user-attachments/assets/c7d51f0e-9e58-4972-ac49-4008d47b17a1

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.
