### ISSUE TITLE
Improve Home Page

### ISSUE THREAD

**Issue by Nandini-13** [ML-Fusion-Lab/ML-Fusion-Lab-Website#7]
Design of the home page can be made better. About section requires better padding.
![1](https://github.com/user-attachments/assets/129afb5a-f85d-4ec0-825c-e18c3267cf04)

Kindly assign this issue to me so that I can start working on it

**Comment by vivekvardhan2810** [comment]
@Nandini-13 assigned to you.

**Comment by Codewithmeowmeow** [comment]
Kindly assign me this issue i would love to work on this.

**Comment by vivekvardhan2810** [comment]
Hi, @Codewithmeowmeow , as this issue was presented by other user, so it will be first on first serve, if that user doesn't do this work

Then I will assign you the issue.

But still you can look out for other issues at website like improvements.

And create a new issue

**Comment by vivekvardhan2810** [comment]
make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH
