### ISSUE TITLE
not all cards have same length 

### ISSUE THREAD

**Issue by SATYAM0LUFFY** [ML-Fusion-Lab/ML-Fusion-Lab-Website#700]
### Description

all cards in courses section are not off same length 

### Steps to Reproduce

https://ml-fusion-lab.netlify.app/pages/courses  

### Expected Behavior

all card for courses must be of same size 

### Screenshots

![Screenshot (840)](https://github.com/user-attachments/assets/9abc3bc2-701b-4711-b358-39ce5ce4d375)

### What browser are you seeing the problem on?

- [x] Firefox
- [x] Chrome
- [x] Safari
- [x] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
i think it occurs due to the zoom size.

but from my side it is looking good

![image](https://github.com/user-attachments/assets/fa0dbbd4-c409-4a9b-93a4-a7c18c8408c3)

we will look for this later

so i am closing this issue.

please understand and don't get discouraged.
