### ISSUE TITLE
Logo in the courses page is not completely visible.

### ISSUE THREAD

**Issue by rakheshkrishna2005** [ML-Fusion-Lab/ML-Fusion-Lab-Website#702]
### Description

# I have noticed that the company logo of the course provider is not completely visible.

### Steps to Reproduce

Modify the css in `course.css` file.

## Expected Logo Visibility
![Expected Logo Visibility](https://github.com/user-attachments/assets/3b5fae9f-24b8-4d74-b2e0-fa1cb123bd5c)

## Actual Logo Visibility
![Actual Logo Visibility](https://github.com/user-attachments/assets/8eef59e5-a217-4435-ba4a-fbf35d50b846)

### Please assign this to me. Thanks for consideration!
Labels: `gssoc-extd`, `hacktoberfest-accepted` and level

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@rakheshkrishna2005 assigning this issue to you.

make sure to complete this very fast.

**Comment by rakheshkrishna2005** [comment]
Thank you. I have created a pull request with the changes mentioned above.
