### ISSUE TITLE
Alignment issue on Nav bar

### ISSUE THREAD

**Issue by chamaneth** [ML-Fusion-Lab/ML-Fusion-Lab-Website#703]
I would like to enhance the nav bar

![image](https://github.com/user-attachments/assets/43377955-e1d8-4011-9548-e875e2cc1dec)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before, please understand.
