### ISSUE TITLE
Improving Contact Page

### ISSUE THREAD

**Issue by chamaneth** [ML-Fusion-Lab/ML-Fusion-Lab-Website#705]
### Issue Description

Alignment of the contactpage has to improve more

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/f08e3508-aa75-4d84-a937-963e57e71f5f)

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
for now it is looking good and don't want any improvements in contact form for right now.

and some of the issues regarding this page was assigned before.

so i am closing this issue.

Please understand.
