### ISSUE TITLE
[Navbar]: Changing the style and look of the navbar.

### ISSUE THREAD

**Issue by Kritika745** [ML-Fusion-Lab/ML-Fusion-Lab-Website#706]
### Is your feature request related to a problem? Please describe.

Hey @vivekvardhan2810 I think the navbar would look much better if we change its styling and the user experience of the website would get enhanced.

### Describe the solution you'd like.

I would suggest more sleek and light colored navbar for day mode and dark colored navbar for dark mode.

### Additional context.

![Screenshot 2024-10-16 202007](https://github.com/user-attachments/assets/02de0e55-880c-4333-9cab-3ed5f5115ded)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes were happened many times.

Please understand.
