### ISSUE TITLE
Inaccurate Course Listings on ML Fusion Lab

### ISSUE THREAD

**Issue by snehhhcodes** [ML-Fusion-Lab/ML-Fusion-Lab-Website#708]
### Is your feature request related to a problem? Please describe.

The ML Fusion Lab website claims to offer free content for users looking to learn about machine learning and artificial intelligence. However, upon reviewing the course offerings, it appears that all the courses listed are provided by IBM, and every one of them is paid. This misrepresentation may lead to user dissatisfaction and could damage the website's credibility as a source of free learning resources.

### Describe the solution you'd like.

I propose that we remove the paid course listings from the website and instead curate a collection of free courses available on YouTube. By providing links to relevant playlists, users can be directly redirected to these resources, enabling them to access high-quality, free content. This solution will enhance user experience and ensure that the website maintains its commitment to offering genuinely free educational material.

### Describe alternatives you've considered.

An alternative would be to keep the current paid courses alongside a few free resources; however, this could still lead to confusion for users who may not fully understand which resources are free and which are not. By solely focusing on free content, we eliminate this potential issue and streamline the learning experience. Another consideration could be to add a filter option for free vs. paid courses, but this may require additional development work and could still complicate the user experience.

### Show us the magic with screenshots

![Screenshot 2024-10-16 211323](https://github.com/user-attachments/assets/a245fce6-fb7d-4ba1-b3bc-8ff773847cf5)
![Screenshot 2024-10-16 212156](https://github.com/user-attachments/assets/d0c69097-0847-40bc-933d-2a7f06e2c505)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
thank you for creating this issue, for now we don't want any changes in courses page, as we have kept the paid courses only for the basic just to have a glimpse and we will for the course page enhancement later.

So i am closing this issue, Please Understand.
