### ISSUE TITLE
adjust the page, 

### ISSUE THREAD

**Issue by shruti9935** [ML-Fusion-Lab/ML-Fusion-Lab-Website#709]
### Description

page is not fix,moving plus when we click for large tab it size increases

### Steps to Reproduce

in css we can go where we wrote the code then adjust - fixed not flex ig this will work

### Additional Information

assigne me  include me in hacktober fest gssoc

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
i didn't get it, please explain it.
