### ISSUE TITLE
Scroll up button speed

### ISSUE THREAD

**Issue by sriraghavi22** [ML-Fusion-Lab/ML-Fusion-Lab-Website#71]
The "scroll to top" button currently scrolls up too quickly, making it difficult for users to have a smooth navigation experience. The scroll action occurs at a speed that feels abrupt and unnatural.

https://github.com/user-attachments/assets/f06fdf00-468d-41d8-bd9e-eaca49bd1a1f

The scroll-to-top button should scroll back to the top of the page smoothly and gradually, enhancing the user experience by providing a more controlled scroll speed.

I would like to work on this. Can you assign it to me?

**Comment by vivekvardhan2810** [comment]
@sriraghavi22 speed is ok, can you improve the UI of the button.

**Comment by sriraghavi22** [comment]
Okay i will work on that

**Comment by Raj-Aditya-27** [comment]
Hi @vivekvardhan2810 

I just went through this website and noticed that the "Back to Top" button moves rapidly to the top, which is not pleasing for user experience. Please assign this issue to me, and I can fix it.

You can refer to my previous project where I implemented a more user-friendly "Back to Top" functionality.
https://raj-aditya-27.github.io/SarvottamSamachar/
