### ISSUE TITLE
[DOCS] Wanted To Make Some Enhancements In The contribute.md File

### ISSUE THREAD

**Issue by milansamuel609** [ML-Fusion-Lab/ML-Fusion-Lab-Website#711]
### Issue Description

1) Instructions are not been perfectly aligned and not in a well structured manner.
2) Some code snippets were labeled with the wrong programming language (e.g., using css for git commands).
3) The instructions for committing changes were somewhat unclear and lacked detail regarding co-authors and may sometimes lead to confusion.
4) The original document could be seen as less inviting, lacking encouragement for non-developers or non-coders to contribute.

### Screenshots or Examples (if applicable)

![image](https://github.com/user-attachments/assets/0fcd795f-cc54-483e-bdca-aab521e8b0bd)

### Proposed Solution (optional)

I can fix all the issues mentioned in the issues section and also can add some more sections which can engage the non-developers also. Please kindly assign me this issue and I will try to do my best to make the contributing.md file more easy to be readable and understandable.  Also please kindly assign the gssoc extend label.

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't any readme and contributing.md changes.

so i am closing this issue.

please understand.

And please don't get discouraged with this.
