### ISSUE TITLE
Implement Search Bar and Language Dropdown Selection

### ISSUE THREAD

**Issue by sriharsha0x1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#712]
### Is your feature request related to a problem? Please describe.

I will improve UI by adding a search bar and a dropdown menu for selecting languages in project. This feature will enhance user experience and accessibility.

Could you please assign this issue to me? I am eager to work on it.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/9eb7770a-0ee0-4218-9f86-c93b8a77140c)

i would like to change:
EXAMPLE:
![image](https://github.com/user-attachments/assets/3b807f33-1b82-4b79-80b2-384641fd5fb6)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
thank you for raising this issue, but we don't want to require the further improvements in language translation.

so i am closing this issue.

Please understand and don't get discouraged.
