### ISSUE TITLE
Wanted to improve footer design on the website

### ISSUE THREAD

**Issue by akshattiwarii** [ML-Fusion-Lab/ML-Fusion-Lab-Website#713]
### Is your feature request related to a problem? Please describe.

No problem in the footer but it is not attractive as I wanted 

### Additional context.

Assign this task to me if you wanted to change footer design !

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@akshattiwarii can you make the footer like this.

![image](https://github.com/user-attachments/assets/da2631b8-d910-431e-b4a7-4de9652e766c)

for all the pages in website.

**Comment by akshattiwarii** [comment]
yes sure

**Comment by vivekvardhan2810** [comment]
And do it properly.
