### ISSUE TITLE
[Mention The Feature]:  fixing Ui in home page.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#714]
### Is your feature request related to a problem? Please describe.

UI fix required in homepage.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 make sure to complete this.
