### ISSUE TITLE
[Mention The Feature]: Add the bloging section for the new one for the guidance and motivational.

### ISSUE THREAD

**Issue by ykchoudhary110** [ML-Fusion-Lab/ML-Fusion-Lab-Website#717]
### Is your feature request related to a problem? Please describe.

Student sometimes lakes motivation to learn as they didn't get instant result.

### Describe the solution you'd like.

We should allow the people to share there blogs so that it could help the new person or guide them for continuing their journey and be always motivated.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was assigned before and he is doing this.

so i am closing this issue.

Please understand.

**Comment by ykchoudhary110** [comment]
Thankyou for the information
Have a great day
