### ISSUE TITLE
Overlapping Project post cards

### ISSUE THREAD

**Issue by xenomancy** [ML-Fusion-Lab/ML-Fusion-Lab-Website#718]
### Description

On the projects page, the project cards tend to overlap due to insufficient padding or spacing between them. This makes navigation and visibility difficult. Adding appropriate padding or margins between the cards will enhance the layout and ensure responsiveness.

### Steps to Reproduce

To reproduce the issue of overlapping project cards:

1. Open the webpage with project cards.

2. Reduce the browser window size to trigger responsive design issues.

3. Observe that the cards overlap due to insufficient padding or spacing.

4. Inspect the CSS to verify the missing or inadequate grid/flexbox layout.

This will demonstrate the cause of the overlap issue.

### Expected Behavior

Responsive grid layout.

### Actual Behavior

Cards overlapping visually.

### Screenshots

![IMG_20241017_001006](https://github.com/user-attachments/assets/5aa58c2d-dcc5-471b-b437-02f9d0a6689e)

### Additional Information

please assign me this task 

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
as the project page is updating slowly, we will look for overlapping issue later.

so i am closing this issue.

Please Understand.
