### ISSUE TITLE
[FEAT]: Adding tutorial for using Transfer Learning Models Like InceptionV3, VGG16 model, InceptionResNetV2 in projects page website.

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#719]
### Is your feature request related to a problem? Please describe.

I would like to add a tutorial that demonstrates how to use transfer learning models, specifically **InceptionV3**, **VGG16**, and **InceptionResNetV2**.
I will be using Bird Species Dataset to demonstrate the following tasks in the tutorial

### Describe the solution you'd like.

- **Objective**: To guide users through the process of implementing transfer learning with these models for classifying different bird species.
- **Content**:
  1. Introduction to Transfer Learning
  2. Overview of each model (InceptionV3, VGG16, InceptionResNetV2)
  3. Dataset preparation and preprocessing
  4. Step-by-step implementation for each model
  5. Evaluating model performance
  6. Conclusion and potential next steps

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@IkkiOcean assigning this issue to you.

Make sure to complete this.
