### ISSUE TITLE
[Header UI Enhancement]: Chnages in UI of header nav buttons

### ISSUE THREAD

**Issue by rakheshkrishna2005** [ML-Fusion-Lab/ML-Fusion-Lab-Website#723]
### Is your feature request related to a problem? Please describe.

The header is little big and then during the border radius of the nav buttons is not the same when hovered and not hovered.

### Describe the solution you'd like.

I have modified the `index.html` and `style/styles.css` to adjust the height of the header and the looks of nav buttons.

### Show us the magic with screenshots

Before:
![Screenshot 2024-10-17 022741](https://github.com/user-attachments/assets/cb31e0aa-d352-4d02-b67c-b428b59bf7f3)

After:
![Screenshot 2024-10-17 023020](https://github.com/user-attachments/assets/9b63d84e-189f-46a6-a695-52c4f12b5603)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

please understand.

**Comment by rakheshkrishna2005** [comment]
Ok, Thanks for the information 👍
