### ISSUE TITLE
Website is not responsive. 

### ISSUE THREAD

**Issue by royvivi29** [ML-Fusion-Lab/ML-Fusion-Lab-Website#726]
### Is your feature request related to a problem? Please describe.

Yes, my feature request is related to a problem. The website is not responsive, meaning it doesn't adjust properly across different screen sizes (mobile, tablet, desktop). This affects user experience, as the layout and functionality break or become difficult to navigate on smaller devices.

### Show us the magic with screenshots

![Screenshot 2024-10-17 082317](https://github.com/user-attachments/assets/66577ad3-440e-434e-92df-f20f685dbe52)
![Screenshot 2024-10-17 082332](https://github.com/user-attachments/assets/ee0239fd-5091-422d-b290-a50a92ca3844)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
What's your solution on this, like how do you rectify this.

Please explain.

**Comment by royvivi29** [comment]
I will make the website responsive by changing the code of CSS.

**Comment by royvivi29** [comment]
Can I have a chance to work on making it responsive?

**Comment by vivekvardhan2810** [comment]
for now the responsive is not required, you can look for other issues in website, then create an new issue.
