### ISSUE TITLE
[Mention The Feature]: Implement Toast Notification and Auto-Navigation for Sign Up Button

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#727]
### Is your feature request related to a problem? Please describe.

i think when clicked on signup through toast-notification system it should take to signup page displaying message navigating to sign up page something like that. as that is not functional right now i want to make this modifications

![image](https://github.com/user-attachments/assets/9d2a64cb-d9d2-470a-a00f-f1294dc5cada)

### Describe the solution you'd like.

To improve the user experience, I'd like to modify the current system so that when the "Sign Up" button is clicked, instead of showing a basic alert, a toast notification appears. The toast should display a message such as "Navigating to Sign Up page..." and then redirect the user to the signup page after a brief delay.

Proposed Modifications:
Toast Notification: Implement a toast notification system to inform users that they are being redirected to the signup page.
Navigation Delay: Once the "Sign Up" button is clicked, show the toast message and automatically navigate to the signup page after a few seconds.
Non-intrusive Experience: The toast should appear smoothly, enhancing the user experience without disrupting the page flow.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ananyag309 assigning this issue to you.

Make sure to complete this within 2 days.
