### ISSUE TITLE
[Mention The Feature]: add a faq section at footer 

### ISSUE THREAD

**Issue by ananyag309** [ML-Fusion-Lab/ML-Fusion-Lab-Website#728]
### Is your feature request related to a problem? Please describe.

beside here i am willing to add faq section at footer. To enhance user experience and provide quick answers to common queries, a FAQ (Frequently Asked Questions) section should be added to the footer of the website. This section will serve as a resource for users to find information without having to navigate away from the page.

![image](https://github.com/user-attachments/assets/37596942-a3da-46b4-ae64-50a2362f5cc6)

### Describe the solution you'd like.

Content Structure: The FAQ section should include a list of common questions and concise answers on topics such as account setup, password recovery, product information, and customer support.

Expandable List: Each question can be displayed as a clickable item that expands to reveal the answer, keeping the footer clean and organized.

Accessibility: Ensure the FAQ section is accessible and easy to read, with a responsive design that adapts to different screen sizes.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was mentioned before and kept it hold for now, we will look into this later.

So I am closing this issue.

Please understand.
