### ISSUE TITLE
Footer Image Not Displaying on ML Fusion Labs Projects Page

### ISSUE THREAD

**Issue by paricharm** [ML-Fusion-Lab/ML-Fusion-Lab-Website#729]
### Description

The image in the footer section of the [ML Fusion Labs Projects page](https://ml-fusion-lab.netlify.app/pages/projects) is not displaying. I have tried refreshing the page and clearing the browser cache, but the issue persists. I also checked for any error messages in the console but did not find any related to this image. Other images on the site are functioning correctly, indicating that this problem is specific to the footer image.

### Steps to Reproduce

1. Navigate to the [ML Fusion Labs Projects page](https://ml-fusion-lab.netlify.app/pages/projects).
2. Scroll down to the footer section.
3. Observe that the image is not displayed.

### Expected Behavior

The footer image should be visible and properly displayed.

### Actual Behavior

The footer image is missing and does not appear on the page.

### Screenshots

![bug](https://github.com/user-attachments/assets/c8825876-6a2c-4a8f-9daa-8576ad112b90)

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

Name : Moumita Halder
Participant Role : GSSOC, Hacktoberfest 2024
I would like to work on this issue. Please assign it to me @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@paricharm assigning this issue to you.

Make sure to complete this.

**Comment by Kroszborg** [comment]
@vivekvardhan2810 Im also seeing this issue of zen browser. I would like this issue to be assigned to me so i can fix it

**Comment by vivekvardhan2810** [comment]
@paricharm have you completed with this.

**Comment by paricharm** [comment]
@vivekvardhan2810 yea working on it,, almost done.... will finish by today
