### ISSUE TITLE
add effects to subscribe button like (hover and transition)

### ISSUE THREAD

**Issue by devxMani** [ML-Fusion-Lab/ML-Fusion-Lab-Website#73]
can assign this task to me and add GSOC ext  label to this

**Comment by vivekvardhan2810** [comment]
@devxMani can you share the screenshot on which you wanna work

**Comment by devxMani** [comment]
![image](https://github.com/user-attachments/assets/4b1cde46-53d2-4102-b000-f3305c0080fc)
adding transition hover to this and enhance design

**Comment by AkashJaiswal15** [comment]
can assign this task to me and add any other name label to this

**Comment by vivekvardhan2810** [comment]
have you completed this work, i have assigned you this 5 days ago.

**Comment by AkashJaiswal15** [comment]
Sir I will do it by tomorrow ☺️

**Comment by vivekvardhan2810** [comment]
@AkashJaiswal15 this issue was completed.
