### ISSUE TITLE
[Mention The Feature]: can add one student reviews section under the courses 

### ISSUE THREAD

**Issue by Aditya-edith** [ML-Fusion-Lab/ML-Fusion-Lab-Website#732]
Reviews are very important for everyone as they buy any course after that only if they will find some good reviews they surely invest some there.

we can add one text section and one rating section on which a job professional or a student can give some reviews.
but later on we have to make sure that only authorized person can give review. 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising this issue.

But we are not looking for this.

So I am closing this issue.

Please understand and don't get discouraged.
