### ISSUE TITLE
Dark Theme Toggle is not working many pages such as project pages

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#735]
### Description

The toggle to convert to change themes is not working in most of the websites pages 

https://github.com/user-attachments/assets/2fdc3d78-5c4b-4321-af74-5e532b54a588

### Steps to Reproduce

There is error in javascript code that preventing the DOM event listener to trigger .

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 see the dark mode is working, the animation is not working.

can you fix it.

**Comment by DarshAgrawal14** [comment]
yes , I can

**Comment by vivekvardhan2810** [comment]
Okay @DarshAgrawal14 assigning this issue to you.

Make sure to complete it.

And do it properly.
