### ISSUE TITLE
footer is not responsive

### ISSUE THREAD

**Issue by siddhant-2002** [ML-Fusion-Lab/ML-Fusion-Lab-Website#737]
### Description

footer is not responsive

### Steps to Reproduce

i woll give good layout so that  it will be responsive for laptops and mobiles too

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Please share the screenshot.
