### ISSUE TITLE
header design is not good

### ISSUE THREAD

**Issue by siddhant-2002** [ML-Fusion-Lab/ML-Fusion-Lab-Website#738]
### Description

header is not looking good i can give it good layout and look stylish

### Steps to Reproduce

header is not looking good i can give it good layout and look stylish

### Screenshots

![image](https://github.com/user-attachments/assets/b763c190-f4b0-4a91-8780-071d8b7f7c1c)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

please understand.
