### ISSUE TITLE
[Mention The Feature]: Hover Animation on Footer Social Icons & Proper Alignment of Copyright text

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [ML-Fusion-Lab/ML-Fusion-Lab-Website#740]
### Is your feature request related to a problem? Please describe.

The Social Icons on the Footer section are at default gray in color and on hover they all change to the color white, which does not look that attractive

### Describe the solution you'd like.

# 1. Hover Animation on Footer Social Icons
I would like to add a hover animation on the footer social icons that does the follows:

- Zoom animation

I want to add another feature but there's a problem with that
- Changes color to the respective logo color
Ex: Twitter[X] logo changes to black color on hover

**NOTE:** The problem with this is the color of your footer(which is black) so the logo might not be visible. I would like to change the color to a deeper shade of something other than black. Let me know your thoughts on this.

# 2. Proper Alignment of Copyright text
The Copyright text is at the very bottom of the website(left side) and not properly visible. I want to increase the font size and adjust it to the center as it is important information.

### Describe alternatives you've considered.

As an alternative, I would like to change the footer color from black to any other dark shade so that the icon colors are visible(especially the X logo, since it changes to black) upon hover.

### Additional context.

Please let me know your thoughts on this.
I would like to work on this issue and would love to provide you updates regarding the work progress and discuss any other difficulties faced along the way.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/5ebc9a97-0b31-4997-8af7-daacee2a82dc)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc assigning this issue to you.

Make sure to complete this.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 Yes I intend to do that. I hope I can discuss with you about any issues or suggestions along the way

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc assigning this issue to you.
> 
> Make sure to complete this.
> 
> And please don't change the footer colour.
> 
> Just add the hover animation on the footer social icons that does the follow

@vivekvardhan2810 The hover animation which will change the color of the twitter logo to black will make it quite invisible due to the color of the footer.

**Comment by vivekvardhan2810** [comment]
see for twitter logo you can ad blue colour logo as hover

**Comment by rajdeepchakraborty-rc** [comment]
> see for twitter logo you can add blue colour logo as hover

@vivekvardhan2810 Since the logo has been updated for Twitter(Blue) to X(Black), thus I felt that It would look odd if the X logo had blue color. But if you want me to do that, then fine.

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc continue with this.

see for twitter logo you can add blue colour logo as hover

**Comment by vivekvardhan2810** [comment]
okay @rajdeepchakraborty-rc take your time and do it carefully.

**Comment by rajdeepchakraborty-rc** [comment]
> okay @rajdeepchakraborty-rc take your time and do it carefully.

@vivekvardhan2810 I can assure you that I will give my all to the work and you can rest assured that I will try my very best to give you the best results possible!

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 I am done with my pending issues and will start with your work now. I wanted to ask something. Would you prefer if I changed the Twitter(X) logo like this:
- Before
![image](https://github.com/user-attachments/assets/4bc93e0e-a152-4b2d-aa0e-93077b5d7b92)

- After
![image](https://github.com/user-attachments/assets/4fee640f-8dc3-413e-9bc4-ae0adeb31436)

It is looking better without the box. Let me know your thoughts so that I can apply the changes if you feel like it.

**Comment by vivekvardhan2810** [comment]
> @vivekvardhan2810 I am done with my pending issues and will start with your work now. I wanted to ask something. Would you prefer if I changed the Twitter(X) logo like this:
> 
> * Before
>   ![image](https://private-user-images.githubusercontent.com/68934988/377965992-4bc93e0e-a152-4b2d-aa0e-93077b5d7b92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzQ2NDcsIm5iZiI6MTcyOTI3NDM0NywicGF0aCI6Ii82ODkzNDk4OC8zNzc5NjU5OTItNGJjOTNlMGUtYTE1Mi00YjJkLWFhMGUtOTMwNzdiNWQ3YjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE3NTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NmFjZDI0NDNlYTc5OGYyMDA0Y2M1ODdjZGI0NjEwNjhlNTBjYTFjNGMwYjcxMzc0ZmRhNjBjZWRkZTNiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OkEfXmaR94maKC8xpHIXGjcdFxr5UkErXrBkXCXgquE)
> * After
>   ![image](https://private-user-images.githubusercontent.com/68934988/377965909-4fee640f-8dc3-413e-9bc4-ae0adeb31436.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNzQ2NDcsIm5iZiI6MTcyOTI3NDM0NywicGF0aCI6Ii82ODkzNDk4OC8zNzc5NjU5MDktNGZlZTY0MGYtOGRjMy00MTNlLTliYzQtYWUwYWRlYjMxNDM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDE3NTkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMDQwZWU5N2ZiNWQ0NzFlYTVmNDQ2Yjc4N2M3MmJmYTE0NDAwYjY4ZDkxNzU2ZDMzNTcwMmJkYWFlYTY1YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M-_NVizq7G2JzbDxPDs2xyKbkl09F3BgZrnu1NpqBT4)
> 
> It is looking better without the box. Let me know your thoughts so that I can apply the changes if you feel like it.

@rajdeepchakraborty-rc you can do like this.

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc can you also update the alignment of the footer in home page.

as there were some changes happened.

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc can you also update the alignment of the footer in home page.
> 
> it is only in home page.
> 
> as there were some changes happened now.
> 
> ![image](https://private-user-images.githubusercontent.com/91594529/378071634-4a541423-13b8-40bd-af37-8a7b7a27e6d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzk1NDEsIm5iZiI6MTcyOTMzOTI0MSwicGF0aCI6Ii85MTU5NDUyOS8zNzgwNzE2MzQtNGE1NDE0MjMtMTNiOC00MGJkLWFmMzctOGE3YjdhMjdlNmQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDEyMDA0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NWViNzIyNGUzNTAyODYwNGMyMDcxYmY3NTIzNDQyMmZiMzEzMjVlZDhkZGQwODEzZDgzNTY3Y2EyZWExNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.77lcmB9s4Eg938VfP20fsjnU5AOUhimfmKOeSG-QPvU)

@vivekvardhan2810 It is quite messed up. I have to align them back again. Sure I will pull these changes and fix it again. Please do update the level of the issue to **level2**

**Comment by vivekvardhan2810** [comment]
yes @rajdeepchakraborty-rc updated the level.

**Comment by rajdeepchakraborty-rc** [comment]
> Thank god bro @rajdeepchakraborty-rc. don't create the PR for now, i am gonna merge one guy's PR, then i will let you know.

@vivekvardhan2810 Yes sure. Actually, I can't since the sync caused some conflicts on my end. I have to resolve them first. I was resolving this issue first but it took a bit more time than expected. Do merge the code and let me know.

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc i have merged the PR now, now you can do it.

waiting for your PR.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 Ok I will sync my code. Also, I will need some time to resolve my merge conflicts. I will let you know once I am done.

**Comment by vivekvardhan2810** [comment]
Okay @rajdeepchakraborty-rc take your time.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 Sorry for the delay, I had a power cut at my place. Just got back now.
Here's how the Footer section is looking right now:

https://github.com/user-attachments/assets/01887052-0ecb-45d4-813f-542c4dd8d181

I have modified the following:

- Added: **Zoom on hover** on the Social Icons.
- Added: **Color Change on hover** on the Social Icons.
- Centred and Enlarged the **Copyright section** for better visibility.

These are applied only to the Home Page right not. Let me know your thoughts on the modifications, while I will quickly go and apply it to the other pages.

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc this is looking good.

Make sure to apply it for remaining pages also.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 I’m glad you liked it! Please give me some time to apply the changes to the other pages, and I will open a pull request soon and let you know.

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc take your time.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 I am done with the footer social icons work. Just wanted to ask something. I noticed your README file and wanted to add a feature to it:
**A Team section**:
![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)
Let me know if you want me to add this to your README file. This will help the Contributors to know whom to talk to and ask queries.

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc yes you can add this into readme file.

**Comment by rajdeepchakraborty-rc** [comment]
Ok just a minute. I will share how it will look for you.

**Comment by rajdeepchakraborty-rc** [comment]
This is how it is looking for you:
![image](https://github.com/user-attachments/assets/0be4cbfa-e69f-4fc1-9bde-9efe79907bbc)

**Comment by vivekvardhan2810** [comment]
@rajdeepchakraborty-rc Okay and Good.

**Comment by rajdeepchakraborty-rc** [comment]
@vivekvardhan2810 I have opened the PR. Please review the changes at your convenience.
