### ISSUE TITLE
Wrong Designing and Overlapping Issue

### ISSUE THREAD

**Issue by AkshatSharma5** [ML-Fusion-Lab/ML-Fusion-Lab-Website#742]
### Description

The logo in the course page is overlapping with the navbar due to improper styling. needs to be readressed well.

![image](https://github.com/user-attachments/assets/ea2c0785-620d-406d-89ea-3920589e4607)

### Steps to Reproduce

go to https://ml-fusion-lab.netlify.app/pages/course_details.html?courseId=course_1

### Expected Behavior

This should not be overlapping

### Actual Behavior

Overlapping is observed

### Screenshots

![image](https://github.com/user-attachments/assets/d7721d81-5eb1-4320-891e-756c95ac455a)

### Additional Information

Needs proper CSS Redesigning

### What browser are you seeing the problem on?

- [ x] Firefox
- [ x] Chrome
- [ x] Safari
- [ x] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)
- 
**Please assign me this issue as I have understood and fixed it locally.**

**Comment by vivekvardhan2810** [comment]
@AkshatSharma5 make sure to complete this.
