### ISSUE TITLE
Naviagtion Bar UI enhancement 

### ISSUE THREAD

**Issue by KAUSHIKRM-36** [ML-Fusion-Lab/ML-Fusion-Lab-Website#743]
![Screenshot 2024-10-17 163934](https://github.com/user-attachments/assets/fd0a1739-7f62-4221-95a6-1f861c76f2d5)
this is how it is currently looking , i want to work on enhancing its look and make it somewhat like
![Screenshot 2024-10-17 163542](https://github.com/user-attachments/assets/f4552e20-4dd3-4817-b5ef-3c57d7764a30)
suitable and matching to the theme of the website overall 
please assign me this task under GSSOC24 and Hacktoberfest24

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes were happened many times.

Please understand. and don't be discouraged.
