### ISSUE TITLE
Imporve the navbar for sleek and good design 

### ISSUE THREAD

**Issue by shubhagarwal1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#745]
<img width="1409" alt="Screenshot 2024-10-17 at 5 13 29 PM" src="https://github.com/user-attachments/assets/1d274450-de0d-4610-bd05-89ac1bb0645e">

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes were happened many times.

Please understand. and don't be discouraged.
