### ISSUE TITLE
Restrict 'Contact Us' Submissions to Trusted Email Providers.

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#746]
Restricting the "Contact Us" feature to users with email addresses from trusted providers like Gmail or Outlook can have several advantages. Here are some key reasons:

**Spam Reduction:** 

Trusted email providers typically have robust spam filtering mechanisms. By restricting contact to these providers, you can significantly reduce the volume of spam and unwanted inquiries.

**Increased Credibility:**
Emails from established providers are often perceived as more legitimate. This can enhance the credibility of the inquiries received and increase the likelihood of meaningful communication.

There is no css for contact.html file.
 
I will also add the css file! (#747)

_**i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!**_

**Comment by vivekvardhan2810** [comment]
@smog-root please complete the previous issue that i have assigned you.

**Comment by smog-root** [comment]
i will complete it. but it's some what complex. so i will complete it! assign me this. first i will complete this!

**Comment by vivekvardhan2810** [comment]
for now i am giving level 2 only, i will update the level on he basis of the work.

**Comment by smog-root** [comment]
okay! respect to respect towards you! @vivekvardhan2810
