### ISSUE TITLE
There is no css file for contact.html!

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#747]
Every css is included in the contacts.html! 

i wil create a separate css file for it! 

_**i'm expecting a gssoc-ext with level3 (or) level2 and a hacktoberfest-accepted label!**_

**Comment by vivekvardhan2810** [comment]
@smog-root please add this in previous issue, why are you creating multiple issues.

**Comment by smog-root** [comment]
okay. my bad!!!! @vivekvardhan2810
