### ISSUE TITLE
Feedback page UI/UX

### ISSUE THREAD

**Issue by Amankr200** [ML-Fusion-Lab/ML-Fusion-Lab-Website#748]
Feedback page UI/UX is very basic and not looking professional and also not properly allign ,assign it level 3 
![Screenshot 2024-10-17 183535](https://github.com/user-attachments/assets/1427d3c4-a180-4520-bccd-6e89544c8e06)

**Comment by Amankr200** [comment]
but there is allignment issue in the feedback form  of stars , months , year along with it is looking simple  ,  but at the end it`s your choice

**Comment by vivekvardhan2810** [comment]
@Amankr200 can you do this.

i just want to reopen this issue.

**Comment by vivekvardhan2810** [comment]
@Amankr200 assigning this issue to you.

Make sure to complete this.

**Comment by vivekvardhan2810** [comment]
@Amankr200

**Comment by Amankr200** [comment]
okk
