### ISSUE TITLE
[Mention The Feature]: Want to add icons in navbar

### ISSUE THREAD

**Issue by Mansi07sharma** [ML-Fusion-Lab/ML-Fusion-Lab-Website#750]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/159f5687-ea66-4297-9318-4789b1221591)
 there I want to add icons corresponding to its name.

Like home icon , Book icon in front to course any many.

Kindly assign me 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes were happened many times.

Please understand. and don't be discouraged.
