### ISSUE TITLE
[Feature]: Adding github action workflow for PR validation

### ISSUE THREAD

**Issue by ygowthamr** [ML-Fusion-Lab/ML-Fusion-Lab-Website#751]
### Is your feature request related to a problem? Please describe.

**The workflow checks consist of following steps-**

- Should check for the PR Description in the pull request
- Check for the issue number, if the PR is not addressing any issue it should include `Fixes #NEW`

@vivekvardhan2810 @vivekv2810
Pls assign me this issue give me labels like gssoc-extd,hacktoberfest,level3

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/54ddf374-51cf-4332-b630-a58d31d83ae7)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we are not looking for any workflows.

So i am closing this issue.

Please understand.
