### ISSUE TITLE
[Mention The Feature]: Want to enhance course cards to align

### ISSUE THREAD

**Issue by Mansi07sharma** [ML-Fusion-Lab/ML-Fusion-Lab-Website#752]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/9c8d437c-ed4a-4d96-87cc-eab7cd2adf10)
 

In this cards are not align. I want to make it align can you assign it to me .

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
from my side it is looking good 

![image](https://github.com/user-attachments/assets/d1d68d7e-3b18-4fe8-a35e-21dae4c30937)

and the course card alignments issues were raised before and made many changes.

So i am closing this issue.

Please Understand.
