### ISSUE TITLE
[Mention The Feature]:  Signup and Login page not working

### ISSUE THREAD

**Issue by mdfaizaanalam** [ML-Fusion-Lab/ML-Fusion-Lab-Website#754]
### Is your feature request related to a problem? Please describe.

As you can see when an user register and try to login it does not working.

### Describe the solution you'd like.

So, i want to properly functional Signup and Login page in which when user try to register it user user data temporary and when user try to login after signup it will login and redirect to home page after login.

### Show us the magic with screenshots

![Screenshot 2024-10-17 193206](https://github.com/user-attachments/assets/ce47019d-97cc-4e77-8ef8-ac3c4dfaf2b4)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@mdfaizaanalam assigning this issue to you.

Make sure to complete this.
