### ISSUE TITLE
Stargazers not displaying

### ISSUE THREAD

**Issue by neeru24** [ML-Fusion-Lab/ML-Fusion-Lab-Website#755]
### Description

Error in displaying this

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/14068ef7-e5a5-4d57-adb2-d208b3ba736a)

### Screenshots

![image](https://github.com/user-attachments/assets/bb41c509-f3fe-43ec-a5c9-39e90a835e06)

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
![image](https://github.com/user-attachments/assets/5fe2b816-6ec3-4072-8b31-a24a45ccbd80)

@neeru24 from my side it is displaying.

**Comment by neeru24** [comment]
> @neeru24 from my side it is displaying.

Okay, but give it a check, it's not displaying on my side, that's why I said

**Comment by vivekvardhan2810** [comment]
i have given a check, it is displaying

**Comment by neeru24** [comment]
Ok, got it. You can close this issue, It was just to let you know
