### ISSUE TITLE
Under footer website logo image not loading in projects page

### ISSUE THREAD

**Issue by sneha056** [ML-Fusion-Lab/ML-Fusion-Lab-Website#757]
### Description

Under projects page https://ml-fusion-lab.netlify.app/pages/projects when we scroll down toward the end. in footer website logo image is not loading

### Steps to Reproduce

1. Go to projects page https://ml-fusion-lab.netlify.app/pages/projects
2. scroll down to the end
3. You will notice website logo image is not loading

### Expected Behavior

Image should be shown

### Actual Behavior

Image is not available

### Screenshots

![Screenshot 2024-10-17 202408](https://github.com/user-attachments/assets/fc47d21c-00c1-4d22-a0eb-491a832b365f)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was assigned to someone else. You can check it in issues.

So i am closing this issue.

Please Understand.
