### ISSUE TITLE
Login page: Eye icon not working

### ISSUE THREAD

**Issue by swathivemula7** [ML-Fusion-Lab/ML-Fusion-Lab-Website#758]
The toggle button(eye icon) in the password field in login page is not working...(toggle functionality not working)...

Eventhough it is working in signup page, not working in login page...I would like to fix this.

![Capturebhvg](https://github.com/user-attachments/assets/381c7a82-18d1-44a5-9359-cde96108fe42)

Kindly assign me this issue with gssoc and hacktoberfest labels.

**Comment by vivekvardhan2810** [comment]
@swathivemula7 can you fix this now.

**Comment by swathivemula7** [comment]
> @swathivemula7 can you fix this now.

Sure, i can fix this before tonight

**Comment by vivekvardhan2810** [comment]
@swathivemula7 make sure to complete this fast.

**Comment by Kroszborg** [comment]
i am interested in fixing this issue, can I be assigned this?

**Comment by swathivemula7** [comment]
> @swathivemula7 I think this issue was resolved, Because, i have assigned a login page updation before I have assigned you, i think he had also updated this one also.
> 
> Will it be okay for you, if i close this issue, so that you can look for other issues.
> 
> But please don't be discouraged.

@vivekvardhan2810 I was also about to raise a PR. But it's okay I will find an another issue.

**Comment by vivekvardhan2810** [comment]
@swathivemula7 can i close this issue. so that you can for other issues also.
