### ISSUE TITLE
🐞 Bad Feedback Page Design 

### ISSUE THREAD

**Issue by iarmaanx** [ML-Fusion-Lab/ML-Fusion-Lab-Website#761]
### Description

The website looks nice. We need to improve UI of Feedback page. The heading can to set to top. The star color can be changed.
 

### Steps to Reproduce

I would love to work on this issue. 

### Screenshots

![Screenshot 2024-10-17 210313](https://github.com/user-attachments/assets/dcce8d6b-6a47-4234-8c17-7cc8723c0674)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
the feedback related issue was assigned before, so i am closing this issue.

Please understand.
