### ISSUE TITLE
[Mention The Feature]: Improve the "Contact Us" Page UI

### ISSUE THREAD

**Issue by iarmaanx** [ML-Fusion-Lab/ML-Fusion-Lab-Website#762]
### Is your feature request related to a problem? Please describe.

![Screenshot 2024-10-17 210707](https://github.com/user-attachments/assets/b1e86f05-1349-44fb-bfe7-1dbd317eece8)

### Describe the solution you'd like.

The illustration on the right side of the form looks very small as compared to form. I can make it fit to the page.

### Describe alternatives you've considered.

I would love to work on this issue.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by iarmaanx** [comment]
Consider assigning this issue to me.

**Comment by vivekvardhan2810** [comment]
for now we are not looking for contact us page improvements. As there were many changes before.

So i am closing this issue

Please Understand.
