### ISSUE TITLE
[🚀]: Improve the Term and Conditions 

### ISSUE THREAD

**Issue by iarmaanx** [ML-Fusion-Lab/ML-Fusion-Lab-Website#763]
### Is your feature request related to a problem? Please describe.

The current "Terms and Conditions" page of the ML-Fusion-Lab website requires improvements to enhance its clarity, legal accuracy, and user-friendliness.
![Screenshot 2024-10-17 211238](https://github.com/user-attachments/assets/6d7f3f8c-a3f5-4f98-9b92-3df735e54d6c)

### Describe the solution you'd like.

**Solution** 
I'll
- Simplify complex legal terms to make the document more readable for users without a legal background.
- Ensure that the terms comply with relevant data protection laws (such as GDPR or CCPA) and include clear details about data collection, processing, and user rights.
- Review and update any outdated information or policies that no longer apply.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by iarmaanx** [comment]
I would love to work on this issue. Please consider assigning this to me.

**Comment by vivekvardhan2810** [comment]
@iarmaanx assigning this issue to you.

make sure to complete this.

and do it properly.

and don't create multiple issues

please understand.

**Comment by iarmaanx** [comment]
Thanks @vivekvardhan2810  for assigning the issue. I'll keep these things in mind.

**Comment by iarmaanx** [comment]
I have raised a PR please check.
