### ISSUE TITLE
Navbar hover color - dark mode

### ISSUE THREAD

**Issue by saumyayadav25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#765]
### Description

While hovering on navbar text, the text color turns grey which is not visible

### Steps to Reproduce

Hover on navbar topics

### Expected Behavior

Black or white color should be used on blue background instead of grey for better visibilty.

### Screenshots

<img width="1250" alt="Screenshot 2024-10-17 at 9 22 20 PM" src="https://github.com/user-attachments/assets/f990d670-79a6-4755-8ba6-41ee56625fb9">

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

please understand.

And the dark mode toggle related issue was assigned before and he is fixing it.
