### ISSUE TITLE
[Improve the community page ]: Improve the UI 

### ISSUE THREAD

**Issue by eshaalal** [ML-Fusion-Lab/ML-Fusion-Lab-Website#768]
### Is your feature request related to a problem? Please describe.

Adding animation and hovering effect and improving card design

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@eshaalal assigning this issue to you.

Make sure to complete this fast.

**Comment by eshaalal** [comment]
sure

**Comment by vivekvardhan2810** [comment]
And @eshaalal 

The Project Admin (me) of the ML Fusion Lab Won't be Available from Oct 28th and also this Project won't be active from Oct 28.
