### ISSUE TITLE
Ui change of the notification

### ISSUE THREAD

**Issue by HimangshuSharma01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#771]
### Description

![image](https://github.com/user-attachments/assets/4f5d9c48-b66c-4050-8600-f13fc7f2c17e)
It doesnt match the ui of the page 

### Steps to Reproduce

Its in the main page 

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HimangshuSharma01 can you show me a sample one's that you want to change this.

**Comment by HimangshuSharma01** [comment]
> @HimangshuSharma01 can you show me a sample one's like screenshot that you want to change this.

![image](https://github.com/user-attachments/assets/addea8d5-fe44-4238-8f98-96be8d2ef03b)
