### ISSUE TITLE
Bug Report: Navbar Home Button Missing & Layout/Position Changes on Project Page

### ISSUE THREAD

**Issue by Atul7307** [ML-Fusion-Lab/ML-Fusion-Lab-Website#773]
### Description

When navigating to the "Projects" page of the website, two issues occur:

1. The "Home" button disappears from the navbar.
2. The position and layout of the navbar change, which affects the overall user experience and visual consistency.

### Steps to Reproduce

1. Visit the website: https://ml-fusion-lab.netlify.app/
2. Click on the "Projects" link in the navbar.
3. Observe the following issues:
  - The "Home" button is missing from the navbar.
  - The navbar's position and layout differ from other pa

### Expected Behavior

- The "Home" button should remain visible across all pages.
- The navbar's position and layout should remain consistent across all pages for a smooth user experience.

### Actual Behavior

- The "Home" button is missing when navigating to the "Projects" page.
- The navbar's position and layout change when navigating to the "Projects" page.

### Screenshots

![Screenshot 2024-10-17 225603](https://github.com/user-attachments/assets/dd7b9db0-17a0-4e4b-b6a8-bf49fdfbd656)

### Additional Information

This issue may be related to how the navbar is dynamically styled or structured based on the active route.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
see when you click the logo in the project page, it redirects to home and there is no need of creating a separate navbar for home button.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

please understand.
