### ISSUE TITLE
[Mention The Feature]: Enhance Footer Section with Animation and Hover Effects

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [ML-Fusion-Lab/ML-Fusion-Lab-Website#777]
### Is your feature request related to a problem? Please describe.

I have observed that the current footer section lacks engaging animations and hover effects for its items. To improve user interactivity and enhance the visual appeal of the website, I propose implementing the following enhancements:

### Describe the solution you'd like.

1. Add CSS for Footer Item Animation
Style the Footer Items: Use flexbox to align items and apply padding.
Hover Effect: Change the text color and scale the item on hover.
2. Implement 3D Hover Effect on Footer Logo
Style the Logo: Set a transition for smooth effects.
3D Effect on Hover: Slightly lift and rotate the logo.
3. Update HTML Structure
Ensure your footer HTML reflects the updated classes for styling.

### Show us the magic with screenshots

![footer-update](https://github.com/user-attachments/assets/6018b7f3-451a-4fe2-bbed-47e104328f56)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
the footer and hover related issue was assigned before and he is working on it.

So i am closing this issue.

Please understand.
