### ISSUE TITLE
UI Improvements: Cross Button, Navbar Alignment, Dark Mode, Centered Copyright, Button Adjustment

### ISSUE THREAD

**Issue by Kavish-Paraswar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#779]
The UI component requires a cross button as part of its functionality.
![image](https://github.com/user-attachments/assets/2f429709-74d8-4a67-872c-0f8d88ada296)'

 Enhance the navbar with better alignment, place dark mode and translation on the right side, and center the links in the middle.
![image](https://github.com/user-attachments/assets/954a97fb-1e2f-4178-9b07-cf061d8a9b7f)

The copyright text at the bottom should be centered for better visual appeal.![image](https://github.com/user-attachments/assets/609233a6-67ea-47c4-acf6-c8073ad07af9)

Move the buttons slightly to the right and ensure all course boxes have equal length. The navbar also needs to be updated for consistency.
![image](https://github.com/user-attachments/assets/41a0f28d-525b-4ab5-a861-dd42c3012252)

The form is missing a name label, which needs to be added for clarity.
![image](https://github.com/user-attachments/assets/21224f9a-d43e-47cb-a59f-095f92913371)

Please , assign me this under GSOC'EXD and Hacktoberfest . With a strong background in HTML, CSS, and JavaScript, and given the complexity and scope of the work, I believe it warrants Level 2 or Level 3 assignment.

**Comment by vivekvardhan2810** [comment]
For now we don't require cross button functionality, and the dark mode issue was assigned before and he is working on it.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

And the centered copyright button issue was assigned before and he is working on it.

So I am closing this issue

please understand.
