### ISSUE TITLE
Making Home-Page more appealing

### ISSUE THREAD

**Issue by devanshaggarwal03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#78]
The "About ML Fusion Labs" section in homepage is very dull and not appealing.
Please assign me this issue under GSSoC-ext tag. I will also improve the Header since it is not same for all the pages and it is also not responsive.

**Comment by vivekvardhan2810** [comment]
@devanshaggarwal03 now it is looking good.

So i am closing this issue.
