### ISSUE TITLE
 Create Course Details Page for `Data Science Essentials` card

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#781]
### Is your feature request related to a problem? Please describe.

This page is not built yet and hence not clickable card

### Describe the solution you'd like.

I will develop a new page that connects to the Data Science course card. This page will include detailed information about the course, covering the following aspects:
- An introduction to Data Science and its prerequisites.
- A step-by-step breakdown of how the course will be structured.
- A list of additional courses related to Data Science, filtered from our website.

### Additional context.

@vivekvardhan2810 

### Show us the magic with screenshots

![Screenshot 2024-10-18 115057](https://github.com/user-attachments/assets/f7413ce8-2d61-499a-8c61-c71c1199dcca)
![Screenshot 2024-10-18 115110](https://github.com/user-attachments/assets/222d9936-031f-48de-8018-2b02a1f22d31)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810  please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this.

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 And this project will be active till October 27th after that I and the Project will be inactive from October 28th.
