### ISSUE TITLE
Updating Pop description with projects

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#783]
### Description

 Pop description are not matching  with projects again

### Steps to Reproduce

Users who are adding pages in between are not updating projects html which is causing the pop description of projects to not match the given title

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 can you share the screenshot.

**Comment by DarshAgrawal14** [comment]
sure give me 1 min

**Comment by DarshAgrawal14** [comment]
sorry my bad it seems updated now

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 then is it okay to close this issue.

**Comment by DarshAgrawal14** [comment]
give me one min some are matching some are not , i will create a video and send

**Comment by DarshAgrawal14** [comment]
here is a video showing the bug :

https://github.com/user-attachments/assets/0e326563-e9a5-467f-896c-e8549d4e8e27

**Comment by DarshAgrawal14** [comment]
@vivekvardhan2810  , i have mentioned the steps to reproduce this issue in the PR , if the contributor is adding page in the end no problem , but some are adding in between ,if they want to add in between they need to update the projects.html as well accordingly

**Comment by vivekvardhan2810** [comment]
yes, @DarshAgrawal14

**Comment by vivekvardhan2810** [comment]
And @DarshAgrawal14 

The Project Admin of the ML Fusion Lab Won't be Available from Oct 28th and also this Project won't be active from Oct 28.

**Comment by DarshAgrawal14** [comment]
@vivekvardhan2810 , i can make all contribution i want till 27th right?

**Comment by vivekvardhan2810** [comment]
yes @DarshAgrawal14, you can make contribution till 27th.
