### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Birth Rate prediction using time series analysis in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#785]
### Is your feature request related to a problem? Please describe.

Daily Births Forecasting using Machine Learning.

- Collect and process datasets regarding child births
- develop and analyze various ML models along with Facebook Prophet Model.
- develop traditional ML models and compare with prophet model
- perform hyper-parameter tuning to optimize performance

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.
