### ISSUE TITLE
Background Images Not Visible in "Contact Us" and "Projects" Sections

### ISSUE THREAD

**Issue by sheezah01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#787]
### Description

The background images in the "Contact Us" and "Projects" sections of the website are not visible, which affects the overall aesthetic and user engagement in these areas.

### Steps to Reproduce

1. Navigate to the "Contact Us" section of the website.

2. Observe the background image; it appears to be missing or not displaying correctly.

3. Go to the "Projects" section and check the background image there as well.

4. Notice that the background image is also not visible in this section.

### Expected Behavior

The background images in both the "Contact Us" and "Projects" sections should be clearly visible and enhance the overall design.

### Actual Behavior

The background images in the specified sections are not visible, leading to a bland appearance that detracts from user engagement.

### Screenshots

![IMG-20241018-WA0401](https://github.com/user-attachments/assets/c39b4267-4686-4403-9b8a-e714c09aa460)

### Additional Information

This issue may be related to incorrect image paths, CSS properties, or loading issues. Verifying the image URLs and ensuring proper styling in the CSS could resolve the visibility problem. If the images have not been assigned, we can add the appropriate images to enhance the design and user experience in both sections.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
see we haven't kept any background image till now for both the pages.

@sheezah01

**Comment by sheezah01** [comment]
I noticed that the "About Us" section features an appealing background image that enhances its visual appeal. I recommend adding similar background images to the "Projects" and "Contact Us" sections to create a design . If the images have not yet been assigned, we can implement this enhancement to further enrich these sections. @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
can you add the images in both project section and contact us with respect to their pages.@sheezah01

**Comment by vivekvardhan2810** [comment]
Just only add the background images in both the pages, Don't change anything. @sheezah01 

Assigning this issue to you.

Make sure that image should look in both light and dark mode.

**Comment by vivekvardhan2810** [comment]
@sheezah01 make sure to complete this fast.

As it won't take much time i think.
