### ISSUE TITLE
Add Faqs section in website

### ISSUE THREAD

**Issue by Deepanshu-pathak** [ML-Fusion-Lab/ML-Fusion-Lab-Website#79]
Website doesn't have FAQ section. Will make it look visually appealing and styling and transition and hover effects

**Comment by vivekvardhan2810** [comment]
Hi, @Deepanshu-pathak There was issue created before based on FAQ.

But i will encourage to look for other issues in website like improvements.

I am closing this issue.

**Comment by vivekvardhan2810** [comment]
Hi @Deepanshu-pathak, This issue was created before only, will look into afterwards.

so i am closing this issue.
