### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Human Migration using time series analysis in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#790]
### Is your feature request related to a problem? Please describe.

Predicting human migration as accurately as possible is important in city planning applications, international trade, the spread of infectious diseases, conservation planning, and public policymaking. Various parameters can be considered in migration prediction like citizenship , city , visa etc by implementing time series analysis we can analyze past trends and introduce seasonality for better and more accurate predictions .

Modify dataset for better time series analysis .
analyze trends , seasonality .
Comparison with traditional algorithms
Compile findings.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by DarshAgrawal14** [comment]
> @DarshAgrawal14 assigning this issue to you.
> 
> Make sure to complete this.
> 
> And don't create multiple issues, as the organisers think you are contributing to only one project with high labels.
> 
> please understand, And do contribute to other projects also.

I understand your concern , I am proficient in machine learning and have been contributing to machine learning repos as well .I have recently started web development and found your repo to be perfect place to contribute as it has both of them . please dont worry i am contributing to other repos as well , the amount of commits today were because it was for removing bigs rather than feature addition.

**Comment by vivekvardhan2810** [comment]
Okay @DarshAgrawal14 Wishing you all the best and keep contributing to open source.
