### ISSUE TITLE
[Mention The Feature]: Google translator

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ML-Fusion-Lab/ML-Fusion-Lab-Website#791]
### Is your feature request related to a problem? Please describe.

It will change the language of whole website as we know in India even in world there are many language and our user can be from any place and some user doesn't understand english so it will be better if we provide them the content of our website in there native language

![Screenshot 2024-10-17 140930](https://github.com/user-attachments/assets/deb048dd-d7ab-43ca-8870-3188255876d6)

Please assign me i can work on this Default is english but user has a button on clicking he get option of language and we could select form that

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this feature exists in website and it was resolved and we don't want any further updation for this, please check it before creating an issue.

So i am closing this issue.

Please understand.
