### ISSUE TITLE
[Mention The Feature]: Card design should be enhance as its not looking professional 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ML-Fusion-Lab/ML-Fusion-Lab-Website#793]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/80e439ee-f923-4dd3-a173-6dc7e42d607c)

it is not looking good all alignment of content is here and there i can fix it

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah this is the last warning from my side don't create the issues one by one.

for now i am assigning this.

make sure to complete it.

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah have you done with this.

**Comment by Sawan-Kushwah** [comment]
@vivekvardhan2810 yes done

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah please make the required changes that i have asked you in the pull request, then i will close this issue.
