### ISSUE TITLE
[Mention The Feature]: Improving the Testimonial Page

### ISSUE THREAD

**Issue by Ashish-Patnaik** [ML-Fusion-Lab/ML-Fusion-Lab-Website#795]
### Is your feature request related to a problem? Please describe.

The Testimonial Page looks very laggy and slow , I want to improve the whole UI of the Testimonial Page

### Describe the solution you'd like.

A better UI with great animations like this , I have already worked on this type of feature 

https://github.com/user-attachments/assets/80e65888-71a5-4244-87c1-78175ff2c6e7

### Additional context.

Please assign me with higher level if you want to

### Show us the magic with screenshots

https://github.com/user-attachments/assets/5e152a43-f347-4abf-8d9a-47fa2890a7d4

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising this issue, for now testimonial page looks okay, as we don't want any further improvements on this.

so i am closing this issue.

please understand.

**Comment by Ashish-Patnaik** [comment]
ok no problem
