### ISSUE TITLE
Theme changing toggle button is same on both dark theme and light theme.

### ISSUE THREAD

**Issue by Adityadhiman0** [ML-Fusion-Lab/ML-Fusion-Lab-Website#796]
### Description

When I click on the toggle button to change the theme on dark mode, theme changed but toggle button remained same.
Toggle button should also change according to the dark mode or light mode.

### Steps to Reproduce

Open the website.
Click on toggle button to change the theme.
You will see theme changed but toggle button remained same.

### Expected Behavior

Toggle button should change according to the website theme.

### Screenshots

![Screenshot 2024-10-18 201113](https://github.com/user-attachments/assets/62ec695d-91e3-4d19-9ffa-159ff490e387)
![Screenshot 2024-10-18 201158](https://github.com/user-attachments/assets/14b5f912-4b2f-4272-94cc-603b9eafb0d3)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 can you fix this.

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 assigning this issue to you.

Make sure to complete this very fast.

Again this is the warning from side 

from next time don't create multiple issues one by one.

**Comment by Adityadhiman0** [comment]
Ok thank you and I won't create multiple issues at ones.
