### ISSUE TITLE
[Mention The Feature]: Change the style of nav bar links.

### ISSUE THREAD

**Issue by Adityadhiman0** [ML-Fusion-Lab/ML-Fusion-Lab-Website#797]
### Is your feature request related to a problem? Please describe.

Nav bar is not looking good right now. We should add some style or animation on nav bar links.

### Describe the solution you'd like.

I want to add some styles on them.

### Additional context.

![Screenshot 2024-10-18 203527](https://github.com/user-attachments/assets/0497ab6a-2256-48b0-acd9-82cb6f372f46)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 please reply for the previous issue, that i have asked you.

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

**Comment by vivekvardhan2810** [comment]
Do not create unnecessary issues until you complete the previous one.

**Comment by Adityadhiman0** [comment]
I apologize for creating issue on nav bar.
Will you please help me to remined me what you have asked for previous issue.

**Comment by vivekvardhan2810** [comment]
check this issue #796
