### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by Nandini-13** [ML-Fusion-Lab/ML-Fusion-Lab-Website#8]
Add the logo of ML-Fusion-Labs as a favicon to help visitors locate the page easily when they have multiple tabs open.

![1](https://github.com/user-attachments/assets/1055f774-e9ce-4bb2-8e82-dfe2de889b35)

Kindly assign this issue to me so that I can start working on it.

**Comment by vivekvardhan2810** [comment]
Hi @Nandini-13, pls complete the issue that I have assigned now, then you can do this

**Comment by riyarane46** [comment]
@Nandini-13 , i believe i can solve this issue . please assign it me under . GSSoC24 Extd

**Comment by vivekvardhan2810** [comment]
@Nandini-13, is it okay for you, if i assign @riyarane46

**Comment by vivekvardhan2810** [comment]
@riyarane46,

till then you can look for other issues at website like improvements and create an new issue for that.

**Comment by Nandini-13** [comment]
@vivekvardhan2810 I have implemented the necessary changes and made a pull request for issue #7 . Kindly assign issue #8 to me if the changes for the previous issue are upto the mark.
