### ISSUE TITLE
enhancing UI

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [ML-Fusion-Lab/ML-Fusion-Lab-Website#80]
<img width="943" alt="Screenshot 2024-10-02 at 4 08 08 PM" src="https://github.com/user-attachments/assets/8a1de7da-4c34-43ad-908a-e288d4e29851">
 

the UI of this can be improved.

can u assign me this and label it aswell.
thank you!

**Comment by vivekvardhan2810** [comment]
@T-Rahul-prabhu-38 make sure to complete this issue for the next 2 days

and make sure to join discord channel mentioned at readme,

**Comment by T-Rahul-prabhu-38** [comment]
sure sir,

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@Akanshaku don't spam in other issues, this is the last warning.
