### ISSUE TITLE
[Mention The Feature]: Navigation bar improvement for contacts page

### ISSUE THREAD

**Issue by Sneha22072005** [ML-Fusion-Lab/ML-Fusion-Lab-Website#800]
### Is your feature request related to a problem? Please describe.

here the navigation bar tabs aren't there in the Contacts page when the screen is made smaller under media query. I would like to add it.
![image](https://github.com/user-attachments/assets/c7d286d1-df07-469f-8746-dff33f5118cf)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, thank you for creating this issue.

but for now we are not looking for navbar updates in contact page


I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
