### ISSUE TITLE
Adding card slider effect on the courses 

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#801]
### Is your feature request related to a problem? Please describe.

A card slider effect allows users to view multiple course cards in a horizontally sliding carousel on the website. Each card typically contains brief information about a course.
 Users can navigate through the courses by sliding the cards left or right, either manually using arrow buttons .
 This design element provides a sleek and organized way to showcase multiple courses in a limited space, ensuring easy browsing without overwhelming the user.

### Describe the solution you'd like.

1. Improved User Experience: The slider effect allows users to explore more courses without excessive scrolling, creating a smoother navigation flow.
2. Space Efficiency: It enables displaying multiple courses in a compact space, making it ideal for mobile and desktop views alike.
3. Visual Appeal: A card slider adds a modern, interactive element to the design, enhancing the overall look and feel of the website.
4. Better Focus: Each course card gets its moment in focus as it slides into view, making it easier for users to absorb the information.
5. Increased Engagement: Interactive elements like sliders tend to keep users on the page longer, increasing the likelihood of them exploring more content.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
we are not looking for this.

so i am closing this issue.

Please understand.
