### ISSUE TITLE
Home page is not responsive for mobile devices

### ISSUE THREAD

**Issue by Palmistry2310** [ML-Fusion-Lab/ML-Fusion-Lab-Website#803]
currently for mobile phones view homepage is not responsive, it has a large white space at right side which lowers user experience (on mobile phones). 
![Screenshot 2024-10-18 223649](https://github.com/user-attachments/assets/63ff0938-30dd-40b8-acc4-b84a59662b66)

If you find it necessary then i would like to fix this, please assign me this issue under gssoc-ext, hacktober-accepted,level labels.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 assigning this issue to you.

Make sure to complete this.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 have you completed.

**Comment by vivekvardhan2810** [comment]
And @Palmistry2310 this project won't be active from october 25th, and me also.

this is an remainder.

**Comment by vivekvardhan2810** [comment]
@Palmistry2310 have you done with this.
