### ISSUE TITLE
The about section is not responsive.

### ISSUE THREAD

**Issue by ambarmishraa** [ML-Fusion-Lab/ML-Fusion-Lab-Website#804]
### Description

The About section of the website is not displaying correctly on mobile devices. The layout does not adjust to smaller screen sizes, causing text and images to either overlap or require horizontal scrolling. This makes the section difficult to read and navigate on smartphones and tablets.

What I Tried:
Implemented CSS flex and grid layouts to position text and images.
Used media queries to adjust the layout for smaller screens.
What Did Not Work:
Despite using media queries, the content does not stack vertically as expected on mobile devices.
Images do not resize correctly, either appearing too large or distorted.
Padding and margins are not adjusting properly, leading to cramped or misaligned content on smaller screens.

### Steps to Reproduce

Open the Website:

Visit the webpage where the About section is located using a desktop browser.
Resize the Browser Window:

Gradually reduce the width of the browser window to simulate smaller screen sizes (e.g., tablet or mobile). You should see the layout start to break down, especially around 600px width or smaller.
Test on Mobile Device:

Open the website on an actual smartphone or tablet to see how the About section displays. Alternatively, use a browser's developer tools (e.g., Chrome DevTools) to simulate a mobile device (choose "Inspect" and toggle "Device Toolbar").
Observe the Following Issues:

Text and images do not stack properly on small screens.
Horizontal scrolling may be required to view all content.
Images do not resize dynamically, possibly leading to distortion or improper alignment.
Padding and margins are either too large or too small, affecting the readability of the text.

### Expected Behavior

Responsive Layout:

On larger screens (desktops and laptops), the About section should display the text and image side-by-side in a well-aligned manner, maintaining visual appeal.
Stacking on Smaller Screens:

On tablets and mobile devices, I expected the layout to automatically adjust, stacking the text above or below the image for better readability.
Dynamic Image Resizing:

Images within the About section should resize proportionally to fit the screen width, ensuring they maintain their aspect ratio without distortion.
Adjusted Text Size:

Font sizes for headings and paragraphs should scale appropriately for smaller screens, ensuring that all text remains legible without the need for zooming in.
Proper Spacing:

Adequate padding and margins should be applied, ensuring that the content does not appear cramped and remains visually appealing on all devices.
No Horizontal Scrolling:

Users should be able to scroll vertically without needing to scroll horizontally, making the content easy to consume on mobile devices.

### Actual Behavior

Layout Issues:

On larger screens, the About section appears correctly with text and images side-by-side. However, when resizing the browser window or viewing on mobile devices, the layout does not adjust as expected.
No Stacking on Smaller Screens:

Instead of stacking the text above or below the image on smaller screens (tablets and mobile), the content remains in a single row, causing elements to overlap or appear misaligned.
Image Resizing Problems:

The images do not resize properly. They either remain too large for the screen or become distorted, breaking their aspect ratio, which affects the overall appearance of the section.
Text Size Issues:

The font sizes do not scale down appropriately for smaller devices, making some text difficult to read without zooming in.
Inconsistent Spacing:

Padding and margins do not adjust effectively, leading to cramped content or excessive white space, which detracts from the visual balance of the section.
Horizontal Scrolling:

Users are required to scroll horizontally to view the entire content on mobile devices, making the experience cumbersome and frustrating.

### Screenshots

![Screenshot 2024-10-18 230226](https://github.com/user-attachments/assets/cd4c9cac-07b9-4406-b9ba-88a28dbc0d88)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by ambarmishraa** [comment]
Assign this task to me asap.

**Comment by vivekvardhan2810** [comment]
@ambarmishraa can you fix this by tonight.

**Comment by ambarmishraa** [comment]
@vivekvardhan2810 Assign me i will surely fix this by tonight.

**Comment by vivekvardhan2810** [comment]
Okay @ambarmishraa Assigning this issue to you.

make sure to complete this by tonight.

**Comment by ambarmishraa** [comment]
@vivekvardhan2810 sure..
