### ISSUE TITLE
Contact Form Alignment and spacing improvement

### ISSUE THREAD

**Issue by shantanu020** [ML-Fusion-Lab/ML-Fusion-Lab-Website#805]
### Description

The initial form design had several layout issues, including inconsistent field sizes, lack of spacing between fields, and poor alignment. Additionally, the button for submitting the form wasn’t as prominent as it should have been. These issues could affect the user experience, making it harder to fill out the form efficiently and clearly.

### Steps to Reproduce

Navigate to contact 

### Expected Behavior

Field Alignment: All input fields should be uniformly aligned and have the same width and height, creating a clean and professional appearance.

Spacing: There should be consistent and adequate spacing between all form fields, ensuring they are not too close or too far apart. This improves readability and ease of use.

Mobile Responsiveness: On smaller screens, the form should adapt and stack neatly to maintain usability. All fields and buttons should be easily accessible on mobile devices without horizontal scrolling.

Button Visibility: The "SEND MESSAGE" button should be prominent, well-designed, and clearly distinguishable from other form elements. Users should easily locate and click it to submit the form.

Accessibility: The form should provide clear focus indicators when users interact with it via keyboard navigation or screen readers. Each field should highlight as the user tabs through, making the form accessible for users with disabilities.

Image Placement: The image should be placed in a way that doesn’t interfere with the form's functionality, ensuring that users can focus on filling out the fields.

Clear Submission Confirmation: After pressing "SEND MESSAGE," the user should receive a clear confirmation that their message has been successfully submitted, or be alerted to any errors in a user-friendly way (e.g., highlighting required fields).

### Actual Behavior

Alignment and spacing is not correct

### Screenshots

![image](https://github.com/user-attachments/assets/2934e935-286b-4d18-8da0-4b4cc9630503)

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@shantanu020 assigning this issue to you.

Make sure complete this fast.

**Comment by shantanu020** [comment]
@vivekvardhan2810 thank you sir.
 I’ve completed the issue. Let me know if you need anything else!
