### ISSUE TITLE
[Mention The Feature]: Contact Page overall styling.

### ISSUE THREAD

**Issue by ambarmishraa** [ML-Fusion-Lab/ML-Fusion-Lab-Website#808]
### Is your feature request related to a problem? Please describe.

Yes, the current layout of the page presents a usability issue. The form and map are positioned on different rows, causing a disjointed user experience. Users need to scroll between the map and the form, which disrupts the workflow and creates inefficiencies. This is especially problematic for users who want to interact with the form while keeping the map in view for reference, as they are forced to switch back and forth between the two elements.

### Describe the solution you'd like.

The page is not looking and attractive as the map and the form are both at different rows. I was thinking of making the map in the same row as of form so it would look more good.

### Describe alternatives you've considered.

Keeping the Existing Layout: One alternative was to keep the current layout with the map and form on different rows. However, this made the page look unbalanced and caused a lot of unused whitespace, especially on larger screens.

Using Tabs: Another alternative was to use tabs to switch between the map and the form, but this would have hidden one element at a time, which could reduce usability, as both elements are important to be visible at once.

Placing the Map Above the Form: Another idea was to place the map above the form, but this would result in a tall layout that forces users to scroll more, reducing efficiency.

### Additional context.

The form and map are integral to the functionality of this page. Users typically need to fill out the form while referencing the map. By having them in separate rows, users have to scroll up and down, leading to a less intuitive experience, particularly on larger screens. Placing the form and map side by side makes the interface more user-friendly, especially on desktop and tablet devices where there's enough horizontal space to accommodate both.

This change also aligns the page's layout with modern design principles, where related content is often grouped together horizontally to reduce scrolling and improve usability. Additionally, the side-by-side layout is responsive and will maintain functionality on smaller screens by stacking vertically when necessary.

This modification ensures a cleaner, more professional look and enhances user interaction with the page.

### Show us the magic with screenshots

https://github.com/user-attachments/assets/63859941-64c7-4fd6-8cd1-c76eea0a7e7b

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ambarmishraa assigning this issue to you.

Make sure to complete this fast.

**Comment by vivekvardhan2810** [comment]
@ambarmishraa and update the branch also, before committing. as the contact page was updated.

**Comment by ambarmishraa** [comment]
yes i will do that sir.
