### ISSUE TITLE
[Mention The Feature]:  improve Translation Tool 

### ISSUE THREAD

**Issue by VidhanThakur09** [ML-Fusion-Lab/ML-Fusion-Lab-Website#810]
### Is your feature request related to a problem? Please describe.

The current Translation Tool  has a very basic layout and outdated design. Additionally, the Translation Tool lacks modern styling  , resulting in bad impression toward website . Enhancing the Translation Tool with from scratch with modern design  would significantly enhance the user experience and overall website presentation.

### Describe the solution you'd like.

Redesign the Translation Tool with modern styling to enhance the website presentation and user experience. 

- Redesign the Translation Tool  for better visual appeal.
- Improving the styling of Translation Tool .

### Additional context.

@v can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

### Show us the magic with screenshots

https://github.com/user-attachments/assets/8ca8ab9d-7222-4ba6-8ee9-f444bb0cd61b

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 for now we are not looking improvements in translation one's.

So i am closing this issue.

Please Understand.

**Comment by VidhanThakur09** [comment]
ok, sir

**Comment by vivekvardhan2810** [comment]
And @VidhanThakur09 please don't tag me on discord for every issue which you have created, I will look into all issues.

**Comment by VidhanThakur09** [comment]
ok sir ,  i will not tag .

**Comment by vivekvardhan2810** [comment]
And @VidhanThakur09 

The Project Admin (me) of the ML Fusion Lab Won't be Available from Oct 28th and also this Project won't be active from Oct 28.

**Comment by VidhanThakur09** [comment]
Thank you for bringing this to my attention. I will ensure that I refrain from raising any issues from given time period.

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 Wishing you all the best and keep contributing to open source.

**Comment by VidhanThakur09** [comment]
I am grateful for your kind and thoughtful wishes.
