### ISSUE TITLE
Contact Page form input field functionality.

### ISSUE THREAD

**Issue by Devanshu1603** [ML-Fusion-Lab/ML-Fusion-Lab-Website#814]
### Is your feature request related to a problem? Please describe.

The input fields in contact us form section don't get cleared after succesfull submission of details.

### Describe the solution you'd like.

i want that on form submission text fields got cleared for next submission.

### Show us the magic with screenshots

https://github.com/user-attachments/assets/0b460327-ae87-4aa5-b680-1b237b0ca863

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Devanshu1603** [comment]
@vivekvardhan2810 please assign me this issue under gssoc-extended.

**Comment by vivekvardhan2810** [comment]
For now we don't require for this, we will look into this later, please complete the issue that I have assigned you.

**Comment by vivekvardhan2810** [comment]
@Devanshu1603 assigning this issue to you.

Make sure to complete this.

**Comment by Devanshu1603** [comment]
@vivekvardhan2810  doing it in a while.
