### ISSUE TITLE
Contact Page is not responsive in Mobile mode

### ISSUE THREAD

**Issue by Devanshu1603** [ML-Fusion-Lab/ML-Fusion-Lab-Website#815]
### Description

The contact page need to be made responsive in mobile view. input fields need to align properly and map need to be place accuretly.

### Steps to Reproduce

Should improve styling in smaller view .

### Screenshots

https://github.com/user-attachments/assets/bf9ac458-f702-46a1-8650-278e40c1b207

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Devanshu1603** [comment]
@vivekvardhan2810  please assign me this issue under gssoc-extended.

**Comment by vivekvardhan2810** [comment]
@Devanshu1603 assigning this issue to you

Make sure to complete this
