### ISSUE TITLE
Contact us page is not responsive 

### ISSUE THREAD

**Issue by Kaaditya19k** [ML-Fusion-Lab/ML-Fusion-Lab-Website#816]
### Description

As i go through the website i found the contact us page is not responsive and the div that contains map and other optional details collapse over each other and this leads to degrade of the website
![Screenshot 2024-10-19 090850](https://github.com/user-attachments/assets/ed53134e-2e68-4ba0-a770-77945b5aa604)
 

### Steps to Reproduce

Please assign me this task so that i can improve the responsiveness of that targeted div and let the layout look attractive.

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags. @Rahul verma

### Screenshots

![Screenshot 2024-10-19 090850](https://github.com/user-attachments/assets/98a24b89-893e-4add-8d9c-fc0dbde711b3)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was assigned before, and they are working on it.

Please check it.

So I am closing this issue.

Please understand.

**Comment by Kaaditya19k** [comment]
sorry for the inconvenience its a mistake from my side
