### ISSUE TITLE
Navbar UI is not looking good

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#818]
### Description

The navbar UI does not meet design expectations and appears unappealing.

### Steps to Reproduce

- Open the application in a web browser.
- Navigate to the homepage where the navbar is displayed.
- Observe the design and layout of the navbar.

### Screenshots

![image](https://github.com/user-attachments/assets/a94262df-9046-4671-b52b-ec967adcd8ea)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by sandeepmaddheshiya** [comment]
@vivekvardhan2810 please assign to me, I'll do this asap!

**Comment by vivekvardhan2810** [comment]
I  have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
