### ISSUE TITLE
Create `Programming & Development`  ; and `Artificial Intelligence` Course Detail Page  

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#819]
### Is your feature request related to a problem? Please describe.

These sections are yet to be built.

### Describe the solution you'd like.

I will develop a new page that connects to both  `Programming & Development`  ; and `Artificial Intelligence` Course card. This page will include detailed information about the course, covering the following aspects:
- An introduction to Data Science and its prerequisites.
- A step-by-step breakdown of how the course will be structured.
- A list of additional courses related to Data Science, filtered from our website.

@vivekvardhan2810 

### Show us the magic with screenshots

![Screenshot 2024-10-18 115057](https://github.com/user-attachments/assets/f7413ce8-2d61-499a-8c61-c71c1199dcca)
![Screenshot 2024-10-18 115110](https://github.com/user-attachments/assets/222d9936-031f-48de-8018-2b02a1f22d31)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you

Make sure to complete this.

And don't only contribute on this project, as the organisers think you are contributing to only one project with high level labels and think as spamming.

please understand, And do contribute to other projects also.

**Comment by vivekvardhan2810** [comment]
And @Adarsh-Chaubey03 

The Project Admin (me) of the ML Fusion Lab Won't be Available from Oct 28th and also this Project won't be active from Oct 28.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03 assigning this issue to you
> 
> Make sure to complete this.
> 
> And don't only contribute on this project, as the organisers think you are contributing to only one project with high level labels and think as spamming.
> 
> please understand, And do contribute to other projects also.

![image](https://github.com/user-attachments/assets/6867eacc-d7b7-4508-9a78-2a29f686fe61)
 I have been contributing to different project as well . But i will make sure to increase the number of contributions to other projects.  I completely understood the points. Thanks!!!
