### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by Prit16** [ML-Fusion-Lab/ML-Fusion-Lab-Website#82]
entire home page's ui needs to be changed
its looks like much simple and out-of-date design.

**Comment by sajal-11111** [comment]
@vivekvardhan2810 hello sir i want to contribute to this project could you assign this to me?

**Comment by vivekvardhan2810** [comment]
Hi @sajal-11111 this issue was create by @Prit16, it will be on first on first serve basis.

But to encourage you, You can create new issue by looking on website and improvements.

and then create new issue.

**Comment by vivekvardhan2810** [comment]
@Prit16 now it is looking good.

So i am closing this issue.

**Comment by Prit16** [comment]
Sure ! Thanks!
