### ISSUE TITLE
Footer content is not properly alligned.

### ISSUE THREAD

**Issue by DPS-2912** [ML-Fusion-Lab/ML-Fusion-Lab-Website#820]
### Issue Description

The alignment is not proper between the footer contents.

### Screenshots or Examples (if applicable)

![Capture](https://github.com/user-attachments/assets/8e184ea1-b66a-4313-950f-ee8d4eeed532)

### Proposed Solution (optional)

Ensure the proper padding and margin between the footer content.
Copyright content and social media icons need to be centered for better view.
Also ensuring proper alignment between the bullet points and sites definition.

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by DPS-2912** [comment]
Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

**Comment by vivekvardhan2810** [comment]
The footer related issue was assigned to someone before and they are working on it.

So I am closing this issue.

Please understand.
