### ISSUE TITLE
Newsletter section is not responsive

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#821]
### Description

News Letter Section is not responsive across all screen sizes.

### Steps to Reproduce

Check on all screen sizes

### Screenshots

![image](https://github.com/user-attachments/assets/dad7a7a3-eac0-460d-9869-5a5f7198622d)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by sandeepmaddheshiya** [comment]
@vivekvardhan2810 please assign this to me under label gssoc-extd, hacktoberfest.

**Comment by vivekvardhan2810** [comment]
@sandeepmaddheshiya assigning this issue to you.

Make sure to complete this fast.

And don't create the issues one by one.

Please understand.
