### ISSUE TITLE
**"Add 'Events and Webinars' Page in the Footer Section of ML Fusion Lab"**

### ISSUE THREAD

**Issue by ansiace** [ML-Fusion-Lab/ML-Fusion-Lab-Website#822]
### Description

There is currently no **'Events and Webinars'** page linked in the footer section of the **ML Fusion Lab** website. Adding this page will provide users with easy access to information about upcoming events and webinars.

### Steps to Reproduce

1. **Open the ML Fusion Lab website** in a browser.
2. **Scroll down** to the bottom of the page to view the **footer section**.
3. Look for any existing links or sections related to **Events and Webinars**.
4. **Observe** that there is no link or page dedicated to **Events and Webinars** in the footer section.
5. **Navigate** through the website to confirm that there is no page available for **upcoming or past events and webinars**.
6. **Expected Outcome**: There should be a link in the footer for users to easily access information about **upcoming events and webinars**.

### Expected Behavior

- A new link labeled **'Events and Webinars'** should be added to the **footer section** of the website under an appropriate category.
- The link should redirect users to a new page where they can find details about **upcoming events, webinars, or past recordings**.

### Actual Behavior

- The footer section does not contain a link to an **Events and Webinars** page, which limits user access to information about ongoing or future events.

### Screenshots

![Screenshot 2024-10-19 111359(1)](https://github.com/user-attachments/assets/73f5c2f2-f5c0-4830-b3d6-7f6984713448)

### Additional Information

Adding this page will enhance user engagement by keeping them informed about upcoming events and webinars, providing more value and interactivity to the website.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now we don't require this in footer.

So I am closing this issue.

Please understand.

**Comment by ansiace** [comment]
Ok fine.
