### ISSUE TITLE
Navbar contents not properly aligned under Projects section

### ISSUE THREAD

**Issue by DPS-2912** [ML-Fusion-Lab/ML-Fusion-Lab-Website#823]
### Issue Description

The navbar contents are not properly aligned under the projects section. Either it should be centered or placed at extremes for better view.

### Screenshots or Examples (if applicable)

![Capture](https://github.com/user-attachments/assets/1266b69d-e3ec-4bfe-9196-ee965c441e4c)

### Checklist

- [X] I have checked the existing [issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I am willing to work on this issue (optional)

**Comment by DPS-2912** [comment]
Kindly assign this issue to me under GSSoC-Extd and Hacktoberfest.

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

And don't create the issues one by one.
