### ISSUE TITLE
UI enhancements for coutry selection

### ISSUE THREAD

**Issue by Sivasaiklu** [ML-Fusion-Lab/ML-Fusion-Lab-Website#825]
![image](https://github.com/user-attachments/assets/a200be23-040c-4e69-bb5e-20de97a373bc)

=> UI has to change for the country selectio, if we add dropdown menu means it will be good

**Comment by vivekvardhan2810** [comment]
for now we are not looking for any further improvements on this.

So i am closing this issue.

Please unserstand.
