### ISSUE TITLE
Image not visible

### ISSUE THREAD

**Issue by Sivasaiklu** [ML-Fusion-Lab/ML-Fusion-Lab-Website#826]
![image](https://github.com/user-attachments/assets/01f0b1c3-32a8-43b0-a00e-af3b51136f9f)

> here image is not visible

**Comment by vivekvardhan2810** [comment]
this issue was assigned before and they are working on it. So i am closing this issue.

And Please don't create multiple issues one by one.

this is the warning.

Please Understand.
