### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Stock Prediction using time series analysis in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#827]
### Is your feature request related to a problem? Please describe.

create a tutorial page explaining creation of advanced time series forecasting model for stock prediction. Adding features to dataset such as moving averages for 3 days back and in future to todays point and dividing date into parts to take day , month and year into account

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 Assigning this issue to you.

From now onwards i am gonna assign level 2 for these tutorials once, as there were instructions provided by organisers for Project Admins.

Make sure to complete this.

**Comment by DarshAgrawal14** [comment]
@vivekvardhan2810 ,is it going to be level 2 for all following tutorial pages?

**Comment by vivekvardhan2810** [comment]
from now @DarshAgrawal14 it's going to be level 2
