### ISSUE TITLE
Improve the Navbar

### ISSUE THREAD

**Issue by Prizag** [ML-Fusion-Lab/ML-Fusion-Lab-Website#828]
### Description

The current navbar design is not providing a smooth and great experince for users.

### Steps to Reproduce

I will improve the navbar structure and design so that users will have better experience.

### Expected Behavior

i expected it to have a better structure and design.

### Actual Behavior

its not having a proper structure

### Screenshots

![Screenshot 2024-10-19 150451](https://github.com/user-attachments/assets/4709745e-f20e-453a-a3dc-f194d480b24b)

### What browser are you seeing the problem on?

- [X] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
