### ISSUE TITLE
Add code of conduct.md

### ISSUE THREAD

**Issue by kartikey369-ind** [ML-Fusion-Lab/ML-Fusion-Lab-Website#83]
I want to add code of conduct.md

**Comment by vivekvardhan2810** [comment]
@kartikey369-ind  sure go ahead make sure to star the repo and join the discord server

also make sure to complete in the next 2 days or it will be assigned to someone else

**Comment by kartikey369-ind** [comment]
done my work https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/pull/84

**Comment by vivekvardhan2810** [comment]
@kartikey369-ind I will check and merge it tomorrow.
