### ISSUE TITLE
Make the header uniform across all the pages

### ISSUE THREAD

**Issue by avogadroB** [ML-Fusion-Lab/ML-Fusion-Lab-Website#834]
### Is your feature request related to a problem? Please describe.

All the headers are different and do not link to all the pages. We need to make this uniform

### Describe the solution you'd like.

Use one template for the footer and place it on all the pages

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/fee77bda-5ce4-483e-a1e3-d2a8cde15386)
![image](https://github.com/user-attachments/assets/f9a240a3-6071-422d-9e6f-ec1e85913a47)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by avogadroB** [comment]
[vivekvardhan2810](https://github.com/vivekvardhan2810) please assign me this issue

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header based issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

please understand
