### ISSUE TITLE
[Mention The Feature]: Payment Gateway Integration to buy courses

### ISSUE THREAD

**Issue by AkshatSharma5** [ML-Fusion-Lab/ML-Fusion-Lab-Website#835]
### Is your feature request related to a problem? Please describe.

Adding a Payment Gateway Integration to buy courses using Credit Card currently.
![image](https://github.com/user-attachments/assets/6d9f6552-300c-4873-9ce9-2e77adbee966)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by AkshatSharma5** [comment]
@vivekvardhan2810 Kindly assign me this issue with appropriate labels of gssoc & hactoberfest

**Comment by vivekvardhan2810** [comment]
hi, we are not looking for this.

so i am closing this issue.

Please understand.
