### ISSUE TITLE
[Mention The Feature]: Add Translation tool

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ML-Fusion-Lab/ML-Fusion-Lab-Website#836]
### Is your feature request related to a problem? Please describe.

I want to add a Translation Tool(all language) properly.

PA please assign me this task.

![image](https://github.com/user-attachments/assets/3c0e8ef7-5c0b-4dde-b406-aa2f7dfa9697)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require any further improvements in the translation tool.

so i am closing this issue.

Please understand.

**Comment by Subhajit-2023-44** [comment]
> for now we don't require any further improvements in the translation tool.
> 
> so i am closing this issue.
> 
> Please understand.

need contribution page ?

**Comment by vivekvardhan2810** [comment]
i think it was also completed.

**Comment by Subhajit-2023-44** [comment]
> i think it was also completed, and don't need any further improvements in that.

Ohh

**Comment by vivekvardhan2810** [comment]
and also this project won't be active from 25th october and me also.

**Comment by Subhajit-2023-44** [comment]
> and also this project won't be active from 25th october and me also.

Ooo
