### ISSUE TITLE
Dark Mode not working correctly due to incorrect CSS in Community Page & Improving its design

### ISSUE THREAD

**Issue by AkshatSharma5** [ML-Fusion-Lab/ML-Fusion-Lab-Website#837]
### Description

The community page cards' headers get invisible in light mode due to incorrect CSS.Also in Dark mode the bg color of cards is white which should have been black.
![image](https://github.com/user-attachments/assets/ca7fb279-7b7b-4642-87dd-297f35341e43)
![image](https://github.com/user-attachments/assets/35b47d0c-7119-4870-b059-023097ebb0ad)

### Steps to Reproduce

Go to https://ml-fusion-lab.netlify.app/pages/community_suport

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@AkshatSharma5 assigning this issue to you.

Make sure to complete this.

And please don't disturb the navbar and the header one's.

please understand.
