### ISSUE TITLE
Redesign Newsletter UI 

### ISSUE THREAD

**Issue by ArchanRD** [ML-Fusion-Lab/ML-Fusion-Lab-Website#839]
The newsletter UI can be redesigned and can be made look much better than now. Currently it is looking like this.
![image](https://github.com/user-attachments/assets/6bbe15f8-199e-4ad5-9f10-395271099313)

- No proper padding
- Not approaching on basis of design

Please assign this issue to me!

**Comment by vivekvardhan2810** [comment]
@ArchanRD assigning this issue to you.

Make sure to complete this.

and don't disturb the other things.

And one more information this project won't be active from october 28th and me also.
