### ISSUE TITLE
To adding the animation effect to social media icons

### ISSUE THREAD

**Issue by Sujal1201** [ML-Fusion-Lab/ML-Fusion-Lab-Website#840]
### Steps to Reproduce

hover effect

### Expected Behavior

no

### Actual Behavior

no

### Screenshots

<img width="261" alt="image" src="https://github.com/user-attachments/assets/bfd9efbb-cfdf-4134-8514-29e3a322977c">

### Additional Information

To more attractive and good experience

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Sujal1201** [comment]
please assign me for this issue

**Comment by vivekvardhan2810** [comment]
this footer and social media icon hover issue was assigned before and he is working on it.

so i am closing this issue.

Please understand.

**Comment by Sujal1201** [comment]
ok
