### ISSUE TITLE
[Mention The Feature]: Add style on features card.

### ISSUE THREAD

**Issue by Adityadhiman0** [ML-Fusion-Lab/ML-Fusion-Lab-Website#841]
### Is your feature request related to a problem? Please describe.

I wan to add style on features card.

### Describe the solution you'd like.

Before

https://github.com/user-attachments/assets/c3b32b98-d3db-4854-885b-f968d1b046e6

### Show us the magic with screenshots

After

https://github.com/user-attachments/assets/e9ec0a37-b84f-4d77-8dac-274251b57b34

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 assigning this issue to you.

make sure to complete this.

and please don't disturb the footer and other things.

as some contributor is working on it.

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 and also this project won't be active from october 25th, including me also.
