### ISSUE TITLE
[Mention The Feature]: ADD A PRELOADER FOR THE WEBSITE 

### ISSUE THREAD

**Issue by HimangshuSharma01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#845]
### Is your feature request related to a problem? Please describe.

Add a Preloader to the website for better user experience 

### Describe the solution you'd like.

I can Add a preloader to this Website 
SAMPLE I HAVE MADE IT PREVIOUSLY I WILL CHANGE THE COLOR ACCORDINGLY 

https://github.com/user-attachments/assets/b5b7d87b-a1a1-4bde-961a-09f8afd203f8

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
we don't need this for now, so i am closing this issue.

Please understand.
