### ISSUE TITLE
Adding icons to the footer

### ISSUE THREAD

**Issue by Ketanop321** [ML-Fusion-Lab/ML-Fusion-Lab-Website#846]
### Is your feature request related to a problem? Please describe.

Adding icons to the footer
 also aligning the contact section of footer  in homepage
![image](https://github.com/user-attachments/assets/45cc6916-deab-4e25-8269-5282d184e421)

adding icons like this in footer

![Screenshot 2024-10-09 180744](https://github.com/user-attachments/assets/6b822497-a3ac-4038-8592-61c66c2b6e16)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
The footer related issue was assigned before and he is resolving it.

And we don't want any further updation of footer.

So I am closing this issue.

Please understand.
