### ISSUE TITLE
[Mention The Feature]: Enhancing the UI for the 'Sign Up Now' page

### ISSUE THREAD

**Issue by Chinmayee-cd** [ML-Fusion-Lab/ML-Fusion-Lab-Website#847]
### Is your feature request related to a problem? Please describe.

The flashy lights showing up as the background even where there is text (Start your Journey Now part) makes it slightly confusing to read through. The 'Start your Journey Now' tag has words overlapping slightly. The home icon takes up quite a bit of space due to which the card is not completely shown on the page.
![image](https://github.com/user-attachments/assets/f739edb2-f72b-46de-bc51-c517798d68f0)

### Describe the solution you'd like.

I would like to make the background black for the right hand side part, adjust the title alignment of the heading and decrease the size of the home page icon.

### Show us the magic with screenshots

After making the changes,
![image](https://github.com/user-attachments/assets/6705a780-baaa-45b8-acbe-9ad2d7f98b7e)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, Thank you for rising this issue.

But for now we are not looking for further improvements in login page.

So I am Closing this issue.

Please understand.
