### ISSUE TITLE
[Mention The Feature]: I would like to implement the mobile responsive design for Testimonial Page.

### ISSUE THREAD

**Issue by ambarmishraa** [ML-Fusion-Lab/ML-Fusion-Lab-Website#849]
### Is your feature request related to a problem? Please describe.

The feature request to implement mobile responsive design for the Testimonial Page is likely related to the problem of ensuring that the page is accessible and user-friendly across various devices. Without a responsive design, the page may not render properly on smaller screens, making the testimonials difficult to read, interact with, or navigate. A lack of responsiveness could result in a poor user experience, especially for mobile users, which may lead to increased bounce rates and reduced user engagement.

### Describe the solution you'd like.

The solution would involve implementing a mobile-responsive design for the Testimonial Page that adapts seamlessly to different screen sizes, including mobile, tablet, and desktop. Key aspects of the solution include:

Flexible Layout: Use CSS Grid or Flexbox to ensure that the layout adjusts dynamically based on the screen size. For instance, testimonials could be displayed in a grid on larger screens but stack vertically on smaller devices.

Responsive Typography: Ensure that font sizes, spacing, and padding adjust appropriately on mobile devices. This includes making text large enough to read on small screens while avoiding excessive line lengths.

Optimized Images: Testimonial images (if any) should be responsive, scaling appropriately without losing quality. This could be achieved using responsive img tags with max-width: 100%, or CSS background-image with media queries.

Navigation and Interactivity: On mobile, navigation elements should be simplified (e.g., using a hamburger menu) to make the page easy to use with touch inputs. Ensure buttons and links are adequately sized for tapping.

Media Queries: Use CSS media queries to apply specific styles based on device width. This allows you to hide or adjust certain elements that may be unnecessary or crowded on smaller screens.

Performance Optimization: Minimize the loading time for mobile users by optimizing assets (such as compressed images, lazy-loading) and ensuring the page structure is efficient.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/dd41702f-3a69-48dc-9279-b55565ee15ed)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ambarmishraa assigning this issue to you.

Make sure to complete this.

But I won't be active from 11 pm.

**Comment by ambarmishraa** [comment]
Ok i will do it
