### ISSUE TITLE
BUTTON on NAVBAR ANIMATION EFFECT 

### ISSUE THREAD

**Issue by sahhoArjun097** [ML-Fusion-Lab/ML-Fusion-Lab-Website#85]
i can style button on the NAVBAR and provide them animation .
![image](https://github.com/user-attachments/assets/f0f93d0b-4dcb-41ff-992c-b5fe0ef276b3)

Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl.

**Comment by vivekvardhan2810** [comment]
Hi, @sahhoArjun097, I Will check and assign the issue by tomorrow.

**Comment by sahhoArjun097** [comment]
please assign me this issue

**Comment by vivekvardhan2810** [comment]
@sahhoArjun097 I will assign you the issue, Once I resolve the conflicts.

**Comment by sahhoArjun097** [comment]
ok
