### ISSUE TITLE
[Mention The Feature]: Community Support Section is not Responsive

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [ML-Fusion-Lab/ML-Fusion-Lab-Website#850]
### Is your feature request related to a problem? Please describe.

Community Support Section is not responsive for all screen sizes.

### screenshots

![image](https://github.com/user-attachments/assets/a5335993-0376-4c8b-a23e-227e506255e3)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by sandeepmaddheshiya** [comment]
@vivekvardhan2810 Please assign to me, I'll do this asap!

**Comment by vivekvardhan2810** [comment]
@sandeepmaddheshiya assigning this issue to you.

Make sure to complete this.

But please do work on other projects also.
