### ISSUE TITLE
Subscribe section input field functionality

### ISSUE THREAD

**Issue by Devanshu1603** [ML-Fusion-Lab/ML-Fusion-Lab-Website#859]
### Description

On clicking on the input field of Subscribe section on home page it is rendering the user to community contact page .

### Steps to Reproduce

Instead of  rendering the user to community contact page it must pop an alert that you have subscribe successfully.

### Screenshots

https://github.com/user-attachments/assets/0f3e846a-b0ed-4665-be41-7b53ec28dbf8

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Devanshu1603** [comment]
@vivekvardhan2810  please assign me this issue under gssoc-extended

**Comment by vivekvardhan2810** [comment]
@Devanshu1603 from my side it is coming good.

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.

**Comment by Devanshu1603** [comment]
@vivekvardhan2810  ok . Thanks for your valuable concern.
