### ISSUE TITLE
[Mention The Feature]: I would like to change the the logo 

### ISSUE THREAD

**Issue by Aaryafalle** [ML-Fusion-Lab/ML-Fusion-Lab-Website#860]
### Is your feature request related to a problem? Please describe.

please assign me this issue i would like to change the logo
![LOGO ml fusion labs](https://github.com/user-attachments/assets/d76b1309-26db-4fc1-88a3-3971801735ff)
@vive

### Show us the magic with screenshots

![LOGO ml fusion labs](https://github.com/user-attachments/assets/9809ac01-4274-4854-8505-d25babe5a647)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we are not looking for any logo updation.

So i am closing this issue.

Please understand.
