### ISSUE TITLE
[Mention The Feature]: add hover effect on a button in dark theme

### ISSUE THREAD

**Issue by vedant3337** [ML-Fusion-Lab/ML-Fusion-Lab-Website#862]
### Is your feature request related to a problem? Please describe.

I want to add hover effect on a button in dark theme on home page.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/8a03fdd4-abb2-405f-9a4c-715894ef6c99)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now it is not required.

So I am closing this issue.

Please understand.
