### ISSUE TITLE
Adding a Quiz test feature for the course "Python For Everybody"

### ISSUE THREAD

**Issue by SoumyaU25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#863]
I want to add a Quiz test for  the course "Python For Everybody" . So  which will tell a student based upon their performance in a this topic that he/she is at beginner , Intermediate or advance level and on that basis the Student can decide that this course is preferable for them. It will make the site more Interactive for users.

Please assign me this issue under gssoc-ext label.

**Comment by vivekvardhan2810** [comment]
For now we are not looking for this.

So I am closing this issue.

Please understand.
