### ISSUE TITLE
Add  `Business Development`  &  `Autonomous System`  Under Courses

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#864]
### Is your feature request related to a problem? Please describe.

These pages are not built yet.

### Describe the solution you'd like.

I will develop a new page that connects to both   `Business Development`  &  `Autonomous System` Course card separately. This page will include detailed information about the course, covering the following aspects:
- An introduction and its prerequisites.
- A step-by-step breakdown of how the course will be structured.
- A list of additional courses related to it.

@vivekvardhan2810 

### Show us the magic with screenshots

![Screenshot 2024-10-18 115057](https://github.com/user-attachments/assets/222db3b1-da3a-4766-b9bf-10ba34cd6a74)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810 please assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this.
