### ISSUE TITLE
Adding More Valuable Resources to the Resource Library Section. 

### ISSUE THREAD

**Issue by SoumyaU25** [ML-Fusion-Lab/ML-Fusion-Lab-Website#867]
I want to add more resources to the Resource Library Section .I could enrich it by adding a few more valuable resources that cover some emerging topics in the field of Machine Learning.
I believe these additions could further enhance the utility of the resource library for both beginners and more experienced learners. Let me know what you think, and I’d be happy to make the necessary updates.

Please assign me this issue under gssoc-ext label.
<img width="905" alt="r8" src="https://github.com/user-attachments/assets/de39fc08-00a2-4fa9-a851-ae1f9199f7e1">

**Comment by vivekvardhan2810** [comment]
@SoumyaU25 for now I am assigning this issue to you.

Make sure to complete this.

And please don't create multiple issues one by one.

Please understand.

**Comment by vivekvardhan2810** [comment]
And @SoumyaU25  this Project And me (Project Admin) will remain inactive from October 28th.

Take your time. but make sure to complete it before the mentioned date i.e October 27th.

**Comment by SoumyaU25** [comment]
Okay @vivekvardhan2810  sure I will complete it before 27th.
