### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Face Landmark Detection  in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#868]
### Is your feature request related to a problem? Please describe.

Face landmark detection is the task of mapping a person's face for better computing and processing by software and machines. These landmarks provide a detailed geometric map of the face, enabling various applications such as

- Entertainment
- Healthcare
- Security
- Sentiment Analysis
- Gaming

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.
