### ISSUE TITLE
[Mention The Feature]: Want to add FAQ section in feedback or community support page

### ISSUE THREAD

**Issue by toshankanwar** [ML-Fusion-Lab/ML-Fusion-Lab-Website#869]
### Is your feature request related to a problem? Please describe.

hello @vivekv2810 

ya it is said to be big issue if your user want to know answer about some question where he actually go. in faq section

### Describe the solution you'd like.

adding a faq section that that helps new user to know more about the aim of webpage

### Additional context.

once you assign i start working on that

thankyou

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now It is not required for faq one's.

So I am closing this issue.

Please understand.
