### ISSUE TITLE
Improving the HOME Page and making the website responsive.

### ISSUE THREAD

**Issue by samriddhitiwary** [ML-Fusion-Lab/ML-Fusion-Lab-Website#87]
The cards, Newsletter and footer are not responsive and I will make it responsive and will surely improve the UI also
![image](https://github.com/user-attachments/assets/a87d43b1-147d-4193-a15e-93d588cf85ce)

**Comment by samriddhitiwary** [comment]
@vivekvardhan2810 Could please assign this issue to me under the GSSoC-ext and Hactoberfest label

**Comment by Ishika-codeit** [comment]
hey kindly assign this to me i try my best to make it responsive and attractive...

**Comment by vivekvardhan2810** [comment]
@samriddhitiwary this issue was fixed, so i am closing this issue.
