### ISSUE TITLE
[Mention The Feature]: Enhance css of term and condition

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ML-Fusion-Lab/ML-Fusion-Lab-Website#872]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/6f67db2d-8541-4e21-83c8-328f43a2292a)
i can improve its styling in more better way 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Sawan-Kushwah firstly please make the required changes that i have asked you in the Pull Request.

And i didn't merged that Pull Request yet.

**Comment by vivekvardhan2810** [comment]
and for now we don't require any improvements in this page.

so i am closing this issue.

please understand.
