### ISSUE TITLE
[Custom Curved Navigation Bar UI Design]

### ISSUE THREAD

**Issue by Priyanshi0112** [ML-Fusion-Lab/ML-Fusion-Lab-Website#874]
### Is your feature request related to a problem? Please describe.

This navigation bar UI is a modern, curved design that provides an aesthetically pleasing and minimalistic look. The navbar consists of distinct, rounded icons for navigation options. The clicked  button will be  visually separated from the rest of the menu items through a creative and curved background effect, while the other options maintain a clean, uncluttered appearance.

This design is ideal for mobile or responsive interfaces as it simplifies navigation, provides a fresh visual experience, and highlights the currently active option. It uses a smooth curve and icon-based interface for ease of recognition and accessibility.

### Show us the magic with screenshots

Changing the UI of navbar like this :
![navigation bar](https://github.com/user-attachments/assets/f08c0d33-2c39-4b46-b222-25a15cd0c18e)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
