### ISSUE TITLE
in the contact us form mobile number is taking more than 10 digits

### ISSUE THREAD

**Issue by Ritikabiswas** [ML-Fusion-Lab/ML-Fusion-Lab-Website#875]
### Description

in the contact us form mobile number is taking more than 10 digits

### Steps to Reproduce

we can modify it to take only 10 digits

### Screenshots

![Screenshot 2024-10-20 124413](https://github.com/user-attachments/assets/161a5cbe-da02-4cfd-bf8e-1cd5e38cbe9d)

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Ritikabiswas assigning this issue to you.

Make sure to complete this fast.

**Comment by Ritikabiswas** [comment]
hello I checked and corrected it but actually you already have applied that feature but you were taking 10–15 digits. I thought you had not applied any constraints. So it was not a big change .will you accept pull request?

**Comment by vivekvardhan2810** [comment]
yes, i will accept tbe PR, but i think i won't assign you the labels like level 1, but  i will add gssoc-ext and hacktoberfest labels, as it is a minor change.

will it be okay for you. @Ritikabiswas

**Comment by Ritikabiswas** [comment]
OK fine. Yeah its very minor change

**Comment by vivekvardhan2810** [comment]
okay, i will merge the PR with gssoc-ext and hacktoberfest accepted label.

**Comment by vivekvardhan2810** [comment]
And @Ritikabiswas this project won't be active from 22nd and me also.

**Comment by Ritikabiswas** [comment]
ok
