### ISSUE TITLE
[Mention The Feature]: Add icons on contact page.

### ISSUE THREAD

**Issue by Adityadhiman0** [ML-Fusion-Lab/ML-Fusion-Lab-Website#876]
### Is your feature request related to a problem? Please describe.

i want to add icon on contact form . I have attached screenshot before and after were i want to change for better under standing.

### Additional context.

Before
![Screenshot 2024-10-20 125605](https://github.com/user-attachments/assets/42e14b7c-9efa-43ed-8262-faae281e3c72)

### Show us the magic with screenshots

After
![Screenshot 2024-10-20 125502](https://github.com/user-attachments/assets/9c862424-2f49-4fd5-a51d-9c7db70e66a2)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Adityadhiman0** [comment]
Please assign me this issue. I have committed my code in fork.

**Comment by vivekvardhan2810** [comment]
@Adityadhiman0 assigning this issue to you.

Make sure to complete this.

And please do contribute to other projects also.

**Comment by vivekvardhan2810** [comment]
And @Adityadhiman0 don't commit your code in your fork until i assign you the issue.

**Comment by vivekvardhan2810** [comment]
And please do contribute to other projects also.
