### ISSUE TITLE
Enhance Navbar and Add Video Links to Modules in Courses Section

### ISSUE THREAD

**Issue by falakniyaz94** [ML-Fusion-Lab/ML-Fusion-Lab-Website#878]
### Enhance Navbar and Add Video Links to Modules in Courses Section
I would like to propose an enhancement for the navbar and the modules section of the website. This includes:

1. **Navbar Improvement:** Improve the design and responsiveness of the current navbar for better user experience.

2. **Adding Video Links to Courses Section:** Include relevant video links within the course modules to provide additional resources for users.

These enhancements aim to make the navigation more intuitive and improve the learning experience by providing multimedia resources.

I would be excited to work on implementing these changes and help take the website to the next level!
@vivekvardhan2810 

Best Regards
@falakniyaz94

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

and we are not looking for Adding Video Links to Courses Section.

So I am closing this issue.

please understand.
