### ISSUE TITLE
[Mobile dropdown menu]: 

### ISSUE THREAD

**Issue by Kehinde13** [ML-Fusion-Lab/ML-Fusion-Lab-Website#880]
### Is your feature request related to a problem? Please describe.

The items in the dropdown are not centered

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Kehinde13** [comment]
Can you assign this to me under hactoberfest

**Comment by vivekvardhan2810** [comment]
for now it is not required.

so i am closing this issue.

Please Understand.

and don't create multiple issues with the same context.

**Comment by Kehinde13** [comment]
Ok, is there any issue you can assign to me?
