### ISSUE TITLE
[Mention The Feature]: Add enhancement in navbar

### ISSUE THREAD

**Issue by mehendisil2004** [ML-Fusion-Lab/ML-Fusion-Lab-Website#881]
### Is your feature request related to a problem? Please describe.

The navbar is to broad with no css applied separately to light and dark mode

### Describe the solution you'd like.

I'll make it compact with rounded corner buttons

### Describe alternatives you've considered.

Separate color combo for light and dark mode

### Additional context.

May try to add responsiveness if assigned with level 3 or higher (gssoc ext, hacktoberfest)

### Show us the magic with screenshots

![Screenshot 2024-10-20 154630](https://github.com/user-attachments/assets/095caf6c-971d-4197-adf2-a152eb08653a)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
