### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Image Deblurring using CNN in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#883]
### Is your feature request related to a problem? Please describe.

Despite the prevalence of high-precision cameras, the world is full of low-quality, blurry images .It can be particularly useful in fields such as photography, medical imaging, and satellite imagery. Therefore , i want to develop a model that can deblur images

Describe the solution you'd like

Data preparation and processing
Developing a multi-scale CNN or GAN model
Implement various evaluation metrics such as Peak Signal-to-Noise Ratio (PSNR)
Optimize the model for inference speed; create and deploy use-friendly web application

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.
