### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Earthquake Prediction Model with Machine Learning  in projects page website.

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#884]
### Is your feature request related to a problem? Please describe.

create a model for the task of Earthquake Prediction using Machine Learning and the Python programming language. Predicting earthquakes is one of the great unsolved problems in the earth sciences.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 please complete the previous issue which i have assigned you.

This is the warning.

Don't create multiple issues at single time.

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 make sure to complete this.
