### ISSUE TITLE
[Mention The Feature]: make the about page mobile responsive

### ISSUE THREAD

**Issue by Kehinde13** [ML-Fusion-Lab/ML-Fusion-Lab-Website#885]
### Is your feature request related to a problem? Please describe.

make the about page mobile responsive

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Kehinde13 for now i am assigning you.

make sure to complete it.

**Comment by Kehinde13** [comment]
Ok

**Comment by vivekvardhan2810** [comment]
And don't change anything in about us page, please.
