### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Skill Gap Analysis and Course Recommendation using Gemini LLM, Proxy curl API and Linkedin API in project page website.

### ISSUE THREAD

**Issue by J-B-Mugundh** [ML-Fusion-Lab/ML-Fusion-Lab-Website#891]
### Is your feature request related to a problem? Please describe.

I dont see project with LLMs. So, I want to start with this wonderful project. 

### Describe the solution you'd like.

Skill Gap Analysis using fine-tuning of Gemini LLM and integration with Proxy curl API and Linkedin API

### Additional context.

This will be an advanced level LLM based project with integration of proxy curl and linkedin api for skill gap analysis and course recommendation. 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@J-B-Mugundh assigning this issue you.

Makes sure to complete this.

This is the warning.

Don't create multiple issues at single time.

Please understand.

you have still 7 days of time to create issues.

this Project And me (Project Admin) will remain inactive from October 28th.

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh assigning this issue you.
> 
> Makes sure to complete this.
> 
> This is the warning.
> 
> Don't create multiple issues at single time.
> 
> Please understand.
> 
> you have still 7 days of time to create issues.
> 
> And the organisers think that i am in favour of you, so please understand.
> 
> this Project And me (Project Admin) will remain inactive from October 28th.

Yeah okay bro. Is it not allowed to create a new issue once I complete one? Actually, I'm not repeating things and taking time to do. I understand 🙂

**Comment by vivekvardhan2810** [comment]
@J-B-Mugundh no problem you can create the issue, but take your time, that's all.

**Comment by vivekvardhan2810** [comment]
@J-B-Mugundh anyways wishing you all the best and keep contributing to open source.

**Comment by J-B-Mugundh** [comment]
Sure! Thank you bro 😊

**Comment by vivekvardhan2810** [comment]
@J-B-Mugundh Don't worry about that PR, you can continue, some random guy don't know has created PR, he didn't look the guidelines properly.

You can continue with the work.

**Comment by J-B-Mugundh** [comment]
> @J-B-Mugundh Don't worry about that PR, you can continue, some random guy don't know has created PR, he didn't look the guidelines properly. And that PR is different. he don't know.
> 
> You can continue with the work.

Okay man!

**Comment by noobremon** [comment]
Please assign this to me @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@noobremon this issue was assigned before and he is working on it.

This is the warning from my side.

Don't spam in other's issues.

Please understand.
