### ISSUE TITLE
[Mention The Feature]: Add animations to improve user experience 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [ML-Fusion-Lab/ML-Fusion-Lab-Website#893]
### Is your feature request related to a problem? Please describe.

we can add animation on our main pages to enhance user experience as it give good look to our website and smoothness

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now it is now required.

So i am closing this issue.

Please understand.
