### ISSUE TITLE
Missing Details in "About This Course" Section on Courses Page

### ISSUE THREAD

**Issue by iarmaanx** [ML-Fusion-Lab/ML-Fusion-Lab-Website#894]
### Description

It appears that the "About this course" section on the courses page is currently empty, with no details available for users to understand what the course entails. This can create confusion for potential students who are looking for more information about the course content

### Steps to Reproduce

Steps to Reproduce:

1. Go to the ML Fusion Lab website.
2. Navigate to the Courses page.
3. Click on any course.
4. Scroll to the "About this course" section – notice that no details are provided.

### Screenshots

![Screenshot 2024-10-20 210319](https://github.com/user-attachments/assets/48752726-ea60-4146-9c3d-94cfae3eef65)
<img width="957" alt="Screenshot 2024-10-20 210332" src="https://github.com/user-attachments/assets/af9c5d57-2961-4b72-986b-6bba2516efb4">

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by iarmaanx** [comment]
Consider assigning this to me.

**Comment by vivekvardhan2810** [comment]
@iarmaanx assigning this issue to you.

Make sure to complete it.

And don't disturb the remaining one's in course page.

please do it perfectly.

**Comment by iarmaanx** [comment]
Thanks @vivekvardhan2810 for assigning the issue.
