### ISSUE TITLE
Implement Chatbot on Website for Improved User Engagement and Support.

### ISSUE THREAD

**Issue by SRV30** [ML-Fusion-Lab/ML-Fusion-Lab-Website#896]
### Is your feature request related to a problem? Please describe.

Many website visitors often face difficulties in navigating or finding the information they need quickly. This can lead to frustration and lost potential leads. In addition, customer support teams may be overwhelmed with repetitive queries that could be easily automated. Users expect fast, 24/7 support, and without a real-time solution in place, there's a risk of poor customer experience, decreased engagement, and loss of business opportunities.

### Describe the solution you'd like.

I would like to implement a chatbot on the website that can handle common user queries, guide users through the site, provide personalized product recommendations, and assist with basic troubleshooting. 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this one is already there in website please check it before creating an issue.

So i am closing this issue.

Please Understand.

**Comment by SRV30** [comment]
![image](https://github.com/user-attachments/assets/cb2ce276-3534-4596-ad63-4cf4d4e0b0c9)
actually it is not shown on the front page

**Comment by vivekvardhan2810** [comment]
![image](https://github.com/user-attachments/assets/1b3aa079-1195-4857-b9e1-b98d9723990a)
it is showing

**Comment by SRV30** [comment]
> ![image](https://private-user-images.githubusercontent.com/91594529/378206197-1b3aa079-1195-4857-b9e1-b98d9723990a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDI0MTEsIm5iZiI6MTcyOTQ0MjExMSwicGF0aCI6Ii85MTU5NDUyOS8zNzgyMDYxOTctMWIzYWEwNzktMTE5NS00ODU3LWI5ZTEtYjk4ZDk3MjM5OTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE2MzUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ODc4NDQ4ZTE0MWQ2M2UzMTBjZTVjNzhiYzFmNTc3MmU1MmRkNTkxOWU3ZTkwZmFiMzM4N2JkMjEyNzUyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zdU2h-plSzLtuJcZqaqsZwAW-8LGvPQ-LUzKfKdsJiU) it is showing

ok, thank u
