### ISSUE TITLE
Blend logo background with the footer and nav bar 

### ISSUE THREAD

**Issue by HimangshuSharma01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#897]
### Description

![Screenshot 2024-10-20 221526](https://github.com/user-attachments/assets/485ddaa1-a7e2-4ff4-a9a7-42589e773733)
![image](https://github.com/user-attachments/assets/9bd5270c-459c-4c41-8b9c-25beb6e927e5)
I can fix this 

### Steps to Reproduce

You see the nav bar and footer 

### Expected Behavior

I could be blended properly for good looks

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HimangshuSharma01 assigning this issue to you.

make sure to complete this.

**Comment by vivekvardhan2810** [comment]
And @HimangshuSharma01 this project won't be active from 27th october.

**Comment by HimangshuSharma01** [comment]
please add level 2
