### ISSUE TITLE
Improving navbar and improving navgation easeness

### ISSUE THREAD

**Issue by SamparkBhol** [ML-Fusion-Lab/ML-Fusion-Lab-Website#899]
### Description

The navbar currently looks like design as boxes , cards and has improper padding
![image](https://github.com/user-attachments/assets/2a0a1cc2-071a-4233-903e-006ad4c950e1)

### Steps to Reproduce

Review and adjust the CSS margin and padding properties for all affected elements.
Ensure uniform spacing and alignment throughout the landing page to create a cleaner, more organized design.

### Expected Behavior

To get it designed in a better and professional looking manner

### Screenshots

![image](https://github.com/user-attachments/assets/f0b594f8-5cd9-40a5-8987-61ce5772a9d2)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
