### ISSUE TITLE
Re-designing of About us page  

### ISSUE THREAD

**Issue by Amarjeetkumart** [ML-Fusion-Lab/ML-Fusion-Lab-Website#9]
![1st](https://github.com/user-attachments/assets/73f982cc-1e98-4d2a-81bb-883babf6bc35)

The About Page re-design focuses on providing a clear, welcoming introduction to your open-source project while offering essential information about your vision, team, and what the project offers. It includes a streamlined layout that highlights the project’s goals, core values, and key features, alongside an easy-to-navigate section for contact details

**Comment by vivekvardhan2810** [comment]
@Amarjeetkumart please complete this issue in the next 2 days.

**Comment by vivekvardhan2810** [comment]
make sure to fork and star this repo.

and join the discord: https://discord.gg/FZxBRpTEeH
