### ISSUE TITLE
[Mention The Feature]: Add Signup and Login form for view status of course completion.

### ISSUE THREAD

**Issue by govindbairi** [ML-Fusion-Lab/ML-Fusion-Lab-Website#900]
### Is your feature request related to a problem? Please describe.

Yes, the feature request for a Signup and Login form for users to view the status of course completion is related to several common problems faced by online learning platforms and users.

### Describe the solution you'd like.

I propose implementing a Signup and Login system that allows users to securely create accounts and access their personalized dashboard. This dashboard will display their course completion status and progress, motivating them to stay engaged with their learning. Additionally, the system will enhance security and provide valuable data for course administrators to improve the platform.

### Show us the magic with screenshots

![Screenshot 2024-10-21 020230](https://github.com/user-attachments/assets/24c61f80-83a4-40a0-a6da-e88913ddfd67)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Thank you for raising this issue.

But we are not looking for this.

So I am Closing this issue

Please understand.
