### ISSUE TITLE
Improve the "Contact Us" Section Banner on the Website

### ISSUE THREAD

**Issue by iarmaanx** [ML-Fusion-Lab/ML-Fusion-Lab-Website#904]
### Is your feature request related to a problem? Please describe.

 The current "Contact Us" section banner on the ML Fusion Lab website needs improvement to enhance its visual appeal and user engagement. The existing design appears basic and does not align with the overall theme of the website.
### Current Issues:

-The banner lacks visual contrast and is not eye-catching.
-The text in the banner is hard to read due to insufficient contrast with the background.
-The overall layout feels static and does not match the dynamic feel of the rest of the website.

## Solution - 
I can create a banner for Contact Us Page that will:
-Use more engaging visuals such as illustrations 
-Include a bold, visible button or link with a clear call-to-action like "Get in Touch" or "Contact Us".

## Screenshot
![Screenshot 2024-10-21 060846](https://github.com/user-attachments/assets/4b0c8178-c7e7-4a56-b607-f2909206e54e)

Link to page - https://ml-fusion-lab.netlify.app/pages/contact

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now it is not required.

So I am closing this issue.

Please understand.
