### ISSUE TITLE
Redesign Navbar 

### ISSUE THREAD

**Issue by shubhagarwal1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#905]
- Make it thin 
- align nav items consistently with less space 
- Make it responsive for mobile and desktop 
<img width="1440" alt="Screenshot 2024-10-21 at 6 54 48 AM" src="https://github.com/user-attachments/assets/dd192e76-3003-4bfc-bab0-fb6adcffd68c">

**Comment by shubhagarwal1** [comment]
> I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.
> 
> we are not looking for navbar updates for now, as it was done and changes many times before.
> 
> So I am closing this issue.
> 
> please understand.
@vivekvardhan2810 
I understand you concern and follow the same for the further contribution, may i knwo anything specific you are palnning to implemetnt, would love to work on that.

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 can you improve the page of privacy policy

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 can you improve the page of privacy policy.
> 
> Like UI of that Page.

what changes are you expecting on the page can you provide some details please.

**Comment by vivekvardhan2810** [comment]
![Screenshot_2024-10-21-09-07-32-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/ad1361c6-5e3f-49d4-9ed8-efd5ea137bd1)

Like in this page.

ADDING SOME ANNIMATIONS
UI IMPROVEMENT
IMPROVEMENTS IN FOOTER

Means the footer is not looking same as like in the home page.

And the styling also.

**Comment by shubhagarwal1** [comment]
> ![Screenshot_2024-10-21-09-07-32-70_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/91594529/378265567-ad1361c6-5e3f-49d4-9ed8-efd5ea137bd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0ODI0MTMsIm5iZiI6MTcyOTQ4MjExMywicGF0aCI6Ii85MTU5NDUyOS8zNzgyNjU1NjctYWQxMzYxYzYtNWUzZi00OWQ0LTllZDgtZWZkNWVhMTM3YmQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIxVDAzNDE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NDYwZmQ2YWU3MGQ0YzNmNmVkY2U2ZjZlYTE1Y2I2ZWRiNWE3MTRjNTNhNjljNzU0MjcwMTIyNTg1MzE0N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.R_BFVyoFQ3OCe2ekYNCudBHDsMCbQfC2GWlMvC-OKAM)
> 
> Like in this page.
> 
> ADDING SOME ANNIMATIONS UI IMPROVEMENT IMPROVEMENTS IN FOOTER
> 
> Means the footer is not looking same as like in the home page.
> 
> And the styling also.

Sure i can do this, can i rasie a different issue?

**Comment by vivekvardhan2810** [comment]
Yes, you can raise a different issue.

And one more thing, this project will remains inactive from 24th, due to some reasons.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 Yes, you can raise a different issue.
> 
> And one more thing, this project will remains inactive from 24th, due to some reasons.

I will complete the doings by EOD will that be okay? Will my PR will get merged ?

**Comment by vivekvardhan2810** [comment]
Yes, @shubhagarwal1 your PR will be merged and points will be counted.
