### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [ML-Fusion-Lab/ML-Fusion-Lab-Website#906]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @vivekvardhan2810 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by vivekvardhan2810** [comment]
@smog-root auto comment for issue open is there, but auto comment on closed issue is not there.

And auto comment on PR raise is there, but Auto comment is not there for PR merged.

I will assign you this issue, if you work on 2 things only for level 2

1. Auto comment on issue Closed.
2. Auto comment on PR mergs.

Will.this be okay for you.

**Comment by smog-root** [comment]
Okay. I will work on it for level2! @vivekvardhan2810

**Comment by vivekvardhan2810** [comment]
@smog-root assigning this issue to you.

Make sure to complete this.

Do work on these 2 only.

1.Auto comment on issue Closed.

2. Auto comment on PR mergs.

**Comment by smog-root** [comment]
@vivekvardhan2810 Auto comment for  issue open is not there!!

if it is there. why there is no comment on this issue!!

**Comment by vivekvardhan2810** [comment]
![image](https://github.com/user-attachments/assets/4bcb7f8e-627d-4415-8410-86c09f417115)

**Comment by smog-root** [comment]
okay i will work on those two!
