### ISSUE TITLE
REVAMP Privacy Policy Page 

### ISSUE THREAD

**Issue by shubhagarwal1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#907]
- ADDING SOME ANNIMATIONS
- UI IMPROVEMENT
- IMPROVEMENTS IN FOOTER to make it same as home page
- Fix styling
hey @vivekvardhan2810 please assign me this task

**Comment by vivekvardhan2810** [comment]
@shubhagarwal1 assigning this issue to you.

Make sure to complete this.

Make sure it looks good.

And do it good.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 assigning this issue to you.
> 
> Make sure to complete this.
> 
> Make sure it looks good.
> 
> And do it good.

sure ...
