### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Predicting Fuel Efficiency with Machine Learning in projects page website

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#909]
### Is your feature request related to a problem? Please describe.

machine learning  to predict fuel efficiency,  aim to predict the output of a continuous value, such as a price or a probability. 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 make sure to complete this.
