### ISSUE TITLE
Add one remaining `Cloud Computing` Course Detail Page

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#910]
### Is your feature request related to a problem? Please describe.

this section is yet to be built

### Describe the solution you'd like.

I will develop a new page that connects to  `Cloud Computing` Course card . This page will include detailed information about the course, covering the following aspects:

- An introduction and its prerequisites.
- A step-by-step breakdown of how the course will be structured.
- A list of additional courses related to it.

@vivekvardhan2810 

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/440f6b6a-1797-4012-ae93-eff286ca3327)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this.
