### ISSUE TITLE
[Mention The Feature]:  Add complete tutorial page for Next-Word Predictor Model  in projects page website

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#914]
### Is your feature request related to a problem? Please describe.

create a tutorial page

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 for now i am assigning this issue to you.

Make sure to complete this.

And please create the issues atleast 1 to 2 per day, as you will be in safer side, and they don't consider it as spamming or favouring, please understand.
