### ISSUE TITLE
Button lacks animation, needs improvement for better visual appeal

### ISSUE THREAD

**Issue by akhulisumit** [ML-Fusion-Lab/ML-Fusion-Lab-Website#915]
### Is your feature request related to a problem? Please describe.

The current buttons on the website/application lack animation and visual appeal, making the user experience feel static and less engaging. To improve the design and user interaction, I propose adding smooth animations such as hover effects, transitions, and other enhancements to make the buttons look more attractive and responsive.

### Describe the solution you'd like.

This solution will involve:

Adding hover animations (e.g., color change, scaling, shadow effects)
Implementing smooth transitions for better interaction
Ensuring the animations are lightweight and do not affect performance
These improvements will help create a more dynamic and visually appealing interface, enhancing the overall user experience.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by akhulisumit** [comment]
Please assign me this issue

**Comment by vivekvardhan2810** [comment]
thank you for raising this issue.


I have seen many navbar issues and button issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

**Comment by vivekvardhan2810** [comment]
and @akhulisumit this project won't be active from 23rd october, make sure to contribute to other projects also.

please understand.
