### ISSUE TITLE
Footer is not responsive for all devices in section about us, contact us and projects

### ISSUE THREAD

**Issue by adityalaxkar123** [ML-Fusion-Lab/ML-Fusion-Lab-Website#918]
![Screenshot_2024-10-21-18-22-36-03_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/e84486f9-01bd-4250-b7f6-9eb03ec42543)

Me a GSSOC'24 extended member can you assign it to me

**Comment by vivekvardhan2810** [comment]
see footer is not responsive in only mobile one's right
