### ISSUE TITLE
Improving UI of NavBar

### ISSUE THREAD

**Issue by Dishika18** [ML-Fusion-Lab/ML-Fusion-Lab-Website#919]
### Description

NavBar is not looking much impressive and is very broad in length. I can make it look impressive and responsive.

### Steps to Reproduce

Please assign this issue to me under `gssoc-ext` & `hacktoberfest-accepted`. 

### Screenshots

![Screenshot 2024-10-21 183524](https://github.com/user-attachments/assets/de858a93-e8df-45b7-9cb2-e9fd791c2ff3)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
