### ISSUE TITLE
[Enhance]: bad navbar , update UI navbar . 

### ISSUE THREAD

**Issue by Jashwanth-rit** [ML-Fusion-Lab/ML-Fusion-Lab-Website#920]
### Is your feature request related to a problem? Please describe.

Description: The current navigation bar (navbar) has a suboptimal design that negatively impacts user experience and overall aesthetics. We need to update the UI of the navbar to create a more modern, user-friendly, and visually appealing interface.

### Show us the magic with screenshots

![Screenshot 2024-10-21 191201](https://github.com/user-attachments/assets/d4284be5-ec0d-4fc4-960c-3cfeba0faad8)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

**Comment by Jashwanth-rit** [comment]
ok sir , i close this.

**Comment by vivekvardhan2810** [comment]
And this project won't be active from october 24th, and me also, 

reason being due to some of my works.
