### ISSUE TITLE
[FEAT]: Add Blog page

### ISSUE THREAD

**Issue by ArchanRD** [ML-Fusion-Lab/ML-Fusion-Lab-Website#921]
### Is your feature request related to a problem? Please describe.

It is a new feature.

### Describe the solution you'd like.

To add a blog page where posts about new tech is posted. 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@ArchanRD please check the existing issues.

this issue was assigned also.

**Comment by ArchanRD** [comment]
Ohh I am sorry. I might have missed it!
