### ISSUE TITLE
[Mention The Feature]: Header buttons and text are too small

### ISSUE THREAD

**Issue by Jyothishree2k5** [ML-Fusion-Lab/ML-Fusion-Lab-Website#925]
### Is your feature request related to a problem? Please describe.

The header buttons and their text are too small, making them difficult to interact with and read, especially on mobile devices.

### Describe the solution you'd like.

Increase the size of the header buttons and their text for better usability and readability.

### Describe alternatives you've considered.

Adjusting only the padding around the buttons.
Making the font size larger without changing button size.

### Additional context.

Larger buttons will enhance user experience, especially for those on smaller screens.
Please assign it to me under gssco ext and hacktoberfest

### Show us the magic with screenshots

![Screenshot 2024-10-21 212608](https://github.com/user-attachments/assets/7a2c5743-22e7-4d0b-9ab7-d66fca9e475d)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header based issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar and header updates for now, as it was done and changes many times before.

please understand.
