### ISSUE TITLE
Few Issues In script.js

### ISSUE THREAD

**Issue by rimmon1234** [ML-Fusion-Lab/ML-Fusion-Lab-Website#926]
### Description

Issue 1: You are handling the theme toggle in two different sections (themeSwitch and themeToggle), which could create conflicts or confusion.
Issue 2 : If either themeSwitch or themeToggle doesn't exist in the DOM, the script will throw an error.

issue 3: Currently, you're applying dark mode to the body, header, and footer separately, which can be redundant.

issue 4. The onscroll event is triggered many times during a scroll, which can cause performance issues.

### Steps to Reproduce

For Issue 1: We Can Consolidate the theme toggle functionality to avoid redundancy.
For Issue 2:We Can Add null checks to ensure the elements exist before adding event listeners
For Issue 3: If the dark mode affects the entire page, you can apply it just to body and let CSS handle child elements. For example, using a .dark-mode class that applies to everything inside body.
For Issue 4: We Can Use a debounce function to limit how often updateProgressBar runs during a scroll event.

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
thank you for raising this issue.

but for now we are not looking for further improvements in toggle side or any update on script.js also.

so i am closing this issue.

please understand.
