### ISSUE TITLE
[Mention The Feature]: add Faq

### ISSUE THREAD

**Issue by yeshwanth-ds** [ML-Fusion-Lab/ML-Fusion-Lab-Website#927]
### Is your feature request related to a problem? Please describe.

add faq

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
this issue was raised before and i have kept hold on it.

please check the existing issues.

so i am closing this issue

please understand.

and this project won't be in active from 24th october.
