### ISSUE TITLE
In the pop window the terms/condition is not visible complete (fix the ui )

### ISSUE THREAD

**Issue by REHAN-18** [ML-Fusion-Lab/ML-Fusion-Lab-Website#928]
### Description

In the pop window the terms/condition is not visible complete  
& in sign up page the background is very bad the background should be changes

### Steps to Reproduce

fix the ui for pop
for signup issue change the background of this

### Expected Behavior

change make better dent sign up with modern looking sign up ui

### Screenshots

<img width="1244" alt="Screenshot 2024-10-21 at 11 33 54 PM" src="https://github.com/user-attachments/assets/e66a1cbf-ff8a-4c06-a90b-37d6181b31bc">
<img width="1360" alt="Screenshot 2024-10-21 at 11 36 58 PM" src="https://github.com/user-attachments/assets/eedbba26-f8cf-42e0-8eea-b193f3cf7498">

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [X] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for me it is visible 

![image](https://github.com/user-attachments/assets/57a9cb7f-7c01-4c1b-a221-4dc5ea8875f7)

and coming to login and signup page, for now we are not looking for any changes in that page, even background also.

so i am closing this issue.

please understand.
