### ISSUE TITLE
IMPROPER ALLIGNMENT IN CONTRIBUTORS PAGE 

### ISSUE THREAD

**Issue by HimangshuSharma01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#929]
### Description

![Screenshot 2024-10-22 002650](https://github.com/user-attachments/assets/c07162b5-a848-4563-b57c-0e307bf39939)
![Screenshot 2024-10-22 002642](https://github.com/user-attachments/assets/0f842005-a18c-4afd-b676-4c6cea725bc6)

### Steps to Reproduce

Go to the Contributors page 

### Expected Behavior

Proper alignment 

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HimangshuSharma01 assigning this issue to you.

Make sure to complete this.

**Comment by vivekvardhan2810** [comment]
And @HimangshuSharma01 one more thing.

this project won't be active from 25th october, including me.
