### ISSUE TITLE
THERE IS NO CHAT BOT IN COURSES PAGE 

### ISSUE THREAD

**Issue by HimangshuSharma01** [ML-Fusion-Lab/ML-Fusion-Lab-Website#933]
### Description

https://github.com/user-attachments/assets/8e2b9c5d-b69a-4af5-89d7-80364fc75148

### Steps to Reproduce

GO TO THE COURSE SECTION AND YOU WILL FIND NO CHATBOT

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@HimangshuSharma01 assigning this issue to you.

make sure to complete this.

And don't disturb anything, please.

**Comment by vivekvardhan2810** [comment]
add that same chatbot that is there in home page.

**Comment by HimangshuSharma01** [comment]
> add that same chatbot that is there in home page.

yes
