### ISSUE TITLE
Contributor text not visible in dark mode 

### ISSUE THREAD

**Issue by Peart-Guy** [ML-Fusion-Lab/ML-Fusion-Lab-Website#936]
### Description

Contributor text not visible in dark mode 

### Steps to Reproduce

In the Contibutors page the name of the users are not visible in dark mode

### Screenshots

![Screenshot 2024-10-22 011942](https://github.com/user-attachments/assets/b6694c50-cdf8-4140-ad24-b3269bba3a1a)

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [ ] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Peart-Guy assigning this issue to you.

Make sure to complete this fast.

And please do contribute to other projects also.
