### ISSUE TITLE
TO ADD SEARCH BAR IN LANGUAGE SECTION

### ISSUE THREAD

**Issue by subhamghosh7** [ML-Fusion-Lab/ML-Fusion-Lab-Website#938]
### Is your feature request related to a problem? Please describe.

THERE IS NO SEARCH OPTION IN LANGUAGE SECTION.SO I WANT YOU TO ADD A SEARCH BAR IN THE SECTION.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
for now we don't require any further improvements in the language translation tool.

so i am closing this issue.

Please understand.
