### ISSUE TITLE
Night Mode Bug: Front page image displays only half in light and dark modes

### ISSUE THREAD

**Issue by bavi404** [ML-Fusion-Lab/ML-Fusion-Lab-Website#942]
### Description

When switching between light and dark modes on the front page, the image only partially displays. The bottom half of the image shows up in light mode, while the upper half becomes visible in dark mode. It seems the image is not fully visible in either mode.

### Steps to Reproduce

Go to the front page.
Toggle between light mode and night mode.
Observe that the bottom half of the image shows up in light mode, while the upper half shows up in dark mode.

### Expected Behavior

The entire image should be visible regardless of whether light or dark mode is selected.

### Screenshots

![image](https://github.com/user-attachments/assets/f840d6e3-532d-4b2d-8558-577cf45de36e)
![image](https://github.com/user-attachments/assets/276db1e1-2571-4f4d-a081-285807b08467)

### Additional Information

I would like to work on resolving this issue as part of GSSoC Extended and Hacktoberfest 2024. Please assign this issue to me.

Thank you!

-- Bavishya Sankaranarayanan

**Comment by vivekvardhan2810** [comment]
Thank you for raising this issue

But for now we are not looking for any further improvements in light and dark mode one's.

So I am closing this issue.

Please understand.
