### ISSUE TITLE
EMAIL US PAGE DOESNT WORK

### ISSUE THREAD

**Issue by KhanjarSingh** [ML-Fusion-Lab/ML-Fusion-Lab-Website#943]
### Description

When we scroll to Bottom and click on Email us it shows page not found

### Steps to Reproduce

We should change or fix the link attached 

### Expected Behavior

I expected to open email us page

### Actual Behavior

IT showed page not found

### Screenshots

<img width="234" alt="Screenshot 2024-10-22 at 8 45 52 AM" src="https://github.com/user-attachments/assets/92c234c3-e2a5-41c7-ba52-c9da2530b741">
<img width="561" alt="Screenshot 2024-10-22 at 8 46 11 AM" src="https://github.com/user-attachments/assets/7dd75342-d8b8-45cc-a3ad-d4741efc7139">

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by KhanjarSingh** [comment]
@vivekv2810 @vivekvardhan2810 I would love to work on this issue

**Comment by vivekvardhan2810** [comment]
For now we have kept it like this in footer, we don't want any further improvements on this page.

So I am closing this issue.

Please understand.
