### ISSUE TITLE
Creating  Project Detail Page to the Card `AI-Powered Fraud Detection System`

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#944]
### Is your feature request related to a problem? Please describe.

this page is yet to be built.

### Describe the solution you'd like.

-  I will create a Project Detail Page to the Card `AI-Powered Fraud Detection System`
- similar to the other project detail pages
- consistent header and footer.
@vivekvardhan2810 

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/8f591db0-2b03-43a7-99de-daa395ba9ef3)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 assigning this issue to you.

Make sure to complete this.

And one more thing this project is gonna be inactive from October 27th including me also.
