### ISSUE TITLE
[Mention The Feature]: Add Quizes on each topic

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [ML-Fusion-Lab/ML-Fusion-Lab-Website#947]
### Is your feature request related to a problem? Please describe.

Add Quizes on each topic
i will complete this by today

### Describe the solution you'd like.

Add Quizes on each topic

### Describe alternatives you've considered.

Add Quizes on each topic

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now we are not looking for this.

So I am closing this issue.

Please understand.

And don't create multiple issues.
