### ISSUE TITLE
FIXING THE TESTIMONAL PAGE 

### ISSUE THREAD

**Issue by Gahlotkumkum** [ML-Fusion-Lab/ML-Fusion-Lab-Website#948]
### Is your feature request related to a problem? Please describe.

NOT WELL RESPONSIVE FOR ALL DEVICES AND FEELS LAGGY 

### Describe the solution you'd like.

FIXING THE TESTIONAL PAGE SO THAT IT CAN SUPPORT EVERY DEVICE 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@Gahlotkumkum assigning this issue to you.

Make sure to complete this.

**Comment by sourav349** [comment]
Hey @vivekvardhan2810 I am interested in this issue, can you assign this issue too me.
 I believe these changes will significantly enhance the overall user experience.

**Comment by vivekvardhan2810** [comment]
@sourav349 this issue was assigned before.

And they are working on it.

so please understand.
