### ISSUE TITLE
Scrollytelling

### ISSUE THREAD

**Issue by STSonyThomas** [ML-Fusion-Lab/ML-Fusion-Lab-Website#95]
ISSUE: The home page looks dull and not attractive at the moment. It should be more interactive to maintain user engagement from a UX POV.

Ref:
![image](https://github.com/user-attachments/assets/1eb7e981-3b68-4984-be9f-c45a76af5a28)

Solution:
Implement Scrollytelliing animation at the page.

**Comment by STSonyThomas** [comment]
The layout isn't uniform either so I can make the elements flex, assign each particular image and the story that it tells a screen or 90 percent of a screen and then work on the animation for scrolly telling. Basically there'll be a fade-in fade-out effect that looks smooth.

**Comment by STSonyThomas** [comment]
# Also How do I add labels here?

**Comment by vivekvardhan2810** [comment]
this issue has been solved, so i am closing this issue
