### ISSUE TITLE
Pop description is not matching the titles

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#950]
### Description

Mouse Control Using Eye Tracking with Python page was added in top pages but the projects.html was not updated causing mismatch.

### Steps to Reproduce

not updating projects.html concurrently

### Screenshots

https://github.com/user-attachments/assets/cfccaf63-0ae3-43dd-832a-a8eb5e6a6043

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.
