### ISSUE TITLE
[Mention The Feature]: Adding relevant background images and graphics with hover effects to 'Our Features' Cards

### ISSUE THREAD

**Issue by Edasgh** [ML-Fusion-Lab/ML-Fusion-Lab-Website#952]
### Is your feature request related to a problem? Please describe.

Adding relevant graphics and background images will enhance the UI of the 'Our Features' Section. 

### Describe the solution you'd like.

I will add relevant background images and graphics with hover effects to the cards of the  'Our Features' section

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Edasgh** [comment]
Please assign this issue to me.
I'm a GSSOC'24-EXT Contributor so please add the gssoc-ext and a relevant level label to it

**Comment by vivekvardhan2810** [comment]
And @Edasgh one more thing.

this project will be inactive from 24th october.

so make sure to complete it fast and do it carefully.
