### ISSUE TITLE
[Mention The Feature]: add  faqs 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [ML-Fusion-Lab/ML-Fusion-Lab-Website#954]
### Is your feature request related to a problem? Please describe.

add  faqs 

### Describe the solution you'd like.

add  faqs 

### Describe alternatives you've considered.

add  faqs 

### Additional context.

add  faqs 

### Show us the magic with screenshots

add  faqs 

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was existing, please check it, i have kept it on hold.

So I am closing this issue.

Please understand.

And don't create multiple issues.
