### ISSUE TITLE
Security Section Missing and Redirects to Incorrect Page 

### ISSUE THREAD

**Issue by VidhanThakur09** [ML-Fusion-Lab/ML-Fusion-Lab-Website#956]
### Description

the security section on landing page is redirecting to wrong page and in project page ,  the security section is missing in the footer section.the 

### Steps to Reproduce

- go to landing page 
- click on security section 
- go to project page
- go to footer section

### Actual Behavior

- on landing page security section redirect to privacy page
- on project section there is security section which can redirect to privacy page

### Screenshots

![Screenshot 2024-10-22 153052](https://github.com/user-attachments/assets/718ee64f-e058-4b55-9804-3b322c954028)
![Screenshot 2024-10-22 154218](https://github.com/user-attachments/assets/4f8ff5d1-7c70-4e1d-b1c3-3e039f0fafee)

### Additional Information

can you assign this issue to me with labels "gssoc-ext" and "hacktoberfest-accepted";

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 i have kept the security button on footer as like formality only, and don't want any improvements on that.

so i am closing this issue.

please understand.

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 can you redirect that security page link to privacy policy page,

**Comment by VidhanThakur09** [comment]
yes sir

**Comment by vivekvardhan2810** [comment]
Okay @VidhanThakur09 i am assigning this issue to you.

Make sure to complete this fast.

**Comment by vivekvardhan2810** [comment]
And @VidhanThakur09 don't change or disturb anything on footer in landing page and project page.

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me

**Comment by VidhanThakur09** [comment]
Sir in project page the security section is missing shall I add that or not

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 the security section is already there in projects page

![image](https://github.com/user-attachments/assets/327b6cea-42e2-49e1-ac44-cd22552bbc3c)

**Comment by VidhanThakur09** [comment]
> @VidhanThakur09 the security section is already there in projects page
> 
> ![image](https://github.com/user-attachments/assets/327b6cea-42e2-49e1-ac44-cd22552bbc3c)
> 

It is missing contribution section shall I add that in project page.

**Comment by vivekvardhan2810** [comment]
@VidhanThakur09 no need to add contribution section in that page and in every page of the website also.

i have kept that contributions section for home page only.

**Comment by VidhanThakur09** [comment]
Ok sir, so I need to only need to  redirect security to privacy page

**Comment by vivekvardhan2810** [comment]
yes, @VidhanThakur09
