### ISSUE TITLE
[⭐FEATURE] Add a Visitor Counter feature ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [ML-Fusion-Lab/ML-Fusion-Lab-Website#960]
### Is your feature request related to a problem? Please describe.

I want to add a Visitor Counter feature properly.

PA please assign me this task.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 where you want to add this.
> 
> like on which page do you want to add this.
> 
> please send the screenshot of it.

bottom left corner

**Comment by vivekvardhan2810** [comment]
@Subhajit-2023-44 assigning this issue to you.

Make sure to complete this.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 assigning this issue to you.
> 
> Make sure to complete this.

Sure but it level 3 work, you can check other website.. please upgrade the level 2 to 3

Thank you

**Comment by vivekvardhan2810** [comment]
@Subhajit-2023-44 see, it depends Upon the decision the Project Admin and the level of the work.

so please understand.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 see, it depends Upon the decision the Project Admin and the level of the work. like the quality of code.
> 
> not every project admin assigns level 3.
> 
> so please understand.

Okay I will first give PR

**Comment by vivekvardhan2810** [comment]
@Subhajit-2023-44 have you done with it.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 have you done with it.

Wait wait, Give me just 15 minutes
