### ISSUE TITLE
colour change of explore course 

### ISSUE THREAD

**Issue by 121hemank** [ML-Fusion-Lab/ML-Fusion-Lab-Website#961]
### Description

the explore course icon is not visible in the homepage in the cursor is very distracting  

### Steps to Reproduce

I will be changing the color of the explore course and the cursor color 

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
we are not looking for this and we don't want any further changes in that page.

so i am closing this issue.

please understand.
