### ISSUE TITLE
[Mention The Feature]: Improving hover effects on nav links

### ISSUE THREAD

**Issue by Son7c** [ML-Fusion-Lab/ML-Fusion-Lab-Website#962]
### Is your feature request related to a problem? Please describe.

The hover effect on nav links is not smooth and is very basic

### Describe the solution you'd like.

I would add smoother transition and enhance the hovering effects

### Describe alternatives you've considered.

none

### Show us the magic with screenshots

https://github.com/user-attachments/assets/27fe5442-c445-48a4-8694-533e0dbfd32e

I would enhance this section.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header based issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar and header updates for now, as it was done and changes many times before.

please understand.
