### ISSUE TITLE
Fix the head navigation bar and the "Sign up for newsletter" section

### ISSUE THREAD

**Issue by sanchitc05** [ML-Fusion-Lab/ML-Fusion-Lab-Website#966]
### Description

The top navigation bar is very cluttered, and various elements are overlapping themselves. Also, the "Sign up for newsletter" section appears static. I would suggest you add a minimal hover effect on the "Enter your email" and a highlighted hover effect on the Subscribe button.

If you would like, I'll be more than happy to work on this issue.

### Steps to Reproduce

N/A

### Screenshots

![Screenshot (261)](https://github.com/user-attachments/assets/a015f020-3964-45e2-82ce-ac1cd8cc9dd5)

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

from my side navbar is looking good 

![image](https://github.com/user-attachments/assets/f0d33fa0-48f3-4815-afcf-fa650948b7a6)

and i don't want any improvements further on the "Sign up for newsletter" section
