### ISSUE TITLE
Enhance the UI of the footer section

### ISSUE THREAD

**Issue by tatheer-fathima** [ML-Fusion-Lab/ML-Fusion-Lab-Website#967]
### Is your feature request related to a problem? Please describe.

Yes, Currently the alignment of the sections in the footer are not properly alignment which impacts the overall user experience and visual appeal.

### Describe the solution you'd like.

I would to work on it by fixing these issues of the footer and make it more interactive.

### Additional context.

I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

### Show us the magic with screenshots

![image](https://github.com/user-attachments/assets/8477f0ae-cb7f-46e0-880c-0b283a5b48c6)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
thank you for raising this issue.

but for now we are not looking for any further updates on footer, as there were many changes happened before.

so i am closing this issue.

please understand.
