### ISSUE TITLE
Improve Navigation Bar Design and Dark Mode Compatibility

### ISSUE THREAD

**Issue by khushigupta86** [ML-Fusion-Lab/ML-Fusion-Lab-Website#969]
Improve Navigation Bar Design and Dark Mode Compatibility

The current design of the navigation bar lacks a professional touch and could be enhanced to improve the overall user experience. Specifically, when switching to dark mode, the logo appears in a different color compared to the navigation bar, which results in an inconsistent and unpolished look.

This issue affects both the aesthetics and usability of the site, as it distracts users from the core functionality. A cohesive and visually appealing design is crucial for making the interface look professional and engaging.
![Screenshot 2024-10-22 160910](https://github.com/user-attachments/assets/a1debc97-2378-47dd-bfc9-c88fd5d577c6)

### Describe the solution you'd like.

I would like to take the opportunity to improve the design of the navigation bar by:

- Ensuring that the logo and navigation bar colors are consistent across all modes (light and dark).
- Enhancing the navigation bar layout to achieve a more modern and professional appearance.
- Optimizing the design for better user experience and responsiveness across different devices

I believe these changes will significantly enhance the look and feel of the website. Please assign this issue to me so I can start working on it.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
