### ISSUE TITLE
Accessibility and Usability

### ISSUE THREAD

**Issue by kundana29** [ML-Fusion-Lab/ML-Fusion-Lab-Website#97]
Text Readability: The gray text on a light gray background in the "About ML Fusion Labs" section has low contrast. This might be challenging to read for some users, particularly those with visual impairments. Increasing contrast between text and background would enhance accessibility.
Navigation Menu Visibility: The top navigation menu (Home, Courses, Projects, About Us, Contact) should be more visually distinctive. could use brighter colors or larger fonts to make them stand out.
please assign this to me

**Comment by TanishSen** [comment]
I would like to work on this issue, please assign me this task

**Comment by Kavish-Paraswar** [comment]
"I would like to work on this issue as I have a strong background in CSS and HTML. Please assign me to this task under GSSOC'24 Extended."

**Comment by kundana29** [comment]
@faisal07777 please assign this to me . i am the one who raised the issue

**Comment by vivekvardhan2810** [comment]
this issue was resolved, so i am closing this issue.
