### ISSUE TITLE
Lots Of Site Pages Not Responsive On Mobile Devices

### ISSUE THREAD

**Issue by khushigupta86** [ML-Fusion-Lab/ML-Fusion-Lab-Website#970]
Lots Of Site Pages Not Responsive On Mobile Devices

Description:

The website currently lacks proper responsiveness on mobile devices. This affects the user experience significantly, as the layout does not adapt well to smaller screen sizes. Navigation elements, text, and images appear misaligned or too small/large, which makes it difficult for users to interact with the site on smartphones and tablets.

Given the increasing number of users accessing websites via mobile devices, ensuring responsive design is crucial. A responsive layout will provide a seamless experience across different screen sizes, enhancing usability and accessibility.

![WhatsApp Image 2024-10-22 at 23 45 18_e3d69505](https://github.com/user-attachments/assets/f681dc0b-ba70-4b65-b168-475d831889f2)

![WhatsApp Image 2024-10-23 at 00 13 47_420eacb3](https://github.com/user-attachments/assets/3f4d7fc7-f77c-4585-845d-744ae0cd5084)

### Describe the solution you'd like.

I would like to work on improving the mobile responsiveness of the website by:

Implementing responsive design principles using media queries to ensure the site adjusts properly on all devices.
Testing the layout on different mobile screen sizes and browsers to ensure compatibility.
Optimizing the UI components, such as navigation, buttons, and images, to enhance touch-screen usability.
These improvements will help provide a better user experience for mobile users, which is vital in today’s mobile-first web environment. Please assign this issue to me so I can start working on it

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
See mobile responsiveness related issue was assigned before and they are resolving it.

So I am closing this issue.

Please understand.

And please don't create multiple issues.

**Comment by khushigupta86** [comment]
but they only making it reponsive it for home pages. I want to  make it responsive it for the whole site

**Comment by vivekvardhan2810** [comment]
@khushigupta86 can you fix this now.

**Comment by khushigupta86** [comment]
yes i can fix it

**Comment by vivekvardhan2810** [comment]
okay i am

**Comment by vivekvardhan2810** [comment]
@khushigupta86 assigning this issue to you.

make sure to complete this.

And please don't disturb anything on navbar and footer one's.

**Comment by vivekvardhan2810** [comment]
@khushigupta86 assigned you.

make sure to complete this fast.

and do it carefully.

**Comment by vivekvardhan2810** [comment]
And @khushigupta86 one more thing, this project won't be active from 25th october including me also.

**Comment by vivekvardhan2810** [comment]
@khushigupta86 have you forked and star this repository.

**Comment by khushigupta86** [comment]
not forked the project yet .
 Please add atleast level 2 label .People making it responsive for only one page have level 2 label on it.
i m making it responsive it   for the whole site

**Comment by vivekvardhan2810** [comment]
@khushigupta86 updated the level.

**Comment by vivekvardhan2810** [comment]
@khushigupta86 have you done with this.

**Comment by vivekvardhan2810** [comment]
@khushigupta86 have you done with this.

As I said earlier this project is going to be inactive from October 25th including me also.

**Comment by vivekvardhan2810** [comment]
@khushigupta86 have you done with this.

**Comment by vivekvardhan2810** [comment]
@khushigupta86 have you done with the task.

if this task is delaying from your side, then you can close this issue also. No problem.

As i have said earlier that this project and i won't be active from tomorrow afternoon.

**Comment by sharanikaa** [comment]
I would like to work on this, kindly assign me this issue.
