### ISSUE TITLE
Making navbar consistent to all the pages

### ISSUE THREAD

**Issue by shubhagarwal1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#973]
Pages to which navbar is not consistent 
[Courses](https://ml-fusion-lab.netlify.app/pages/courses)
[Projects](https://ml-fusion-lab.netlify.app/pages/projects)
[About Us](https://ml-fusion-lab.netlify.app/pages/about)
[Contact](https://ml-fusion-lab.netlify.app/pages/contact)

**Comment by vivekvardhan2810** [comment]
For now it is okay and don't want any improvements on the navbars.

I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.

**Comment by shubhagarwal1** [comment]
Hey @vivekvardhan2810 fo you have any specific improvement planned, please assign one to me, would love working on that

**Comment by vivekvardhan2810** [comment]
Hey @shubhagarwal1 can you work on the terms and conditions page.

Same as like you did for privacy policy page.

**Comment by shubhagarwal1** [comment]
sure, thank yiu  for the opportunity, should i raise a new issue ?

**Comment by vivekvardhan2810** [comment]
Yes, you can raise a new issue @shubhagarwal1.

I think this will be last issue that I am gonna assign

Because as I said this project is gonna be inactive from October 25th.

**Comment by shubhagarwal1** [comment]
then can i get one more

**Comment by vivekvardhan2810** [comment]
I didn't understand @shubhagarwal1

**Comment by shubhagarwal1** [comment]
as the project is hoing to be inactive from 25 
can i work on1 more issue? if you have sometjing planned please let me know

**Comment by vivekvardhan2810** [comment]
Yes, for now you can work on improving the terms and conditions page @shubhagarwal1

**Comment by shubhagarwal1** [comment]
yes i have raised issue for that,do you have more pages that i can improve
