### ISSUE TITLE
Improve Readability of Homepage's  "About Us" Section on Bright Mode

### ISSUE THREAD

**Issue by prata-hp** [ML-Fusion-Lab/ML-Fusion-Lab-Website#974]
### Is your feature request related to a problem? Please describe.

 The text in the "About Us" section on the homepage is not very readable when the website is viewed in bright mode. I propose changing the font color to improve readability. Additionally, I plan to make other enhancements to the section.

**Steps to Reproduce:**

Visit the ML Fusion homepage.

Switch to bright mode.

Scroll Down to the "About Us" section.

**Expected Behavior:** The text should be easily readable in bright mode.

**Actual Behavior:** The text is not easily readable in bright mode.

I Have also Attached a screenshot.

![Screenshot 2024-10-22 172240](https://github.com/user-attachments/assets/80330a42-411d-4797-8aa2-a9afbaeec3d4)

### Describe the solution you'd like.

**Proposed Solution:** Change the font color to a slight darker tone to improve readability as it will be more clear in bright white background also consider other enhancements to the section.

### Describe alternatives you've considered.

**Proposed Alternative Solution:** Instead of changing the font color, you could adjust the background color of the homepage's "About Us" section to a shade that contrasts better with the existing font color.

### Additional context.

**What I am describing is The Homepage's ABOUT US section not to be confused with the Website's about us section**

Please assign this task to me.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
This issue was raised before and assigned also, please check the existing issues.

And in home page about us we have kept it for formality to show this on main website.

So I am closing this issue.

Please understand.
