### ISSUE TITLE
Redesign the terms and conditions page

### ISSUE THREAD

**Issue by shubhagarwal1** [ML-Fusion-Lab/ML-Fusion-Lab-Website#975]
ADDING SOME ANNIMATIONS

UI IMPROVEMENT

IMPROVEMENTS IN FOOTER to make it same as home page

Fix styling

Hey @vivekvardhan2810 please assign me this task

**Comment by vivekvardhan2810** [comment]
Can you elaborate @shubhagarwal1 what are you gonna improve on that page.

**Comment by vivekvardhan2810** [comment]
ADDING SOME ANNIMATIONS
UI IMPROVEMENT
IMPROVEMENTS IN FOOTER to make it same as home page
Fix styling

**Comment by shubhagarwal1** [comment]
> Can you elaborate @shubhagarwal1 what are you gonna improve on that page.

suggested changes sounds good, i will work on them.

**Comment by vivekvardhan2810** [comment]
I have updated the changes in the description of your issue which you have kept @shubhagarwal1 

Assigning this issue to you.

Make sure to complete this.

**Comment by shubhagarwal1** [comment]
> I have updated the changes in the description of your issue which you have kept @shubhagarwal1, please work on that.
> 
> 
> 
> Assigning this issue to you.
> 
> 
> 
> Make sure to complete this.

Thank you for the opportunity.
