### ISSUE TITLE
Social Media Links Open in Same Tab, Affecting User Experience

### ISSUE THREAD

**Issue by Ravi-1606** [ML-Fusion-Lab/ML-Fusion-Lab-Website#976]
### Description

When clicking on the social media links, they currently open in the same tab, which negatively impacts the user experience by navigating users away from the site. I attempted to manually open the links in a new tab but realized the current implementation does not specify the target="_blank" attribute. This attribute should be added to ensure that external links open in a new tab, allowing users to stay on the site while accessing social media profiles.

### Steps to Reproduce

1. Go to the footer section of the website.
2. Click on any social media link.
3. Observe that the link opens in the same tab.

### Expected Behavior

Social media links should open in a new tab to prevent users from being redirected away from the website.

### Actual Behavior

When clicking on the social media links, they open in the same tab, causing users to leave the current website. This disrupts the browsing experience as users have to manually navigate back to the site.

### Screenshots

https://github.com/user-attachments/assets/71f1b0d8-8abc-4d27-8408-6d131c0a2bf2

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
For now we don't have any official social media links for this website, so that's why we kep it like that formally.

So I am closing this issue.

Please understand.
