### ISSUE TITLE
Navbar size is inconsistent with the overall design

### ISSUE THREAD

**Issue by Chitrakadyan2005** [ML-Fusion-Lab/ML-Fusion-Lab-Website#978]
### Description

 The size of the navbar appears disproportionate compared to the rest of the content on the webpage. It occupies more vertical space than necessary, which affects the aesthetic appeal and functionality of the design.

### Steps to Reproduce

Navigate to the home page.
Observe the space taken up by the navbar compared to the content below.
Compare with the desired compact design for better usability.

### Expected Behavior

The navbar should have a more compact design, taking up minimal vertical space while still fitting all the menu items properly. This would ensure that the main content below it is more prominent and accessible without requiring extra scrolling.

### Actual Behavior

The current navbar is too tall, which makes the top part of the webpage appear bulky. It covers a significant portion of the page, which results in a less streamlined user experience.

### Screenshots

![navbar](https://github.com/user-attachments/assets/c82d05e5-9046-4109-b2f7-a5a71584c528)

### Additional Information

Please assign this issue to me under GSSOC'24EXTD, hacktoberfest'24 and level labels .
@vivekvardhan2810 

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
