### ISSUE TITLE
Contributor page shows "Page Not Found" error on click

### ISSUE THREAD

**Issue by Chitrakadyan2005** [ML-Fusion-Lab/ML-Fusion-Lab-Website#979]
### Description

Clicking on the "Contributor" button leads to a "Page Not Found" error. The link appears to be broken or incorrectly routed, preventing users from accessing the intended contributor information.

### Steps to Reproduce

Navigate to the website.
Click on the "Contributor" button in the navigation menu.
Observe the "Page Not Found" error that appears.

### Expected Behavior

Upon clicking the "Contributor" button, users should be directed to the contributor page that provides information about the project contributors, their roles, and contributions.

### Actual Behavior

 Clicking the "Contributor" button results in a "Page Not Found" error, indicating that the page URL is either incorrect or the page is missing.

### Screenshots

https://github.com/user-attachments/assets/dd6c0d8c-a863-42f9-afb3-5f5effe229e2

### Additional Information

please assign this issue to me under GSSOC'24EXTD, hacktoberfest'24 and level labels.
@vivekvardhan2810 

### What browser are you seeing the problem on?

- [ ] Firefox
- [X] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
See you can see in home page that contributor page is there and opening.

Sp that's why I have kept that contributor page in home page.

And i have kept on privacy policy page footer on formality 

And there is no updates required now.

So I am closing this issue.

Please understand.

And don't create multiple issues. This is the warning.

And this project is going to be inactive from 25th October including me also.

**Comment by vivekvardhan2810** [comment]
I think the page is missing.

@Chitrakadyan2005 can you fix this issue.

**Comment by vivekvardhan2810** [comment]
I can see the contributors page in home page

And you are seeing this in home page only, I think you are seeing the privacy and policy page footer

For now there isn't any required improvements.

So I am closing this issue.

please understand.
