### ISSUE TITLE
Enhancing navbar.

### ISSUE THREAD

**Issue by itishacodes** [ML-Fusion-Lab/ML-Fusion-Lab-Website#98]
Adding right hand alignment to the navbar elements with some neon border can enhance it's look.

Please assign me this issue under GSSoC'24 EXTENDED and HACKTOBERFEST.

**Comment by Antima2004** [comment]
hii,
please assign me this issue

**Comment by harshitpathak528** [comment]
I want to work on it Please assign to me.

**Comment by Bhavya445** [comment]
i work with frontend, assign this issue to me

**Comment by itishacodes** [comment]
Please assign me this issue.

**Comment by tanishirai** [comment]
I would like to work on this issue

**Comment by vivekvardhan2810** [comment]
Hi, @itishacodes This issue was created before and the PR was created, 

For now i am closing this issue 

But i will Encourage you to look for other issues in website like improvements, then you can create new issue.
