### ISSUE TITLE
[Mention The Feature]:  enhancing header and home page 

### ISSUE THREAD

**Issue by MimanshaKaur** [ML-Fusion-Lab/ML-Fusion-Lab-Website#980]
### Is your feature request related to a problem? Please describe.

the header is looking very basic according to the machine learning (ML) theme and the first image used in the background of home page is also very bright which in turn is disturbing the user's focus on the main content written over it.

### Describe the solution you'd like.

- i want to make some CSS changes in the header...adjust its spacing and indentation from both left and right sides.
- wanted to add enhanced hover styling instead of button kind of style in the options. 
- little bit reduction in the opacity of this background image will bring wonders to your website....so that the white coloured text will also be more readable👍👍
- also adjusting the same text with different styling will be the cherry on the cake.

### Additional context.

i am Gssoc-ext contributor and hacktoberfest registered👍

i will be more than happy if you assign me this task @vivekvardhan2810 
pls assign this to me with gssoc-ext and hacktoberfest-accepted and required labels.

### Show us the magic with screenshots

![Screenshot 2024-10-23 132107](https://github.com/user-attachments/assets/5df181f4-b2f1-443c-a749-39a1cd349840)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
Hi, I have seen many navbar and header based issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar and header updates for now, as it was done and changes many times before.

please understand.

**Comment by MimanshaKaur** [comment]
ok
