### ISSUE TITLE
Improper spacing in the about us section of home page

### ISSUE THREAD

**Issue by MimanshaKaur** [ML-Fusion-Lab/ML-Fusion-Lab-Website#981]
### Description

The spacing above the about us section is not properly set. there is some extra spacing above the image.

### Steps to Reproduce

- here, the spacing should be reduced.
- about us heading should be there at the place where the image is added, i.e., at the top.
- then after the "About Us" heading, the description should be there that too justify aligned.
- and the image used can be added in the right side of the content.
- this will actually give a more professional look for both light and dark themes.

### Screenshots

![Screenshot 2024-10-23 133326](https://github.com/user-attachments/assets/08e30d0c-2890-40b3-8ff6-49ec274743fe)
 see, the space above the picture is little bit more than required.
so this should be reduced.

### Additional Information

I am gssoc-ext 2024 contributor and Hacktoberfest registered.
@v please assign me this task to resolve this BUG.
Please do add gssox-ext and hacktoberfest-accepted labels.

### What browser are you seeing the problem on?

- [ ] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [ ] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@MimanshaKaur can you fix this now.

**Comment by vivekvardhan2810** [comment]
@MimanshaKaur can you make it like this

![image](https://github.com/user-attachments/assets/acbb7162-3fa3-4279-b127-6f6c28243d90)

**Comment by MimanshaKaur** [comment]
> @MimanshaKaur can you fix this now.

yes sure...

 i really want to work on the home page...

**Comment by MimanshaKaur** [comment]
> @MimanshaKaur can you make it like this
> 
> ![image](https://private-user-images.githubusercontent.com/91594529/379168908-acbb7162-3fa3-4279-b127-6f6c28243d90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NzE5MjQsIm5iZiI6MTcyOTY3MTYyNCwicGF0aCI6Ii85MTU5NDUyOS8zNzkxNjg5MDgtYWNiYjcxNjItM2ZhMy00Mjc5LWIxMjctNmY2YzI4MjQzZDkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA4MjAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MmUxMzdiZDc4NDU4MzA0MWFhMjdiZjAwOWJjZjFkNTk0ODBkOWYwNmM2NGEzZTM0ZTU2OWVhMTkwYmJmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7uqaUuSiA9YjWr_HNF9IPxEIbX9B0lzdxJtVZXijfNc)

i am suggesting this only

**Comment by vivekvardhan2810** [comment]
Okay @MimanshaKaur assigning this issue to you.

Make sure to complete this fast.

And one more thing this project won't be active from 25th october including me.

**Comment by MimanshaKaur** [comment]
ok...only about us section?

**Comment by vivekvardhan2810** [comment]
yes @MimanshaKaur only about us section only, don't disturb anything on home page.

**Comment by MimanshaKaur** [comment]
ok

**Comment by MimanshaKaur** [comment]
i will complete it by today only

**Comment by MimanshaKaur** [comment]
don't worry

**Comment by MimanshaKaur** [comment]
@vivekvardhan2810  done👍👍

![Screenshot 2024-10-23 140915](https://github.com/user-attachments/assets/cc16626e-dbb5-46fb-b81c-31659c1616f8)

**Comment by vivekvardhan2810** [comment]
Good Work @MimanshaKaur.👍👍

you can create the PR.

Make sure the footer and all things are aligned right in the home page.

**Comment by MimanshaKaur** [comment]
there is some extra space below footer... i have to adjust it ...

**Comment by MimanshaKaur** [comment]
> Good Work @MimanshaKaur.👍👍
> 
> you can create the PR.
> 
> Make sure the footer and all things are aligned right in the home page.

Thank YOU.

**Comment by MimanshaKaur** [comment]
done with both horizontal and vertical alignments.
both spacings were disturbed the screen was also scrolling horizontally so i managed he margin on body tag .. 
and for vertical also, it is resolved 

footer is also set.

![Screenshot 2024-10-23 142946](https://github.com/user-attachments/assets/ac7e461b-8ae3-4049-8d5e-d9f03c5f47ff)

**Comment by vivekvardhan2810** [comment]
Good Work @MimanshaKaur 👍👍

you can create the PR.

**Comment by MimanshaKaur** [comment]
ok

**Comment by vivekvardhan2810** [comment]
i will check that Pr and review it.
