### ISSUE TITLE
Description not matching title

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#983]
### Description

A tutorial page ,"Email Spam Classifier " was appended in projects mid pages and the projects.html was not updated cincurrently resulting in mismatch 

### Steps to Reproduce

not updating projects.html

### Screenshots

https://github.com/user-attachments/assets/183e82f4-cab3-42ec-a3bb-c42f71f3ec10

### What browser are you seeing the problem on?

- [X] Firefox
- [X] Chrome
- [X] Safari
- [X] Microsoft Edge

### Checklist

- [X] I have checked the [existing issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.
