### ISSUE TITLE
 A bug In `Contributor Page`  & Create  Project Detail Page to the Card `Healthcare Predictive Analytics` 

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [ML-Fusion-Lab/ML-Fusion-Lab-Website#985]
# Project Card  `Healthcare Predictive Analytics`
-  I will create a Project Detail Page to this Card `Healthcare Predictive Analytics`
- similar to the other project detail pages
- consistent header and footer.

![image](https://github.com/user-attachments/assets/d72c23cc-7c40-4613-9f35-8ab99348d103)

# Bug In `Contributor Page`  & Feature request 
- `Course link`  is broken on this page nav bar
- During dark mode it's better to have some less bright image (like grey) similar to cards on rest of website during dark mode

https://github.com/user-attachments/assets/93fe235c-6eea-453a-9a99-53c7a0e960b4

@vivekvardhan2810

**Comment by Adarsh-Chaubey03** [comment]
@vivekvardhan2810  assign me the task

**Comment by vivekvardhan2810** [comment]
@Adarsh-Chaubey03 one more thing.

this project won't be active from october 25th including me also.
