### ISSUE TITLE
[Mention The Feature]:  Add Tutorial for Creating a Recommendation System (Movie recommender as an example) in Project Page Website.

### ISSUE THREAD

**Issue by IkkiOcean** [ML-Fusion-Lab/ML-Fusion-Lab-Website#988]
### Is your feature request related to a problem? Please describe.

We need to create a tutorial that guides users through the process of building a recommendation system. This tutorial will help users understand the fundamental concepts and practical implementations of recommendation algorithms specifically tailored for movies.

### Describe the solution you'd like.

1. **Introduction to Movie Recommendation Systems**
   - Overview of what movie recommendation systems are.
   - Importance and applications in the film industry.

2. **Types of Recommendation Systems**
   - Content-Based Filtering
     - Using movie features (genres, actors, etc.) for recommendations.

3. **Setting Up the Environment**
   - Tools and libraries needed (e.g., Python, Pandas, Scikit-learn, Surprise, etc.).
   - Installation instructions.

4. **Data Collection and Preprocessing**
   - Techniques for cleaning and preparing the data for analysis.

5. **Building the Movie Recommendation Model**
   - Step-by-step implementation of algorithms.
   - Code snippets with explanations for content-based filtering.

6. **Model Evaluation**
   - Techniques to evaluate the effectiveness of the movie recommendation system.

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@IkkiOcean assigning this issue to you.

Make sure to complete this.

And one more thing this project is going to be inactive from october 26th.
