### ISSUE TITLE
[Mention The Feature]: Add complete tutorial page for Fashion Recommendation System using Machine Learning in projects page website

### ISSUE THREAD

**Issue by DarshAgrawal14** [ML-Fusion-Lab/ML-Fusion-Lab-Website#991]
### Is your feature request related to a problem? Please describe.

add a tutorial page

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/ML-Fusion-Lab/ML-Fusion-Lab-Website/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by vivekvardhan2810** [comment]
@DarshAgrawal14 assigning this issue to you.

Make sure to complete this.

And don't create multiple issues.

pls understand.

**Comment by DarshAgrawal14** [comment]
> @DarshAgrawal14 assigning this issue to you.
> 
> Make sure to complete this.
> 
> And don't create multiple issues.
> 
> And please do contribute to other projects also.
> 
> pls understand.

i do , but since the repo is closing soon and i myself am going to get busy due to my upcoming exams so i am commiting as much as i can for next two days..
