### ISSUE TITLE
add a scroll up button for the testimonial page.

### ISSUE THREAD

**Issue by 2004pra** [ML-Fusion-Lab/ML-Fusion-Lab-Website#995]
please assign me this issue under gssox extd 24, hactober fest, level 2
you can see the testimonial page below
![Screenshot 2024-10-24 015923](https://github.com/user-attachments/assets/f0bc6029-a126-49e0-9eb3-cfece1a6782f)

**Comment by vivekvardhan2810** [comment]
@2004pra assigning this issue to you.

Make sure to complete this very fast.

the scroll bar should be the same as in the home page.

![image](https://github.com/user-attachments/assets/9074c48e-4b23-4324-8359-ef7ae41b6cb3)

**Comment by 2004pra** [comment]
ok sir

**Comment by vivekvardhan2810** [comment]
@2004pra Make sure to complete this fast.

I will be waiting for your Pull Request

**Comment by vivekvardhan2810** [comment]
@2004pra will it be okay for you, if i give you level 1.

if i assign you level 2 then there will be some issues from my side. as a project admin and program manager reviews all this PR's and it's a clear instruction.

so please understand.

will it be okay for you.

As this PR's are reviewed by program manager 😭

**Comment by 2004pra** [comment]
Ok

**Comment by vivekvardhan2810** [comment]
@2004pra make sure to complete this work fast.

I will be waiting for your Pull Request

make sure to fork the repository.

**Comment by 2004pra** [comment]
right i am doing it you will get  PR  in 1 hour
