### ISSUE TITLE
Enhancement of navbar

### ISSUE THREAD

**Issue by Chinmayeep58** [ML-Fusion-Lab/ML-Fusion-Lab-Website#999]
The font of navbar is very small, and it is not looking good in the dark mode. I will enhance the font of the navbar, so that is is readable, not giving an issue in the dark mode.
Please assign this issue to me under GSSoC-ext, Hacktoberfest

**Comment by vivekvardhan2810** [comment]
I have seen many navbar issues, and i have mentioned it before for contributors to not create issues regarding navbar and there should be no more navbar issues, so i have closed this issue, if you have any queries, you can join discord server for further updates and communication.

we are not looking for navbar updates for now, as it was done and changes many times before.

So I am closing this issue.

please understand.
